{
 "title": "Arista: Switch",
 "tags": [
  "arista",
  "harvest"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(arista_switch_labels{}, datacenter)"
    }
   },
   {
    "name": "Switch",
    "query": {
     "query": "label_values(arista_switch_labels{datacenter=~\"$Datacenter\"}, switch)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "label_values(arista_interface_admin_up{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}, interface)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Switch Details",
   "type": "table",
   "description": "Displays detail of the Switches.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "arista_switch_labels{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "arista_switch_uptime{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Power",
     "type": "stat",
     "description": "This panel displays total power of all switches.",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(arista_environment_power_in{datacenter=~\"$Datacenter\",switch=~\"$Switch\"})"
      }
     ]
    },
    {
     "title": "PSU Efficiency",
     "type": "stat",
     "description": "This panel displays PSU efficiency.",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(arista_environment_power_out{datacenter=~\"$Datacenter\",switch=~\"$Switch\"})\n/\n  sum(arista_environment_power_in{datacenter=~\"$Datacenter\",switch=~\"$Switch\"})",
       "legendFormat": "PSU efficiency"
      }
     ]
    },
    {
     "title": "Top $TopResources Power Consumption",
     "type": "timeseries",
     "description": "Displays power consumption detail.",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "arista_environment_power_in{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(arista_environment_power_in{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}[3h] @ end())\n  )",
       "legendFormat": "{{switch}} PSU {{power_supply}} Input"
      },
      {
       "expr": "sum by (switch) (arista_environment_power_in{datacenter=~\"$Datacenter\",switch=~\"$Switch\"})",
       "legendFormat": "{{switch}} Total Input"
      },
      {
       "expr": "arista_environment_power_out{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(arista_environment_power_out{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}[3h] @ end())\n  )",
       "legendFormat": "{{switch}} PSU {{power_supply}} Output"
      },
      {
       "expr": "sum by (switch) (arista_environment_power_out{datacenter=~\"$Datacenter\",switch=~\"$Switch\"})",
       "legendFormat": "{{switch}} Total Output"
      }
     ]
    },
    {
     "title": "PSU Details",
     "type": "table",
     "description": "Displays detail of the PSUs. `power_out / power_capacity` would be the usage % of that PSU.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "arista_environment_power_capacity{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}"
      },
      {
       "expr": "arista_environment_power_out{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}\n/\n  arista_environment_power_capacity{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}"
      },
      {
       "expr": "arista_environment_power_up{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Temperature and Fan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Sensor Temperatures",
     "type": "timeseries",
     "description": "Displays detail of the temperature.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "arista_environment_sensor_temp{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      arista_environment_sensor_temp{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{switch}} - {{sensor}}"
      }
     ]
    },
    {
     "title": "Fan Details",
     "type": "table",
     "description": "Displays detail of the Fans.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "arista_environment_fan_up{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}"
      },
      {
       "expr": "arista_environment_fan_speed{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transceiver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Transceiver RX Power",
     "type": "timeseries",
     "description": "Displays power of Transceiver RX.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "arista_optic_rx{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      arista_optic_rx{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{switch}} - {{interface}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Transceiver TX Power",
     "type": "timeseries",
     "description": "Displays power of Transceiver TX.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "arista_optic_tx{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      arista_optic_tx{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{switch}} - {{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic on Switch",
     "type": "table",
     "description": "This table tracks hardware switch traffic for all supported network interface cards.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "rate(\n  arista_interface_transmit_bytes{datacenter=~\"$Datacenter\",description!=\"\",interface=~\"$Interface\",switch=~\"$Switch\"}[4m]\n)"
      },
      {
       "expr": "rate(\n  arista_interface_receive_bytes{datacenter=~\"$Datacenter\",description!=\"\",interface=~\"$Interface\",switch=~\"$Switch\"}[4m]\n)"
      }
     ]
    },
    {
     "title": "Top $TopResources Interface Send Throughput",
     "type": "timeseries",
     "description": "Displays total send traffic per interface per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (switch, interface, mac) (\n    rate(\n      arista_interface_transmit_bytes{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[4m]\n    )\n  )\nand on (switch, interface, mac)\n  topk(\n    $TopResources,\n    sum by (switch, interface, mac) (\n      avg_over_time(\n        arista_interface_transmit_bytes{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{switch}} - {{interface}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Interface Receive Throughput",
     "type": "timeseries",
     "description": "Displays total receive traffic per interface per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (switch, interface, mac) (\n    rate(\n      arista_interface_receive_bytes{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[4m]\n    )\n  )\nand on (switch, interface, mac)\n  topk(\n    $TopResources,\n    sum by (switch, interface, mac) (\n      avg_over_time(\n        arista_interface_receive_bytes{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{switch}} - {{interface}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Interface Receive Drops",
     "type": "timeseries",
     "description": "Displays drop packets per interface per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (switch, interface, mac) (\n    rate(\n      arista_interface_receive_drops{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[4m]\n    )\n  )\nand on (switch, interface, mac)\n  topk(\n    $TopResources,\n    sum by (switch, interface, mac) (\n      avg_over_time(\n        arista_interface_receive_drops{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "Transmit - {{switch}} - {{interface}}"
      },
      {
       "expr": "sum by (switch, interface, mac) (\n    rate(\n      arista_interface_transmit_drops{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[4m]\n    )\n  )\nand on (switch, interface, mac)\n  topk(\n    $TopResources,\n    sum by (switch, interface, mac) (\n      avg_over_time(\n        arista_interface_transmit_drops{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "Receive - {{switch}} - {{interface}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Interface Errors",
     "type": "timeseries",
     "description": "Displays errors per interface per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "errors/s" } },
     "targets": [
      {
       "expr": "sum by (switch, interface, mac) (\n    rate(\n      arista_interface_transmit_errors{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[4m]\n    )\n  )\nand on (switch, interface, mac)\n  topk(\n    $TopResources,\n    sum by (switch, interface, mac) (\n      avg_over_time(\n        arista_interface_transmit_errors{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "Transmit - {{switch}} - {{interface}}"
      },
      {
       "expr": "sum by (switch, interface, mac) (\n    rate(\n      arista_interface_receive_errors{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[4m]\n    )\n  )\nand on (switch, interface, mac)\n  topk(\n    $TopResources,\n    sum by (switch, interface, mac) (\n      avg_over_time(\n        arista_interface_receive_errors{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "Receive - {{switch}} - {{interface}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Interface CRC error",
     "type": "timeseries",
     "description": "Displays CRC error per interface.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "errors/s" } },
     "targets": [
      {
       "expr": "sum by (switch, interface, mac) (\n    rate(\n      arista_interface_crc_errors{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[4m]\n    )\n  )\nand on (switch, interface, mac)\n  topk(\n    $TopResources,\n    sum by (switch, interface, mac) (\n      avg_over_time(\n        arista_interface_crc_errors{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{switch}} - {{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Neighbors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Layer Discovery Protocol",
     "type": "table",
     "description": "Displays Link Layer Discovery Protocol (LLDP) neighbors.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "arista_lldp_neighbor_labels{datacenter=~\"$Datacenter\",switch=~\"$Switch\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Down (Last 24h)",
     "type": "stat",
     "description": "Total interfaces count which are down once or more times in past 24 hours duration.",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n      min_over_time(\n        arista_interface_admin_up{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[1d]\n      )\n    ==\n      0\n  )\nor\n  vector(0)"
      }
     ]
    },
    {
     "title": "Down (Last 24h)",
     "type": "table",
     "description": "These interfaces are down once or more times in past 24 hours duration.",
     "gridPos": { "h": 9, "w": 20, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "label_join(\n  min_over_time(\n    arista_interface_admin_up{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[1d]\n  ),\n  \"index\",\n  \"-\",\n  \"datacenter\",\n  \"switch\",\n  \"interface\"\n)"
      },
      {
       "expr": "label_join(\n    min_over_time(\n      arista_interface_up{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[1d]\n    )\n  ==\n    0,\n  \"index\",\n  \"-\",\n  \"datacenter\",\n  \"switch\",\n  \"interface\"\n)"
      }
     ]
    },
    {
     "title": "Down (Last 24h)",
     "type": "timeseries",
     "description": "These interfaces are down once or more times in past 24 hours duration.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "min_over_time(\n    arista_interface_admin_up{datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[1d]\n  )\n==\n  0",
       "legendFormat": "{{switch}} - {{interface}}"
      }
     ]
    }
   ]
  }
 ]
}