{
 "title": "StorageGrid: S3",
 "description": "StorageGrid S3 operations, data transfers, objects, and buckets",
 "tags": [
  "harvest",
  "storagegrid"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(storagegrid_s3_operations_successful, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(storagegrid_s3_operations_successful{datacenter=~\"$Datacenter\"},cluster)"
    }
   },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(storagegrid_s3_operations_successful{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"},node)"
    }
   },
   { "name": "TopResources", "label": "Top Resources", "query": "1,2,3,4,5,6,8,10,15,25,50,100" }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top $TopResources Nodes by S3 Successful Operations",
   "type": "timeseries",
   "description": "Successful S3 operations per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (cluster, datacenter, node) (\n    rate(\n      storagegrid_s3_operations_successful{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[4m]\n    )\n  )\nand\n  topk(\n    $TopResources,\n    sum by (cluster, datacenter, node) (\n      avg_over_time(\n        storagegrid_s3_operations_successful{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} / {{node}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by S3 Operations per Second (unauthorized)",
   "type": "timeseries",
   "description": "Unauthorized S3 operations per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (cluster, datacenter, node) (\n    rate(\n      storagegrid_s3_operations_unauthorized{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[4m]\n    )\n  )\nand\n  topk(\n    $TopResources,\n    sum by (cluster, datacenter, node) (\n      avg_over_time(\n        storagegrid_s3_operations_unauthorized{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} / {{node}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by S3 Operations per Second (failed)",
   "type": "timeseries",
   "description": "Failed S3 operations per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (cluster, datacenter, node) (\n    rate(\n      storagegrid_s3_operations_failed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[4m]\n    )\n  )\nand\n  topk(\n    $TopResources,\n    sum by (cluster, datacenter, node) (\n      avg_over_time(\n        storagegrid_s3_operations_failed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} / {{node}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by GET Operations",
   "type": "timeseries",
   "description": "S3 GET operations per node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (cluster, datacenter, node) (\n    increase(\n      storagegrid_private_s3_total_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",type=~\"get_.*\"}[4m]\n    )\n  )\nand\n  topk(\n    $TopResources,\n    sum by (cluster, datacenter, node) (\n      avg_over_time(\n        storagegrid_private_s3_total_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",type=~\"get_.*\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} / {{node}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by DELETE Operations",
   "type": "timeseries",
   "description": "S3 DELETE operations per node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (cluster, datacenter, node) (\n    increase(\n      storagegrid_private_s3_total_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",type=~\"delete_.*\"}[4m]\n    )\n  )\nand\n  topk(\n    $TopResources,\n    sum by (cluster, datacenter, node) (\n      avg_over_time(\n        storagegrid_private_s3_total_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",type=~\"delete_.*\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} / {{node}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by PUT Operations",
   "type": "timeseries",
   "description": "S3 PUT operations per node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (cluster, datacenter, node) (\n    increase(\n      storagegrid_private_s3_total_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",type=~\"put_.*\"}[4m]\n    )\n  )\nand\n  topk(\n    $TopResources,\n    sum by (cluster, datacenter, node) (\n      avg_over_time(\n        storagegrid_private_s3_total_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",type=~\"put_.*\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} / {{node}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by HEAD Operations",
   "type": "timeseries",
   "description": "S3 HEAD operations per node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (cluster, datacenter, node) (\n    increase(\n      storagegrid_private_s3_total_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",type=~\"head_.*\"}[4m]\n    )\n  )\nand\n  topk(\n    $TopResources,\n    sum by (cluster, datacenter, node) (\n      avg_over_time(\n        storagegrid_private_s3_total_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",type=~\"head_.*\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} / {{node}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by S3 Upload Rate",
   "type": "timeseries",
   "description": "S3 data upload rate (ingestion)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (cluster, datacenter, node) (\n    rate(\n      storagegrid_s3_data_transfers_bytes_ingested{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[4m]\n    )\n  )\nand\n  topk(\n    $TopResources,\n    sum by (cluster, datacenter, node) (\n      avg_over_time(\n        storagegrid_s3_data_transfers_bytes_ingested{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} / {{node}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by S3 Download Rate",
   "type": "timeseries",
   "description": "S3 data download rate (retrieval)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (cluster, datacenter, node) (\n    rate(\n      storagegrid_s3_data_transfers_bytes_retrieved{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[4m]\n    )\n  )\nand\n  topk(\n    $TopResources,\n    sum by (cluster, datacenter, node) (\n      avg_over_time(\n        storagegrid_s3_data_transfers_bytes_retrieved{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} / {{node}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Nodes by Percent Usable Space",
     "type": "timeseries",
     "description": "Percentage of usable storage space",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n      storagegrid_storage_utilization_usable_space_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n    /\n      storagegrid_storage_utilization_total_space_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand\n  topk(\n    $TopResources,\n      avg_over_time(\n        storagegrid_storage_utilization_usable_space_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    /\n      avg_over_time(\n        storagegrid_storage_utilization_total_space_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n  )",
       "legendFormat": "{{cluster}} / {{node}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Nodes by Used Storage for Data",
     "type": "timeseries",
     "description": "Storage used for data",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "storagegrid_storage_utilization_data_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      storagegrid_storage_utilization_data_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n    )\n  )",
       "legendFormat": "{{cluster}} / {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Content",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Nodes by S3 Buckets and Swift Containers",
     "type": "timeseries",
     "description": "Total S3 buckets and Swift containers",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (cluster, datacenter, node) (\n    storagegrid_content_buckets_and_containers{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand\n  topk(\n    $TopResources,\n    max by (cluster, datacenter, node) (\n      avg_over_time(\n        storagegrid_content_buckets_and_containers{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{cluster}} / {{node}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Nodes by S3 and Swift Objects (excluding empty objects)",
     "type": "timeseries",
     "description": "Total S3 and Swift objects (excluding empty objects)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (cluster, datacenter, node) (\n    storagegrid_content_objects{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (cluster, datacenter, node) (\n      avg_over_time(\n        storagegrid_content_objects{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{cluster}} / {{node}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Nodes by Metadata Query Latency",
     "type": "timeseries",
     "description": "Average metadata query latency in milliseconds",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (cluster, datacenter, node) (\n    storagegrid_metadata_queries_average_latency_milliseconds{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand\n  topk(\n    $TopResources,\n    sum by (cluster, datacenter, node) (\n      avg_over_time(\n        storagegrid_metadata_queries_average_latency_milliseconds{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{cluster}} / {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ILM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Nodes by ILM Scan Rate",
     "type": "timeseries",
     "description": "ILM scan rate (objects per second)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (cluster, datacenter, node) (\n    storagegrid_ilm_scan_objects_per_second{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand\n  topk(\n    $TopResources,\n    sum by (cluster, datacenter, node) (\n      avg_over_time(\n        storagegrid_ilm_scan_objects_per_second{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{cluster}} / {{node}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Nodes by ILM Awaiting Object Evaluation (incoming from clients)",
     "type": "timeseries",
     "description": "ILM objects awaiting evaluation (incoming from clients)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (cluster, datacenter, node) (\n    storagegrid_ilm_awaiting_client_objects{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand\n  topk(\n    $TopResources,\n    sum by (cluster, datacenter, node) (\n      avg_over_time(\n        storagegrid_ilm_awaiting_client_objects{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{cluster}} / {{node}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Nodes by ILM Awaiting Object Evaluation",
     "type": "timeseries",
     "description": "Total ILM objects awaiting evaluation",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (cluster, datacenter, node) (\n    storagegrid_ilm_awaiting_total_objects{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand\n  topk(\n    $TopResources,\n    sum by (cluster, datacenter, node) (\n      avg_over_time(\n        storagegrid_ilm_awaiting_total_objects{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{cluster}} / {{node}}"
      }
     ]
    }
   ]
  }
 ]
}