{
 "title": "ONTAP: SnapMirror Destinations",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "query_result(snapmirror_labels{system_type!=\"7mode\",datacenter=~\"$Datacenter\"})"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(snapmirror_labels{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\"}, destination_vserver)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(snapmirror_labels{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\",destination_vserver=~\"$SVM\"}, destination_volume)"
    }
   },
   {
    "name": "ConsistencyGroup",
    "query": {
     "query": "label_values(snapmirror_labels{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\", destination_vserver=~\"$SVM\"}, source_cg_name)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information about SnapMirror Destinations dashboard",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "The SnapMirror Destinations dashboard displays the destination view of all SnapMirror relationships. The filters provided above are applied from the destination side of SnapMirror."
   }
  },
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Unhealthy",
   "type": "stat",
   "description": "Number of unhealhty snapmirrors.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\",healthy=\"false\",relationship_id!=\"\"}\n  )\nor\n  vector(0)"
    }
   ]
  },
  {
   "title": "Relationships by Protection Policy",
   "type": "piechart",
   "description": "This panel displays volume relationship count based on the relationship type.",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",derived_relationship_type=\"extended_data_protection\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\",relationship_id!=\"\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Asynchronous Mirror"
    },
    {
     "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",derived_relationship_type=\"mirror_vault\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\",relationship_id!=\"\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Asynchronous Mirror and Vault"
    },
    {
     "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",derived_relationship_type=\"vault\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\",relationship_id!=\"\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Asynchronous Vault"
    },
    {
     "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",derived_relationship_type=\"sync_mirror_strict\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\",relationship_id!=\"\"}\n  )\nor\n  vector(0)",
     "legendFormat": "StrictSync"
    },
    {
     "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",derived_relationship_type=\"sync_mirror\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\",relationship_id!=\"\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Sync"
    },
    {
     "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",derived_relationship_type=\"automated_failover\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\",relationship_id!=\"\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Automated Failover"
    },
    {
     "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",derived_relationship_type=\"automated_failover_duplex\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\",relationship_id!=\"\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Automated Failover Duplex"
    }
   ]
  },
  {
   "title": "Healthy",
   "type": "stat",
   "description": "Number of healhty snapmirrors.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\",healthy=\"true\",relationship_id!=\"\"}\n  )\nor\n  vector(0)"
    }
   ]
  },
  {
   "title": "Relationships",
   "type": "table",
   "description": "This panel displays detail of all the snapmirror relationships from destination side of view.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "snapmirror_last_transfer_duration{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\",relationship_id!=\"\"}"
    },
    {
     "expr": "snapmirror_last_transfer_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\",relationship_id!=\"\"}"
    },
    {
     "expr": "snapmirror_lag_time{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\",relationship_id!=\"\"}"
    },
    {
     "expr": "snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",derived_relationship_type!=\"load_sharing\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\",relationship_id!=\"\"}"
    }
   ]
  },
  {
   "title": "Top $TopResources Relationships by Transfer Duration",
   "type": "timeseries",
   "description": "This panel displays duration of the last SnapMirror transfer in seconds.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "snapmirror_last_transfer_duration{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      snapmirror_last_transfer_duration{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{source_location}} -> {{destination_location}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Relationships by Lag Time",
   "type": "timeseries",
   "description": "This panel displays amount of time since the last snapmirror transfer in seconds.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "snapmirror_lag_time{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      snapmirror_lag_time{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{source_location}} -> {{destination_location}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Relationships by Transfer Data",
   "type": "timeseries",
   "description": "This panel displays size in kilobytes (1024 bytes) of the last transfer.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "snapmirror_last_transfer_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      snapmirror_last_transfer_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",destination_location=~\".*$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{source_location}} -> {{destination_location}}"
    }
   ]
  },
  {
   "title": "Consistency Group Data Protection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unhealthy",
     "type": "stat",
     "description": "Number of unhealhty snapmirrors.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",destination_cg_name=~\"$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\",group_type=\"consistencygroup\",healthy=\"false\",relationship_id=\"\"}\n  )\nor\n  vector(0)"
      }
     ]
    },
    {
     "title": "Consistency Group relationships by relationship type",
     "type": "piechart",
     "description": "This panel displays consistency group relationship count based on the relationship type.",
     "gridPos": { "h": 12, "w": 18, "x": 6, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",derived_relationship_type=\"extended_data_protection\",destination_cg_name=~\"$ConsistencyGroup\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",group_type=\"consistencygroup\",relationship_id=\"\"}\n  )\nor\n  vector(0)",
       "legendFormat": "Asynchronous Mirror"
      },
      {
       "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",derived_relationship_type=\"mirror_vault\",destination_cg_name=~\"$ConsistencyGroup\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",group_type=\"consistencygroup\",relationship_id=\"\"}\n  )\nor\n  vector(0)",
       "legendFormat": "Asynchronous Mirror and Vault"
      },
      {
       "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",derived_relationship_type=\"vault\",destination_cg_name=~\"$ConsistencyGroup\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",group_type=\"consistencygroup\",relationship_id=\"\"}\n  )\nor\n  vector(0)",
       "legendFormat": "Asynchronous Vault"
      },
      {
       "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",derived_relationship_type=\"sync_mirror_strict\",destination_cg_name=~\"$ConsistencyGroup\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",group_type=\"consistencygroup\",relationship_id=\"\"}\n  )\nor\n  vector(0)",
       "legendFormat": "StrictSync"
      },
      {
       "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",derived_relationship_type=\"sync_mirror\",destination_cg_name=~\"$ConsistencyGroup\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",group_type=\"consistencygroup\",relationship_id=\"\"}\n  )\nor\n  vector(0)",
       "legendFormat": "Sync"
      },
      {
       "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",derived_relationship_type=\"automated_failover\",destination_cg_name=~\"$ConsistencyGroup\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",group_type=\"consistencygroup\",relationship_id=\"\"}\n  )\nor\n  vector(0)",
       "legendFormat": "Automated Failover"
      },
      {
       "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",derived_relationship_type=\"automated_failover_duplex\",destination_cg_name=~\"$ConsistencyGroup\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",group_type=\"consistencygroup\",relationship_id=\"\"}\n  )\nor\n  vector(0)",
       "legendFormat": "Automated Failover Duplex"
      }
     ]
    },
    {
     "title": "Healthy",
     "type": "stat",
     "description": "Number of healthy snapmirrors.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n    snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",destination_cg_name=~\"$ConsistencyGroup\",destination_volume=~\".*$Volume.*\",destination_vserver=~\"$SVM\",group_type=\"consistencygroup\",healthy=\"true\",relationship_id=\"\"}\n  )\nor\n  vector(0)"
      }
     ]
    },
    {
     "title": "Consistency Group Relationships",
     "type": "table",
     "description": "This panel displays detail of all Consistency Group relationships from destination side of view.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",destination_cg_name=~\"$ConsistencyGroup\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",group_type=\"consistencygroup\",relationship_id=\"\"}"
      }
     ]
    }
   ]
  }
 ]
}