{
 "title": "ONTAP: Volume",
 "tags": [
  "harvest",
  "ontap",
  "cdot",
  "fsx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, netapp_cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(volume_labels{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\"}, svm)"
    }
   },
   {
    "name": "Tag",
    "query": {
     "query": "label_values(volume_tags{datacenter=~\"$Datacenter\", netapp_cluster=~\"$Cluster\", svm=~\"$SVM\"},tag)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(volume_labels{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\",svm=~\"$SVM\",style!=\"flexgroup_constituent\",tags=~\".*$Tag.*\"}, volume)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information about Volume dashboard",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Volume latencies are missing some latencies from NAS protocols. Use the workload volume metrics in the QoS row for a more detailed breakdown. <br>[Details in ONTAP Performance KB article](https://kb.netapp.com/on-prem/ontap/Perf/Perf-KBs/What_is_the_difference_in_latency_of_the_same_volume_between_statistics_volume_show_and_qos_statistics_volume_latency_show_commands)"
   }
  },
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Volume Average Latency",
   "type": "stat",
   "description": "Average Latency of top $TopResources volumes.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  topk(\n    $TopResources,\n      (\n        avg by (datacenter, netapp_cluster, svm, volume) (\n          volume_avg_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n        )\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      (\n        max by (datacenter, netapp_cluster, svm, volume, node) (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n        )\n      )\n  )\n)"
    }
   ]
  },
  {
   "title": "Top $TopResources Volumes Total Throughput",
   "type": "stat",
   "description": "Throughput of top $TopResources volumes.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n    topk(\n      $TopResources,\n        (\n          sum by (datacenter, netapp_cluster, svm, volume) (\n            volume_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n          )\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )\n+\n  sum(\n    topk(\n      $TopResources,\n        (\n          sum by (datacenter, netapp_cluster, svm, volume) (\n            volume_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n          )\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )"
    }
   ]
  },
  {
   "title": "Top $TopResources Volumes by Total IOPs",
   "type": "stat",
   "description": "IOPs of top $TopResources volumes.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  topk(\n    $TopResources,\n      (\n        sum by (datacenter, netapp_cluster, svm, volume) (\n          volume_total_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n        )\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      (\n        max by (datacenter, netapp_cluster, svm, volume, node) (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n        )\n      )\n  )\n)"
    }
   ]
  },
  {
   "title": "Top $TopResources Volumes by Average Latency",
   "type": "timeseries",
   "description": "Average latency in microseconds for the WAFL filesystem to process all the operations on the volume; not including request processing or network communication time.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "volume_avg_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_avg_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Volumes by Average Throughput",
   "type": "timeseries",
   "description": "Total throughput.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(\n      volume_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n    +\n      volume_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n          avg_over_time(\n            volume_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n          )\n        * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n          (\n            max by (datacenter, netapp_cluster, svm, volume, node) (\n              volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n            )\n          )\n      +\n          avg_over_time(\n            volume_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n          )\n        * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n          (\n            max by (datacenter, netapp_cluster, svm, volume, node) (\n              volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n            )\n          )\n    )\n  )",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Volumes by Total IOPs",
   "type": "timeseries",
   "description": "Number of operations per second serviced by the volume.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "volume_total_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_total_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Volume Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumes in Cluster",
     "type": "table",
     "description": "Volume details.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_new_status{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n* on (datacenter, netapp_cluster, svm, volume) group_left (node)\n  volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_size_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n* on (datacenter, netapp_cluster, svm, volume) group_left (node)\n  volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_size_used_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n* on (datacenter, netapp_cluster, svm, volume) group_left (node)\n  volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_sis_dedup_saved{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n* on (datacenter, netapp_cluster, svm, volume) group_left (node)\n  volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_sis_compress_saved{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n* on (datacenter, netapp_cluster, svm, volume) group_left (node)\n  volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_sis_dedup_saved\n+\n    volume_sis_compress_saved{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n  * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n    volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_space_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n* on (datacenter, netapp_cluster, svm, volume) group_left (node)\n  volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_space_physical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n* on (datacenter, netapp_cluster, svm, volume) group_left (node)\n  volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_clone_split_estimate{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n* on (datacenter, netapp_cluster, svm, volume) group_left (node)\n  volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Read Latency",
     "type": "table",
     "description": "Average latency in microseconds for the WAFL filesystem to process read request to the volume; not including request processing or network communication time.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "volume_read_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        volume_read_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n  )",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Read Throughput",
     "type": "table",
     "description": "Bytes read per second from the volume.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "volume_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        volume_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n  )",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Read IOPS",
     "type": "table",
     "description": "Number of reads per second from the volume.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "volume_read_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        volume_read_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n  )",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write Latency",
     "type": "table",
     "description": "Average latency in microseconds for the WAFL filesystem to process write request to the volume; not including request processing or network communication time.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "volume_write_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        volume_write_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n  )",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write Throughput",
     "type": "table",
     "description": "Bytes written per second to the volume.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "targets": [
      {
       "expr": "volume_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        volume_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n  )",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write IOPS",
     "type": "table",
     "description": "Number of writes per second to the volume.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "targets": [
      {
       "expr": "volume_write_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        volume_write_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n  )",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
     "options": {
      "content": "Volume latencies are missing some latencies from NAS protocols. Use the workload volume metrics in the QoS row for a more detailed breakdown. <br>[Details in ONTAP Performance KB article](https://kb.netapp.com/on-prem/ontap/Perf/Perf-KBs/What_is_the_difference_in_latency_of_the_same_volume_between_statistics_volume_show_and_qos_statistics_volume_latency_show_commands)"
     }
    },
    {
     "title": "Top $TopResources Volumes by Read Latency",
     "type": "timeseries",
     "description": "Average latency in microseconds for the WAFL filesystem to process read request to the volume; not including request processing or network communication time.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "volume_read_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_read_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write Latency",
     "type": "timeseries",
     "description": "Average latency in microseconds for the WAFL filesystem to process write request to the volume; not including request processing or network communication time.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "volume_write_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_write_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Other Latency",
     "type": "timeseries",
     "description": "Average latency in microseconds for the WAFL filesystem to process other operations to the volume; not including request processing or network communication time.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "volume_other_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_other_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Read IOPs",
     "type": "timeseries",
     "description": "Number of reads per second from the volume.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "volume_read_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_read_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write IOPs",
     "type": "timeseries",
     "description": "Number of writes per second to the volume.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "volume_write_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_write_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Other IOPs",
     "type": "timeseries",
     "description": "Number of other operations per second to the volume.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "volume_other_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_other_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Read Throughput",
     "type": "timeseries",
     "description": "Bytes read per second from the volume.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "volume_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write Throughput",
     "type": "timeseries",
     "description": "Bytes written per second to the volume.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "volume_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Volume Latency by Op Type",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (__name__) (\n  {__name__=~\"volume_nfs_(.*)_latency\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n)",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Volume IOPs per Type",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (__name__) (\n  {__name__=~\"volume_nfs_(.*)_ops\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n)",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "QoS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources QoS Volumes Latency",
     "type": "stat",
     "description": "Latency of top $TopResources QoS volumes.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(\n  topk(\n    $TopResources,\n    (\n        qos_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\n      * on (datacenter, netapp_cluster, svm, volume) group_left ()\n        (\n          max by (datacenter, netapp_cluster, svm, volume) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )\n)"
      }
     ]
    },
    {
     "title": "Top $TopResources Qos Volumes Total Throughput",
     "type": "stat",
     "description": "Throughput of top $TopResources QoS volumes.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(\n    topk(\n      $TopResources,\n      (\n          qos_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\n        * on (datacenter, netapp_cluster, svm, volume) group_left ()\n          (\n            max by (datacenter, netapp_cluster, svm, volume) (\n              volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n            )\n          )\n      )\n    )\n  )\n+\n  sum(\n    topk(\n      $TopResources,\n      (\n          qos_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\n        * on (datacenter, netapp_cluster, svm, volume) group_left ()\n          (\n            max by (datacenter, netapp_cluster, svm, volume, node) (\n              volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n            )\n          )\n      )\n    )\n  )"
      }
     ]
    },
    {
     "title": "Top $TopResources QoS Volumes by Total IOPs",
     "type": "stat",
     "description": "IOPs of top $TopResources QoS volumes.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(\n  topk(\n    $TopResources,\n    (\n        qos_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\n      * on (datacenter, netapp_cluster, svm, volume) group_left ()\n        (\n          max by (datacenter, netapp_cluster, svm, volume) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )\n)"
      }
     ]
    },
    {
     "title": "Top $TopResources QoS Volumes by Latency",
     "type": "timeseries",
     "description": "This is the average response time for requests that were initiated by the workload.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          qos_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left ()\n        (\n          max by (datacenter, netapp_cluster, svm, volume) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources QoS Volumes by Average Throughput",
     "type": "timeseries",
     "description": "This is the total throughput of data read/write per second from the filer by the workload.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(\n      qos_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\n    +\n      qos_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n          avg_over_time(\n            qos_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}[3h] @ end()\n          )\n        * on (datacenter, netapp_cluster, svm, volume) group_left ()\n          (\n            max by (datacenter, netapp_cluster, svm, volume) (\n              volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n            )\n          )\n      +\n          avg_over_time(\n            qos_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}[3h] @ end()\n          )\n        * on (datacenter, netapp_cluster, svm, volume) group_left ()\n          (\n            max by (datacenter, netapp_cluster, svm, volume) (\n              volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n            )\n          )\n    )\n  )",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources QoS Volumes by Total IOPs",
     "type": "timeseries",
     "description": "This field is the workload's rate of operations that completed during the measurement interval; measured per second.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "qos_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          qos_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left ()\n        (\n          max by (datacenter, netapp_cluster, svm, volume) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by QoS Volume Read Latency",
     "type": "timeseries",
     "description": "This is the average response time for read requests that were initiated by the workload.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_read_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          qos_read_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left ()\n        (\n          max by (datacenter, netapp_cluster, svm, volume) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by QoS Volume Write Latency",
     "type": "timeseries",
     "description": "This is the average response time for write requests that were initiated by the workload.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_write_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          qos_write_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left ()\n        (\n          max by (datacenter, netapp_cluster, svm, volume) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by QoS Volume Read IOPS",
     "type": "timeseries",
     "description": "This is the rate of this workload&apos;s read operations that completed during the measurement interval.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "qos_read_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          qos_read_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left ()\n        (\n          max by (datacenter, netapp_cluster, svm, volume) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by QoS Volume Write IOPS",
     "type": "timeseries",
     "description": "This is the workload&apos;s write operations that completed during the measurement interval; measured per second.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "qos_write_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          qos_write_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left ()\n        (\n          max by (datacenter, netapp_cluster, svm, volume) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by QoS Volume Other IOPS",
     "type": "timeseries",
     "description": "This is the rate of this workload&apos;s other operations that completed during the measurement interval.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "qos_other_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          qos_other_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left ()\n        (\n          max by (datacenter, netapp_cluster, svm, volume) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by QoS Volume Read Throughput",
     "type": "timeseries",
     "description": "This is the amount of data read per second from the filer by the workload.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "qos_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          qos_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left ()\n        (\n          max by (datacenter, netapp_cluster, svm, volume) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by QoS Volume Write Throughput",
     "type": "timeseries",
     "description": "This is the amount of data written per second to the filer by the workload.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "qos_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          qos_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left ()\n        (\n          max by (datacenter, netapp_cluster, svm, volume) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by QoS Volume Sequential Reads",
     "type": "timeseries",
     "description": "This is the percentage of reads, performed on behalf of the workload, that were sequential.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "qos_sequential_reads{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          qos_sequential_reads{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left ()\n        (\n          max by (datacenter, netapp_cluster, svm, volume) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by QoS Volume Sequential Writes",
     "type": "timeseries",
     "description": "This is the percentage of writes, performed on behalf of the workload, that were sequential. This counter is only available on platforms with more than 4GB of NVRAM.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "qos_sequential_writes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          qos_sequential_writes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume!=\"\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left ()\n        (\n          max by (datacenter, netapp_cluster, svm, volume) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O Density",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Volumes by IO Density (IOPs/TiB)",
     "type": "timeseries",
     "description": "This panel displays the top k volumes with the highest I/O density within the selected time range. I/O density is calculated as the average number of I/O operations (IOPS) per terabyte of logical used space. Volumes with high I/O density are typically more active and may be critical for performance-sensitive applications.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "(\n        volume_total_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n      / on (datacenter, netapp_cluster, svm, volume)\n        clamp_min(\n            volume_space_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n          /\n            1099511627776,\n          1\n        )\n    )\n  and on (datacenter, netapp_cluster, svm, volume)\n    topk(\n      $TopResources,\n      (\n            avg_over_time(\n              volume_total_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n            )\n          * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n            (\n              max by (datacenter, netapp_cluster, svm, volume, node) (\n                volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n              )\n            )\n        /\n          clamp_min(\n                avg_over_time(\n                  volume_space_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n                )\n              * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n                (\n                  max by (datacenter, netapp_cluster, svm, volume, node) (\n                    volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n                  )\n                )\n            /\n              1099511627776,\n            1\n          )\n      )\n    )\nunless on (datacenter, netapp_cluster, svm, volume)\n  volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",root_volume=\"Yes\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Bottom $TopResources Volumes by IO Density (IOPs/TiB)",
     "type": "timeseries",
     "description": "This panel displays the bottom k volumes with the lowest I/O density over the selected time range, excluding any volumes with average IOPS below 50. I/O density is calculated as the average IOPS per terabyte of logical used space. These volumes are active but have relatively low I/O activity compared to their used capacity.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "(\n      volume_total_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n    / on (datacenter, netapp_cluster, svm, volume)\n      clamp_min(\n          volume_space_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n        /\n          1099511627776,\n        1\n      )\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  bottomk(\n    $TopResources,\n      (\n            avg_over_time(\n              volume_total_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n            )\n          * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n            (\n              max by (datacenter, netapp_cluster, svm, volume, node) (\n                volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n              )\n            )\n        /\n          clamp_min(\n                avg_over_time(\n                  volume_space_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n                )\n              * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n                (\n                  max by (datacenter, netapp_cluster, svm, volume, node) (\n                    volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n                  )\n                )\n            /\n              1099511627776,\n            1\n          )\n      )\n    and on (datacenter, netapp_cluster, svm, volume)\n      (\n              volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",root_volume!=\"Yes\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n            * on (datacenter, netapp_cluster, svm, volume)\n              avg_over_time(\n                volume_total_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n              )\n          * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n            (\n              max by (datacenter, netapp_cluster, svm, volume, node) (\n                volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n              )\n            )\n        >\n          50\n      )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Volumes Per Physical Space Used",
     "type": "timeseries",
     "description": "Size that is physically used in the volume, in bytes.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_space_physical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_space_physical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Per Logical Space Used",
     "type": "timeseries",
     "description": "Sum of (physical-used, shared_refs, compression_saved_in_plane0, vbn_zero, future_blk_cnt), in bytes.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_space_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_space_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Per Volume Size Used",
     "type": "timeseries",
     "description": "The virtual space used (includes volume reserves) before storage efficiency, in bytes.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Per Volume Total Size",
     "type": "timeseries",
     "description": "Physical size of the volume, in bytes.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Per Snapshot Size Available",
     "type": "timeseries",
     "description": "Available space for Snapshot copies from snap-reserve, in bytes.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_snapshots_size_available{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_snapshots_size_available{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Per Snapshot Reserve Size",
     "type": "timeseries",
     "description": "Size in the volume that has been set aside as a reserve for Snapshot copy usage, in bytes.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_snapshot_reserve_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_snapshot_reserve_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Per Snapshot Reserve Available",
     "type": "timeseries",
     "description": "Size available for Snapshot copies within the Snapshot copy reserve, in bytes.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_snapshot_reserve_available{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_snapshot_reserve_available{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Per Snapshot Size Used",
     "type": "timeseries",
     "description": "The total space used by Snapshot copies in the volume, in bytes.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_snapshots_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_snapshots_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Inactive Data",
     "type": "timeseries",
     "description": "The size that is physically used in the performance tier of the volume and has a cold temperature. This parameter is only supported if the volume is in an aggregate that is either attached to an object store or could be attached to an object store.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_space_performance_tier_inactive_user_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_space_performance_tier_inactive_user_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity %",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Volumes Per Physical Space Used",
     "type": "timeseries",
     "description": "Size that is physically used in the volume, as a percentage.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_space_physical_used_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_space_physical_used_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Per Logical Space Used",
     "type": "timeseries",
     "description": "Sum of (physical-used, shared_refs, compression_saved_in_plane0, vbn_zero, future_blk_cnt), as a percentage.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_space_logical_used_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_space_logical_used_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Per Volume Size Used",
     "type": "timeseries",
     "description": "percentage of utilized storage space in a volume relative to its total capacity.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_size_used_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_size_used_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Per Snapshot Reserve",
     "type": "timeseries",
     "description": "The space that has been set aside as a reserve for Snapshot copy usage, in percent.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_snapshot_reserve_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_snapshot_reserve_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Per Snapshot Reserve Used",
     "type": "timeseries",
     "description": "Percentage of snapshot reserve size that has been used.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_snapshot_reserve_used_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_snapshot_reserve_used_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Inactive Data",
     "type": "timeseries",
     "description": "The size (in percent) that is physically used in the performance tier of the volume and has a cold temperature. This parameter is only supported if the volume is in an aggregate that is either attached to an object store or could be attached to an object store.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_space_performance_tier_inactive_user_data_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_space_performance_tier_inactive_user_data_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 23 },
     "options": {
      "content": "<br>\n\nTop clients panels are disabled by default and are supported by the Volume Template in RestPerf Collector starting from ONTAP version 9.13.1. For more details on how to enable them, please refer to the discussion at https://github.com/NetApp/harvest/discussions/3130."
     }
    },
    {
     "title": "Top $TopResources Volumes Clients by Read IOPs",
     "type": "timeseries",
     "description": "This panel displays the top $TopResources volume clients based on their Read IOPs.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "volume_top_clients_read_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        volume_top_clients_read_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      (\n        max by (datacenter, netapp_cluster, svm, volume, node) (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n        )\n      )\n  )",
       "legendFormat": "{{svm}} - {{volume}} - {{client_ip}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Clients by Write IOPs",
     "type": "timeseries",
     "description": "This panel displays the top $TopResources volume clients based on their Write IOPs.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "volume_top_clients_write_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        volume_top_clients_write_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      (\n        max by (datacenter, netapp_cluster, svm, volume, node) (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n        )\n      )\n  )",
       "legendFormat": "{{svm}} - {{volume}} - {{client_ip}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Clients by Read Throughput",
     "type": "timeseries",
     "description": "This panel displays the top $TopResources volume clients based on their read throughput.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "volume_top_clients_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        volume_top_clients_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      (\n        max by (datacenter, netapp_cluster, svm, volume, node) (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n        )\n      )\n  )",
       "legendFormat": "{{svm}} - {{volume}} - {{client_ip}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Clients by Write Throughput",
     "type": "timeseries",
     "description": "This panel displays the top $TopResources volume clients based on their write throughput.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "volume_top_clients_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        volume_top_clients_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      (\n        max by (datacenter, netapp_cluster, svm, volume, node) (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n        )\n      )\n  )",
       "legendFormat": "{{svm}} - {{volume}} - {{client_ip}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
     "options": {
      "content": "<br>\n\nTop files panels are disabled by default and are supported by the Volume Template in RestPerf Collector starting from ONTAP version 9.13.1. For more details on how to enable them, please refer to the discussion at https://github.com/NetApp/harvest/discussions/3130."
     }
    },
    {
     "title": "Top $TopResources Volumes Files by Read IOPs",
     "type": "timeseries",
     "description": "This panel displays the top $TopResources volume files based on their Read IOPs.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "volume_top_files_read_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        volume_top_files_read_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      (\n        max by (datacenter, netapp_cluster, svm, volume, node) (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n        )\n      )\n  )",
       "legendFormat": "{{svm}} - {{volume}} - {{path}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Files by Write IOPs",
     "type": "timeseries",
     "description": "This panel displays the top $TopResources volume files based on their Write IOPs.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "volume_top_files_write_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        volume_top_files_write_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      (\n        max by (datacenter, netapp_cluster, svm, volume, node) (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n        )\n      )\n  )",
       "legendFormat": "{{svm}} - {{volume}} - {{path}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Files by Read Throughput",
     "type": "timeseries",
     "description": "This panel displays the top $TopResources volume files based on their read throughput.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "volume_top_files_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        volume_top_files_read_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      (\n        max by (datacenter, netapp_cluster, svm, volume, node) (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n        )\n      )\n  )",
       "legendFormat": "{{svm}} - {{volume}} - {{path}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Files by Write Throughput",
     "type": "timeseries",
     "description": "This panel displays the top $TopResources volume files based on their write throughput.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "volume_top_files_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        volume_top_files_write_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      (\n        max by (datacenter, netapp_cluster, svm, volume, node) (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n        )\n      )\n  )",
       "legendFormat": "{{svm}} - {{volume}} - {{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Volumes by Object Storage GET Latency",
     "type": "timeseries",
     "description": "Average latency per GET operation to object storage.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "fabricpool_cloud_bin_op_latency_average{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"GET\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        fabricpool_cloud_bin_op_latency_average{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"GET\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      (\n        max by (datacenter, netapp_cluster, svm, volume, node) (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n        )\n      )\n  )",
       "legendFormat": "{{svm}} - {{volume}} - {{cloud_target}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Object Storage GET Request Count",
     "type": "timeseries",
     "description": "Total GET request count, per volume, in the collection interval to object storage.  Not scaled per second, but a cumulative count (delta) since the previous poll.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "fabricpool_cloud_bin_operation{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"GET\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        fabricpool_cloud_bin_operation{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"GET\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      (\n        max by (datacenter, netapp_cluster, svm, volume, node) (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n        )\n      )\n  )",
       "legendFormat": "{{svm}} - {{volume}} - {{cloud_target}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Object Storage PUT Latency",
     "type": "timeseries",
     "description": "Average latency per PUT operation to object storage.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "fabricpool_cloud_bin_op_latency_average{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"PUT\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        fabricpool_cloud_bin_op_latency_average{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"PUT\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      (\n        max by (datacenter, netapp_cluster, svm, volume, node) (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n        )\n      )\n  )",
       "legendFormat": "{{svm}} - {{volume}} - {{cloud_target}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Object Storage PUT Request Count",
     "type": "timeseries",
     "description": "Total PUT request count, per volume, in the collection interval to object storage.  Not scaled per second, but a cumulative count (delta) since the previous poll.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "fabricpool_cloud_bin_operation{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"PUT\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n      avg_over_time(\n        fabricpool_cloud_bin_operation{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"PUT\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n      (\n        max by (datacenter, netapp_cluster, svm, volume, node) (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n        )\n      )\n  )",
       "legendFormat": "{{svm}} - {{volume}} - {{cloud_target}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Object Storage Requests",
     "type": "table",
     "description": "Average request count, per volume, in the chosen time window, to object storage.  Not scaled per second, but a cumulative count (delta) since the previous poll.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum by (volume) (\n    fabricpool_cloud_bin_operation{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    sum by (volume) (\n        avg_over_time(\n          fabricpool_cloud_bin_operation{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )"
      }
     ]
    }
   ]
  },
  {
   "title": "FabricPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumes Footprint",
     "type": "table",
     "description": "Display a list of volumes and metadata footprints in their associated aggregate.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "volume_delayed_free_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_metadata_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_total_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_total_metadata_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_guarantee_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_performance_tier_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_capacity_tier_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Performance Tier Footprint",
     "type": "timeseries",
     "description": "Footprint of blocks written to the volume in bytes for the performance tier (bin 0).",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_performance_tier_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_performance_tier_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}} "
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Performance Tier Footprint %",
     "type": "timeseries",
     "description": "Footprint of blocks written to the volume in performance tier (bin 0) as a percentage of aggregate size.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_performance_tier_footprint_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_performance_tier_footprint_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}} "
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Capacity Tier Footprint",
     "type": "timeseries",
     "description": "Footprint of blocks written to the volume in bytes for capacity tier (bin 1).",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_capacity_tier_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_capacity_tier_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}} "
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Capacity Tier Footprint %",
     "type": "timeseries",
     "description": "Footprint of blocks written to the volume in capacity tier (bin 1) as a percentage of aggregate size.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_capacity_tier_footprint_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_capacity_tier_footprint_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}} "
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Delayed Free Footprint",
     "type": "timeseries",
     "description": "This field represents the delayed free blocks footprint. This is used to improve delete performance by batching delete requests.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_delayed_free_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_delayed_free_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}} "
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Metadata Footprint",
     "type": "timeseries",
     "description": "This represents flexible metadata for a volume.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_metadata_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_metadata_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}} "
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Total Footprint",
     "type": "timeseries",
     "description": "Volume total footprint.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_total_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_total_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}} "
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Total Metadata Footprint",
     "type": "timeseries",
     "description": "Total metadata footprint for a volume.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_total_metadata_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_total_metadata_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}} "
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Capacity Tier Footprint",
     "type": "timeseries",
     "description": "This field represents the volume guarantee footprint. Alternatively, it is the space reserved for future writes in the volume.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_guarantee_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_guarantee_footprint{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Inode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Volumes by Inode Files Used",
     "type": "timeseries",
     "description": "Number of user-visible files (inodes) used. This field is valid only when the volume is online.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "volume_inode_files_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_inode_files_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Inode Files Total",
     "type": "timeseries",
     "description": "Total user-visible file (inode) count, i.e., current maximum number of user-visible files (inodes) that this volume can currently hold.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "volume_inode_files_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_inode_files_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Inode Files Used Percentage",
     "type": "timeseries",
     "description": "volume_inode_files_used / volume_inode_total.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_inode_used_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_inode_used_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sis Stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
     "options": {
      "content": "This panel requires ONTAP 9.12+ and the APIs are only available via REST. Enable the REST collector in your `harvest.yml` config.<br>\nSee https://github.com/NetApp/harvest/wiki/Troubleshooting-Harvest#why-do-i-have-volume-sis-stat-panel-empty-in-volume-dashboard for more details."
     }
    },
    {
     "title": "Top $TopResources Volumes by Number of Compress Fail %",
     "type": "timeseries",
     "description": "Percent of compress fail.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(\n      (\n          volume_num_compress_fail{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n        *\n          100\n      )\n    /\n      volume_num_compress_attempts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n            avg_over_time(\n              volume_num_compress_fail{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n            )\n          * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n            (\n              max by (datacenter, netapp_cluster, svm, volume, node) (\n                volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n              )\n            )\n        /\n          avg_over_time(\n            volume_num_compress_attempts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n          )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Number of Compress Attempts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "volume_num_compress_attempts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_num_compress_attempts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Number of Compress Fail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "volume_num_compress_fail{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_num_compress_fail{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Growth Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top $TopResources Volumes Per Growth Rate of Physical Used",
     "type": "timeseries",
     "description": "Physical space used growth rate per second in the volume.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "deriv(\n    volume_space_physical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[4m]\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_space_physical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes Per Growth Rate of Logical Used",
     "type": "timeseries",
     "description": "Logical space used growth rate per second in the volume.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "deriv(\n    volume_space_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[4m]\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_space_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Physical Usage: Delta",
     "type": "table",
     "description": "This panel tracks changes in the physical usage space of the top $TopResources volumes by physical space. It includes the following delta columns:\n\n- **1-Day Delta:** This column shows the change in physical usage space over the past 24 hours. \n  \n- **7-Day Delta:** This column displays the change in physical usage space over the past 7 days.\n  \n- **Time Range Delta:** This column reflects the change in physical usage space over the selected time range in the Grafana dashboard.\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "label_join(\n    delta(\n      volume_space_physical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[1d]\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"netapp_cluster\",\n    \"svm\",\n    \"volume\"\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_space_physical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h]\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )"
      },
      {
       "expr": "label_join(\n    delta(\n      volume_space_physical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[1w]\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"netapp_cluster\",\n    \"svm\",\n    \"volume\"\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_space_physical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h]\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )"
      },
      {
       "expr": "label_join(\n    delta(\n      volume_space_physical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[$__range]\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"netapp_cluster\",\n    \"svm\",\n    \"volume\"\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_space_physical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h]\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Logical Usage: Delta",
     "type": "table",
     "description": "This panel tracks changes in the logical usage space of the top $TopResources volumes by logical space. It includes the following delta columns:\n\n- **1-Day Delta:** This column shows the change in logical usage space over the past 24 hours. \n  \n- **7-Day Delta:** This column displays the change in logical usage space over the past 7 days.\n  \n- **Time Range Delta:** This column reflects the change in logical usage space over the selected time range in the Grafana dashboard.\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "label_join(\n    delta(\n      volume_space_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[1d]\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"netapp_cluster\",\n    \"svm\",\n    \"volume\"\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_space_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h]\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )"
      },
      {
       "expr": "label_join(\n    delta(\n      volume_space_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[1w]\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"netapp_cluster\",\n    \"svm\",\n    \"volume\"\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_space_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h]\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )"
      },
      {
       "expr": "label_join(\n    delta(\n      volume_space_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[$__range]\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"netapp_cluster\",\n    \"svm\",\n    \"volume\"\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_space_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h]\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )"
      }
     ]
    }
   ]
  },
  {
   "title": "Forecast Volume Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top $TopResources Volumes Per Size Used Percentage Trend",
     "type": "table",
     "description": "This table would show 15 day predicted value of size used percentage for top volumes.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "predict_linear(\n    volume_size_used_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3d],\n    15 * 24 * 3600\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_size_used_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )"
      },
      {
       "expr": "volume_size_used_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_size_used_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style!=\"flexgroup_constituent\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n        )\n      * on (datacenter, netapp_cluster, svm, volume) group_left (node)\n        (\n          max by (datacenter, netapp_cluster, svm, volume, node) (\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"}\n          )\n        )\n    )\n  )"
      }
     ]
    }
   ]
  }
 ]
}