linters:
  disable-all: true
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - gosec
    - gosimple
    - govet
    - ineffassign
    - intrange
    - makezero
    - mirror
    - nilerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - reassign
    - revive
    - sloglint
    - staticcheck
    - stylecheck
    - tenv
    - testifylint
    - thelper
    - testableexamples
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign

run:
  timeout: 10m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  include:
    - EXC0009

output:
  formats:
  - format: colored-line-number

linters-settings:
  thelper:
    test:
      begin: false
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - exposedSyncMutex
      - hugeParam
      - octalLiteral
      - paramTypeCombine
      - rangeValCopy
      - regexpSimplify
      - typeDefFirst
      - unnamedResult
      - whyNoLint
  dogsled:
    max-blank-identifiers: 3
