linters:
  disable-all: true
  enable:
#    - bodyclose
    - deadcode
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - staticcheck
    - structcheck
    - stylecheck
    - tenv
    - thelper
    - typecheck
    - unconvert
    - unused
    - varcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: github-actions

linters-settings:
  thelper:
    test:
      begin: false
