# This dummy api call is used for appending security related non-get iter response via plugin
name:       Security
query:      cluster-identity-get
object:     security

counters:
  - ^^cluster-uuid             =>  uuid

collect_only_labels: true
no_max_records: true

plugins:
  - Security:
      schedule:
        - data: 180s  # should be multiple of data poll duration

export_options:
  instance_keys:
    - uuid
  instance_labels:
    - fips_enabled
    - rsh_enabled
    - telnet_enabled