{
 "title": "ONTAP: LUN 7 mode",
 "tags": [
  "harvest",
  "ontap",
  "7mode"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(node_labels{system_type=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(lun_labels{system_type=\"7mode\",datacenter=~\"$Datacenter\"}, node)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(lun_labels{datacenter=~\"$Datacenter\",node=~\"$Node\"}, volume)"
    }
   },
   {
    "name": "LUN",
    "query": {
     "query": "label_values(lun_labels{datacenter=~\"$Datacenter\",node=~\"$Node\", volume=~\"$Volume\"},lun)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LUN Average Read Latency",
   "type": "stat",
   "description": "Average Latency of top $TopResources volumes",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(topk($TopResources, lun_avg_read_latency{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}))/1000"
    }
   ]
  },
  {
   "title": "LUN Average Write Latency",
   "type": "stat",
   "description": "Average Latency of top $TopResources volumes",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(topk($TopResources, lun_avg_write_latency{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}))/1000"
    }
   ]
  },
  {
   "title": "Total Read Throughput",
   "type": "stat",
   "description": "Throughput of top $TopResources volumes",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(topk($TopResources, lun_read_data{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}))"
    }
   ]
  },
  {
   "title": "Total Write Throughput",
   "type": "stat",
   "description": "Throughput of top $TopResources volumes",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(topk($TopResources, lun_write_data{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}))"
    }
   ]
  },
  {
   "title": "Total Read IOPs",
   "type": "stat",
   "description": "IOPs of top $TopResources volumes",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(topk($TopResources, lun_read_ops{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}))"
    }
   ]
  },
  {
   "title": "Total Write IOPs",
   "type": "stat",
   "description": "IOPs of top $TopResources volumes",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(topk($TopResources, lun_write_ops{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}))"
    }
   ]
  },
  {
   "title": "LUN Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Latency",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_avg_read_latency{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"})/1000"
      }
     ]
    },
    {
     "title": "Read Throughput",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_read_data{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"})"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_read_ops{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"})"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_avg_write_latency{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"})/1000",
       "legendFormat": "{{svm}}/{{volume}}/{{lun}}"
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_write_data{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"})"
      }
     ]
    },
    {
     "title": "Write IOPS",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_write_ops{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"})"
      }
     ]
    },
    {
     "title": "LUNS in Node",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lun_labels{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}"
      },
      {
       "expr": "lun_new_status{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}"
      },
      {
       "expr": "lun_size{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}"
      },
      {
       "expr": "lun_size_used{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top LUN Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Average Read Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_avg_read_latency{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"})/1000",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top Read Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_read_data{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"})",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top Read IOPs",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_read_ops{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"})",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top Average Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_avg_write_latency{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"})/1000",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_write_data{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"})",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top Write IOPs",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_write_ops{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"})",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top LUN Performance Efficiency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top LUN Write Misalignment Buckets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_write_align_histo{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"})",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} : {{metric}}"
      }
     ]
    },
    {
     "title": "Top LUN Read Misalignment Buckets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_read_align_histo{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"})",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} : {{metric}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Volume and LUN Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Used Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk($TopResources, volume_size_used_percent{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "LUN Percent Least Filled",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_size_used/lun_size{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "LUN Percent Most Filled",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk($TopResources, lun_size_used/lun_size{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per LUN (Must Select Node/SVM/Volume/LUN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "lun_avg_read_latency{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}/1000",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
      },
      {
       "expr": "lun_avg_write_latency{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}/1000",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "lun_read_data{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
      },
      {
       "expr": "lun_write_data{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
      }
     ]
    },
    {
     "title": "IOPs",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "lun_read_ops{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
      },
      {
       "expr": "lun_write_ops{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
      }
     ]
    },
    {
     "title": "IO Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "lun_read_data/lun_read_ops{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}/1024",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
      },
      {
       "expr": "lun_write_data/lun_write_ops{datacenter=~\"$Datacenter\",node=~\"$Node\",volume=~\"$Volume\",lun=~\"$LUN\"}/1024",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
      }
     ]
    }
   ]
  }
 ]
}