{
 "title": "ONTAP: Shelf 7 mode",
 "tags": [
  "harvest",
  "ontap",
  "7mode"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(shelf_labels{system_type=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(shelf_labels{system_type=\"7mode\",datacenter=~\"$Datacenter\"}, node)"
    }
   },
   {
    "name": "Channel",
    "query": {
     "query": "label_values(shelf_labels{datacenter=~\"$Datacenter\",node=~\"$Node\"}, channel)"
    }
   },
   {
    "name": "Shelf",
    "query": {
     "query": "label_values(shelf_labels{datacenter=~\"$Datacenter\",node=~\"$Node\",channel=~\"$Channel\"}, shelf)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Shelves",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(shelf_labels{datacenter=~\"$Datacenter\",node=~\"$Node\",channel=~\"$Channel\"}) by (shelf_id))"
    }
   ]
  },
  {
   "title": "Temperature Avg",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(shelf_temperature_reading{datacenter=~\"$Datacenter\",node=~\"$Node\",channel=~\"$Channel\"})"
    }
   ]
  },
  {
   "title": "Fan RPM Avg",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(shelf_fan_rpm{datacenter=~\"$Datacenter\",node=~\"$Node\",channel=~\"$Channel\"})"
    }
   ]
  },
  {
   "title": "Custom Sensor Avg",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(shelf_sensor_reading{datacenter=~\"$Datacenter\",node=~\"$Node\",channel=~\"$Channel\"})"
    }
   ]
  },
  {
   "title": "Shelves",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "shelf_labels{datacenter=~\"$Datacenter\",node=~\"$Node\",channel=~\"$Channel\"}"
    },
    {
     "expr": "shelf_new_status{datacenter=~\"$Datacenter\",node=~\"$Node\",channel=~\"$Channel\"}"
    }
   ]
  },
  { "title": "Temperature Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Temperature Sensors",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 14 },
   "repeat": "TempShelf",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shelf_temperature_reading{datacenter=~\"$Datacenter\",node=~\"$Node\",channel=~\"$Channel\",shelf=~\"$Shelf\"}",
     "legendFormat": "{{shelf}} · {{sensor_id}}"
    }
   ]
  },
  {
   "title": "Cooling Sensors",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "repeat": "FanShelf",
   "fieldConfig": { "defaults": { "unit": "RPM" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shelf_fan_rpm{datacenter=~\"$Datacenter\",node=~\"$Node\",channel=~\"$Channel\",shelf=~\"$Shelf\"}",
     "legendFormat": "{{shelf}} · {{fan_id}}"
    }
   ]
  },
  { "title": "Voltage & PSU Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Voltage Sensors",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "shelf_voltage_reading{datacenter=~\"$Datacenter\",node=~\"$Node\",channel=~\"$Channel\",shelf=~\"$Shelf\"}",
     "legendFormat": "{{shelf}} · {{sensor_id}}"
    }
   ]
  },
  { "title": "Custom Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Custom Sensors - Shelf",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 49 },
   "repeat": "SensShelf",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shelf_sensor_reading{datacenter=~\"$Datacenter\",node=~\"$Node\",channel=~\"$Channel\",shelf=~\"$Shelf\"}",
     "legendFormat": "{{shelf}} · {{sensor_id}}"
    }
   ]
  }
 ]
}