collector:          StatPerf

# Order here matters!
schedule:
  - counter:  24h
  - instance: 10m
  - data:      1m

objects:
  FlexCache:                flexcache.yaml
  FcpPort:                  fcp.yaml
  SystemNode:               system_node.yaml
  NicCommon:                nic_common.yaml
  NvmMirror:                nvm_mirror.yaml