collector:          KeyPerf

# Order here matters!
schedule:
  - counter:  24h
  - data:      1m

objects:
  Aggregate:                   aggr.yaml
  CIFSvserver:                 cifs_vserver.yaml
  Cluster:                     cluster.yaml
  FlexCache:                   flexcache.yaml
  LIF:                         lif.yaml
  NFSv3:                       nfsv3.yaml
  NFSv41:                      nfsv4_1.yaml
  NFSv4:                       nfsv4.yaml
  SystemNode:                  node.yaml
  Volume:                      volume.yaml
  Qtree:                       qtree.yaml
