
collector:          Zapi

# Order here matters!
schedule:
  - data: 180s

objects:
  Aggregate:                   aggr.yaml
  AggregateEfficiency:         aggr_efficiency.yaml
  ClusterPeer:                 clusterpeer.yaml
  Disk:                        disk.yaml
  Lun:                         lun.yaml
#  NetPort:                     netPort.yaml
  Node:                        node.yaml
  NtpServer:                   ntpserver.yaml
  QosPolicy:                   qos_policy_fixed.yaml
  Qtree:                       qtree.yaml
  Security:                    security.yaml
  SecurityAccount:             security_account.yaml
  SecurityAuditDestination:    security_audit_dest.yaml
  SecurityCert:                security_certificate.yaml
  SecurityLogin:               security_login.yaml
  Sensor:                      sensor.yaml
  Shelf:                       shelf.yaml
  SnapMirror:                  snapmirror.yaml
  SnapshotPolicy:              snapshotPolicy.yaml
  Status:                      status.yaml
  Status_7mode:                status_7.yaml
  Subsystem:                   subsystem.yaml
  Support:                     support.yaml
  SVM:                         svm.yaml
  Volume:                      volume.yaml

