
collector:          Zapi
  
client_timeout: 180

# Order here matters!
schedule:
  - instance: 600s
  - data: 180s

objects:
  Node:             node.yaml
  Aggregate:        aggr.yaml
  Volume:           volume.yaml
  SnapMirror:       snapmirror.yaml
  Disk:             disk.yaml
  Shelf:            shelf.yaml
  Status:           status.yaml
  Subsystem:        subsystem.yaml
  Lun:              lun.yaml
  Status_7mode:     status_7.yaml
  Sensor:           sensor.yaml
  Qtree:            qtree.yaml
