{
 "title": "Harvest Metadata",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Datacenter",
    "query": "from(bucket: \"harvest\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"status\")\r\n  |> keep(columns: [\"datacenter\"])\r\n  |> group()\r\n  |> distinct(column: \"datacenter\")"
   },
   {
    "name": "Hostname",
    "query": "from(bucket: \"harvest\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"status\")\r\n  |> keep(columns: [\"hostname\"])\r\n  |> group()\r\n  |> distinct(column: \"hostname\")"
   },
   {
    "name": "Poller",
    "query": "from(bucket: \"harvest\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"status\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> keep(columns: [\"poller\"])\r\n  |> group()\r\n  |> distinct(column: \"poller\")"
   },
   {
    "name": "Collector",
    "query": "from(bucket: \"harvest\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"_field\"] == \"status\" and r[\"type\"] == \"collector\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> keep(columns: [\"name\"])\r\n  |> group()\r\n  |> distinct(column: \"name\")"
   },
   {
    "name": "Object",
    "query": "from(bucket: \"harvest\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"_field\"] == \"status\" and r[\"type\"] == \"collector\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"name\"], set: ${Collector:json}))\r\n  |> keep(columns: [\"target\"])\r\n  |> group()\r\n  |> distinct(column: \"target\")"
   },
   {
    "name": "Exporter",
    "query": "from(bucket: \"harvest\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"_field\"] == \"status\" and r[\"type\"] == \"exporter\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> keep(columns: [\"target\"])\r\n  |> group()\r\n  |> distinct(column: \"target\")"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Datacenters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"status\")\r\n  |> group()\r\n  |> unique(column: \"datacenter\")\r\n  |> count(column: \"datacenter\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pollers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"status\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> group()\r\n  |> unique(column: \"poller\")\r\n  |> count(column: \"poller\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Collectors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"_field\"] == \"status\" and r[\"type\"] == \"collector\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> map(fn: (r) => ({unique_name: r.name + \"_\" + r.target}) )\r\n  |> unique(column: \"unique_name\")\r\n  |> count(column: \"unique_name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"_field\"] == \"status\" and r[\"type\"] == \"exporter\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> map(fn: (r) => ({unique_name: r.name + \"_\" + r.target}) )\r\n  |> unique(column: \"unique_name\")\r\n  |> count(column: \"unique_name\")\r\n  |> yield(name: \"count\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Collected/1m",
   "type": "stat",
   "description": "Data points collected every minute",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"_field\"] == \"count\" and r[\"type\"] == \"collector\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"name\"], set: ${Collector:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"target\"], set: ${Object:json}))\r\n  |> group()\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exported/1m",
   "type": "stat",
   "description": "Data points exported per minute",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"_field\"] == \"count\" and r[\"type\"] == \"exporter\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"target\"], set: ${Exporter:json}))  \r\n  |> group()\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "description": "System CPU used by Harvest Pollers. Number can be higher than 100% on multi-core systems.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"cpu_percent\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group()\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "description": "System Memory used by Harvest Pollers",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"memory_percent\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group()\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pollers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"status\")\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\n  |> last()\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({r with status: int(v: r._value) }) )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Target Systems",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_target\" and r[\"_field\"] == \"ping\")\n  |> last()\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_target\" and r[\"_field\"] == \"status\")\n  |> last()\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({r with status: int(v: r._value) }) )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Collectors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"_field\"] == \"status\" and r[\"type\"] == \"collector\")\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\n  |> filter(fn: (r) => contains(value: r[\"name\"], set: ${Collector:json}))\n  |> filter(fn: (r) => contains(value: r[\"target\"], set: ${Object:json}))\n  |> last()\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({r with status: int(v: r._value) }) )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"_field\"] == \"status\" and r[\"type\"] == \"exporter\")\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\n  |> filter(fn: (r) => contains(value: r[\"target\"], set: ${Exporter:json}))\n  |> last()\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with status: int(v: r._value) }) )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average poll time per poller",
   "type": "graph",
   "description": "Average duration of data poll of all collectors",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"poll_time\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"poller\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average poll time per collector",
   "type": "graph",
   "description": "Average duration of data poll (includes API time and plugins)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"poll_time\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"collector\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average export time per exporter",
   "type": "graph",
   "description": "Average export time (includes render time)",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"export_time\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"exporter\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Resources Used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization %",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and  r[\"_field\"] == \"cpu_percent\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"hostname\"], set: ${Hostname:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"poller\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory Utilization %",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "   from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"poller\" and r._field == \"memory_percent\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"hostname\"], set: ${Hostname:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"poller\"], mode:\"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU times: Breakdown",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "clocks" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_iowait\" or r[\"_field\"] == \"cpu_system\" or r[\"_field\"] == \"cpu_user\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"hostname\"], set: ${Hostname:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"poller\", \"_field\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory breakdown",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"memory_swap\" or r[\"_field\"] == \"memory_shared\" or r[\"_field\"] == \"memory_rss\" or r[\"_field\"] == \"memory_private\" or r[\"_field\"] == \"memory_anonymous\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"hostname\"], set: ${Hostname:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"poller\", \"_field\"], mode:\"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"memory_vms\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"hostname\"], set: ${Hostname:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"poller\", \"_field\"], mode:\"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "IO Bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "import \"experimental/aggregate\"\r\nfrom(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"io_write_bytes\" or r[\"_field\"] == \"io_read_bytes\" or r[\"_field\"] == \"io_cancelled_write_bytes\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"hostname\"], set: ${Hostname:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> aggregate.rate(every: 1m, groupColumns: [\"poller\", \"_field\"], unit: 1s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "IO Chars",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "import \"experimental/aggregate\"\r\nfrom(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"io_wchar\" or r[\"_field\"] == \"io_rchar\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"hostname\"], set: ${Hostname:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> aggregate.rate(every: 1m, groupColumns: [\"poller\", \"_field\"], unit: 1s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "IO Syscalls",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "import \"experimental/aggregate\"\r\nfrom(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"io_syscw\" or r[\"_field\"] == \"io_syscr\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"hostname\"], set: ${Hostname:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> aggregate.rate(every: 1m, groupColumns: [\"poller\", \"_field\"], unit: 1s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Net IO Bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "import \"experimental/aggregate\"\r\nfrom(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"net_sent_bytes\" or r[\"_field\"] == \"net_rcv_bytes\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"hostname\"], set: ${Hostname:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> aggregate.rate(every: 1m, groupColumns: [\"poller\", \"_field\"], unit: 1s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Net IO Packets",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "import \"experimental/aggregate\"\r\nfrom(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"net_sent_packets\" or r[\"_field\"] == \"net_rcv_packets\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"hostname\"], set: ${Hostname:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> aggregate.rate(every: 1m, groupColumns: [\"poller\", \"_field\"], unit: 1s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network IO Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "import \"experimental/aggregate\"\r\nfrom(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"net_sent_errs\" or r[\"_field\"] == \"net_rcv_errs\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"hostname\"], set: ${Hostname:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> aggregate.rate(every: 1m, groupColumns: [\"poller\", \"_field\"], unit: 1s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FDs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"fds\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"hostname\"], set: ${Hostname:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"poller\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"threads\")\r\n  |> filter(fn: (r) => contains(value: r[\"datacenter\"], set: ${Datacenter:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"hostname\"], set: ${Hostname:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"poller\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_target\" and r[\"_field\"] == \"goroutines\")\r\n  |> filter(fn: (r) => contains(value: r[\"hostname\"], set: ${Hostname:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"poller\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Zapi collectors drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time per Data Poll",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"poll_time\" and r[\"task\"] == \"data\")\r\n  |> group(columns: [\"collector\", \"object\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": " Data Points per Poll",
     "type": "graph",
     "description": "API wait time of each data poll",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"count\" and r[\"task\"] == \"data\")\r\n  |> group(columns: [\"collector\", \"object\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "API Time",
     "type": "graph",
     "description": "API wait time of each data poll",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"api_time\" and r[\"task\"] == \"data\")\r\n  |> group(columns: [\"collector\", \"object\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "XML Parse Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"parse_time\" and r[\"task\"] == \"data\")\r\n  |> group(columns: [\"collector\", \"object\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Postprocessing Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"harvest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"calc_time\" and r[\"task\"] == \"data\")\r\n  |> group(columns: [\"collector\", \"object\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}