{
 "title": "ONTAP: SVM",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Bucket", "label": "Data Source", "query": "buckets()" },
   {
    "name": "Datacenter",
    "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"svm_nfs\" or r._measurement == \"svm_cifs\")\r\n  |> keep(columns: [\"datacenter\"])\r\n  |> group()\r\n  |> distinct(column: \"datacenter\")"
   },
   {
    "name": "Cluster",
    "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"svm_nfs\" or r._measurement == \"svm_cifs\")\r\n  |> filter(fn: (r) => r.datacenter == \"${Datacenter}\")\r\n  |> keep(columns: [\"cluster\"])\r\n  |> group()\r\n  |> distinct(column: \"cluster\")"
   },
   {
    "name": "SVM",
    "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"svm_nfs\" or r._measurement == \"svm_cifs\")\r\n  |> filter(fn: (r) => r.cluster == \"${Cluster}\")\r\n  |> keep(columns: [\"svm\"])\r\n  |> group()\r\n  |> distinct(column: \"svm\")"
   },
   {
    "name": "NFSv",
    "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"svm_nfs\")\r\n  |> filter(fn: (r) => r.cluster == \"${Cluster}\")\r\n  |> keep(columns: [\"nfsv\"])\r\n  |> group()\r\n  |> distinct(column: \"nfsv\")"
   }
  ]
 },
 "panels": [
  { "title": "NFS${NFSv} Frontend Drilldown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"svm_nfs\" and r[\"_field\"] == \"read_avg_latency\" and r[\"nfsv\"] == \"${NFSv}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"svm\"], set: ${SVM:json}))\r\n  |> group()\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"svm_nfs\" and r[\"_field\"] == \"write_avg_latency\" and r[\"nfsv\"] == \"${NFSv}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"svm\"], set: ${SVM:json}))\r\n  |> group()\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"svm_nfs\" and r[\"_field\"] == \"latency\" and r[\"nfsv\"] == \"${NFSv}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"svm\"], set: ${SVM:json}))\r\n  |> group()\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read IOPs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"svm_nfs\" and r[\"_field\"] == \"read_total\" and r[\"nfsv\"] == \"${NFSv}\")\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\n  |> filter(fn: (r) => contains(value: r[\"svm\"], set: ${SVM:json}))\n  |> group()\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false) "
    }
   ]
  },
  {
   "title": "Write IOPs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"svm_nfs\" and r[\"_field\"] == \"write_total\" and r[\"nfsv\"] == \"${NFSv}\")\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\n  |> filter(fn: (r) => contains(value: r[\"svm\"], set: ${SVM:json}))\n  |> group()\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false) "
    }
   ]
  },
  {
   "title": "Totsl IOPs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"svm_nfs\" and r[\"_field\"] == \"ops\" and r[\"nfsv\"] == \"${NFSv}\")\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\n  |> filter(fn: (r) => contains(value: r[\"svm\"], set: ${SVM:json}))\n  |> group()\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false) "
    }
   ]
  },
  {
   "title": "Read and Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"svm_nfs\" and r[\"nfsv\"] == \"${NFSv}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"write_avg_latency\" or r[\"_field\"] == \"read_avg_latency\" )\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\n  |> filter(fn: (r) => contains(value: r[\"svm\"], set: ${SVM:json}))\n  |> group(columns: [\"_field\"], mode: \"by\")\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false) "
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"svm_nfs\" and r[\"nfsv\"] == \"${NFSv}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"read_throughput\" or r[\"_field\"] == \"write_throughput\" )\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\n  |> filter(fn: (r) => contains(value: r[\"svm\"], set: ${SVM:json}))\n  |> group(columns: [\"_field\"], mode: \"by\")\n  |> map(fn: (r) => ({r with status: int(v: r._value) }) )\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"svm_nfs\" and r[\"nfsv\"] == \"${NFSv}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"throughput\" )\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\n  |> filter(fn: (r) => contains(value: r[\"svm\"], set: ${SVM:json}))\n  |> map(fn: (r) => ({r with renamed: \"total\" }) )\n  |> group(columns: [\"renamed\"], mode: \"by\")\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "IOPs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"svm_nfs\" and r[\"nfsv\"] == \"${NFSv}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"read_total\" or r[\"_field\"] == \"write_total\" )\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\n  |> filter(fn: (r) => contains(value: r[\"svm\"], set: ${SVM:json}))\n  |> group(columns: [\"_field\"], mode: \"by\")\n  |> map(fn: (r) => ({r with status: int(v: r._value) }) )\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"svm_nfs\" and r[\"nfsv\"] == \"${NFSv}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ops\" )\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\n  |> filter(fn: (r) => contains(value: r[\"svm\"], set: ${SVM:json}))\n  |> map(fn: (r) => ({r with renamed: \"total\" }) )\n  |> group(columns: [\"renamed\"], mode: \"by\")\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Latency per Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"svm_nfs\" and r[\"nfsv\"] == \"${NFSv}\")\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\n  |> filter(fn: (r) => contains(value: r[\"svm\"], set: ${SVM:json}))\n  |> filter(fn: (r) => r[\"_field\"] =~ /_avg_latency/ )\n  |> filter(fn: (r) => r[\"_field\"] != \"read_avg_latency\" and r[\"_field\"] != \"write_avg_latency\")\n  |> group(columns: [\"_field\"], mode: \"by\")\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false) "
    }
   ]
  },
  {
   "title": "IOPs per Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"svm_nfs\" and r[\"nfsv\"] == \"${NFSv}\")\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\n  |> filter(fn: (r) => contains(value: r[\"svm\"], set: ${SVM:json}))\n  |> filter(fn: (r) => r[\"_field\"] =~ /_total/ )\n  |> filter(fn: (r) => r[\"_field\"] != \"read_total\" and r[\"_field\"] != \"write_total\")\n  |> group(columns: [\"_field\"], mode: \"by\")\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false) "
    }
   ]
  }
 ]
}