collector: Ems

client_timeout: 1m
schedule:
  - instance: 24h
  - data:     3m

# More information https://github.com/NetApp/harvest/blob/main/cmd/collectors/ems/README.md

objects:
  Ems: ems.yaml

