collector: Ems

#  Keep this below the data interval below.
client_timeout: 2m

schedule:
  - instance: 24h
  - data:     3m

# More information https://netapp.github.io/harvest/latest/configure-ems

objects:
  Ems: ems.yaml

