/*
	Copyright NetApp Inc, 2021 All rights reserved

	Package imports the modules that should be dynamically loaded by Harvest.
	File is generated by Makefile.
*/

package modules

import (
	_ "github.com/vgratian/GithubCollector"
	_ "goharvest2/cmd/collectors/unix"
	_ "goharvest2/cmd/collectors/zapi/collector"
	_ "goharvest2/cmd/collectors/zapiperf"
)
