/*
	Copyright NetApp Inc, 2021 All rights reserved

	Package imports the modules that should be dynamically loaded by Harvest.
	File is generated by Makefile. Don't edit manually.
*/

package modules

import (
	_ "goharvest2/cmd/collectors/unix"
	_ "goharvest2/cmd/collectors/zapi/collector"
	_ "goharvest2/cmd/collectors/zapi/plugins/shelf"
	_ "goharvest2/cmd/collectors/zapi/plugins/snapmirror"
	_ "goharvest2/cmd/collectors/zapiperf"
	_ "goharvest2/cmd/collectors/zapiperf/plugins/fcp"
	_ "goharvest2/cmd/collectors/zapiperf/plugins/headroom"
	_ "goharvest2/cmd/collectors/zapiperf/plugins/nic"
	_ "goharvest2/cmd/collectors/zapiperf/plugins/volume"
	_ "goharvest2/cmd/exporters/influxdb"
	_ "goharvest2/cmd/exporters/prometheus"
)
