apiVersion: v2
name: harvest
description: NetApp Harvest exporter for NetApp ONTAP storage systems.
type: application
version: 0.1.0
appVersion: 26.02.0
icon: https://raw.githubusercontent.com/NetApp/harvest/refs/heads/main/docs/assets/harvest.svg
keywords:
  - netapp
  - harvest
  - ontap
  - prometheus
  - grafana
maintainers:
  - name: NetApp
    url: https://github.com/NetApp/harvest
sources:
  - https://github.com/NetApp/harvest
