{
 "title": "NetApp Detail: SVM - Details",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(volume_labels, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(volume_labels{datacenter=\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}, svm)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Highlights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "SVM Average Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(volume_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000"
      }
     ]
    },
    {
     "title": "SVM Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(volume_read_data+volume_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(volume_total_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM Average Read Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(volume_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000"
      }
     ]
    },
    {
     "title": "SVM Average Write Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(volume_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000"
      }
     ]
    },
    {
     "title": "SVM Read Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM Write Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(volume_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM Read Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(volume_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM Write Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(volume_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM Average Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(volume_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(volume_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Write"
      },
      {
       "expr": "avg(volume_other_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "SVM Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(volume_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "SVM Throughput (IOPs)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(volume_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(volume_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(volume_other_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Other"
      }
     ]
    }
   ]
  },
  {
   "title": "Volumes Performance Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Read Latency",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "volume_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}/ 1000",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Volume Read Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Volume Read Throughput (IOPs)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "volume_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Volume Write Latency",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "volume_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}/ 1000",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Volume Write Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "volume_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Volume Write Throughput (IOPs)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "volume_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NAS LIF Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "NAS LIF Send Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "lif_sent_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    },
    {
     "title": "NAS LIF Receive Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "lif_recv_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    },
    {
     "title": "NVMe/FC LIF Send Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "nvme_lif_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    },
    {
     "title": "NVMe/FC LIF Receive Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "nvme_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    },
    {
     "title": "iSCSI LIF Send Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "iscsi_lif_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    },
    {
     "title": "iSCSI LIF Receive Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "iscsi_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CIFS Frontend Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "SVM CIFS Average Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(svm_cifs_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000"
      }
     ]
    },
    {
     "title": "SVM CIFS Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(svm_cifs_read_ops+svm_cifs_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM CIFS Connections and Open Files",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "svm_cifs_connections{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "Connections"
      },
      {
       "expr": "svm_cifs_open_files{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "Open Files"
      }
     ]
    },
    {
     "title": "SVM CIFS Average Read Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(svm_cifs_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000"
      }
     ]
    },
    {
     "title": "SVM CIFS Average Read Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(svm_cifs_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000"
      }
     ]
    },
    {
     "title": "SVM CIFS Read Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(svm_cifs_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM CIFS Write Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(svm_cifs_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM CIFS Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(svm_cifs_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(svm_cifs_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "SVM CIFS Throughput (IOPs)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(svm_cifs_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(svm_cifs_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "SVM CIFS IOP by Type",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "svm_cifs_op_count{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FCP Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "SVM FCP Average Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(fcp_lif_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000"
      }
     ]
    },
    {
     "title": "SVM FCP Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fcp_lif_read_data+fcp_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM FCP Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fcp_lif_total_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM FCP Average Read Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(fcp_lif_avg_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000"
      }
     ]
    },
    {
     "title": "SVM FCP Average Write Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(fcp_lif_avg_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000"
      }
     ]
    },
    {
     "title": "SVM FCP Read Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fcp_lif_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM FCP Write Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fcp_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM FCP Read Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fcp_lif_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM FCP Write Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fcp_lif_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM FCP Average Latency",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(fcp_lif_avg_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(fcp_lif_avg_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Write"
      },
      {
       "expr": "avg(fcp_lif_avg_other_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Other"
      },
      {
       "expr": "avg(fcp_lif_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "SVM FCP Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(fcp_lif_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(fcp_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "SVM FCP Throughput (IOPs)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(fcp_lif_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(fcp_lif_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(fcp_lif_other_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "FCP LIF Send Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "fcp_lif_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    },
    {
     "title": "FCP LIF Receive Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "fcp_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    }
   ]
  },
  {
   "title": "iSCSI Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "SVM iSCSI Average Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(iscsi_lif_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000"
      }
     ]
    },
    {
     "title": "SVM iSCSI Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(iscsi_lif_read_data+iscsi_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM iSCSI Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(iscsi_lif_iscsi_read_ops+iscsi_lif_iscsi_write_ops+iscsi_lif_iscsi_other_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM iSCSI Average Read Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(iscsi_lif_avg_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000"
      }
     ]
    },
    {
     "title": "SVM iSCSI Average Write Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(iscsi_lif_avg_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000"
      }
     ]
    },
    {
     "title": "SVM iSCSI Read Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(iscsi_lif_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM iSCSI Write Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(iscsi_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM iSCSI Read Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(iscsi_lif_iscsi_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM iSCSI Write Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(iscsi_lif_iscsi_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM iSCSI Average Latency",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(iscsi_lif_avg_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(iscsi_lif_avg_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Write"
      },
      {
       "expr": "avg(iscsi_lif_avg_other_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "SVM iSCSI Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(iscsi_lif_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(iscsi_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "SVM FCP Throughput (IOPs)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(fcp_lif_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(fcp_lif_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(fcp_lif_other_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "iSCSI LIF Send Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "iscsi_lif_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    },
    {
     "title": "iSCSI LIF Receive Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "iscsi_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NFSv3 Frontend Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFSv3 Avg Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(svm_nfs_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"}) / 1000"
      }
     ]
    },
    {
     "title": "NFSv3 Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "svm_nfs_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"}"
      }
     ]
    },
    {
     "title": "NFSv3 Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "svm_nfs_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"}"
      }
     ]
    },
    {
     "title": "NFSv3 Read Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(svm_nfs_read_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"}) / 1000"
      }
     ]
    },
    {
     "title": "NFSv3 Write Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(svm_nfs_write_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"}) / 1000"
      }
     ]
    },
    {
     "title": "NFSv3  Read Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "svm_nfs_read_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"}"
      }
     ]
    },
    {
     "title": "NFSv3  Write Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "svm_nfs_write_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"}"
      }
     ]
    },
    {
     "title": "NFSv3 Read Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "svm_nfs_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"}"
      }
     ]
    },
    {
     "title": "NFSv3 Write Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "svm_nfs_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"}"
      }
     ]
    },
    {
     "title": "NFSv3 Read and Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "svm_nfs_read_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"} / 1000",
       "legendFormat": "Read"
      },
      {
       "expr": "svm_nfs_write_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"} / 1000",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "NFSv3 Read and Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "svm_nfs_read_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"} / 1000",
       "legendFormat": "Read"
      },
      {
       "expr": "svm_nfs_write_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"} / 1000",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "NFSv3 IOPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "svm_nfs_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "svm_nfs_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"}",
       "legendFormat": "Write"
      },
      {
       "expr": "svm_nfs_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "NFSv3 Latency by Op Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"svm_nfs_.+_avg_latency\",datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "NFSv3 IOPs per Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"svm_nfs_.+_total\",datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v3\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NFSv4 Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFSv4 Avg Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(svm_nfs_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}) / 1000"
      }
     ]
    },
    {
     "title": "NFSv4 Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "svm_nfs_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}"
      }
     ]
    },
    {
     "title": "NFSv4 Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "svm_nfs_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}"
      }
     ]
    },
    {
     "title": "NFSv4 Read Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(svm_nfs_read_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}) / 1000"
      }
     ]
    },
    {
     "title": "NFSv4 Write Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(svm_nfs_write_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}) / 1000"
      }
     ]
    },
    {
     "title": "NFSv4 Read Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "svm_nfs_read_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}"
      }
     ]
    },
    {
     "title": "NFSv4 Write Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "svm_nfs_write_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}"
      }
     ]
    },
    {
     "title": "NFSv4 Read Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "svm_read_total{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}"
      }
     ]
    },
    {
     "title": "NFSv4 Write Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "svm_write_total{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}"
      }
     ]
    },
    {
     "title": "NFSv4 Read and Write Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "svm_nfs_read_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"} / 1000",
       "legendFormat": "Read"
      },
      {
       "expr": "svm_nfs_write_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"} / 1000",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "NFSv4 Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "svm_nfs_read_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "svm_nfs_write_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "NFSv4 IOPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "svm_nfs_read_total{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "svm_nfs_write_total{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}",
       "legendFormat": "Write"
      },
      {
       "expr": "svm_nfs_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "NFSv4 Latency by Op Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"svm_nfs_.+_avg_latency\",datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "NFSv4 IOPs per Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"svm_nfs_.+_total\",datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NFSv4.1 Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFSv4.1 Avg Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(svm_nfs_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}) / 1000"
      }
     ]
    },
    {
     "title": "NFSv4 .1 Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "svm_nfs_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}"
      }
     ]
    },
    {
     "title": "NFSv4.1 Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "svm_nfs_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}"
      }
     ]
    },
    {
     "title": "NFSv4.1 Read Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(svm_nfs_read_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}) / 1000"
      }
     ]
    },
    {
     "title": "NFSv4.1 Write Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(svm_nfs_write_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}) / 1000"
      }
     ]
    },
    {
     "title": "NFSv4 .1 Read Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "svm_nfs_read_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}"
      }
     ]
    },
    {
     "title": "NFSv4 .1 Write Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "svm_nfs_write_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}"
      }
     ]
    },
    {
     "title": "NFSv4.1 Read Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "svm_nfs_read_total{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}"
      }
     ]
    },
    {
     "title": "NFSv4.1 Write Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "svm_nfs_write_total{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}"
      }
     ]
    },
    {
     "title": "NFSv4 Read and Write Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "svm_nfs_read_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"} / 1000",
       "legendFormat": "Read"
      },
      {
       "expr": "svm_nfs_write_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"} / 1000",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "NFSv4.1 Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "svm_nfs_read_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "svm_nfs_write_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "NFSv4 IOPs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "svm_nfs_read_total{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "svm_nfs_write_total{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}",
       "legendFormat": "Write"
      },
      {
       "expr": "svm_nfs_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "NFSv4 Latency by Op Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"svm_nfs_.+_avg_latency\",datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "NFSv4 IOPs per Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"svm_nfs_.+_total\",datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",nfsv=\"v4.1\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NVMe/FC Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "SVM NVMe/FC Average Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(nvme_lif_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000"
      }
     ]
    },
    {
     "title": "SVM NVMe/FC Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(nvme_lif_read_data+nvme_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM NVMe/FC Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(nvme_lif_total_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM FCP Average Read Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(fcp_lif_avg_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000"
      }
     ]
    },
    {
     "title": "SVM FCP Average Write Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(fcp_lif_avg_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000"
      }
     ]
    },
    {
     "title": "SVM FCP Read Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fcp_lif_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM FCP Write Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fcp_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM FCP Read Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fcp_lif_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM FCP Write Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fcp_lif_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "SVM NVMe/FC Average Latency",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(nvme_lif_avg_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(nvme_lif_avg_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Write"
      },
      {
       "expr": "avg(nvme_lif_avg_other_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Other"
      },
      {
       "expr": "avg(nvme_lif_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}) / 1000",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "SVM NVMe/FC Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(nvme_lif_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(nvme_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "SVM NVMe/FC Throughput (IOPs)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(nvme_lif_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(nvme_lif_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(nvme_lif_other_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "SVM NVMe/FC LIF Send Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "nvme_lif_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    },
    {
     "title": "SVM NVMe/FC LIF Receive Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "nvme_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Copy Offload Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Copy Offload Data Copied",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(copy_manager_kb_copied{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "Copy Manager Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"copy_manager_.+_copy_count_curr\",datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "QoS Policy Group Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average QoS Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(qos_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})/1000"
      }
     ]
    },
    {
     "title": "QoS Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(qos_read_data+qos_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "QoS Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(qos_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "Average QoS Read Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(qos_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})/1000"
      }
     ]
    },
    {
     "title": "Average QoS Write Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(qos_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})/1000"
      }
     ]
    },
    {
     "title": "QoS Read Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(qos_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "QoS Write Throughput (Data)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(qos_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "QoS Read Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(qos_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "QoS Write Throughput (IOPs)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(qos_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})"
      }
     ]
    },
    {
     "title": "QoS Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(qos_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})/1000",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(qos_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})/1000",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "QoS Throughput (Data)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(qos_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(qos_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "QoS Throughput (IOPs)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(qos_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(qos_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Qos Sequential Reads and Writes (%)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(qos_sequential_reads{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum(qos_sequential_writes{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"})",
       "legendFormat": "Writes"
      }
     ]
    }
   ]
  },
  {
   "title": "QoS Policy Group Latency from Resource Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workload Latency from Network",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(qos_detail_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",resource=\"network\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Workload Latency from Throttle",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(qos_detail_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",resource=\"throttle\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Workload Latency from Frontend",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(qos_detail_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",resource=\"frontend\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Workload Latency from Backend",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(qos_detail_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",resource=\"backend\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Workload Latency from Cluster",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(qos_detail_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",resource=\"cluster\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Workload Latency from Disk",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(qos_detail_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",resource=\"disk\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Workload Latency from NVLog Mirroring",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(qos_detail_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",resource=\"nvlog\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Workload Latency from Suspend",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(qos_detail_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",resource=\"suspend\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Workload Latency from Cloud",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(qos_detail_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",resource=\"cloud\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume Capacity Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "SVM Volume Percent Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "volume_size_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "SVM Volume Snapshot Reserve Percent Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "volume_snapshot_reserve_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "SVM Volume Deduplication Saved Percent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "volume_sis_dedup_saved_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "SVM Volume Deduplication Savings",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "volume_sis_dedup_saved{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "SVM Volume Compression Saved Percent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "volume_sis_compress_saved_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "SVM Volume Compression Savings",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "volume_sis_compress_saved{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "SVM Volume Total Efficiency Savings",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "volume_sis_total_saved{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    }
   ]
  }
 ]
}