{
 "title": "NetApp Detail: LUN",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(lun_labels, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(lun_labels{datacenter=\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(lun_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}, svm)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(lun_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}, volume)"
    }
   },
   {
    "name": "LUN",
    "query": {
     "query": "label_values(lun_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\", volume=~\"$Volume\"},lun)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   },
   {
    "name": "SystemResources",
    "query": {
     "query": "label_values(qos_detail_volume_resource_latency,resource)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LUN Average Read Latency",
   "type": "stat",
   "description": "Average Latency of top $TopResources volumes",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(topk($TopResources, lun_avg_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}))/1000"
    }
   ]
  },
  {
   "title": "LUN Average Write Latency",
   "type": "stat",
   "description": "Average Latency of top $TopResources volumes",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(topk($TopResources, lun_avg_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}))/1000"
    }
   ]
  },
  {
   "title": "Total Read Throughput",
   "type": "stat",
   "description": "Throughput of top $TopResources volumes",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(topk($TopResources, lun_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}))"
    }
   ]
  },
  {
   "title": "Total Write Throughput",
   "type": "stat",
   "description": "Throughput of top $TopResources volumes",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(topk($TopResources, lun_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}))"
    }
   ]
  },
  {
   "title": "Total Read IOPs",
   "type": "stat",
   "description": "IOPs of top $TopResources volumes",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(topk($TopResources, lun_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}))"
    }
   ]
  },
  {
   "title": "Total Write IOPs",
   "type": "stat",
   "description": "IOPs of top $TopResources volumes",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(topk($TopResources, lun_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}))"
    }
   ]
  },
  { "title": "LUN Table Drilldown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Read Latency",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk($TopResources, lun_avg_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"})/1000"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($TopResources, lun_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"})"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk($TopResources, lun_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"})"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk($TopResources, lun_avg_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"})/1000",
     "legendFormat": "{{svm}}/{{volume}}/{{lun}}"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($TopResources, lun_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"})"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk($TopResources, lun_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"})"
    }
   ]
  },
  {
   "title": "LUNS in Cluster",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lun_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}"
    },
    {
     "expr": "lun_new_status{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}"
    },
    {
     "expr": "lun_size{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}"
    },
    {
     "expr": "lun_size_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}"
    }
   ]
  },
  { "title": "Top LUN Performance Drilldown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Top Average Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, lun_avg_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"})/1000",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
    }
   ]
  },
  {
   "title": "Top Read Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, lun_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"})",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
    }
   ]
  },
  {
   "title": "Top Read IOPs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, lun_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"})",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
    }
   ]
  },
  {
   "title": "Top Average Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, lun_avg_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"})/1000",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
    }
   ]
  },
  {
   "title": "Top Write Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, lun_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"})",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
    }
   ]
  },
  {
   "title": "Top Write IOPs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, lun_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"})",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
    }
   ]
  },
  {
   "title": "Top LUN Performance Efficiency Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }
  },
  {
   "title": "Top LUN Write Misalignment Buckets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, lun_write_align_histo{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"})",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}} : {{metric}}"
    }
   ]
  },
  {
   "title": "Top LUN Read Misalignment Buckets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, lun_read_align_histo{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"})",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}} : {{metric}}"
    }
   ]
  },
  {
   "title": "Top LUN Indirect Access IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, lun_remote_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"})",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
    }
   ]
  },
  { "title": "Top Volume Latency from QoS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Important Information on Top Volume QoS Latency Graphs",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 70 },
   "options": {
    "content": "You must enable the Workload/QOS counters in $HARVEST/conf/zapiperf/default.yaml.\n"
   }
  },
  {
   "title": "Volume Latency from Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"network\"})/1000",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Volume Latency from Throttle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"throttle\"})/1000",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Volume Latency from Frontend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"frontend\"})/1000",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Volume Latency from Cluster",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"cluster\"})/1000",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Volume Latency from Backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"backend\"})/1000",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Volume Latency from Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"disk\"})/1000",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Volume Latency from Suspend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"suspend\"})/1000",
     "legendFormat": "{{svm}} / {{volume}} "
    }
   ]
  },
  {
   "title": "Volume Latency from Cloud",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"cloud\"})/1000",
     "legendFormat": "{{svm}} / {{volume}} "
    }
   ]
  },
  {
   "title": "Volume Latency from NVLog Mirroring",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"nvlog\"})/1000",
     "legendFormat": "{{svm}} / {{volume}} "
    }
   ]
  },
  {
   "title": "Top Volume and LUN Capacity Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }
  },
  {
   "title": "Volume Used Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, volume_size_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Snapshot Used Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, volume_snapshot_reserve_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Deduplication Percent Saved",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, volume_sis_dedup_saved_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Compression Percent Saved",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, volume_sis_compress_saved_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "LUN Percent Most Filled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, lun_size_used/lun_size{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
    }
   ]
  },
  {
   "title": "LUN Percent Least Filled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, lun_size_used/lun_size{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
    }
   ]
  },
  {
   "title": "Per LUN Drilldown (Must Select Cluster/SVM/Volume/LUN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 }
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "lun_avg_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}/1000",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
    },
    {
     "expr": "lun_avg_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}/1000",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "lun_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
    },
    {
     "expr": "lun_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
    }
   ]
  },
  {
   "title": "IOPs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "lun_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
    },
    {
     "expr": "lun_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
    }
   ]
  },
  {
   "title": "Indirect Access",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "lun_remote_bytes{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}} Remote Data"
    },
    {
     "expr": "lun_remote_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}} Remote IOPs"
    }
   ]
  },
  {
   "title": "vStorage Offload Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "lun_caw_reqs{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}",
     "legendFormat": "Compare and Write"
    },
    {
     "expr": "lun_unmap_reqs{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}",
     "legendFormat": "Unmap"
    },
    {
     "expr": "lun_writesame_reqs{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}",
     "legendFormat": "Write Same"
    },
    {
     "expr": "lun_writesame_unmap_reqs{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}",
     "legendFormat": "Write Same Unmap"
    },
    {
     "expr": "lun_xcopy_reqs{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}",
     "legendFormat": "Xcopy"
    }
   ]
  },
  {
   "title": "IO Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "lun_read_data/lun_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}/1024",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
    },
    {
     "expr": "lun_write_data/lun_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",lun=~\"$LUN\"}/1024",
     "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
    }
   ]
  }
 ]
}