{
 "title": "ASAr2: Storage Unit",
 "tags": [
  "harvest",
  "ontap",
  "asar2"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(storage_unit_labels{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(storage_unit_labels{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(storage_unit_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, svm)"
    }
   },
   {
    "name": "HostGroup",
    "query": {
     "query": "label_values(storage_unit_labels{datacenter=~\"$Datacenter\", cluster=~\"$Cluster\", svm=~\"$SVM\"},host_group)"
    }
   },
   {
    "name": "StorageUnit",
    "query": {
     "query": "label_values(storage_unit_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}, storage_unit)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage Units",
   "type": "stat",
   "description": "Number of storage units.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(storage_unit_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "description": "Number of available space in Cluster.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_space_available{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
    }
   ]
  },
  {
   "title": "Online",
   "type": "stat",
   "description": "Number of online storage units.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(storage_unit_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",state=~\"online\"})"
    }
   ]
  },
  {
   "title": "Offline",
   "type": "stat",
   "description": "Number of offline storage units.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(storage_unit_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",state=~\"offline\"})"
    }
   ]
  },
  {
   "title": "SCSI",
   "type": "stat",
   "description": "Number of SCSI.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(igroup_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
    }
   ]
  },
  {
   "title": "NVMe",
   "type": "stat",
   "description": "Number of nvme.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nvme_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
    }
   ]
  },
  {
   "title": "Storage Unit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Units in Cluster",
     "type": "table",
     "description": "Storage unit details.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "storage_unit_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",host_group=~\"$HostGroup\",storage_unit=~\"$StorageUnit\",svm=~\"$SVM\"}"
      },
      {
       "expr": "storage_unit_space_size{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",host_group=~\"$HostGroup\",storage_unit=~\"$StorageUnit\",svm=~\"$SVM\"}"
      },
      {
       "expr": "storage_unit_space_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",host_group=~\"$HostGroup\",storage_unit=~\"$StorageUnit\",svm=~\"$SVM\"}"
      },
      {
       "expr": "storage_unit_space_efficiency_ratio{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",host_group=~\"$HostGroup\",storage_unit=~\"$StorageUnit\",svm=~\"$SVM\"}"
      },
      {
       "expr": "storage_unit_space_physical_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",host_group=~\"$HostGroup\",storage_unit=~\"$StorageUnit\",svm=~\"$SVM\"}"
      },
      {
       "expr": "storage_unit_avg_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",storage_unit=~\"$StorageUnit\",svm=~\"$SVM\"}"
      },
      {
       "expr": "storage_unit_total_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",storage_unit=~\"$StorageUnit\",svm=~\"$SVM\"}"
      },
      {
       "expr": "storage_unit_total_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",storage_unit=~\"$StorageUnit\",svm=~\"$SVM\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hosts in Cluster",
     "type": "table",
     "description": "Hosts details.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "igroup_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}"
      }
     ]
    }
   ]
  }
 ]
}