collector: KeyPerf

schedule:
  - counter: 24h  # This handles cases such as cluster upgrades or collector cache updates.
  - data: 1m

objects:
  StorageUnit:                    storage_unit.yaml



