{
 "title": "E-Series: Application",
 "tags": [
  "harvest",
  "eseries"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(eseries_array_labels, datacenter)"
    }
   },
   {
    "name": "Array",
    "query": {
     "query": "label_values(eseries_array_labels{datacenter=~\"$Datacenter\"}, array)"
    }
   },
   {
    "name": "Application",
    "query": {
     "query": "label_values(eseries_application_read_ops{datacenter=~\"$Datacenter\",array=~\"$Array\"}, application)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top $TopResources Applications by Read Latency",
   "type": "timeseries",
   "description": "Application read latency.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "eseries_application_read_latency{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, application, array)\n  topk(\n    $TopResources,\n    max by (datacenter, application, array) (\n      avg_over_time(\n        eseries_application_read_latency{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{application}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Applications by Write Latency",
   "type": "timeseries",
   "description": "Application write latency.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "eseries_application_write_latency{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, application, array)\n  topk(\n    $TopResources,\n    max by (datacenter, application, array) (\n      avg_over_time(\n        eseries_application_write_latency{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{application}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Applications by Read IOPs",
   "type": "timeseries",
   "description": "Number of reads per second from the application.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_application_read_ops{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, application, array)\n  topk(\n    $TopResources,\n    max by (datacenter, application, array) (\n      avg_over_time(\n        eseries_application_read_ops{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{application}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Applications by Write IOPs",
   "type": "timeseries",
   "description": "Number of writes per second to the application.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_application_write_ops{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, application, array)\n  topk(\n    $TopResources,\n    max by (datacenter, application, array) (\n      avg_over_time(\n        eseries_application_write_ops{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{application}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Applications by Read Throughput",
   "type": "timeseries",
   "description": "Bytes read per second from the application.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "eseries_application_read_data{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, application, array)\n  topk(\n    $TopResources,\n    max by (datacenter, application, array) (\n      avg_over_time(\n        eseries_application_read_data{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{application}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Applications by Write Throughput",
   "type": "timeseries",
   "description": "Bytes written per second to the application.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "eseries_application_write_data{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, application, array)\n  topk(\n    $TopResources,\n    max by (datacenter, application, array) (\n      avg_over_time(\n        eseries_application_write_data{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{application}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Applications by Other IOPs",
   "type": "timeseries",
   "description": "Number of other I/O operations per second to the application.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_application_other_ops{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, application, array)\n  topk(\n    $TopResources,\n    max by (datacenter, application, array) (\n      avg_over_time(\n        eseries_application_other_ops{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{application}}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Applications by Read Cache Hit Ratio",
     "type": "timeseries",
     "description": "Percentage of read requests served from cache.",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_application_read_cache_hit_ratio{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, application, array)\n  topk(\n    $TopResources,\n    max by (datacenter, application, array) (\n      avg_over_time(\n        eseries_application_read_cache_hit_ratio{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{application}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Applications by Write Cache Hit Ratio",
     "type": "timeseries",
     "description": "Percentage of write requests served from cache.",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_application_write_cache_hit_ratio{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, application, array)\n  topk(\n    $TopResources,\n    max by (datacenter, application, array) (\n      avg_over_time(\n        eseries_application_write_cache_hit_ratio{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{application}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Applications by Total Cache Hit Ratio",
     "type": "timeseries",
     "description": "Percentage of total requests served from cache.",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_application_total_cache_hit_ratio{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, application, array)\n  topk(\n    $TopResources,\n    max by (datacenter, application, array) (\n      avg_over_time(\n        eseries_application_total_cache_hit_ratio{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{application}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Applications by Queue Depth Average",
     "type": "timeseries",
     "description": "Average queue depth per I/O operation.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eseries_application_queue_depth_average{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, application, array)\n  topk(\n    $TopResources,\n    max by (datacenter, application, array) (\n      avg_over_time(\n        eseries_application_queue_depth_average{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{application}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Applications by Queue Depth Max",
     "type": "timeseries",
     "description": "Maximum queue depth seen over the observation window.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eseries_application_queue_depth_max{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, application, array)\n  topk(\n    $TopResources,\n    max by (datacenter, application, array) (\n      avg_over_time(\n        eseries_application_queue_depth_max{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{application}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Applications by Read Utilization",
     "type": "timeseries",
     "description": "Percentage of the observation window the application spent servicing read I/O.",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_application_read_utilization{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, application, array)\n  topk(\n    $TopResources,\n    max by (datacenter, application, array) (\n      avg_over_time(\n        eseries_application_read_utilization{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{application}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Applications by Write Utilization",
     "type": "timeseries",
     "description": "Percentage of the observation window the application spent servicing write I/O.",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_application_write_utilization{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, application, array)\n  topk(\n    $TopResources,\n    max by (datacenter, application, array) (\n      avg_over_time(\n        eseries_application_write_utilization{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{application}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Applications by Total Utilization",
     "type": "timeseries",
     "description": "Percentage of the observation window the application spent servicing I/O (read + write).",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_application_total_utilization{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, application, array)\n  topk(\n    $TopResources,\n    max by (datacenter, application, array) (\n      avg_over_time(\n        eseries_application_total_utilization{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{application}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Applications",
     "type": "table",
     "description": "Application details.",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "eseries_application_read_ops{application=~\"$Application\",array=~\"$Array\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  }
 ]
}