{
 "title": "E-Series: Array",
 "description": "E-Series Array - array Information, Capacity, Performance, and Port Status",
 "tags": [
  "eseries",
  "harvest"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(eseries_array_labels, datacenter)"
    }
   },
   {
    "name": "Array",
    "label": "Array",
    "query": {
     "query": "label_values(eseries_array_labels{datacenter=~\"$Datacenter\"}, name)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top $TopResources Arrays by Read IOPS",
   "type": "timeseries",
   "description": "Number of reads per second from the array.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_array_read_ops{array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, array)\n  topk(\n    $TopResources,\n    max by (datacenter, array) (\n      avg_over_time(eseries_array_read_ops{array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
     "legendFormat": "{{datacenter}}/{{array}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Arrays by Write IOPS",
   "type": "timeseries",
   "description": "Number of writes per second to the array.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_array_write_ops{array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, array)\n  topk(\n    $TopResources,\n    max by (datacenter, array) (\n      avg_over_time(eseries_array_write_ops{array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
     "legendFormat": "{{datacenter}}/{{array}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Arrays by Read Throughput",
   "type": "timeseries",
   "description": "Data read per second from the array.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "eseries_array_read_data{array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, array)\n  topk(\n    $TopResources,\n    max by (datacenter, array) (\n      avg_over_time(eseries_array_read_data{array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
     "legendFormat": "{{datacenter}}/{{array}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Arrays by Write Throughput",
   "type": "timeseries",
   "description": "Data written per second to the array.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "eseries_array_write_data{array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, array)\n  topk(\n    $TopResources,\n    max by (datacenter, array) (\n      avg_over_time(eseries_array_write_data{array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
     "legendFormat": "{{datacenter}}/{{array}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Arrays by Cache Hit IOPS",
   "type": "timeseries",
   "description": "Array cache hit operations per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_array_cache_hit_ops{array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, array)\n  topk(\n    $TopResources,\n    max by (datacenter, array) (\n      avg_over_time(eseries_array_cache_hit_ops{array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
     "legendFormat": "{{datacenter}}/{{array}}"
    }
   ]
  },
  {
   "title": "Firmware Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Firmware Versions",
     "type": "table",
     "description": "Array-wide firmware and software code versions",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "eseries_firmware_version_labels{array=~\"$Array\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Array Configuration",
     "type": "table",
     "description": "E-Series Array Details",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "eseries_array_labels{array=~\"$Array\",datacenter=~\"$Datacenter\"}"
      },
      {
       "expr": "eseries_array_login_banner_enabled{array=~\"$Array\",datacenter=~\"$Datacenter\"}"
      }
     ]
    },
    {
     "title": "Top $TopResources Systems by Storage Capacity Used %",
     "type": "timeseries",
     "description": "Storage pool space used percentage",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n      eseries_array_used_pool_space{array=~\"$Array\",datacenter=~\"$Datacenter\"}\n    /\n      (\n          eseries_array_used_pool_space{array=~\"$Array\",datacenter=~\"$Datacenter\"}\n        +\n          eseries_array_free_pool_space{array=~\"$Array\",datacenter=~\"$Datacenter\"}\n      )\n  )\nand on (datacenter, array)\n  topk(\n    $TopResources,\n    max by (datacenter, array) (\n      avg_over_time(\n        (\n            eseries_array_used_pool_space{array=~\"$Array\",datacenter=~\"$Datacenter\"}\n          /\n            (\n                eseries_array_used_pool_space{array=~\"$Array\",datacenter=~\"$Datacenter\"}\n              +\n                eseries_array_free_pool_space{array=~\"$Array\",datacenter=~\"$Datacenter\"}\n            )\n        )[3h:] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{datacenter}}/{{array}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Systems by Used Space",
     "type": "timeseries",
     "description": "Used pool space in bytes",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "eseries_array_used_pool_space{array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, array)\n  topk(\n    $TopResources,\n    max by (datacenter, array) (\n      avg_over_time(eseries_array_used_pool_space{array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
       "legendFormat": "{{datacenter}}/{{array}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Systems by Free Space",
     "type": "timeseries",
     "description": "Free pool space in bytes",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "eseries_array_free_pool_space{array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, array)\n  topk(\n    $TopResources,\n    max by (datacenter, array) (\n      avg_over_time(eseries_array_free_pool_space{array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
       "legendFormat": "{{datacenter}}/{{array}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Systems by Unconfigured Space",
     "type": "timeseries",
     "description": "Unconfigured space in bytes",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "eseries_array_unconfigured_space{array=~\"$Array\",datacenter=~\"$Datacenter\"}\nand on (datacenter, array)\n  topk(\n    $TopResources,\n    max by (datacenter, array) (\n      avg_over_time(\n        eseries_array_unconfigured_space{array=~\"$Array\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{datacenter}}/{{array}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Configuration",
     "type": "table",
     "description": "Host configuration details",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 207 },
     "targets": [
      {
       "expr": "eseries_host_labels{array=~\"$Array\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  }
 ]
}