{
 "title": "E-Series: Controller",
 "description": "E-Series Controller Performance and Capacity",
 "tags": [
  "eseries",
  "harvest"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(eseries_controller_labels, datacenter)"
    }
   },
   {
    "name": "Array",
    "query": {
     "query": "label_values(eseries_controller_labels{datacenter=~\"$Datacenter\"}, array)"
    }
   },
   {
    "name": "Controller",
    "query": {
     "query": "label_values(eseries_controller_labels{datacenter=~\"$Datacenter\",array=~\"$Array\"}, controller)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top $TopResources Controllers by Read IOPS",
   "type": "timeseries",
   "description": "Number of reads per second from the controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_controller_read_ops{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, controller, array)\n  topk(\n    $TopResources,\n    max by (datacenter, controller, array) (\n      avg_over_time(\n        eseries_controller_read_ops{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{datacenter}}/{{array}}/{{controller}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Controllers by Write IOPS",
   "type": "timeseries",
   "description": "Number of writes per second to the controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_controller_write_ops{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, controller, array)\n  topk(\n    $TopResources,\n    max by (datacenter, controller, array) (\n      avg_over_time(\n        eseries_controller_write_ops{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{datacenter}}/{{array}}/{{controller}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Controllers by Read Throughput",
   "type": "timeseries",
   "description": "Data read per second from the controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "eseries_controller_read_data{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, controller, array)\n  topk(\n    $TopResources,\n    max by (datacenter, controller, array) (\n      avg_over_time(\n        eseries_controller_read_data{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{datacenter}}/{{array}}/{{controller}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Controllers by Write Throughput",
   "type": "timeseries",
   "description": "Data written per second to the controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "eseries_controller_write_data{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, controller, array)\n  topk(\n    $TopResources,\n    max by (datacenter, controller, array) (\n      avg_over_time(\n        eseries_controller_write_data{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{datacenter}}/{{array}}/{{controller}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Controllers by CPU Utilization",
   "type": "timeseries",
   "description": "Controller CPU utilization percentage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "eseries_controller_cpu_utilization{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, controller, array)\n  topk(\n    $TopResources,\n    max by (datacenter, controller, array) (\n      avg_over_time(\n        eseries_controller_cpu_utilization{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{datacenter}}/{{array}}/{{controller}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Controllers by Cache Hit Ops",
   "type": "timeseries",
   "description": "Cache hit operations per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_controller_cache_hit_ops{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, controller, array)\n  topk(\n    $TopResources,\n    max by (datacenter, controller, array) (\n      avg_over_time(\n        eseries_controller_cache_hit_ops{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{datacenter}}/{{array}}/{{controller}}"
    }
   ]
  },
  {
   "title": "Controller Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller Configuration",
     "type": "table",
     "description": "Controller configuration and status",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "eseries_controller_labels{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}"
      }
     ]
    },
    {
     "title": "Controller Cache & Memory",
     "type": "table",
     "description": "Controller cache and processor memory - Data Cache (Total/Used) and Processor Cache",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "label_join(\n  eseries_controller_total_cache_memory{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"array\",\n  \"controller\",\n  \"id\"\n)"
      },
      {
       "expr": "label_join(\n  eseries_controller_used_cache_memory{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"array\",\n  \"controller\",\n  \"id\"\n)"
      },
      {
       "expr": "label_join(\n  eseries_controller_processor_memory{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"array\",\n  \"controller\",\n  \"id\"\n)"
      }
     ]
    }
   ]
  }
 ]
}