{
 "title": "E-Series: Drive",
 "description": "E-Series Drive Performance and Capacity",
 "tags": [
  "harvest",
  "eseries"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(eseries_array_labels, datacenter)"
    }
   },
   {
    "name": "Array",
    "query": {
     "query": "label_values(eseries_array_labels{datacenter=~\"$Datacenter\"}, array)"
    }
   },
   {
    "name": "Tray",
    "query": {
     "query": "label_values(eseries_drive_labels{array=~\"$Array\",datacenter=~\"$Datacenter\"}, tray_id)"
    }
   },
   {
    "name": "Slot",
    "query": {
     "query": "label_values(eseries_drive_labels{array=~\"$Array\",datacenter=~\"$Datacenter\",tray_id=~\"$Tray\"}, slot)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top $TopResources Drives by Read Latency",
   "type": "timeseries",
   "description": "Drive read latency.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "eseries_drive_read_latency{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_drive_read_latency{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - Tray {{tray_id}} Slot {{slot}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Drives by Write Latency",
   "type": "timeseries",
   "description": "Drive write latency.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "eseries_drive_write_latency{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_drive_write_latency{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - Tray {{tray_id}} Slot {{slot}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Drives by Read IOPs",
   "type": "timeseries",
   "description": "Number of read operations per second from the drive.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_drive_read_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_drive_read_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - Tray {{tray_id}} Slot {{slot}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Drives by Write IOPs",
   "type": "timeseries",
   "description": "Number of write operations per second to the drive.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_drive_write_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_drive_write_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - Tray {{tray_id}} Slot {{slot}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Drives by Read Throughput",
   "type": "timeseries",
   "description": "Bytes read per second from the drive.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "eseries_drive_read_data{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_drive_read_data{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - Tray {{tray_id}} Slot {{slot}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Drives by Write Throughput",
   "type": "timeseries",
   "description": "Bytes written per second to the drive.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "eseries_drive_write_data{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_drive_write_data{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - Tray {{tray_id}} Slot {{slot}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Drives by Read Utilization",
     "type": "timeseries",
     "description": "Percentage of time the drive was busy servicing read requests.",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_drive_read_utilization{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_drive_read_utilization{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - Tray {{tray_id}} Slot {{slot}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Drives by Write Utilization",
     "type": "timeseries",
     "description": "Percentage of time the drive was busy servicing write requests.",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_drive_write_utilization{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_drive_write_utilization{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - Tray {{tray_id}} Slot {{slot}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Drives by Total Utilization",
     "type": "timeseries",
     "description": "Percentage of time the drive was busy servicing all I/O requests.",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_drive_total_utilization{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_drive_total_utilization{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - Tray {{tray_id}} Slot {{slot}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Drive Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Drives",
     "type": "table",
     "description": "Drive status and configuration",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "eseries_drive_labels{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}"
      },
      {
       "expr": "eseries_drive_capacity{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}"
      },
      {
       "expr": "eseries_drive_percent_endurance_used{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}"
      },
      {
       "expr": "eseries_drive_block_size{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}"
      },
      {
       "expr": "eseries_drive_block_size_physical{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}"
      },
      {
       "expr": "eseries_drive_raw_capacity{array=~\"$Array\",datacenter=~\"$Datacenter\",slot=~\"$Slot\",tray_id=~\"$Tray\"}"
      }
     ]
    }
   ]
  }
 ]
}