{
 "title": "E-Series: Hardware",
 "description": "E-Series Hardware - Controller, Battery, Fan, Power Supply, Thermal Sensor, SFP, and Drives",
 "tags": [
  "harvest",
  "eseries"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(eseries_array_labels, datacenter)"
    }
   },
   {
    "name": "Array",
    "query": {
     "query": "label_values(eseries_array_labels{datacenter=~\"$Datacenter\"}, array)"
    }
   },
   {
    "name": "Controller",
    "query": {
     "query": "label_values(eseries_controller_labels{datacenter=~\"$Datacenter\",array=~\"$Array\"}, controller)"
    }
   },
   { "name": "TopResources", "query": "1,2,3,4,5,6,8,10" }
  ]
 },
 "panels": [
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Controller Configuration",
   "type": "table",
   "description": "Controller configuration and status",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "eseries_controller_labels{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}"
    }
   ]
  },
  {
   "title": "Code Versions",
   "type": "table",
   "description": "Controller firmware and software code versions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "eseries_controller_code_version_labels{array=~\"$Array\",datacenter=~\"$Datacenter\"}"
    }
   ]
  },
  {
   "title": "Drives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Drives",
     "type": "table",
     "description": "Drive status and configuration",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "eseries_drive_labels{array=~\"$Array\",datacenter=~\"$Datacenter\"}"
      },
      {
       "expr": "eseries_drive_capacity{array=~\"$Array\",datacenter=~\"$Datacenter\"}"
      },
      {
       "expr": "eseries_drive_percent_endurance_used{array=~\"$Array\",datacenter=~\"$Datacenter\"}"
      },
      {
       "expr": "eseries_drive_block_size{array=~\"$Array\",datacenter=~\"$Datacenter\"}"
      },
      {
       "expr": "eseries_drive_block_size_physical{array=~\"$Array\",datacenter=~\"$Datacenter\"}"
      },
      {
       "expr": "eseries_drive_raw_capacity{array=~\"$Array\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller Cache & Memory",
     "type": "table",
     "description": "Controller cache and processor memory - Data Cache (Total/Used) and Processor Cache",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "label_join(\n  eseries_controller_total_cache_memory{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"array\",\n  \"controller\",\n  \"id\"\n)"
      },
      {
       "expr": "label_join(\n  eseries_controller_used_cache_memory{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"array\",\n  \"controller\",\n  \"id\"\n)"
      },
      {
       "expr": "label_join(\n  eseries_controller_processor_memory{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"array\",\n  \"controller\",\n  \"id\"\n)"
      }
     ]
    },
    {
     "title": "Cache Memory DIMMs",
     "type": "table",
     "description": "Cache memory DIMMs (data cache modules)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "label_join(\n  eseries_cache_memory_dimm_labels{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"array\",\n  \"dimm_id\"\n)"
      },
      {
       "expr": "label_join(\n  eseries_cache_memory_dimm_capacity{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"array\",\n  \"dimm_id\"\n)"
      }
     ]
    },
    {
     "title": "Cache Backup Devices",
     "type": "table",
     "description": "Cache backup devices (flash-backed cache protection)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "label_join(\n  eseries_cache_backup_device_labels{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"array\",\n  \"device_id\"\n)"
      },
      {
       "expr": "label_join(\n  eseries_cache_backup_device_capacity{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"array\",\n  \"device_id\"\n)"
      }
     ]
    },
    {
     "title": "Top $TopResources Controllers by Data Cache Used",
     "type": "timeseries",
     "description": "Top controllers by data cache used (cacheMemorySize)",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "eseries_controller_used_cache_memory{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, array, controller, controller_id)\n  topk(\n    $TopResources,\n    max by (datacenter, array, controller, controller_id) (\n      avg_over_time(\n        eseries_controller_used_cache_memory{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{controller}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Controllers by Data Cache Total",
     "type": "timeseries",
     "description": "Top controllers by data cache total (physicalCacheMemorySize)",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "eseries_controller_total_cache_memory{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, array, controller, controller_id)\n  topk(\n    $TopResources,\n    max by (datacenter, array, controller, controller_id) (\n      avg_over_time(\n        eseries_controller_total_cache_memory{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{controller}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Controllers by Processor Cache",
     "type": "timeseries",
     "description": "Top controllers by processor cache (processorMemorySize)",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "eseries_controller_processor_memory{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, array, controller, controller_id)\n  topk(\n    $TopResources,\n    max by (datacenter, array, controller, controller_id) (\n      avg_over_time(\n        eseries_controller_processor_memory{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{controller}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Interfaces",
     "type": "table",
     "description": "Host interfaces (storage-side ports)",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "eseries_controller_host_interface_labels{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Drive Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Drive Interfaces",
     "type": "table",
     "description": "Drive interfaces (backend ports)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "eseries_controller_drive_interface_labels{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Management Ports",
     "type": "table",
     "description": "Management network interfaces",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "eseries_controller_net_interface_labels{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}"
      }
     ]
    },
    {
     "title": "DNS & NTP Configuration",
     "type": "table",
     "description": "DNS and NTP configuration per management port. Shows only the first two servers of each type; the DNS & NTP row below lists every server per controller.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "eseries_controller_net_interface_labels{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Power Supply",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power Supply",
     "type": "table",
     "description": "Power supply status and information",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "eseries_power_supply_labels{array=~\"$Array\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fan",
     "type": "table",
     "description": "Fan status and location",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "eseries_fan_labels{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thermal Sensor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thermal Sensor",
     "type": "table",
     "description": "Thermal sensor status and temperature readings",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
     "targets": [
      {
       "expr": "eseries_thermal_sensor_labels{array=~\"$Array\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Battery",
     "type": "table",
     "description": "Battery status and information",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "eseries_battery_labels{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "SFP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "SFP",
     "type": "table",
     "description": "SFP transceiver status and information",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "eseries_sfp_labels{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "IO Module / Host Board",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO Module / Host Board",
     "type": "table",
     "description": "IO module (host interface card) status and inventory",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "eseries_host_board_labels{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS & NTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS Servers",
     "type": "table",
     "description": "DNS servers configured per controller",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "eseries_controller_dns_labels{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}"
      }
     ]
    },
    {
     "title": "NTP Servers",
     "type": "table",
     "description": "NTP servers configured per controller",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "eseries_controller_ntp_labels{array=~\"$Array\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  }
 ]
}