{
 "title": "E-Series: Interface",
 "tags": [
  "harvest",
  "eseries"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(eseries_array_labels, datacenter)"
    }
   },
   {
    "name": "Array",
    "query": {
     "query": "label_values(eseries_array_labels{datacenter=~\"$Datacenter\"}, array)"
    }
   },
   {
    "name": "ChannelType",
    "query": {
     "query": "label_values(eseries_interface_read_ops{datacenter=~\"$Datacenter\",array=~\"$Array\"}, channel_type)"
    }
   },
   {
    "name": "Controller",
    "query": {
     "query": "label_values(eseries_interface_read_ops{datacenter=~\"$Datacenter\",array=~\"$Array\"}, controller)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top $TopResources Interfaces by Read Latency",
   "type": "timeseries",
   "description": "Interface read latency.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "eseries_interface_read_latency{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_interface_read_latency{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{controller}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Interfaces by Write Latency",
   "type": "timeseries",
   "description": "Interface write latency.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "eseries_interface_write_latency{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_interface_write_latency{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{controller}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Interfaces by Read IOPs",
   "type": "timeseries",
   "description": "Number of reads per second on the interface.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_interface_read_ops{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_interface_read_ops{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{controller}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Interfaces by Write IOPs",
   "type": "timeseries",
   "description": "Number of writes per second on the interface.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_interface_write_ops{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_interface_write_ops{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{controller}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Interfaces by Read Throughput",
   "type": "timeseries",
   "description": "Bytes read per second on the interface.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "eseries_interface_read_data{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_interface_read_data{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{controller}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Interfaces by Write Throughput",
   "type": "timeseries",
   "description": "Bytes written per second on the interface.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "eseries_interface_write_data{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_interface_write_data{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{controller}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Interfaces by Other IOPs",
   "type": "timeseries",
   "description": "Number of other I/O operations per second on the interface (e.g. control/management commands).",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_interface_other_ops{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_interface_other_ops{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{controller}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Interfaces by Other Latency",
   "type": "timeseries",
   "description": "Other command response time average.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "eseries_interface_other_latency{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_interface_other_latency{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{controller}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Interfaces by Queue Depth Average",
     "type": "timeseries",
     "description": "Average queue depth per I/O operation.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eseries_interface_queue_depth_average{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_interface_queue_depth_average{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{controller}} - {{interface}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Interfaces by Queue Depth Max",
     "type": "timeseries",
     "description": "Maximum queue depth seen over the observation window.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eseries_interface_queue_depth_max{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_interface_queue_depth_max{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{controller}} - {{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Channel Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Interfaces by Channel Error Count",
     "type": "timeseries",
     "description": "Number of errors detected on the channel.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eseries_interface_channel_error_count{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}\nand on (datacenter, id, array)\n  topk(\n    $TopResources,\n    max by (datacenter, id, array) (\n      avg_over_time(\n        eseries_interface_channel_error_count{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{controller}} - {{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interfaces",
     "type": "table",
     "description": "Interface details.",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "eseries_interface_read_ops{array=~\"$Array\",channel_type=~\"$ChannelType\",controller=~\"$Controller\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  }
 ]
}