{
 "title": "E-Series: Volume",
 "tags": [
  "harvest",
  "eseries"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(eseries_array_labels, datacenter)"
    }
   },
   {
    "name": "Array",
    "query": {
     "query": "label_values(eseries_array_labels{datacenter=~\"$Datacenter\"}, array)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(eseries_volume_labels{datacenter=~\"$Datacenter\",array=~\"$Array\"}, volume)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top $TopResources Volumes by Read Latency",
   "type": "timeseries",
   "description": "Volume read latency.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "eseries_volume_read_latency{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}\nand on (datacenter, volume, array)\n  topk(\n    $TopResources,\n    max by (datacenter, volume, array) (\n      avg_over_time(\n        eseries_volume_read_latency{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Volumes by Write Latency",
   "type": "timeseries",
   "description": "Volume write latency.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "eseries_volume_write_latency{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}\nand on (datacenter, volume, array)\n  topk(\n    $TopResources,\n    max by (datacenter, volume, array) (\n      avg_over_time(\n        eseries_volume_write_latency{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Volumes by Read IOPs",
   "type": "timeseries",
   "description": "Number of reads per second from the volume.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_volume_read_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}\nand on (datacenter, volume, array)\n  topk(\n    $TopResources,\n    max by (datacenter, volume, array) (\n      avg_over_time(\n        eseries_volume_read_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Volumes by Write IOPs",
   "type": "timeseries",
   "description": "Number of writes per second to the volume.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_volume_write_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}\nand on (datacenter, volume, array)\n  topk(\n    $TopResources,\n    max by (datacenter, volume, array) (\n      avg_over_time(\n        eseries_volume_write_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Volumes by Read Throughput",
   "type": "timeseries",
   "description": "Bytes read per second from the volume.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "eseries_volume_read_data{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}\nand on (datacenter, volume, array)\n  topk(\n    $TopResources,\n    max by (datacenter, volume, array) (\n      avg_over_time(\n        eseries_volume_read_data{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Volumes by Write Throughput",
   "type": "timeseries",
   "description": "Bytes written per second to the volume.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "eseries_volume_write_data{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}\nand on (datacenter, volume, array)\n  topk(\n    $TopResources,\n    max by (datacenter, volume, array) (\n      avg_over_time(\n        eseries_volume_write_data{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Volumes by Other IOPs",
   "type": "timeseries",
   "description": "Number of other I/O operations per second to the volume.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_volume_other_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}\nand on (datacenter, volume, array)\n  topk(\n    $TopResources,\n    max by (datacenter, volume, array) (\n      avg_over_time(\n        eseries_volume_other_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Volume Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumes",
     "type": "table",
     "description": "Volume details.",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_join(\n  eseries_volume_labels{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"array\",\n  \"volume\"\n)"
      },
      {
       "expr": "label_join(\n  eseries_volume_reported_capacity{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"array\",\n  \"volume\"\n)"
      },
      {
       "expr": "label_join(\n  eseries_volume_block_size{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"array\",\n  \"volume\"\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Volumes by Read Cache Hit Ratio",
     "type": "timeseries",
     "description": "Percentage of read requests served from cache.",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_volume_read_cache_hit_ratio{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}\nand on (datacenter, volume, array)\n  topk(\n    $TopResources,\n    max by (datacenter, volume, array) (\n      avg_over_time(\n        eseries_volume_read_cache_hit_ratio{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write Cache Hit Ratio",
     "type": "timeseries",
     "description": "Percentage of write requests served from cache.",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_volume_write_cache_hit_ratio{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}\nand on (datacenter, volume, array)\n  topk(\n    $TopResources,\n    max by (datacenter, volume, array) (\n      avg_over_time(\n        eseries_volume_write_cache_hit_ratio{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Total Cache Hit Ratio",
     "type": "timeseries",
     "description": "Percentage of total requests served from cache.",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_volume_total_cache_hit_ratio{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}\nand on (datacenter, volume, array)\n  topk(\n    $TopResources,\n    max by (datacenter, volume, array) (\n      avg_over_time(\n        eseries_volume_total_cache_hit_ratio{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Volumes by Queue Depth Average",
     "type": "timeseries",
     "description": "Average queue depth per I/O operation.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eseries_volume_queue_depth_average{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}\nand on (datacenter, volume, array)\n  topk(\n    $TopResources,\n    max by (datacenter, volume, array) (\n      avg_over_time(\n        eseries_volume_queue_depth_average{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Queue Depth Max",
     "type": "timeseries",
     "description": "Maximum queue depth seen over the observation window.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eseries_volume_queue_depth_max{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}\nand on (datacenter, volume, array)\n  topk(\n    $TopResources,\n    max by (datacenter, volume, array) (\n      avg_over_time(\n        eseries_volume_queue_depth_max{array=~\"$Array\",datacenter=~\"$Datacenter\",volume=~\"$Volume\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{volume}}"
      }
     ]
    }
   ]
  }
 ]
}