{
 "title": "E-Series: Workload",
 "tags": [
  "harvest",
  "eseries"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(eseries_array_labels, datacenter)"
    }
   },
   {
    "name": "Array",
    "query": {
     "query": "label_values(eseries_array_labels{datacenter=~\"$Datacenter\"}, array)"
    }
   },
   {
    "name": "Workload",
    "query": {
     "query": "label_values(eseries_workload_labels{datacenter=~\"$Datacenter\",array=~\"$Array\"}, workload)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top $TopResources Workloads by Read Latency",
   "type": "timeseries",
   "description": "Workload read latency.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "eseries_workload_read_latency{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}\nand on (datacenter, workload, array)\n  topk(\n    $TopResources,\n    max by (datacenter, workload, array) (\n      avg_over_time(\n        eseries_workload_read_latency{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Write Latency",
   "type": "timeseries",
   "description": "Workload write latency.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "eseries_workload_write_latency{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}\nand on (datacenter, workload, array)\n  topk(\n    $TopResources,\n    max by (datacenter, workload, array) (\n      avg_over_time(\n        eseries_workload_write_latency{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Read IOPs",
   "type": "timeseries",
   "description": "Number of reads per second from the workload.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_workload_read_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}\nand on (datacenter, workload, array)\n  topk(\n    $TopResources,\n    max by (datacenter, workload, array) (\n      avg_over_time(\n        eseries_workload_read_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Write IOPs",
   "type": "timeseries",
   "description": "Number of writes per second to the workload.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_workload_write_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}\nand on (datacenter, workload, array)\n  topk(\n    $TopResources,\n    max by (datacenter, workload, array) (\n      avg_over_time(\n        eseries_workload_write_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Read Throughput",
   "type": "timeseries",
   "description": "Bytes read per second from the workload.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "eseries_workload_read_data{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}\nand on (datacenter, workload, array)\n  topk(\n    $TopResources,\n    max by (datacenter, workload, array) (\n      avg_over_time(\n        eseries_workload_read_data{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Write Throughput",
   "type": "timeseries",
   "description": "Bytes written per second to the workload.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "eseries_workload_write_data{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}\nand on (datacenter, workload, array)\n  topk(\n    $TopResources,\n    max by (datacenter, workload, array) (\n      avg_over_time(\n        eseries_workload_write_data{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Other IOPs",
   "type": "timeseries",
   "description": "Number of other I/O operations per second to the workload.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "eseries_workload_other_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}\nand on (datacenter, workload, array)\n  topk(\n    $TopResources,\n    max by (datacenter, workload, array) (\n      avg_over_time(\n        eseries_workload_other_ops{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{array}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Workloads by Read Cache Hit Ratio",
     "type": "timeseries",
     "description": "Percentage of read requests served from cache.",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_workload_read_cache_hit_ratio{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}\nand on (datacenter, workload, array)\n  topk(\n    $TopResources,\n    max by (datacenter, workload, array) (\n      avg_over_time(\n        eseries_workload_read_cache_hit_ratio{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Workloads by Write Cache Hit Ratio",
     "type": "timeseries",
     "description": "Percentage of write requests served from cache.",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_workload_write_cache_hit_ratio{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}\nand on (datacenter, workload, array)\n  topk(\n    $TopResources,\n    max by (datacenter, workload, array) (\n      avg_over_time(\n        eseries_workload_write_cache_hit_ratio{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Workloads by Total Cache Hit Ratio",
     "type": "timeseries",
     "description": "Percentage of total requests served from cache.",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_workload_total_cache_hit_ratio{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}\nand on (datacenter, workload, array)\n  topk(\n    $TopResources,\n    max by (datacenter, workload, array) (\n      avg_over_time(\n        eseries_workload_total_cache_hit_ratio{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{workload}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Workloads by Queue Depth Average",
     "type": "timeseries",
     "description": "Average queue depth per I/O operation.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eseries_workload_queue_depth_average{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}\nand on (datacenter, workload, array)\n  topk(\n    $TopResources,\n    max by (datacenter, workload, array) (\n      avg_over_time(\n        eseries_workload_queue_depth_average{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Workloads by Queue Depth Max",
     "type": "timeseries",
     "description": "Maximum queue depth seen over the observation window.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eseries_workload_queue_depth_max{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}\nand on (datacenter, workload, array)\n  topk(\n    $TopResources,\n    max by (datacenter, workload, array) (\n      avg_over_time(\n        eseries_workload_queue_depth_max{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{workload}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Workloads by Read Utilization",
     "type": "timeseries",
     "description": "Percentage of the observation window the workload spent servicing read I/O.",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_workload_read_utilization{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}\nand on (datacenter, workload, array)\n  topk(\n    $TopResources,\n    max by (datacenter, workload, array) (\n      avg_over_time(\n        eseries_workload_read_utilization{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Workloads by Write Utilization",
     "type": "timeseries",
     "description": "Percentage of the observation window the workload spent servicing write I/O.",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_workload_write_utilization{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}\nand on (datacenter, workload, array)\n  topk(\n    $TopResources,\n    max by (datacenter, workload, array) (\n      avg_over_time(\n        eseries_workload_write_utilization{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Workloads by Total Utilization",
     "type": "timeseries",
     "description": "Percentage of the observation window the workload spent servicing I/O (read + write).",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eseries_workload_total_utilization{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}\nand on (datacenter, workload, array)\n  topk(\n    $TopResources,\n    max by (datacenter, workload, array) (\n      avg_over_time(\n        eseries_workload_total_utilization{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{array}} - {{workload}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workload Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workloads",
     "type": "table",
     "description": "Workload details.",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "eseries_workload_labels{array=~\"$Array\",datacenter=~\"$Datacenter\",workload=~\"$Workload\"}"
      }
     ]
    }
   ]
  }
 ]
}