{
 "title": "ONTAP: Volume Deep Dive",
 "tags": [
  "harvest",
  "ontap",
  "cdot",
  "fsx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(volume_labels{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(volume_labels{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(volume_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, svm)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(volume_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}, volume)"
    }
   },
   {
    "name": "Qtree",
    "query": {
     "query": "label_values(qtree_total_ops{datacenter=~\"$Datacenter\", cluster=~\"$Cluster\", svm=~\"$SVM\", volume=~\"$Volume\"} ,qtree)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Volume Deep Dive: $Volume",
   "type": "row",
   "description": "Maximum latency of selected volumes.",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Volume Performance",
   "type": "table",
   "description": "This panel shows volume performance details.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "volume_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
    },
    {
     "expr": "avg_over_time (volume_total_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"} [$__range])"
    },
    {
     "expr": "avg_over_time (volume_read_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"} [$__range])"
    },
    {
     "expr": "avg_over_time (volume_write_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"} [$__range])"
    },
    {
     "expr": "avg_over_time (volume_write_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"} [$__range])"
    },
    {
     "expr": "avg_over_time (volume_other_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"} [$__range ])"
    },
    {
     "expr": "avg_over_time (volume_read_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"} [$__range])"
    }
   ]
  },
  {
   "title": "Max Read Op Size",
   "type": "stat",
   "description": "This panel shows detail of average amount of data read per read operation.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "volume_read_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}/volume_read_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
    }
   ]
  },
  {
   "title": "Max Write Op Size",
   "type": "stat",
   "description": "This panel shows detail of average amount of data write per write operation.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "volume_write_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}/volume_write_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "stat",
   "description": "Average latency of selected volumes.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "volume_avg_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "stat",
   "description": "Maximum latency in microseconds for the WAFL filesystem to process all the operations on the volume; not including request processing or network communication time.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "volume_avg_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
    }
   ]
  },
  {
   "title": "Read IOPs",
   "type": "timeseries",
   "description": "Number of read operations per second from the selected volumes.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "volume_read_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "timeseries",
   "description": "Bytes read per second from the volume.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "volume_read_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Write IOPs",
   "type": "timeseries",
   "description": "Number of write operations per second from the selected volumes.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "volume_write_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "description": "Bytes written per second to the volume.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "volume_write_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "description": "Average latency in microseconds for the WAFL filesystem to process read request to the volume; not including request processing or network communication time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "volume_read_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "description": "Average latency in microseconds for the WAFL filesystem to process write request to the volume; not including request processing or network communication time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "volume_write_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Qtrees by IOPs",
   "type": "timeseries",
   "description": "Summation of NFS ops, CIFS ops, CSS ops and internal ops.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg_over_time (qtree_total_ops{datacenter=~\"$Datacenter\", cluster=~\"$Cluster\", svm=~\"$SVM\", volume=~\"$Volume\", qtree=~\"$Qtree\"} [$__range])",
     "legendFormat": "{{svm}} - {{volume}} - {{qtree}}"
    }
   ]
  },
  {
   "title": "Volume Capacity: $Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumes in Cluster",
     "type": "table",
     "description": "Volume details.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "volume_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_new_status{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_size_total{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_size_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_sis_dedup_saved{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_sis_compress_saved{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_sis_dedup_saved+volume_sis_compress_saved{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_space_logical_used{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_space_physical_used{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_clone_split_estimate{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "QoS Resource Latencies: $Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Important Information on Top Volume QoS Resource Latency Graphs",
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
     "options": {
      "content": "This panel requires Workload/QOS counter templates. They are disabled by default because they typically slow down data collection due to a high number of metrics. Two actions are required to use this panel: <br>\n1. If you are using ZapiPerf Collector, then On Harvest, You must enable the Workload/QOS counters in $HARVEST/conf/zapiperf/default.yaml. <br>\n2. If you are using RestPerf Collector, then On Harvest, You must enable the Workload/QOS counters in $HARVEST/conf/restperf/default.yaml. <br>\n\nRefer ONTAP Performance - Resolution Guide https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/ONTAP_9_Performance_-_Resolution_Guide"
     }
    },
    {
     "title": "Volumes by Latency from Network",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"network\",volume!=\"\"}",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volumes by Latency from Throttle",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"throttle\",volume!=\"\"}",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volumes by Latency from Qos Min",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"qos_min\",volume!=\"\"}",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volumes by Latency from Cluster",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"cluster\",volume!=\"\"}",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volumes by Latency from Backend",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"backend\",volume!=\"\"}",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volumes by Latency from CP (Consistency Point)",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"cp\",volume!=\"\"}",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volumes by Latency from Suspend",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"suspend\",volume!=\"\"}",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}} "
      }
     ]
    },
    {
     "title": "Volumes by Latency from Cloud",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"cloud\",volume!=\"\"}",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}} "
      }
     ]
    },
    {
     "title": "Volumes by Latency from Frontend",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"frontend\",volume!=\"\"}",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volumes by Latency from NVLog Mirroring",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"nvlog\",volume!=\"\"}",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}} "
      }
     ]
    },
    {
     "title": "Volumes by Latency from Disk",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"disk\",volume!=\"\"}",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per Volume Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per Volume Space Used",
     "type": "timeseries",
     "description": "This panel shows detail of physical size, physical space used, logical space used and size used of the volume, in bytes.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_size{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Volume Total Size"
      },
      {
       "expr": "volume_space_physical_used{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Physical Space Used"
      },
      {
       "expr": "volume_space_logical_used{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Logical Space Used"
      },
      {
       "expr": "volume_size_used{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Volume Size Used"
      }
     ]
    },
    {
     "title": "Per Volume Space Used Percent",
     "type": "timeseries",
     "description": "This panel shows detail of physical used %, logical used % and size used % of the volume.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_space_physical_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Physical Space Used"
      },
      {
       "expr": "volume_space_logical_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Logical Space Used"
      },
      {
       "expr": "volume_size_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Volume Size Used"
      }
     ]
    },
    {
     "title": "Per Volume Snapshot Space Used",
     "type": "timeseries",
     "description": "This panel shows detail of snapshot available size, snapshot reserve size, snapshot reserve available and snapshots size used of the volume.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_snapshots_size_available{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Snapshot Size Available"
      },
      {
       "expr": "volume_snapshot_reserve_size{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Snapshot Reserve Size"
      },
      {
       "expr": "volume_snapshot_reserve_available{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Snapshot Reserve Available"
      },
      {
       "expr": "volume_snapshots_size_used{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Snapshot Size Used"
      }
     ]
    },
    {
     "title": "Per Volume Snapshot Space Used Percent",
     "type": "timeseries",
     "description": "This panel shows detail of snapshot reserve %, snapshot reserve used % and size used % of the volume.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_snapshot_reserve_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Snapshot Reserve"
      },
      {
       "expr": "volume_snapshot_reserve_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Snapshot Reserve Used"
      },
      {
       "expr": "volume_size_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Volume Size Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Inodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inode Files Used",
     "type": "timeseries",
     "description": "Number of user-visible files (inodes) used. This field is valid only when the volume is online.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "volume_inode_files_used{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Inode Files Total",
     "type": "timeseries",
     "description": "Total user-visible file (inode) count, i.e., current maximum number of user-visible files (inodes) that this volume can currently hold.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "volume_inode_files_total{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Inode Files Used Percentage",
     "type": "timeseries",
     "description": "volume_inode_files_used / volume_inode_total.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_inode_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    }
   ]
  }
 ]
}