
collector:          RestPerf

# Order here matters!
schedule:
  - counter: 1200s
  - instance: 600s
  - data: 60s

objects:
  CIFSNode:             cifs_node.yaml
  Fcp:                  fcp.yaml
  FCVI:                 fcvi.yaml
  HeadroomAggr:         resource_headroom_aggr.yaml
  HeadroomCPU:          resource_headroom_cpu.yaml
  HostAdapter:          hostadapter.yaml
  NFSv3Node:            nfsv3_node.yaml
  NFSv41Node:           nfsv4_1_node.yaml
  NFSv4Node:            nfsv4_node.yaml
  Path:                 path.yaml
  Processor:            processor.yaml
  Qtree:                qtree.yaml
  TokenManager:         token_manager.yaml
  VolumeNode:           volume_node.yaml
  WAFL:                 wafl.yaml

  # SVM-level metrics
  CIFSsvm:              cifs_svm.yaml
  CopyManager:          copy_manager.yaml
  FcpLif:               fcp_lif.yaml
  LIF:                  lif.yaml
  NFSv3:                nfsv3.yaml
  NFSv41:               nfsv4_1.yaml
  NFSv4:                nfsv4.yaml
  Volume:               volume.yaml

  #  Uncomment to collect workload/QOS counters
#  Workload:             workload.yaml
#  WorkloadDetail:       workload_detail.yaml
#  WorkloadVolume:       workload_volume.yaml
#  WorkloadDetailVolume: workload_detail_volume.yaml