{
 "title": "ONTAP: External Service Operation",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(external_service_op_request_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, svm)"
    }
   },
   {
    "name": "ServiceName",
    "query": {
     "query": "label_values(external_service_op_request_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}, service_name)"
    }
   },
   {
    "name": "Operation",
    "query": {
     "query": "label_values(external_service_op_request_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",service_name=~\"$ServiceName\"}, operation)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information about External Service Operation dashboard",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "You must uncomment the external_service_operation.yaml section in your $HARVEST/conf/zapiperf/default.yaml file."
   }
  },
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Top $TopResources Request Latency to Server",
   "type": "timeseries",
   "description": "This panel includes Average request latency for operations on specified server.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (datacenter, cluster, svm, operation, service_name) (\n    external_service_op_request_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",operation=~\"$Operation\",service_name=~\"$ServiceName\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, cluster, svm, operation, service_name) (\n      avg_over_time(\n        external_service_op_request_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",operation=~\"$Operation\",service_name=~\"$ServiceName\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} - {{svm}} - {{operation}}"
    }
   ]
  },
  {
   "title": "Request Latency Heatmap to Server",
   "type": "heatmap",
   "description": "This panel tracks histograms for request latency values of this operation to the specified server.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by (le) (\n  increase(\n    external_service_op_request_latency_hist_bucket{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",operation=~\"$Operation\",service_name=~\"$ServiceName\",svm=~\"$SVM\"}[9d2m57s]\n  )\n)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Top $TopResources Number of 'Not Found' Responses Per Operation",
   "type": "timeseries",
   "description": "This panel displays Number of 'Not Found' responses for the operations.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (datacenter, cluster, svm, operation, service_name) (\n    external_service_op_num_not_found_responses{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",operation=~\"$Operation\",service_name=~\"$ServiceName\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, cluster, svm, operation, service_name) (\n      avg_over_time(\n        external_service_op_num_not_found_responses{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",operation=~\"$Operation\",service_name=~\"$ServiceName\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} - {{svm}} - {{operation}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Number of Request Failures",
   "type": "timeseries",
   "description": "This panel displays cumulative count of all request failures.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (datacenter, cluster, svm, operation, service_name) (\n    external_service_op_num_request_failures{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",operation=~\"$Operation\",service_name=~\"$ServiceName\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, cluster, svm, operation, service_name) (\n      avg_over_time(\n        external_service_op_num_request_failures{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",operation=~\"$Operation\",service_name=~\"$ServiceName\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} - {{svm}} - {{operation}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Number of Request Sent",
   "type": "timeseries",
   "description": "This panel displays Number of requests sent to the service.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (datacenter, cluster, svm, operation, service_name) (\n    external_service_op_num_requests_sent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",operation=~\"$Operation\",service_name=~\"$ServiceName\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, cluster, svm, operation, service_name) (\n      avg_over_time(\n        external_service_op_num_requests_sent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",operation=~\"$Operation\",service_name=~\"$ServiceName\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} - {{svm}} - {{operation}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Number of Responses Received",
   "type": "timeseries",
   "description": "This panel displays Number of responses received from the server (does not include timeouts).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (datacenter, cluster, svm, operation, service_name) (\n    external_service_op_num_responses_received{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",operation=~\"$Operation\",service_name=~\"$ServiceName\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, cluster, svm, operation, service_name) (\n      avg_over_time(\n        external_service_op_num_responses_received{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",operation=~\"$Operation\",service_name=~\"$ServiceName\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} - {{svm}} - {{operation}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Number of Successful Responses",
   "type": "timeseries",
   "description": "This panel displays Number of successful responses to the operation.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (datacenter, cluster, svm, operation, service_name) (\n    external_service_op_num_successful_responses{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",operation=~\"$Operation\",service_name=~\"$ServiceName\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, cluster, svm, operation, service_name) (\n      avg_over_time(\n        external_service_op_num_successful_responses{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",operation=~\"$Operation\",service_name=~\"$ServiceName\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} - {{svm}} - {{operation}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Number of Timeouts",
   "type": "timeseries",
   "description": "This panel displays Number of times requests to the server for this operation timed out.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (datacenter, cluster, svm, operation, service_name) (\n    external_service_op_num_timeouts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",operation=~\"$Operation\",service_name=~\"$ServiceName\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, cluster, svm, operation, service_name) (\n      avg_over_time(\n        external_service_op_num_timeouts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",operation=~\"$Operation\",service_name=~\"$ServiceName\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{cluster}} - {{svm}} - {{operation}}"
    }
   ]
  }
 ]
}