{
 "title": "ONTAP: FlexCache",
 "tags": [
  "harvest",
  "ontap",
  "cdot",
  "fsx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(svm_labels{cluster=~\"$Cluster\"}, svm)"
    }
   },
   {
    "name": "FlexCache",
    "query": {
     "query": "label_values(flexcache_size{system_type!=\"7mode\",datacenter=~\"$Datacenter\", cluster=~\"$Cluster\",svm=~\"$SVM\"}, volume)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information about FlexCache Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "\nThis dashboard requires either the Zapi/ZapiPerf or the Rest/StatPerf Collector."
   }
  },
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Top $TopResources Cache Miss percent",
   "type": "timeseries",
   "description": "A high cache miss percent could indicate that the cache is not being effectively utilized. This is because data is being frequently retrieved from the origin instead of the cache, which can lead to increased latency and reduced performance. Therefore, a lower cache miss rate is generally desirable as it means more data is being served directly from the cache, improving system performance.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_max(\n    flexcache_miss_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"},\n    100\n  )\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_miss_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Blocks requested from Client",
   "type": "timeseries",
   "description": "This counter shows the total number of blocks requested by the client. A high number here could indicate heavy usage of the system.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flexcache_blocks_requested_from_client{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_blocks_requested_from_client{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Blocks requested from Origin",
   "type": "timeseries",
   "description": "This counter shows the total number of blocks retrieved from the origin. If this number is high relative to the number of blocks requested by the client, it could indicate that the cache is not being effectively used, as data is being frequently retrieved from the origin rather than the cache.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flexcache_blocks_retrieved_from_origin{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_blocks_retrieved_from_origin{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "FlexCache Details",
   "type": "table",
   "description": "FlexCache Details.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "flexcache_size{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",system_type!=\"7mode\",volume=~\"$FlexCache\"}"
    }
   ]
  },
  {
   "title": "Reconcile Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Reconciled data entries",
     "type": "timeseries",
     "description": "This metric represents the total number of reconciled data entries at the cache side. A high value for this metric could suggest that the system frequently needs to update the cache to match the data in the primary storage. This frequent reconciliation could be indicative of performance issues, as it may mean that the cache is not effectively maintaining a consistent state with the primary storage. On the other hand, a low value for reconciled_data_entries could suggest that the cache is staying consistent with the primary storage, which is generally a sign of good performance.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flexcache_reconciled_data_entries{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_reconciled_data_entries{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Reconciled Lock Entries",
     "type": "timeseries",
     "description": "This metric shows the total number of reconciled lock entries at the cache side. A high value for this metric could indicate potential performance issues. This is because it may suggest that the system is frequently having to reconcile lock entries between the cache and the primary storage. Conversely, a low value for reconciled_lock_entries could indicate that the cache is maintaining a consistent state with the primary storage in terms of lock entries, which is generally indicative of good performance.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flexcache_reconciled_lock_entries{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_reconciled_lock_entries{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Evict",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Evictions Skipped Due to Configuration Issues",
     "type": "timeseries",
     "description": "This metric indicates the number of times an eviction was skipped due to configuration issues. A high value for this metric could point to problems with the cache configuration, which may be preventing the system from correctly managing the cache.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flexcache_evict_skipped_reason_config_noent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_evict_skipped_reason_config_noent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Evictions Skipped Due to Cache Disconnection",
     "type": "timeseries",
     "description": "This metric represents the number of times data eviction from the ONTAP FlexCache was skipped due to a disconnection. A high value could suggest network instability or other issues causing frequent disconnections, which in turn prevents the cache from being properly managed.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flexcache_evict_skipped_reason_disconnected{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_evict_skipped_reason_disconnected{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Evictions Skipped When Cache is Offline",
     "type": "timeseries",
     "description": "This metric shows the number of times an eviction was skipped because the cache was offline. A high value could suggest that the cache is frequently going offline, which could be due to a variety of issues such as network problems, hardware failures, or configuration errors. This prevents the system from effectively managing the cache.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flexcache_evict_skipped_reason_offline{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_evict_skipped_reason_offline{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Read-Write Cache Evictions Skipped Due to Cache Disconnection",
     "type": "timeseries",
     "description": "This metric represents the total number of read-write cache eviction operations that were skipped because the cache was disconnected. A high value for this metric could indicate network instability or other issues causing frequent disconnections, which prevent the system from effectively managing the read-write cache in the ONTAP FlexCache.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flexcache_evict_rw_cache_skipped_reason_disconnected{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_evict_rw_cache_skipped_reason_disconnected{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Invalidate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Invalidate Operations Skipped Due to Unavailable Cache Configuration",
     "type": "timeseries",
     "description": "This metric indicates the total number of times an invalidate operation was skipped because the cache configuration was not available. A high value for this metric could suggest issues with the cache configuration, which may be preventing the system from correctly performing invalidate operations.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flexcache_invalidate_skipped_reason_config_noent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_invalidate_skipped_reason_config_noent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Invalidate Operations Skipped Due to Cache Disconnection",
     "type": "timeseries",
     "description": "This metric shows the total number of times an invalidate operation was skipped because the cache was disconnected. A high value could indicate network instability or other issues causing frequent disconnections, which prevent the system from effectively performing invalidate operations.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flexcache_invalidate_skipped_reason_disconnected{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_invalidate_skipped_reason_disconnected{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Invalidate Operations Skipped When Cache Volume is Offline",
     "type": "timeseries",
     "description": "This metric represents the total number of times an invalidate operation was skipped because the cache volume was offline. A high value could suggest that the cache volume is frequently going offline, which could be due to a variety of issues such as network problems, hardware failures, or configuration errors. This prevents the system from effectively performing invalidate operations.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flexcache_evict_skipped_reason_offline{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_evict_skipped_reason_offline{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nix",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Nix Operations Skipped Due to In-Progress Nix Operation",
     "type": "timeseries",
     "description": "This metric represents the total number of nix operations that were skipped because another nix operation was in progress. A high value could suggest that the system is frequently busy with ongoing nix operations, which could impact the overall performance of the cache.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flexcache_nix_skipped_reason_in_progress{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_nix_skipped_reason_in_progress{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Retry Nix Operations Skipped Due to Retrieve Operation Initiator",
     "type": "timeseries",
     "description": "This metric represents the total number of retry nix operations that were skipped because the initiator was a retrieve operation in the ONTAP FlexCache.\n\nIf this metric has a high value, it could suggest that there are frequent retrieve operations initiating in the system, which are preventing retry nix operations from being executed. This could potentially impact the overall performance of the cache, depending on the specific use case and workload.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flexcache_nix_retry_skipped_reason_initiator_retrieve{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_nix_retry_skipped_reason_initiator_retrieve{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Nix Operations Skipped Due to Unavailable Cache Configuration",
     "type": "timeseries",
     "description": "This metric indicates the total number of nix operations that were skipped because the cache configuration was not available. A high value for this metric could suggest issues with the cache configuration, which may be preventing the system from correctly performing nix operations.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flexcache_nix_skipped_reason_config_noent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_nix_skipped_reason_config_noent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Nix Operations Skipped Due to Cache Disconnection",
     "type": "timeseries",
     "description": "This metric shows the total number of nix operations that were skipped because the cache was disconnected. A high value could indicate network instability or other issues causing frequent disconnections, which prevent the system from effectively performing nix operations.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flexcache_nix_skipped_reason_disconnected{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_nix_skipped_reason_disconnected{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Nix Operations Skipped When Cache Volume is Offline",
     "type": "timeseries",
     "description": "This metric indicates the total number of nix operations that were skipped because the cache volume was offline. A high value could suggest that the cache volume is frequently going offline, which could be due to a variety of issues such as network problems, hardware failures, or configuration errors. This prevents the system from effectively performing nix operations.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flexcache_nix_skipped_reason_offline{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flexcache_nix_skipped_reason_offline{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$FlexCache\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    }
   ]
  }
 ]
}