{
 "title": "ONTAP: SnapMirror",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(snapmirror_labels{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(snapmirror_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "DestinationNode",
    "query": {
     "query": "label_values(snapmirror_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\", cluster=~\"$Cluster\"}, destination_node)"
    }
   },
   {
    "name": "SourceNode",
    "query": {
     "query": "label_values(snapmirror_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}, source_node)"
    }
   },
   {
    "name": "DestinationSVM",
    "query": {
     "query": "label_values(snapmirror_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\"}, destination_vserver)"
    }
   },
   {
    "name": "SourceSVM",
    "query": {
     "query": "label_values(snapmirror_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}, source_vserver)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SnapMirrors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (relationship_id) (snapmirror_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Volume Protection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (relationship_id) (snapmirror_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",group_type=\"none\"}))"
    }
   ]
  },
  {
   "title": "SVM Protection (DR)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (relationship_id) (snapmirror_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",group_type=\"vserver\"}))"
    }
   ]
  },
  {
   "title": "Insync now",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (relationship_id) (snapmirror_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",relationship_status=\"insync\"}))"
    }
   ]
  },
  {
   "title": "Unhealthy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (relationship_id) (snapmirror_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",healthy=\"false\"}))"
    }
   ]
  },
  {
   "title": "Last Transfers",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg (snapmirror_last_transfer_duration{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}) by (relationship_id)"
    },
    {
     "expr": "avg(snapmirror_last_transfer_size{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}) by (relationship_id)"
    },
    {
     "expr": "snapmirror_lag_time{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  { "title": "SnapMirrors per Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Destination Relationships per Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "count by (destination_node, relationship_status) (snapmirror_total_transfer_bytes{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",destination_node=~\"$DestinationNode\",destination_node!=\"\"})",
     "legendFormat": "{{destination_node}} - {{relationship_status}}",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Destination - Break Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (destination_node) (snapmirror_break_failed_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",destination_node=~\"$DestinationNode\",destination_node!=\"\"})",
     "legendFormat": "{{destination_node}} - FAIL",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    },
    {
     "expr": "sum by (destination_node) (snapmirror_break_successful_count{datacenter=~\"$Datacenter\",cluster=~\"$System\",destination_node=~\"$DestinationNode\",destination_node!=\"\"})",
     "legendFormat": "{{destination_node}} - SUCCESS",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Destination - Resync Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (destination_node) (snapmirror_resync_failed_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",destination_node=~\"$DestinationNode\",destination_node!=\"\"})",
     "legendFormat": "{{destination_node}} - FAIL",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    },
    {
     "expr": "sum by (destination_node) (snapmirror_resync_successful_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",destination_node=~\"$DestinationNode\",destination_node!=\"\"})",
     "legendFormat": "{{destination_node}} - SUCCESS",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Destination - Update Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (destination_node) (snapmirror_update_failed_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",destination_node=~\"$DestinationNode\",destination_node!=\"\"})",
     "legendFormat": "{{destination_node}} - FAIL",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    },
    {
     "expr": "sum by (destination_node) (snapmirror_update_successful_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",destination_node=~\"$DestinationNode\",destination_node!=\"\"})",
     "legendFormat": "{{destination_node}} - SUCCESS",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Source Relationships per Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "count by (source_node, relationship_status) (snapmirror_total_transfer_bytes{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_node=~\"$SourceNode\",source_node!=\"\"})",
     "legendFormat": "{{source_node}} - {{relationship_status}}",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Source - Break Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (source_node) (snapmirror_break_failed_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_node=~\"$SourceNode\",source_node!=\"\"})",
     "legendFormat": "{{source_node}} - FAIL",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    },
    {
     "expr": "sum by (source_node) (snapmirror_break_successful_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_node=~\"$SourceNode\",source_node!=\"\"})",
     "legendFormat": "{{source_node}} - SUCCESS",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Source - Resync Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (source_node) (snapmirror_resync_failed_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_node=~\"$SourceNode\",source_node!=\"\"})",
     "legendFormat": "{{source_node}} - FAIL",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    },
    {
     "expr": "sum by (source_node) (snapmirror_resync_successful_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_node=~\"$SourceNode\",source_node!=\"\"})",
     "legendFormat": "{{source_node}} - SUCCESS",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Source - Update Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (source_node) (snapmirror_update_failed_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_node=~\"$SourceNode\",source_node!=\"\"})",
     "legendFormat": "{{source_node}} - FAIL",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    },
    {
     "expr": "sum by (source_node) (snapmirror_update_successful_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_node=~\"$SourceNode\",source_node!=\"\"})",
     "legendFormat": "{{source_node}} - SUCCESS",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  { "title": "SnapMirrors per SVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Source Relationships per SVM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "count by (source_vserver, relationship_status) (snapmirror_total_transfer_bytes{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_vserver=~\"$SourceSVM\",source_vserver!=\"\"})",
     "legendFormat": "{{source_vserver}} - {{relationship_status}}",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Destination Relationships per SVM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "count by (destination_vserver, relationship_status) (snapmirror_total_transfer_bytes{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",destination_vserver=~\"$DestinationSVM\",destination_vserver!=\"\"})",
     "legendFormat": "{{destination_vserver}} - {{relationship_status}}",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "SnapMirror Data Protection Overview per Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "title": "Protected By Status",
   "type": "piechart",
   "description": "Volumes Protected With Snapmirror (Local And Remote)",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",protectedBy=~\"snapmirror.*|consistency_group.*|cg_and_snapmirror.*\",protectionRole=\"protected\", snapshot_policy!=\"\"})",
     "legendFormat": "Volume Snapmirror"
    },
    {
     "expr": "count(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",protectedBy=\"storage_vm_dr\",protectionRole=\"protected\",snapshot_policy!=\"\"})",
     "legendFormat": "Storage VM Snapmirror"
    },
    {
     "expr": "count(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",protectedBy=\"svmdr_and_snapmirror\",protectionRole=\"protected\",snapshot_policy!=\"\"})",
     "legendFormat": "Volume and Storage VM Snapmirror"
    },
    {
     "expr": "count(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",protectionRole=\"unprotected\",snapshot_policy!=\"\"})",
     "legendFormat": "Unprotected"
    }
   ]
  },
  {
   "title": "Volume Snapmirror",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",protectedBy=~\"snapmirror.*|consistency_group.*|cg_and_snapmirror.*\",protectionRole=\"protected\",snapshot_policy!=\"\"})"
    }
   ]
  },
  {
   "title": "Volume & Storage VM Snapmirror",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",protectedBy=~\"svmdr_and_snapmirror\",protectionRole=\"protected\",snapshot_policy!=\"\"})"
    }
   ]
  },
  {
   "title": "Lag Status",
   "type": "piechart",
   "description": "Volumes Experiencing Lag",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(group by (source_volume) (1 < snapmirror_lag_time{datacenter=\"$Datacenter\",cluster=~\"$Cluster\", source_volume!=\"\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\")  <= 900))",
     "legendFormat": "<=15 minutes"
    },
    {
     "expr": "count(group by (source_volume) (900 < snapmirror_lag_time{datacenter=\"$Datacenter\",cluster=~\"$Cluster\", source_volume!=\"\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\")  <= 1800))",
     "legendFormat": "16-30 minutes"
    },
    {
     "expr": "count(group by (source_volume) (1800 < snapmirror_lag_time{datacenter=\"$Datacenter\",cluster=~\"$Cluster\", source_volume!=\"\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\")  <= 3600))",
     "legendFormat": "31-60 minutes"
    },
    {
     "expr": "count(group by (source_volume) (snapmirror_lag_time{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",source_volume!=\"\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\") > 3600))",
     "legendFormat": ">= 60 minutes"
    }
   ]
  },
  {
   "title": "<=15 minutes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (source_volume) (1 < snapmirror_lag_time{datacenter=\"$Datacenter\",cluster=~\"$Cluster\", source_volume!=\"\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\")  <= 900))"
    }
   ]
  },
  {
   "title": "16-30 minutes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (source_volume) (900 < snapmirror_lag_time{datacenter=\"$Datacenter\",cluster=~\"$Cluster\", source_volume!=\"\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\")  <= 1800))"
    }
   ]
  },
  {
   "title": "Storage VM Snapmirror",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",protectedBy=~\"storage_vm_dr\",protectionRole=\"protected\",snapshot_policy!=\"\"})"
    }
   ]
  },
  {
   "title": "Unprotected",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",protectionRole=\"unprotected\",snapshot_policy!=\"\"})"
    }
   ]
  },
  {
   "title": "31-60 minutes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (source_volume) (1800 < snapmirror_lag_time{datacenter=\"$Datacenter\",cluster=~\"$Cluster\", source_volume!=\"\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\")  <= 3600))"
    }
   ]
  },
  {
   "title": ">60 minutes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (source_volume) (snapmirror_lag_time{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",source_volume!=\"\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\") > 3600))"
    }
   ]
  },
  {
   "title": "SnapMirror Volumes (local and remote) Protected by",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\", protectionRole != \"destination\",snapshot_policy!=\"\"}"
    }
   ]
  },
  {
   "title": "Volumes Experiencing Lag",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "snapmirror_lag_time{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",source_volume!=\"\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "SnapMirror Data Protection Analysis per Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 }
  },
  {
   "title": "Volume count by relationship type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(snapmirror_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\", derived_relationship_type=\"extended_data_protection\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\") )  ",
     "legendFormat": "Asynchronous Mirror"
    },
    {
     "expr": "count(snapmirror_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\", derived_relationship_type=\"mirror_vault\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\") )  ",
     "legendFormat": "Asynchronous Mirror and Vault"
    },
    {
     "expr": "count(snapmirror_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\", derived_relationship_type=\"vault\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\") )  ",
     "legendFormat": "Asynchronous Vault"
    },
    {
     "expr": "count(snapmirror_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\", derived_relationship_type=\"sync_mirror_strict\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\") )  ",
     "legendFormat": "StrictSync"
    },
    {
     "expr": "count(snapmirror_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\", derived_relationship_type=\"sync_mirror\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\") )  ",
     "legendFormat": "Sync"
    }
   ]
  },
  {
   "title": "Asynchronous Mirror",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(snapmirror_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\", derived_relationship_type=\"extended_data_protection\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\") )  "
    }
   ]
  },
  {
   "title": "Asynchronous Mirror and Vault",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(snapmirror_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\", derived_relationship_type=\"mirror_vault\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\") )  "
    }
   ]
  },
  {
   "title": "Asynchronous Vault",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(snapmirror_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\", derived_relationship_type=\"vault\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\") )  "
    }
   ]
  },
  {
   "title": "Volume count by relationship health",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 14, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(group by (volume)(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\", volume!~\"MDV.*\", all_sm_healthy=\"true\"}))",
     "legendFormat": "Healthy"
    },
    {
     "expr": "count(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\", all_sm_healthy=\"false\"})",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Healthy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (volume)(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\", volume!~\"MDV.*\", all_sm_healthy=\"true\"}))"
    }
   ]
  },
  {
   "title": "StrictSync",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(snapmirror_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\", derived_relationship_type=\"sync_mirror_strict\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\") )  "
    }
   ]
  },
  {
   "title": "Sync",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(snapmirror_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\", derived_relationship_type=\"sync_mirror\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\") )  "
    }
   ]
  },
  {
   "title": "Unhealthy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\", all_sm_healthy=\"false\"})"
    }
   ]
  },
  {
   "title": "Volume count by relationship type",
   "type": "table",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "snapmirror_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\") "
    }
   ]
  },
  {
   "title": "Volume count by relationship health",
   "type": "table",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 83 },
   "targets": [
    {
     "expr": "snapmirror_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\"} * on (source_volume, source_vserver, cluster) group_left() label_replace( label_replace(volume_labels{datacenter=\"$Datacenter\", cluster=~\"$Cluster\",volume!~\"MDV.*\",type=\"rw\",all_sm_healthy != \"\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\") "
    }
   ]
  }
 ]
}