{
 "title": "ONTAP: NFS Clients",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(volume_labels{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(volume_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}, svm)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\"}, volume)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information about NFS Clients dashboard",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "You must enable the Rest collector in your harvest.yml config and uncomment the nfs_clients.yaml section in your $HARVEST/conf/rest/default.yaml file. Please see https://github.com/NetApp/harvest/wiki/FAQ/_edit#nfs-clients-dashboard for more details"
   }
  },
  {
   "title": "Total NFS Connections",
   "type": "stat",
   "description": "This panel requires a cluster with ONTAP 9.7+ and the Harvest REST collector",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(nfs_clients_idle_duration{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})"
    }
   ]
  },
  {
   "title": "NFS Connections by Protocol",
   "type": "piechart",
   "description": "This panel requires a cluster with ONTAP 9.7+ and the Harvest REST collector",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(nfs_clients_idle_duration{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",protocol=\"nfs\"})",
     "legendFormat": "nfs"
    },
    {
     "expr": "count(nfs_clients_idle_duration{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",protocol=\"nfs3\"})",
     "legendFormat": "nfs3"
    },
    {
     "expr": "count(nfs_clients_idle_duration{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",protocol=\"nfs4\"})",
     "legendFormat": "nfs4"
    },
    {
     "expr": "count(nfs_clients_idle_duration{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",protocol=\"nfs4.1\"})",
     "legendFormat": "nfs4.1"
    },
    {
     "expr": "count(nfs_clients_idle_duration{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",protocol=\"nfs4.2\"})",
     "legendFormat": "nfs4.2"
    }
   ]
  },
  {
   "title": "NFS Clients (active in the past 48 hours)",
   "type": "table",
   "description": "This panel requires a cluster with ONTAP 9.7+ and the Harvest REST collector",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "nfs_clients_idle_duration{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
    }
   ]
  }
 ]
}