{
 "title": "ONTAP: Disk",
 "tags": [
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(disk_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\"},cluster)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(disk_labels{system_type!=\"7mode\",cluster=\"$Cluster\"}, node)"
    }
   },
   {
    "name": "Aggregate",
    "query": {
     "query": "label_values(aggr_disk_busy{cluster=\"$Cluster\",node=~\"$Node\"}, aggr)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   },
   {
    "name": "DiskType",
    "query": {
     "query": "label_values(disk_labels{cluster=\"$Cluster\"}, type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Disks by Node(s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( count by(disk) (disk_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}) )"
    }
   ]
  },
  {
   "title": "Failed Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( count by(serial_number) (disk_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",failed=\"true\"}) )"
    }
   ]
  },
  {
   "title": "Raid Groups",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( count by(raid) (aggr_disk_busy{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}) )"
    }
   ]
  },
  {
   "title": "Plexes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( count by(plex) (aggr_disk_busy{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}) )"
    }
   ]
  },
  {
   "title": "Total Disks by Aggregate(s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_raid_disk_count{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"})"
    }
   ]
  },
  {
   "title": "Disk Capacity per Aggregate",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aggr_raid_disk_count{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
    },
    {
     "expr": "aggr_space_total{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
    },
    {
     "expr": "aggr_space_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
    }
   ]
  },
  {
   "title": "Disk Utilization per Aggregate",
   "type": "table",
   "description": "Highest Disk Utilization per Aggregate for latest record (independent of time range selected)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (node, aggr) (aggr_disk_max_total_transfers{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"})"
    },
    {
     "expr": "max by (node, aggr) (aggr_disk_max_busy{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"})"
    }
   ]
  },
  {
   "title": "Max Disk Utilization Per Aggregate",
   "type": "timeseries",
   "description": "Highest Disk Utilization per Aggregate in the selected time range",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (node, aggr) (aggr_disk_max_busy{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"})",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Disk Transfers",
   "type": "timeseries",
   "description": "Total number of disk operations involving data transfer initiated per second\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (node, aggr) (aggr_disk_max_total_transfers{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"})",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "List of Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disks in Cluster",
     "type": "table",
     "description": "Some Clusters don't report average latency, so the values might be 0s.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "disk_bytes_per_sector * disk_sectors{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}"
      },
      {
       "expr": "disk_stats_io_kbps{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}"
      },
      {
       "expr": "disk_stats_average_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}"
      },
      {
       "expr": "disk_uptime{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}"
      },
      {
       "expr": "label_join(disk_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}, \"diskStatus\", \" \",\"NonSupportedField\", \"outage\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Utilization: Node-level overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "KiBs" } },
     "targets": [
      {
       "expr": "sum (node_disk_data_read{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}) by (node)",
       "legendFormat": "{{node}} - READ"
      },
      {
       "expr": "sum (node_disk_data_written{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}) by (node)",
       "legendFormat": "{{node}} - WRITE"
      }
     ]
    },
    {
     "title": "Disk and Tape Drives Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum (hostadapter_bytes_written{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}) by (node)",
       "legendFormat": "{{node}} - WRITE"
      },
      {
       "expr": "sum (hostadapter_bytes_read{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}) by (node)",
       "legendFormat": "{{node}} - READ"
      }
     ]
    },
    {
     "title": "CP (Consistency Points) Counts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum(wafl_cp_count{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",metric=~\"back_to_back_CP|deferred_back_to_back_CP\"})",
       "legendFormat": "Back-to-back CP Count"
      },
      {
       "expr": "node_vol_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}",
       "legendFormat": "Write Latency {{node}}"
      }
     ]
    },
    {
     "title": "Flash Cache",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (flashcache_hit_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Hit %"
      },
      {
       "expr": "sum (flashcache_disk_reads_replaced{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "HDD Reads Replaced"
      }
     ]
    },
    {
     "title": "Flash Pool",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum (flashpool_read_ops_replaced_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Hit %"
      },
      {
       "expr": "sum (flashpool_read_ops_replaced{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "HDD Reads Replaced"
      }
     ]
    }
   ]
  }
 ]
}