{
 "title": "NetApp Detail: Data Protection",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(volume_labels{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(volume_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\"},cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Snapshot Copies Overview",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(volume_labels{snapshot_policy!=\"\", snapshot_policy!~\"none.*\", volume!~\"MDV.*\"}  * on (snapshot_policy) group_left () group by (snapshot_policy) (snapshot_total_schedules{}) )",
     "legendFormat": "VOLUMES PROTECTED WITH SNAPSHOT COPIES (LOCAL)"
    },
    {
     "expr": "count(volume_labels{snapshot_policy!=\"\", snapshot_policy!~\"none.*\"}  * on (snapshot_policy) group_left () group by (snapshot_policy) (snapshot_total_schedules{}) * on (volume, svm) group_right() ( volume_snapshot_reserve_size{} >= 0 and volume_snapshots_size_used{} > 0 and volume_snapshots_size_used{} > volume_snapshot_reserve_size{}))",
     "legendFormat": "VOLUMES BREACHING SNAPSHOT COPY RESERVE SPACE"
    }
   ]
  },
  { "title": "Snapshot Copies Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Volumes protected with Snapshot copies (Local)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",snapshot_policy!=\"\", snapshot_policy!~\"none.*\", volume!~\"MDV.*\"}  * on (snapshot_policy) group_left () group by (snapshot_policy) (snapshot_total_schedules{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}) )",
     "legendFormat": "protected"
    },
    {
     "expr": "count((volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\", snapshot_policy=~\"none.*\", volume!~\"MDV.*\"}  * on (snapshot_policy) group_left () group by (snapshot_policy) (snapshot_total_schedules{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}) )) ",
     "legendFormat": "unprotected"
    }
   ]
  },
  {
   "title": "Volumes breaching Snapshot copy reserve space",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",snapshot_policy!=\"\", snapshot_policy!~\"none.*\"}  * on (snapshot_policy) group_left () group by (snapshot_policy) (snapshot_total_schedules{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}) * on (volume, svm) group_right() ( volume_snapshot_reserve_size{datacenter=\"$Datacenter\",cluster=\"$Cluster\"} >= 0 and volume_snapshots_size_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\"} == 0))",
     "legendFormat": "Not using reserve space"
    },
    {
     "expr": "count((volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",snapshot_policy!=\"\", snapshot_policy!~\"none.*\"}  * on (snapshot_policy) group_left () group by (snapshot_policy) (snapshot_total_schedules{datacenter=\"$Datacenter\",cluster=\"$Cluster\"})) * on (volume, svm) group_right() (volume_snapshot_reserve_size{datacenter=\"$Datacenter\",cluster=\"$Cluster\"} > 0 and volume_snapshots_size_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\"} > 0 and volume_snapshots_size_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\"} <= volume_snapshot_reserve_size{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}))",
     "legendFormat": "Using allocated reserve space"
    },
    {
     "expr": "count(volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",snapshot_policy!=\"\", snapshot_policy!~\"none.*\"}  * on (snapshot_policy) group_left () group by (snapshot_policy) (snapshot_total_schedules{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}) * on (volume, svm) group_right() ( volume_snapshot_reserve_size{datacenter=\"$Datacenter\",cluster=\"$Cluster\"} >= 0 and volume_snapshots_size_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\"} > 0 and volume_snapshots_size_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\"} > volume_snapshot_reserve_size{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}))",
     "legendFormat": "Reserve space breached"
    }
   ]
  },
  {
   "title": "Volume count by the number of Snapshot copies",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count((volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",snapshot_policy!=\"\", snapshot_policy!~\"none.*\", volume!~\"MDV.*\"}  * on (snapshot_policy) group_left () group by (snapshot_policy) (snapshot_total_schedules{datacenter=\"$Datacenter\",cluster=\"$Cluster\"})) * on (volume,svm) (volume_snapshot_count{} > 0 and volume_snapshot_count{} < 10))",
     "legendFormat": " <10 Copies "
    },
    {
     "expr": "count((volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",snapshot_policy!=\"\", snapshot_policy!~\"none.*\", volume!~\"MDV.*\"}  * on (snapshot_policy) group_left () group by (snapshot_policy) (snapshot_total_schedules{datacenter=\"$Datacenter\",cluster=\"$Cluster\"})) * on (volume,svm) (volume_snapshot_count{} >= 10 and volume_snapshot_count{} <= 100))",
     "legendFormat": "10-100 Copies"
    },
    {
     "expr": "count((volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",snapshot_policy!=\"\", snapshot_policy!~\"none.*\", volume!~\"MDV.*\"}  * on (snapshot_policy) group_left () group by (snapshot_policy) (snapshot_total_schedules{datacenter=\"$Datacenter\",cluster=\"$Cluster\"})) * on (volume,svm) (volume_snapshot_count{} > 100 and volume_snapshot_count{} <= 500))",
     "legendFormat": "101-500 Copies"
    },
    {
     "expr": "count((volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",snapshot_policy!=\"\", snapshot_policy!~\"none.*\", volume!~\"MDV.*\"}  * on (snapshot_policy) group_left () group by (snapshot_policy) (snapshot_total_schedules{datacenter=\"$Datacenter\",cluster=\"$Cluster\"})) * on (volume,svm) (volume_snapshot_count{} > 500))",
     "legendFormat": ">500 Copies"
    }
   ]
  }
 ]
}