{
 "title": "NetApp Detail: Node - Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\", cluster=\"$Cluster\"}, node)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( count by (node) (node_new_status{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}) )"
    }
   ]
  },
  {
   "title": "Aggregates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (aggr) (aggr_new_status{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}))"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(volume_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})/1000"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(volume_write_data+volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "IOPs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(volume_total_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_cpu_busy{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by(node) (volume_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (volume_write_data+volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Top Average IOPs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by(node) (volume_total_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_disk_busy{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uptime{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}",
     "legendFormat": "{{cluster}} - {{node}}"
    }
   ]
  },
  {
   "title": "Node Fan Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_failed_fan{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}",
     "legendFormat": "{{cluster}} - {{node}}"
    }
   ]
  },
  {
   "title": "Node Power Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_failed_power{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}",
     "legendFormat": "{{cluster}} - {{node}}"
    }
   ]
  },
  {
   "title": "CPU Layer Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "node_avg_processor_busy{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CPU Busy Domains ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by(metric) (node_cpu_domain_busy{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{metric}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Layer Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet Port Utilization Percent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, nic_util_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{cluster}} - {{svm}} - {{node}} - {{nic}}"
      }
     ]
    },
    {
     "title": "FC Port Utilization Percent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, fcp_util_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{cluster}} {{svm}} - {{node}} -{{port}}"
      }
     ]
    },
    {
     "title": "Ethernet Port Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, nic_rx_bytes+nic_tx_bytes{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{cluster}} - {{svm}} - {{node}} - {{nic}}"
      }
     ]
    },
    {
     "title": "FC Port Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, fcp_read_data+fcp_write_data+fcp_nvmf_read_data+fcp_nvmf_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{cluster}} - {{svm}} - {{node}} - {{port}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg(volume_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(volume_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Write"
      },
      {
       "expr": "avg(volume_other_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(volume_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "IOPs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(volume_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(volume_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(volume_other_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "System Utilization",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(node_cpu_busy{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "CPU Busy"
      },
      {
       "expr": "avg(node_cpu_domain_busy{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",metric=\"kahuna\"})",
       "legendFormat": "Kahuna"
      },
      {
       "expr": "avg(node_disk_busy{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Disk Busy"
      }
     ]
    },
    {
     "title": "Reads From",
     "type": "graph",
     "description": "Percent of reads on node that are supplied from, and had to wait on, various media types",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by(metric) (wafl_read_io_type{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "Protocol Backend IOPs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(node_cifs_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "cifs"
      },
      {
       "expr": "sum(node_nfs_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "nfs"
      },
      {
       "expr": "sum(node_fcp_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "fcp"
      },
      {
       "expr": "sum(node_iscsi_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "iscsi"
      },
      {
       "expr": "sum(node_nvmf_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "NVMe/FC"
      }
     ]
    }
   ]
  },
  {
   "title": "NFSv3 Frontend Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFSv3 Avg Read Latency",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_nfs_read_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nfsv=\"v3\"})"
      }
     ]
    },
    {
     "title": "NFSv3 Avg Latency",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_nfs_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nfsv=\"v3\"})"
      }
     ]
    },
    {
     "title": "NFSv3 Avg Write Latency",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_nfs_write_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nfsv=\"v3\"})"
      }
     ]
    },
    {
     "title": "NFSv3 Avg Throughput",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg(node_nfs_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nfsv=\"v3\"})",
       "legendFormat": "Avg"
      },
      {
       "expr": "avg(node_nfs_write_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nfsv=\"v3\"})",
       "legendFormat": "Avg"
      },
      {
       "expr": "avg(node_nfs_read_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nfsv=\"v3\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "NFS Avg IOPS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg(node_nfs_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "avg(node_nfs_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}) - avg(node_nfs_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}) - avg(node_nfs_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Avg"
      },
      {
       "expr": "avg(node_nfs_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Avg"
      },
      {
       "expr": "avg(node_nfs_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "NFSv3 Read and Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg(node_nfs_read_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nfsv=\"v3\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(node_nfs_write_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nfsv=\"v3\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "NFSv3 Read and Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg(node_nfs_read_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nfsv=\"v3\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(node_nfs_write_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nfsv=\"v3\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "NFSv3 Read and Write IOPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg(node_nfs_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nfsv=\"v3\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(node_nfs_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nfsv=\"v3\"})",
       "legendFormat": "Write"
      },
      {
       "expr": "avg(node_nfs_total_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nfsv=\"v3\"})",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "CIFS Frontend Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "CIFS Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_cifs_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})"
      }
     ]
    },
    {
     "title": "CIFS IOPs",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_cifs_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})"
      }
     ]
    },
    {
     "title": "CIFS IOPs by Type",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum by (metric) (node_cifs_op_count{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "CIFS Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_cifs_connections{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Connections"
      },
      {
       "expr": "sum(node_cifs_established_sessions{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Established Sessions"
      },
      {
       "expr": "sum(node_cifs_signed_sessions{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Signed Sessions"
      },
      {
       "expr": "sum(node_cifs_open_files{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Open Files"
      }
     ]
    }
   ]
  },
  {
   "title": "FCP Frontend Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "FCP Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(fcp_lif_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})"
      }
     ]
    },
    {
     "title": "FCP IOPs",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fcp_lif_total_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})"
      }
     ]
    },
    {
     "title": "FCP Average Latency by Port / LIF",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg by(lif, port, node) (fcp_lif_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    },
    {
     "title": "FCP Throughput by Port / LIF",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by(node, port, lif) (fcp_lif_read_data+fcp_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    },
    {
     "title": "FCP IOPs by Port / LIF",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "avg by(node, port, lif) (fcp_lif_total_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{port_id}} - {{lif}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NVMe/FC Frontend Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "NVMe/FC Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(nvme_lif_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})"
      }
     ]
    },
    {
     "title": "NVMe/FC IOPs",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(nvme_lif_total_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})"
      }
     ]
    },
    {
     "title": "NVMe/FC Average Latency by Port / LIF",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg by(lif, port, node) (nvme_lif_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    },
    {
     "title": "NVMe/FC Throughput by Port / LIF",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by(node, port, lif) (nvme_lif_read_data+nvme_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{port}} - {{lif}}"
      }
     ]
    },
    {
     "title": "NVMe/FC IOPs by Port / LIF",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "avg by(node, port, lif) (nvme_lif_total_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{port_id}} - {{lif}}"
      }
     ]
    }
   ]
  },
  {
   "title": "iSCSI Frontend Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "iSCSI Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(iscsi_lif_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})"
      }
     ]
    },
    {
     "title": "iSCSI IOPs",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(iscsi_lif_iscsi_read_ops+iscsi_lif_iscsi_write_ops+iscsi_lif_iscsi_other_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})"
      }
     ]
    },
    {
     "title": "Average Latency by LIF",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg by(node, lif) (iscsi_lif_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{lif}}"
      }
     ]
    },
    {
     "title": "Throughput by LIF",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by(node, lif) (iscsi_lif_read_data+iscsi_lif_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{lif}}"
      }
     ]
    },
    {
     "title": "IOPs by LIF",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "avg by(node, lif) (iscsi_lif_iscsi_read_ops+iscsi_lif_iscsi_write_ops+iscsi_lif_iscsi_other_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{lif}}"
      }
     ]
    }
   ]
  }
 ]
}