{
 "title": "ONTAP: Cdot",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\"},cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(svm_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\",cluster=~\"$Cluster\"},svm)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(volume_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"},volume)"
    }
   },
   {
    "name": "TopCpuUtilization",
    "query": {
     "query": "query_result(topk($TopResources, avg by (cluster) (avg_over_time(node_cpu_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}[${__range}]))))"
    }
   },
   {
    "name": "TopAvgLatency",
    "query": {
     "query": "query_result(topk($TopResources, avg by (cluster) (avg_over_time(node_volume_avg_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}[${__range}]))))"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   },
   {
    "name": "TopCifsOps",
    "query": {
     "query": "query_result(topk($TopResources, sum by (cluster) (avg_over_time(node_cifs_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}[${__range}]))))"
    }
   },
   {
    "name": "TopNfsOps",
    "query": {
     "query": "query_result(topk($TopResources, sum by (cluster) (avg_over_time(node_nfs_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}[${__range}]))))"
    }
   },
   {
    "name": "TopTotalOps",
    "query": {
     "query": "query_result(topk($TopResources, sum by (cluster) (avg_over_time(volume_total_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}[${__range}]))))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CIFS Top IOPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk($TopResources, sum by (cluster) (node_cifs_ops{datacenter=~\"$Datacenter\",cluster=~\"$TopCifsOps\"}))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "NFS Top IOPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk($TopResources, sum by (cluster) (node_nfs_ops{datacenter=~\"$Datacenter\",cluster=~\"$TopNfsOps\"}))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Total Top IOPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk($TopResources, sum by (cluster) (volume_total_ops{datacenter=~\"$Datacenter\",cluster=~\"$TopTotalOps\"}))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Top SVM capacity Used Percent",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($TopResources, (100 * sum by (cluster, svm) (volume_size_used{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) /   sum by (cluster, svm) (volume_size_total{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"})))"
    }
   ]
  },
  {
   "title": "Top Volume Capacity Used Percent",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($TopResources, (100 * volume_size_used{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"} / volume_size_total{datacenter=\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}))"
    }
   ]
  },
  {
   "title": "Top Aggregate Capacity Used Percent",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($TopResources, (100 * aggr_space_used{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"} / aggr_space_total{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "IOPs",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk($TopResources, sum(node_volume_total_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by (cluster))"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk($TopResources, avg(node_volume_read_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by (cluster)) / 1000"
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($TopResources, avg by (cluster) (node_cpu_busy{datacenter=~\"$Datacenter\",cluster=~\"$TopCpuUtilization\"}))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk($TopResources, avg(node_volume_avg_latency{datacenter=~\"$Datacenter\",cluster=~\"$TopAvgLatency\"}) by (cluster)) / 1000",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}