{
 "title": "ONTAP: Headroom",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\"}, cluster)"
    }
   },
   { "name": "Interval", "query": "hourly, daily, weekly, monthly" }
  ]
 },
 "panels": [
  { "title": "Available Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available Ops: Aggregate",
   "type": "timeseries",
   "description": "A projection of the amount of available IOP/s each node has with the current workloads before increased hockey stick style latencies are encountered",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "headroom_aggr_optimal_point_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\"} - headroom_aggr_current_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Available Ops: CPU",
   "type": "timeseries",
   "description": "A projection of the amount of available IOP/s each node has with the current workloads before increased hockey stick style latencies are encountered",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "headroom_cpu_optimal_point_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\"} - headroom_cpu_current_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Aggregate Headroom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_aggr_current_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Current IOP/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "headroom_aggr_current_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Current Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_aggr_current_utilization{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Optimal-Point Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_aggr_optimal_point_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Optimal-Point IOP/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "headroom_aggr_optimal_point_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Optimal-Point Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_aggr_optimal_point_utilization{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_aggr_ewma_${Interval}{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",metric=\"latency\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval IOP/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "headroom_aggr_ewma_${Interval}{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",metric=\"ops\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_aggr_ewma_${Interval}{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",metric=\"utilization\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Optimal-Point Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_aggr_ewma_${Interval}{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",metric=\"optimal_point_latency\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Optimal-Point IOP/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "headroom_aggr_ewma_${Interval}{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",metric=\"optimal_point_ops\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Optimal-Point Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_aggr_ewma_${Interval}{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",metric=\"optimal_point_utilization\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Headroom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_cpu_current_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Current CPU Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "headroom_cpu_current_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Current Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_cpu_current_utilization{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Optimal-Point Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_cpu_optimal_point_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Optimal-Point Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "headroom_cpu_optimal_point_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Optimal-Point Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_cpu_optimal_point_utilization{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"latency\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"ops\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"utilization\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Optimal-Point Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"optimal_point_latency\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Optimal-Point Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"optimal_point_ops\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Optimal-Point Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"optimal_point_utilization\"}",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}