{
 "title": "ONTAP: Health",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"},cluster)"
    }
   },
   {
    "name": "EMSDescription",
    "query": "This panel displays all emergency EMS alerts active in the past 24 hours. "
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information about Health Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard is compatible with ONTAP 9.6+ and requires the REST collector. To use this dashboard, please follow the step below:\n\n1. **Enable the REST Collector**: Update your `harvest.yml` configuration file to enable the REST collector."
   }
  },
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n                  count(health_disk_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1)\n                or\n                  vector(0)\n              )\n            +\n              (\n                  count(health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1)\n                or\n                  vector(0)\n              )\n          +\n            (\n                count(health_node_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1)\n              or\n                vector(0)\n            )\n        +\n          (\n              count(health_ha_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1)\n            or\n              vector(0)\n          )\n      +\n        (\n            count(\n                environment_sensor_threshold_value{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",threshold_state!=\"normal\"}\n              ==\n                1\n            )\n          or\n            vector(0)\n        )\n    +\n      (\n          count(\n            health_network_fc_port_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1\n          )\n        or\n          vector(0)\n      )\n  +\n    (\n        count(\n            health_network_ethernet_port_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"}\n          ==\n            1\n        )\n      or\n        vector(0)\n    )\n+\n  (\n      count(health_license_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1)\n    or\n      vector(0)\n  )"
    }
   ]
  },
  {
   "title": "Total Warnings",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n              count(health_disk_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"warning\"} == 1)\n            or\n              vector(0)\n          )\n        +\n          (\n              count(health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"warning\"} == 1)\n            or\n              vector(0)\n          )\n      +\n        (\n            count(health_support_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"warning\"} == 1)\n          or\n            vector(0)\n        )\n    +\n      (\n          count(health_lif_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"warning\"} == 1)\n        or\n          vector(0)\n      )\n  +\n    (\n        count(\n          health_volume_move_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"warning\"} == 1\n        )\n      or\n        vector(0)\n    )\n+\n  (\n      count(\n        health_volume_ransomware_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1\n      )\n    or\n      vector(0)\n  )"
    }
   ]
  },
  {
   "title": "Active Emergency EMS Alerts (Last 24 Hours)",
   "type": "stat",
   "description": "$EMSDescription",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(health_ems_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"emergency\"})\nor\n  vector(0)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(health_disk_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1)\nor\n  vector(0)",
     "legendFormat": "Broken Disk"
    },
    {
     "expr": "count(health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1)\nor\n  vector(0)",
     "legendFormat": "Shelf Error"
    },
    {
     "expr": "count(health_node_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1)\nor\n  vector(0)",
     "legendFormat": "Node Down"
    },
    {
     "expr": "(\n      count(\n        health_network_fc_port_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1\n      )\n    or\n      vector(0)\n  )\n+\n  (\n      count(\n          health_network_ethernet_port_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"}\n        ==\n          1\n      )\n    or\n      vector(0)\n  )",
     "legendFormat": "Network Port Down"
    },
    {
     "expr": "count(health_license_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1)\nor\n  vector(0)",
     "legendFormat": "License Non Compliant"
    },
    {
     "expr": "count(health_ha_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1)\nor\n  vector(0)",
     "legendFormat": "HA Down"
    },
    {
     "expr": "count(\n      environment_sensor_threshold_value{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",threshold_state!=\"normal\"}\n    ==\n      1\n  )\nor\n  vector(0)",
     "legendFormat": "Sensor Failures"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(health_disk_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"warning\"} == 1)\nor\n  vector(0)",
     "legendFormat": "Unassigned Disk"
    },
    {
     "expr": "count(health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"warning\"} == 1)\nor\n  vector(0)",
     "legendFormat": "Shelf Warning"
    },
    {
     "expr": "(\n    count(health_support_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"warning\"} == 1)\n  or\n    vector(0)\n)",
     "legendFormat": "Health Monitor Alerts"
    },
    {
     "expr": "count(health_lif_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"warning\"} == 1)\nor\n  vector(0)",
     "legendFormat": "Lif are not at home port"
    },
    {
     "expr": "count(\n    health_volume_move_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"warning\"} == 1\n  )\nor\n  vector(0)",
     "legendFormat": "Volume Move Alerts"
    },
    {
     "expr": "count(\n    health_volume_ransomware_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1\n  )\nor\n  vector(0)",
     "legendFormat": "Volume Ransomware (9.10+)"
    }
   ]
  },
  {
   "title": "Active Emergency EMS Alerts (Last 24 Hours)",
   "type": "table",
   "description": "$EMSDescription",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (message) (\n  health_ems_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"emergency\"}\n)"
    }
   ]
  },
  {
   "title": "HA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "HA Issues",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "node_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (cluster, node, datacenter) group_left (severity, takeover_possible, partner, partner_state, state_description)\n  (health_ha_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      }
     ]
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Issues",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "node_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (cluster, node, datacenter) group_left (severity)\n  (health_node_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      }
     ]
    }
   ]
  },
  {
   "title": "Sensor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sensor Issues",
     "type": "table",
     "description": "Displays sensors with failed state.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "environment_sensor_threshold_value{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",threshold_state!=\"normal\"}\n==\n  1"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disks Issues",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "disk_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (disk, cluster, datacenter) group_left (severity)\n  (health_disk_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      }
     ]
    }
   ]
  },
  {
   "title": "Shelves",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Shelf Issues",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "shelf_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (shelf, cluster, datacenter) group_left (severity, error_type, error_text)\n  (health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "shelf_disk_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (shelf, cluster, datacenter) group_left (severity)\n  (health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "shelf_new_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (shelf, cluster, datacenter) group_left (severity)\n  (health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "shelf_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (shelf, cluster, datacenter) group_left (severity)\n  (health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "shelf_average_ambient_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (shelf, cluster, datacenter) group_left (severity)\n  (health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "shelf_min_ambient_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (shelf, cluster, datacenter) group_left (severity)\n  (health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "shelf_max_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (shelf, cluster, datacenter) group_left (severity)\n  (health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "shelf_average_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (shelf, cluster, datacenter) group_left (severity)\n  (health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "shelf_min_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (shelf, cluster, datacenter) group_left (severity)\n  (health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "shelf_max_fan_speed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (shelf, cluster, datacenter) group_left (severity)\n  (health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "shelf_average_fan_speed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (shelf, cluster, datacenter) group_left (severity)\n  (health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "shelf_min_fan_speed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (shelf, cluster, datacenter) group_left (severity)\n  (health_shelf_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumes with Ransomware Issues (9.10+ Only)",
     "type": "table",
     "description": "Volumes with abnormal activity",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter) group_left (severity, anti_ransomware_attack_probability)\n  (health_volume_ransomware_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_new_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter) group_left (severity)\n  (health_volume_ransomware_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_size_total{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter) group_left (severity)\n  (health_volume_ransomware_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_size_used_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter) group_left (severity)\n  (health_volume_ransomware_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_sis_dedup_saved{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter) group_left (severity)\n  (health_volume_ransomware_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_sis_compress_saved{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter) group_left (severity)\n  (health_volume_ransomware_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_sis_dedup_saved\n+\n    volume_sis_compress_saved{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n  * on (volume, cluster, datacenter) group_left (severity)\n    (health_volume_ransomware_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_space_logical_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter) group_left (severity)\n  (health_volume_ransomware_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_space_physical_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter) group_left (severity)\n  (health_volume_ransomware_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      }
     ]
    },
    {
     "title": "Volumes Move Issues",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter, svm) group_left (severity, movement_state)\n  (health_volume_move_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_new_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter, svm) group_left (severity)\n  (health_volume_move_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_size_total{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter, svm) group_left (severity)\n  (health_volume_move_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_size_used_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter, svm) group_left (severity)\n  (health_volume_move_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_sis_dedup_saved{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter, svm) group_left (severity)\n  (health_volume_move_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_sis_compress_saved{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter, svm) group_left (severity)\n  (health_volume_move_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_sis_dedup_saved\n+\n    volume_sis_compress_saved{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n  * on (volume, cluster, datacenter, svm) group_left (severity)\n    (health_volume_move_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_space_logical_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter, svm) group_left (severity)\n  (health_volume_move_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      },
      {
       "expr": "volume_space_physical_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (volume, cluster, datacenter, svm) group_left (severity)\n  (health_volume_move_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      }
     ]
    }
   ]
  },
  {
   "title": "License",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non Compliant License",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "health_license_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Lif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lif not at home port",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "lif_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n* on (lif, svm, cluster, datacenter) group_left (severity)\n  (health_lif_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Port",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet ports are down",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "health_network_ethernet_port_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1"
      }
     ]
    },
    {
     "title": "FC ports are down",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "health_network_fc_port_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Emergency EMS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Emergency EMS Alerts (Last 24 Hours)",
     "type": "table",
     "description": "$EMSDescription",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum by (datacenter, cluster, node, message, severity) (\n  health_ems_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"emergency\"}\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "System Health Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Alerts",
     "type": "table",
     "description": "These are the health monitor events that have occurred within the selected time range",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "health_support_alerts{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 1"
      }
     ]
    }
   ]
  }
 ]
}