{
 "title": "ONTAP: Network",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\",cluster=~\"$Cluster\"}, node)"
    }
   },
   {
    "name": "Eth",
    "query": {
     "query": "label_values(nic_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"}, nic)"
    }
   },
   {
    "name": "FCP",
    "query": {
     "query": "label_values(fcp_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"}, port)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,20,50,100,250,500,1000"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ethernet Throughput",
   "type": "stat",
   "description": "Bytes sent.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  nic_tx_bytes + nic_rx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}\n)",
     "legendFormat": "Data"
    }
   ]
  },
  {
   "title": "FC Throughput",
   "type": "stat",
   "description": "This panel displays detail of total number of FC-NVMe/FCP operations and amount of FC-NVMe/FCP traffic to and from the storage system.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    fcp_total_data\n  +\n    fcp_nvmf_total_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\n)",
     "legendFormat": "Data"
    },
    {
     "expr": "sum(\n    fcp_total_ops\n  +\n    fcp_nvmf_total_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\n)",
     "legendFormat": "Operations"
    }
   ]
  },
  {
   "title": "Ethernet Receive",
   "type": "stat",
   "description": "Bytes received.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nic_rx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Ethernet Send",
   "type": "stat",
   "description": "Bytes sent.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nic_tx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "FC Read Throughput",
   "type": "stat",
   "description": "This panel displays detail of number of FC-NVMe/FC read operations and amount of data read from the storage system (FC-NVMe/FC).",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    fcp_read_data\n  +\n    fcp_nvmf_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\n)",
     "legendFormat": "Data"
    },
    {
     "expr": "sum(\n    fcp_read_ops\n  +\n    fcp_nvmf_read_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\n)",
     "legendFormat": "Operations"
    }
   ]
  },
  {
   "title": "FC Write Throughput",
   "type": "stat",
   "description": "This panel displays detail of Number of FC-NVMe/FC write operations and amount of data written to the storage system (FC-NVMe/FC).",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    fcp_write_data\n  +\n    fcp_nvmf_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\n)",
     "legendFormat": "Data"
    },
    {
     "expr": "sum(\n    fcp_write_ops\n  +\n    fcp_nvmf_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\n)",
     "legendFormat": "Operations"
    }
   ]
  },
  {
   "title": "Ethernet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet ports",
     "type": "table",
     "description": "Inventory of ethernet ports (physical, VLAN, and LAG).\n\nStatus:\n- up (green): link is up\n- down (red): administratively enabled, but the link is down\n- degraded (red): ONTAP reports the port as degraded\n- admin down (grey): administratively disabled. Not an unexpected link failure.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "label_replace(\n  net_port_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$Eth\"},\n  \"status\",\n  \"disabled\",\n  \"admin_up\",\n  \"false\"\n)"
      },
      {
       "expr": "label_replace(\n  net_port_mtu{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$Eth\"},\n  \"status\",\n  \"disabled\",\n  \"admin_up\",\n  \"false\"\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NIC ports",
     "type": "table",
     "description": "Physical NIC performance (not VLAN or LAG). VLAN/LAG traffic is already included in the underlying NIC counters.\n\nStatus:\n- up (green): NIC link is up\n- down (red): NIC link is down, but the physical ethernet port is still administratively enabled\n- admin down (grey): physical ethernet port is administratively disabled.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "nic_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}"
      },
      {
       "expr": "(\n      nic_new_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}\n    unless on (cluster, datacenter, node, nic)\n      label_replace(\n        net_port_status{admin_up=\"false\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$Eth\"},\n        \"nic\",\n        \"$1\",\n        \"port\",\n        \"(.+)\"\n      )\n  )\nor\n  (\n      0 * nic_new_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"} + 2\n    and on (cluster, datacenter, node, nic)\n      label_replace(\n        net_port_status{admin_up=\"false\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$Eth\"},\n        \"nic\",\n        \"$1\",\n        \"port\",\n        \"(.+)\"\n      )\n  )"
      },
      {
       "expr": "nic_util_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}"
      },
      {
       "expr": "nic_tx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}"
      },
      {
       "expr": "nic_rx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}"
      },
      {
       "expr": "nic_tx_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}"
      },
      {
       "expr": "nic_rx_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}"
      }
     ]
    },
    {
     "title": "Top $TopResources NICs by Send Throughput",
     "type": "timeseries",
     "description": "Bytes sent.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "nic_tx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      nic_tx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{nic}}"
      }
     ]
    },
    {
     "title": "Top $TopResources NICs by Receive Throughput",
     "type": "timeseries",
     "description": "Bytes received.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "nic_rx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      nic_rx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{nic}}"
      }
     ]
    },
    {
     "title": "Top $TopResources NICs by Port Utilization %",
     "type": "timeseries",
     "description": "Percentage of bytes transferred.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "nic_util_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      nic_util_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{nic}}"
      }
     ]
    },
    {
     "title": "NICs Send Errors by Cluster",
     "type": "timeseries",
     "description": "Summarized on Cluster or Node level. Select Eth to show for a specific Ethernet Port.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(nic_tx_total_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"})",
       "legendFormat": "TOTAL"
      },
      {
       "expr": "sum(nic_tx_hw_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"})",
       "legendFormat": "HW"
      },
      {
       "expr": "sum(nic_tx_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"})",
       "legendFormat": "SENT"
      }
     ]
    },
    {
     "title": "NICs Receive Errors by Cluster",
     "type": "timeseries",
     "description": "Summarized on Cluster or Node level. Select Eth to show for a specific Ethernet Port.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(nic_rx_total_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"})",
       "legendFormat": "TOTAL"
      },
      {
       "expr": "sum(\n  nic_rx_alignment_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}\n)",
       "legendFormat": "ALIGNMENT"
      },
      {
       "expr": "sum(nic_rx_crc_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"})",
       "legendFormat": "CRC"
      },
      {
       "expr": "sum(nic_rx_length_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"})",
       "legendFormat": "LENGTH"
      },
      {
       "expr": "sum(nic_rx_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"})",
       "legendFormat": "RECEIVED"
      }
     ]
    },
    {
     "title": "Ethernet port errors",
     "type": "table",
     "description": "Ethernet port errors.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "nic_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}"
      },
      {
       "expr": "sum_over_time(\n  nic_rx_crc_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[$__range]\n)"
      },
      {
       "expr": "sum_over_time(\n  nic_tx_hw_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[$__range]\n)"
      },
      {
       "expr": "sum_over_time(\n  nic_tx_total_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[$__range]\n)"
      },
      {
       "expr": "sum_over_time(\n  nic_rx_total_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[$__range]\n)"
      },
      {
       "expr": "sum_over_time(\n  nic_link_up_to_downs{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[$__range]\n)"
      },
      {
       "expr": "sum_over_time(\n  nic_rx_alignment_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[$__range]\n)"
      },
      {
       "expr": "sum_over_time(\n  nic_rx_length_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[$__range]\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Link Aggregation Group (LAG)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Aggregation Groups",
     "type": "table",
     "description": "Detail of interface group, also known as a Link Aggregation Group (LAG), created by combining two or more physical ports on the same node into a single logical port.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "nic_ifgrp_tx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",ports!=\"\"}"
      },
      {
       "expr": "nic_ifgrp_rx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",ports!=\"\"}"
      },
      {
       "expr": "nic_ifgrp_tx_perc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",ports!=\"\"}"
      },
      {
       "expr": "nic_ifgrp_rx_perc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",ports!=\"\"}"
      }
     ]
    },
    {
     "title": "Top $TopResources LAGs by Send Throughput",
     "type": "timeseries",
     "description": "Bytes sent.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "nic_ifgrp_tx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      nic_ifgrp_tx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{ifgroup}}"
      }
     ]
    },
    {
     "title": "Top $TopResources LAGs by Receive Throughput",
     "type": "timeseries",
     "description": "Bytes received.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "nic_ifgrp_rx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      nic_ifgrp_rx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{ifgroup}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FibreChannel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "FC ports",
     "type": "table",
     "description": "FC port details.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "fcp_util_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}"
      },
      {
       "expr": "fcp_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}"
      },
      {
       "expr": "fcp_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 63 },
     "options": {
      "content": "This panel requires ONTAP 9.6+ and the APIs are only available via REST. Enable the REST collector in your `harvest.yml` config.<br>\nSee https://github.com/NetApp/harvest/wiki/Troubleshooting-Harvest#why-do-i-have-fc-ports-with-fabric-detail-table-empty-in-network-dashboard\nfor more details."
     }
    },
    {
     "title": "FC ports with Fabric detail",
     "type": "table",
     "description": "FC ports with fabric details.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "fcp_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}"
      },
      {
       "expr": "fcp_max_speed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}"
      },
      {
       "expr": "fcp_fabric_connected_speed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}"
      }
     ]
    },
    {
     "title": "Top $TopResources FCPs by Send Throughput",
     "type": "timeseries",
     "description": "Amount of data read from the storage system.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "fcp_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fcp_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    },
    {
     "title": "Top $TopResources FCPs by Receive Throughput",
     "type": "timeseries",
     "description": "Amount of data written to the storage system.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "fcp_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fcp_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    },
    {
     "title": "Top $TopResources FCPs by Send Latency",
     "type": "timeseries",
     "description": "Average latency for read operations.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "fcp_avg_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fcp_avg_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    },
    {
     "title": "Top $TopResources FCPs by Receive Latency",
     "type": "timeseries",
     "description": "Average latency for write operations.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "fcp_avg_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fcp_avg_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    },
    {
     "title": "FCPs Transmission interrupts",
     "type": "timeseries",
     "description": "Summarized on Cluster or Node level. Select FCP to show for a specific FibreChannel Port.",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(fcp_int_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "interrupts"
      },
      {
       "expr": "sum(\n  fcp_invalid_transmission_word{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\n)",
       "legendFormat": "invalid transmission words (blocks)"
      },
      {
       "expr": "sum(fcp_isr_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "interrupt responses"
      },
      {
       "expr": "sum(\n  fcp_spurious_int_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\n)",
       "legendFormat": "spurious interrupts"
      },
      {
       "expr": "sum(fcp_invalid_crc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "invalid CRCs"
      }
     ]
    },
    {
     "title": "FCPs Transmission errors",
     "type": "timeseries",
     "description": "Summarized on Cluster or Node level. Select FCP to show for a specific FibreChannel Port.",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  fcp_discarded_frames_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\n)",
       "legendFormat": "discarded frames"
      },
      {
       "expr": "sum(fcp_loss_of_signal{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "loss of signal"
      },
      {
       "expr": "sum(fcp_loss_of_sync{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "loss of sync"
      },
      {
       "expr": "sum(fcp_prim_seq_err{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "primitive sequence errors"
      },
      {
       "expr": "sum(fcp_queue_full{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "queue full"
      },
      {
       "expr": "sum(fcp_threshold_full{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "threshold full"
      }
     ]
    },
    {
     "title": "Top $TopResources FCPs by Link Down",
     "type": "timeseries",
     "description": "Number of times the Fibre Channel link was lost.",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fcp_link_down{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fcp_link_down{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    },
    {
     "title": "Top $TopResources FCPs by Link Failure",
     "type": "timeseries",
     "description": "Number of link failures.",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fcp_link_failure{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fcp_link_failure{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NVMe/FC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "NVMe/FC ports",
     "type": "table",
     "description": "NVMe/FC port details.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "fcp_nvmf_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
      },
      {
       "expr": "fcp_nvmf_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
      }
     ]
    },
    {
     "title": "Top $TopResources FCP_NVMFs by Send Throughput",
     "type": "timeseries",
     "description": "Amount of data read from the storage system (FC-NVMe).",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "fcp_nvmf_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fcp_nvmf_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    },
    {
     "title": "Top $TopResources FCP_NVMFs by Receive Throughput",
     "type": "timeseries",
     "description": "Amount of data written to the storage system (FC-NVMe).",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "fcp_nvmf_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fcp_nvmf_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    },
    {
     "title": "Top $TopResources FCP_NVMFs by Send Latency",
     "type": "timeseries",
     "description": "Average latency for read operations (FC-NVMe).",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "fcp_nvmf_avg_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fcp_nvmf_avg_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    },
    {
     "title": "Top $TopResources FCP_NVMFs by Receive Latency",
     "type": "timeseries",
     "description": "Average latency for write operations (FC-NVMe).",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "fcp_nvmf_avg_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fcp_nvmf_avg_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Routes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 139 },
     "options": {
      "content": "This panel requires a cluster with ONTAP 9.6+ and the Harvest REST collector"
     }
    },
    {
     "title": "Routes",
     "type": "table",
     "description": "Detail of network routes.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 141 },
     "targets": [
      {
       "expr": "net_route_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  }
 ]
}