{
 "title": "ONTAP: NFS Troubleshooting",
 "tags": [
  "harvest",
  "ontap",
  "cdot",
  "fsx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"},cluster)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\",datacenter=~\"$Datacenter\", cluster=~\"$Cluster\"},node)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(volume_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, svm)"
    }
   },
   {
    "name": "Eth",
    "query": {
     "query": "label_values(nic_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"},nic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Locate nodes with high NFSv4 StorePool resource utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Important Information",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard requires the NFSv4Pool templates. Two actions are required to use this dashboard: <br>1. If you are using the ZapiPerf collector, then you must enable the NFSv4Pool counters in `$HARVEST/conf/zapiperf/default.yaml`. <br>2. If you are using the RestPerf collector, then you must enable the NFSv4Pool counters in `$HARVEST/conf/restperf/default.yaml`. Please see https://github.com/NetApp/harvest/discussions/1796 for more details."
   }
  },
  {
   "title": "All nodes with 1% or more allocations in $Datacenter",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_DelegStateAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_DelegStateMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - DelegStateAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_ByteLockAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_ByteLockMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - ByteLockAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_ClientAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_ClientMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - ClientAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_CopyStateAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_CopyStateMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - ConnectionParentSessionReferenceAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_ConnectionParentSessionReferenceAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_ConnectionParentSessionReferenceMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - ConnectionParentSessionReferenceAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_DelegAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_DelegMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - DelegAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_LockAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_LockMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - LockAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_LayoutStateAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_LayoutStateMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - LayoutStateAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_LockStateAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_LockStateMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - LockStateAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_OpenStateAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_OpenStateMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - OpenStateAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_OpenAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_OpenMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - OpenAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_OwnerAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_OwnerMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - OwnerAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_SessionConnectionHolderAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_SessionConnectionHolderMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - SessionConnectionHolderAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_SessionHolderAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_SessionHolderMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - SessionHolderAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_SessionAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_SessionMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - SessionAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_StateRefHistoryAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_StateRefHistoryMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - StateRefHistoryAlloc"
    },
    {
     "expr": "100\n  *\n    (\n        nfs_diag_storePool_StringAlloc{datacenter=~\"$Datacenter\"}\n      /\n        nfs_diag_storePool_StringMax{datacenter=~\"$Datacenter\"}\n    )\n>\n  1",
     "legendFormat": "{{node}} - StringAlloc"
    }
   ]
  },
  { "title": "Node CPU Headroom for $Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Headroom Overview (Average by Time Range)",
   "type": "table",
   "description": "○ Performance Capacity Used (‘current utilization’ / 'optimal point utilization') \n- Performance Capacity Used provides CPU usage as a fraction of the 'optimal point utilization'\n\n   - ‘optimal point utilization’ takes into account the anticipated point where a latency spike will be encountered\n \n○ Headroom calculation\n- 'current utilization' subtracted from ‘optimal point utilization’.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg_over_time(\n  headroom_cpu_current_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[$__range]\n)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "avg_over_time(\n  headroom_cpu_optimal_point_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[$__range]\n)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "avg_over_time(\n  headroom_cpu_current_utilization{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[$__range]\n)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "avg_over_time(\n  headroom_cpu_optimal_point_utilization{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[$__range]\n)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(\n      headroom_cpu_current_utilization{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n    /\n      headroom_cpu_optimal_point_utilization{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\n*\n  100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Weighted Avg Daily (Headroom)",
   "type": "timeseries",
   "description": "Headroom (optimal point utilization – current utilization) calculated by daily exponential weighted moving average (EWMA).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (node) (\n    headroom_cpu_ewma_daily{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"optimal_point_utilization\",node=~\"$Node\"}\n  )\n-\n  sum by (node) (\n    headroom_cpu_ewma_daily{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"utilization\",node=~\"$Node\"}\n  )",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Weighted Avg Weekly (Headroom)",
   "type": "timeseries",
   "description": "Headroom (optimal point utilization – current utilization) calculated by weekly exponential weighted moving average (EWMA).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (node) (\n    headroom_cpu_ewma_weekly{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"optimal_point_utilization\",node=~\"$Node\"}\n  )\n-\n  sum by (node) (\n    headroom_cpu_ewma_weekly{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"utilization\",node=~\"$Node\"}\n  )",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Locate Highest Performing SVMs (Click SVM for volume table)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "SVM Performance Table",
   "type": "table",
   "description": "This panel displays SVM performance detail.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}"
    },
    {
     "expr": "avg_over_time(\n  svm_vol_total_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[$__range]\n)"
    },
    {
     "expr": "avg_over_time(\n  svm_vol_read_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[$__range]\n)"
    },
    {
     "expr": "avg_over_time(\n  svm_vol_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[$__range]\n)"
    },
    {
     "expr": "avg_over_time(\n  svm_vol_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[$__range]\n)"
    },
    {
     "expr": "avg_over_time(\n  svm_vol_other_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[$__range]\n)"
    },
    {
     "expr": "avg_over_time(\n  svm_vol_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[$__range]\n)"
    }
   ]
  },
  {
   "title": "Network Port Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet ports",
     "type": "table",
     "description": "Ethernet port details.\n\nStatus:\n- up (green): NIC link is up\n- down (red): NIC link is down, but the physical ethernet port is still administratively enabled\n- admin down (grey): physical ethernet port is administratively disabled.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "nic_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}"
      },
      {
       "expr": "(\n      nic_new_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}\n    unless on (cluster, datacenter, node, nic)\n      label_replace(\n        net_port_status{admin_up=\"false\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$Eth\"},\n        \"nic\",\n        \"$1\",\n        \"port\",\n        \"(.+)\"\n      )\n  )\nor\n  (\n      0 * nic_new_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"} + 2\n    and on (cluster, datacenter, node, nic)\n      label_replace(\n        net_port_status{admin_up=\"false\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",port=~\"$Eth\"},\n        \"nic\",\n        \"$1\",\n        \"port\",\n        \"(.+)\"\n      )\n  )"
      },
      {
       "expr": "avg_over_time(\n  nic_util_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[$__range]\n)"
      },
      {
       "expr": "avg_over_time(\n  nic_tx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[$__range]\n)"
      },
      {
       "expr": "avg_over_time(\n  nic_rx_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[$__range]\n)"
      },
      {
       "expr": "sum_over_time(\n  nic_rx_total_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[$__range]\n)"
      },
      {
       "expr": "sum_over_time(\n  nic_tx_total_errors{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[$__range]\n)"
      },
      {
       "expr": "sum_over_time(\n  nic_link_up_to_downs{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nic=~\"$Eth\",node=~\"$Node\"}[$__range]\n)"
      }
     ]
    }
   ]
  }
 ]
}