{
 "title": "ONTAP: S3 Object Storage SVM",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(ontaps3_svm_max_connected_connections{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(ontaps3_svm_max_connected_connections{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(ontaps3_svm_max_connected_connections{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, node)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(ontaps3_svm_max_connected_connections{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"}, svm)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard requires ONTAP 9.8+. Two actions are required to use this dashboard: <br>1. If you are using the ZapiPerf collector, then you must enable the OntapS3SVM counters in `$HARVEST/conf/zapiperf/default.yaml`. <br>2. If you are using the RestPerf collector, then you must enable the OntapS3SVM counters in `$HARVEST/conf/restperf/default.yaml`. Please see https://github.com/NetApp/harvest/discussions/1796 for more details."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests stats",
   "type": "table",
   "description": "The percentage of the total usable space for object data that has been used for the site.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node, svm)(ontaps3_svm_requests{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"})"
    },
    {
     "expr": "sum by (node, svm)(ontaps3_svm_connections{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"})"
    },
    {
     "expr": "sum by (node, svm)(ontaps3_svm_max_requests_outstanding{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"})"
    },
    {
     "expr": "sum by (node,svm)(ontaps3_svm_max_connected_connections{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"})"
    },
    {
     "expr": "sum by (node, svm)(ontaps3_svm_max_cmds_per_connection{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"})"
    }
   ]
  },
  {
   "title": "Operation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Object Total by Operations",
     "type": "timeseries",
     "description": "Number of GET/PUT/HEAD/DELETE object operations.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(datacenter,cluster,node,svm)(ontaps3_svm_get_object_total{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}) and topk($TopResources, avg by(datacenter,cluster,node,svm) (avg_over_time(ontaps3_svm_get_object_total{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}[3h])))",
       "legendFormat": "{{node}} - {{svm}} - GET"
      },
      {
       "expr": "avg by(datacenter,cluster,node,svm)(ontaps3_svm_put_object_total{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}) and topk($TopResources, avg by(datacenter,cluster,node,svm) (avg_over_time(ontaps3_svm_put_object_total{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}[3h])))",
       "legendFormat": "{{node}} - {{svm}} - PUT"
      },
      {
       "expr": "avg by(datacenter,cluster,node,svm)(ontaps3_svm_head_object_total{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}) and topk($TopResources, avg by(datacenter,cluster,node,svm) (avg_over_time(ontaps3_svm_head_object_total{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}[3h])))",
       "legendFormat": "{{node}} - {{svm}} - HEAD"
      },
      {
       "expr": "avg by(datacenter,cluster,node,svm)(ontaps3_svm_delete_object_total{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}) and topk($TopResources, avg by(datacenter,cluster,node,svm) (avg_over_time(ontaps3_svm_delete_object_total{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}[3h])))",
       "legendFormat": "{{node}} - {{svm}} - DELETE"
      }
     ]
    },
    {
     "title": "Top $TopResources Object by Rate",
     "type": "timeseries",
     "description": "Number of GET/PUT/HEAD/DELETE object operations per second.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg by(datacenter,cluster,node,svm)(ontaps3_svm_get_object_rate{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}) and topk($TopResources, avg by(datacenter,cluster,node,svm) (avg_over_time(ontaps3_svm_get_object_rate{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}[3h])))",
       "legendFormat": "{{node}} - {{svm}} - GET"
      },
      {
       "expr": "avg by(datacenter,cluster,node,svm)(ontaps3_svm_put_object_rate{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}) and topk($TopResources, avg by(datacenter,cluster,node,svm) (avg_over_time(ontaps3_svm_put_object_rate{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}[3h])))",
       "legendFormat": "{{node}} - {{svm}} - PUT"
      },
      {
       "expr": "avg by(datacenter,cluster,node,svm)(ontaps3_svm_head_object_rate{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}) and topk($TopResources, avg by(datacenter,cluster,node,svm) (avg_over_time(ontaps3_svm_head_object_rate{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}[3h])))",
       "legendFormat": "{{node}} - {{svm}} - HEAD"
      },
      {
       "expr": "avg by(datacenter,cluster,node,svm)(ontaps3_svm_delete_object_rate{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}) and topk($TopResources, avg by(datacenter,cluster,node,svm) (avg_over_time(ontaps3_svm_delete_object_rate{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}[3h])))",
       "legendFormat": "{{node}} - {{svm}} - DELETE"
      }
     ]
    },
    {
     "title": "Top $TopResources Object by Latency",
     "type": "timeseries",
     "description": "Average latency for GET/PUT/HEAD/DELETE object operations.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by(datacenter,cluster,node,svm)(ontaps3_svm_get_object_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}) and topk($TopResources, avg by(datacenter,cluster,node,svm) (avg_over_time(ontaps3_svm_get_object_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}[3h])))",
       "legendFormat": "{{node}} - {{svm}} - GET"
      },
      {
       "expr": "avg by(datacenter,cluster,node,svm)(ontaps3_svm_put_object_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}) and topk($TopResources, avg by(datacenter,cluster,node,svm) (avg_over_time(ontaps3_svm_put_object_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}[3h])))",
       "legendFormat": "{{node}} - {{svm}} - PUT"
      },
      {
       "expr": "avg by(datacenter,cluster,node,svm)(ontaps3_svm_head_object_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}) and topk($TopResources, avg by(datacenter,cluster,node,svm) (avg_over_time(ontaps3_svm_head_object_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}[3h])))",
       "legendFormat": "{{node}} - {{svm}} - HEAD"
      },
      {
       "expr": "avg by(datacenter,cluster,node,svm)(ontaps3_svm_delete_object_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}) and topk($TopResources, avg by(datacenter,cluster,node,svm) (avg_over_time(ontaps3_svm_delete_object_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}[3h])))",
       "legendFormat": "{{node}} - {{svm}} - DELETE"
      }
     ]
    },
    {
     "title": "Top $TopResources by Data Transfer",
     "type": "timeseries",
     "description": "Rate of GET/PUT object data transfers per second.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(datacenter,cluster,node,svm)(ontaps3_svm_get_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}) and topk($TopResources, avg by(datacenter,cluster,node,svm) (avg_over_time(ontaps3_svm_get_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}[3h])))",
       "legendFormat": "{{node}} - {{svm}} - GET"
      },
      {
       "expr": "avg by(datacenter,cluster,node,svm)(ontaps3_svm_put_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}) and topk($TopResources, avg by(datacenter,cluster,node,svm) (avg_over_time(ontaps3_svm_put_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",svm=~\"$SVM\"}[3h])))",
       "legendFormat": "{{node}} - {{svm}} - PUT"
      }
     ]
    }
   ]
  }
 ]
}