{
 "title": "ONTAP: SMB2",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(volume_labels{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(volume_labels{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(volume_labels{cluster=~\"$Cluster\"}, svm)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Important Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard requires the ZapiPerf collector. SMB2 is currently unavailable via REST. Refer https://github.com/NetApp/harvest/issues/1756"
   }
  },
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Read / Write IOPS",
   "type": "timeseries",
   "description": "This panel includes sum of read and write SMB OP’s /sec",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(smb2_read_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "read_ops - {{cluster}}"
    },
    {
     "expr": "sum(smb2_write_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "write_ops - {{cluster}}"
    }
   ]
  },
  {
   "title": "Read / Write Latency",
   "type": "timeseries",
   "description": "This panel includes average SMB read and write latency",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(smb2_read_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "Read - {{cluster}}"
    },
    {
     "expr": "avg(smb2_write_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "Write - {{cluster}}"
    }
   ]
  },
  {
   "title": "Other IOPS",
   "type": "timeseries",
   "description": "This panel includes SMB OP’s /sec average broken down by other SMB operations.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(smb2_negotiate_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "negotiate_ops - {{cluster}}"
    },
    {
     "expr": "sum(smb2_session_setup_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "session_setup_ops - {{cluster}}"
    },
    {
     "expr": "sum(smb2_tree_connect_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "tree_connect_ops - {{cluster}}"
    },
    {
     "expr": "sum(smb2_create_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "create_ops - {{cluster}}"
    },
    {
     "expr": "sum(smb2_close_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"})",
     "legendFormat": "close_ops - {{cluster}}"
    },
    {
     "expr": "sum(smb2_lock_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "lock_ops - {{cluster}}"
    },
    {
     "expr": "sum(smb2_query_directory_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "query_directory_ops - {{cluster}}"
    },
    {
     "expr": "sum(smb2_query_info_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "query_info_ops - {{cluster}}"
    },
    {
     "expr": "sum(smb2_set_info_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "set_info_ops - {{cluster}}"
    },
    {
     "expr": "sum(smb2_tree_connect_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "tree_connect_ops - {{cluster}}"
    },
    {
     "expr": "sum(smb2_oplock_break_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "oplock_break_ops - {{cluster}}"
    }
   ]
  },
  {
   "title": "Other Latency",
   "type": "timeseries",
   "description": "This panel includes SMB latency broken down by other SMB operations.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(smb2_negotiate_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "negotiate_latency - {{cluster}}"
    },
    {
     "expr": "avg(smb2_session_setup_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "session_setup_latency - {{cluster}}"
    },
    {
     "expr": "avg(smb2_tree_connect_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "tree_connect_latency - {{cluster}}"
    },
    {
     "expr": "avg(smb2_create_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "create_latency - {{cluster}}"
    },
    {
     "expr": "avg(smb2_close_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "close_latency - {{cluster}}"
    },
    {
     "expr": "avg(smb2_lock_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "lock_latency - {{cluster}}"
    },
    {
     "expr": "avg(smb2_query_directory_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "query_directory_latency - {{cluster}}"
    },
    {
     "expr": "avg(smb2_query_info_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "query_info_latency - {{cluster}}"
    },
    {
     "expr": "avg(smb2_set_info_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "set_info_latency - {{cluster}}"
    },
    {
     "expr": "avg(smb2_oplock_break_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}) by (cluster)",
     "legendFormat": "oplock_break_latency - {{cluster}}"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Session Setup Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for Session Setups and gives good indication of Client Authentication Latency Breakdown",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(increase(smb2_session_setup_latency_histogram_bucket{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Create Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for file opens and creates",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum(increase(smb2_create_latency_histogram_bucket{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Close Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for file closes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(increase(smb2_close_latency_histogram_bucket{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Lock Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for file locks",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "sum(increase(smb2_lock_latency_histogram_bucket{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Query Directory Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for readdir",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(increase(smb2_query_directory_latency_histogram_bucket{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Query Info Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for getattr",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "sum(increase(smb2_query_info_latency_histogram_bucket{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Set Info Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for setattr",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum(increase(smb2_set_info_latency_histogram_bucket{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Oplock Break Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for oplock breaks",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum(increase(smb2_oplock_break_latency_histogram_bucket{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  }
 ]
}