{
 "title": "ONTAP: SnapMirror Destination View",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "query_result(snapmirror_labels{system_type!=\"7mode\",datacenter=~\"$Datacenter\"})"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(snapmirror_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, destination_vserver)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(snapmirror_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",destination_vserver=~\"$SVM\"}, destination_volume)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   },
   {
    "name": "ConsistencyGroup",
    "query": {
     "query": "label_values(snapmirror_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\", destination_vserver=~\"$SVM\"}, source_cg_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Highlights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Volume relationship count by protection method",
   "type": "piechart",
   "description": "This panel displays volume relationship count based on the protection method.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count (count by (relationship_id) (snapmirror_labels{cluster=~\"$Cluster\",group_type=\"none\",relationship_id!=\"\"})) or vector(0)",
     "legendFormat": "Volume Protection"
    },
    {
     "expr": "count (count by (relationship_id) (snapmirror_labels{cluster=~\"$Cluster\",group_type=\"vserver\",relationship_id!=\"\"})) or vector(0)",
     "legendFormat": "SVM Protection (DR)"
    },
    {
     "expr": "count (count by (relationship_id) (snapmirror_labels{cluster=~\"$Cluster\",group_type=\"consistencygroup\",destination_cg_name=~\"$ConsistencyGroup\",relationship_id!=\"\"})) or vector(0)",
     "legendFormat": "Consistency Group"
    },
    {
     "expr": "count (count by (relationship_id) (snapmirror_labels{cluster=~\"$Cluster\",group_type=\"flexgroup\",relationship_id!=\"\"})) or vector(0)",
     "legendFormat": "FlexGroups"
    }
   ]
  },
  {
   "title": "Volume relationship count by relationship type",
   "type": "piechart",
   "description": "This panel displays volume relationship count based on the relationship type.",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",derived_relationship_type=\"extended_data_protection\",relationship_id!=\"\"}) or vector(0)",
     "legendFormat": "Asynchronous Mirror"
    },
    {
     "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",derived_relationship_type=\"mirror_vault\",relationship_id!=\"\"}) or vector(0)",
     "legendFormat": "Asynchronous Mirror and Vault"
    },
    {
     "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",derived_relationship_type=\"vault\",relationship_id!=\"\"}) or vector(0)",
     "legendFormat": "Asynchronous Vault"
    },
    {
     "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",derived_relationship_type=\"sync_mirror_strict\",relationship_id!=\"\"}) or vector(0)",
     "legendFormat": "StrictSync"
    },
    {
     "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",derived_relationship_type=\"sync_mirror\",relationship_id!=\"\"}) or vector(0)",
     "legendFormat": "Sync"
    },
    {
     "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",derived_relationship_type=\"automated_failover\",relationship_id!=\"\"}) or vector(0)",
     "legendFormat": "Automated Failover"
    },
    {
     "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",derived_relationship_type=\"automated_failover_duplex\",relationship_id!=\"\"}) or vector(0)",
     "legendFormat": "Automated Failover Duplex"
    }
   ]
  },
  {
   "title": "Volume relationship count by relationship health",
   "type": "piechart",
   "description": "This panel displays volume relationship count based on the relationship health.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",healthy=\"true\",relationship_id!=\"\"}) or vector (0)",
     "legendFormat": "Healthy"
    },
    {
     "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",healthy=\"false\",relationship_id!=\"\"}) or vector (0)",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Relationships Detail",
   "type": "table",
   "description": "This panel displays detail of all the snapmirror relationships from destination side of view.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "snapmirror_last_transfer_duration{cluster=~\"$Cluster\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",destination_location=~\".*$ConsistencyGroup\",relationship_id!=\"\"}"
    },
    {
     "expr": "snapmirror_last_transfer_size{cluster=~\"$Cluster\", destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",destination_location=~\".*$ConsistencyGroup\",relationship_id!=\"\"}"
    },
    {
     "expr": "snapmirror_lag_time{cluster=~\"$Cluster\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",destination_location=~\".*$ConsistencyGroup\",relationship_id!=\"\"}"
    },
    {
     "expr": "snapmirror_labels{cluster=~\"$Cluster\",destination_volume=~\"$Volume\",destination_location=~\".*$ConsistencyGroup\",derived_relationship_type!=\"load_sharing\",relationship_id!=\"\"} "
    }
   ]
  },
  {
   "title": "Top $TopResources Relationships by Transfer Duration",
   "type": "timeseries",
   "description": "This panel displays duration of the last SnapMirror transfer in seconds.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "snapmirror_last_transfer_duration{cluster=~\"$Cluster\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",destination_location=~\".*$ConsistencyGroup\"}\nand\ntopk($TopResources, avg_over_time(snapmirror_last_transfer_duration{cluster=~\"$Cluster\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",destination_location=~\".*$ConsistencyGroup\"}[3h] @ end()))",
     "legendFormat": "{{destination_volume}} - {{source_volume}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Relationships by Lag Time",
   "type": "timeseries",
   "description": "This panel displays amount of time since the last snapmirror transfer in seconds.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "snapmirror_lag_time{cluster=~\"$Cluster\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",destination_location=~\".*$ConsistencyGroup\"}\nand\ntopk($TopResources, avg_over_time(snapmirror_lag_time{cluster=~\"$Cluster\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",destination_location=~\".*$ConsistencyGroup\"}[3h] @ end()))",
     "legendFormat": "{{destination_volume}} - {{source_volume}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Relationships by Transfer Data",
   "type": "timeseries",
   "description": "This panel displays size in kilobytes (1024 bytes) of the last transfer.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "snapmirror_last_transfer_size{cluster=~\"$Cluster\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",destination_location=~\".*$ConsistencyGroup\"}\nand\ntopk($TopResources, avg_over_time(snapmirror_last_transfer_size{cluster=~\"$Cluster\",destination_volume=~\"$Volume\",destination_vserver=~\"$SVM\",destination_location=~\".*$ConsistencyGroup\"}[3h] @ end()))",
     "legendFormat": "{{destination_volume}} - {{source_volume}}"
    }
   ]
  },
  {
   "title": "Consistency Group Data Protection Analysis per Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Consistency Group relationship count by relationship type",
     "type": "piechart",
     "description": "This panel displays consistency group relationship count based on the relationship type.",
     "gridPos": { "h": 12, "w": 13, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",group_type=\"consistencygroup\",destination_cg_name=~\"$ConsistencyGroup\",derived_relationship_type=\"extended_data_protection\",relationship_id=\"\"}) or vector(0)",
       "legendFormat": "Asynchronous Mirror"
      },
      {
       "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",group_type=\"consistencygroup\",destination_cg_name=~\"$ConsistencyGroup\",derived_relationship_type=\"mirror_vault\",relationship_id=\"\"}) or vector(0)",
       "legendFormat": "Asynchronous Mirror and Vault"
      },
      {
       "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",group_type=\"consistencygroup\",destination_cg_name=~\"$ConsistencyGroup\",derived_relationship_type=\"vault\",relationship_id=\"\"}) or vector(0)",
       "legendFormat": "Asynchronous Vault"
      },
      {
       "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",group_type=\"consistencygroup\",destination_cg_name=~\"$ConsistencyGroup\",derived_relationship_type=\"sync_mirror_strict\",relationship_id=\"\"}) or vector(0)",
       "legendFormat": "StrictSync"
      },
      {
       "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",group_type=\"consistencygroup\",destination_cg_name=~\"$ConsistencyGroup\",derived_relationship_type=\"sync_mirror\",relationship_id=\"\"}) or vector(0)",
       "legendFormat": "Sync"
      },
      {
       "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",group_type=\"consistencygroup\",destination_cg_name=~\"$ConsistencyGroup\",derived_relationship_type=\"automated_failover\",relationship_id=\"\"}) or vector(0)",
       "legendFormat": "Automated Failover"
      },
      {
       "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",group_type=\"consistencygroup\",destination_cg_name=~\"$ConsistencyGroup\",derived_relationship_type=\"automated_failover_duplex\",relationship_id=\"\"}) or vector(0)",
       "legendFormat": "Automated Failover Duplex"
      }
     ]
    },
    {
     "title": "Consistency Group relationship count by relationship health",
     "type": "piechart",
     "description": "This panel displays consistency group relationship count based on the relationship health.",
     "gridPos": { "h": 12, "w": 11, "x": 13, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",group_type=\"consistencygroup\",healthy=\"true\",destination_cg_name=~\"$ConsistencyGroup\",relationship_id=\"\"}) or vector (0)",
       "legendFormat": "Healthy"
      },
      {
       "expr": "count(snapmirror_labels{cluster=~\"$Cluster\",group_type=\"consistencygroup\",healthy=\"false\",destination_cg_name=~\"$ConsistencyGroup\",relationship_id=\"\"}) or vector (0)",
       "legendFormat": "Unhealthy"
      }
     ]
    },
    {
     "title": "Consistency Group relationship count by Relationship type & Health",
     "type": "table",
     "description": "This panel displays detail of all Consistency Group relationships from destination side of view.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "snapmirror_labels{cluster=~\"$Cluster\",group_type=\"consistencygroup\",destination_cg_name=~\"$ConsistencyGroup\",relationship_id=\"\"}"
      }
     ]
    }
   ]
  }
 ]
}