{
 "title": "ONTAP: SnapMirror Sources",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "query_result(snapmirror_labels{system_type!=\"7mode\"} * on (source_volume, source_vserver, source_cluster) group_left() label_replace( label_replace( label_replace( volume_labels{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\"), \"source_cluster\", \"$1\", \"cluster\", \"(.*)\"))"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(snapmirror_labels{source_cluster=~\"$SourceCluster\"}, source_vserver)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(snapmirror_labels{source_cluster=~\"$SourceCluster\",source_vserver=~\"$SourceSVM\"}, source_volume)"
    }
   },
   {
    "name": "ConsistencyGroup",
    "query": {
     "query": "label_values(snapmirror_labels{source_cluster=~\"$SourceCluster\",source_vserver=~\"$SourceSVM\", destination_vserver=~\"$DestinationSVM\"}, source_cg_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information about SnapMirror Sources dashboard",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "To monitor both sides of a snapmirror relationship, both source and destination clusters must be monitored by Harvest. Both clusters need to export their metrics to the same Prometheus instance."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Highlights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Snapshot copies (local)",
   "type": "piechart",
   "description": "Volumes Protected With Snapmirror (Local And Remote).",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(volume_labels{datacenter=~\"$Datacenter\", cluster=~\"$Cluster\",type=\"rw\",snapshot_policy!=\"none\"}) or vector(0)",
     "legendFormat": "Protected"
    },
    {
     "expr": "count(volume_labels{cluster=~\"$Cluster\",type=\"rw\",snapshot_policy!=\"\",state!=\"\",snapshot_policy=\"none\"}) or vector(0)",
     "legendFormat": "Not Protected"
    }
   ]
  },
  {
   "title": "SnapMirror (local or remote)",
   "type": "piechart",
   "description": "Volumes Protected With Snapmirror (Local And Remote).",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(volume_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",type=\"rw\",state!=\"\",isProtected=\"false\"})",
     "legendFormat": "Unprotected"
    },
    {
     "expr": "count(volume_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",type=\"rw\",state!=\"\",isProtected=\"true\",isDestinationOntap=\"true\"})",
     "legendFormat": "Protected"
    }
   ]
  },
  {
   "title": "Back up to cloud",
   "type": "piechart",
   "description": "Volumes Protected With Snapmirror (Local And Remote).",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(volume_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})",
     "legendFormat": "Unprotected"
    },
    {
     "expr": "count(volume_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",state!=\"\",isProtected=\"true\",isDestinationCloud=\"true\"}) or vector(0)",
     "legendFormat": "Protected"
    }
   ]
  },
  {
   "title": "Relationships",
   "type": "table",
   "description": "This panel displays detail of all the snapmirror relationships from destination side of view.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "snapmirror_labels{source_cluster=~\"$Cluster\",source_volume=~\"$Volume\",source_vserver=~\"$SVM\",source_location=~\".*$ConsistencyGroup\",derived_relationship_type!=\"load_sharing\",relationship_id!=\"\"} "
    }
   ]
  }
 ]
}