{
 "title": "ONTAP: Time Till Full",
 "tags": [
  "harvest",
  "ontap",
  "cdot",
  "fsx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"},cluster)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information about Time Till Full dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard has two requirements:\n1. ONTAP 9.12+ with the REST APIs enabled and a REST collector configured for the cluster.\n2. VictoriaMetrics configured as your datasource. VM includes a [linear regression ttf](https://docs.victoriametrics.com/victoriametrics/metricsql/#ttf) function that is used to calculate time to full. NAbox 4.0+ uses VictoriaMetrics as the default datasource."
   }
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Time Till Full by Cluster",
     "type": "timeseries",
     "description": "Time till full of cluster space.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "targets": [
      {
       "expr": "bottomk_last($TopResources, ttf(cluster_space_available{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[1w]) > 0)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Time Till Full by Cluster",
     "type": "table",
     "description": "Time till full of cluster space.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "targets": [
      {
       "expr": "bottomk_last($TopResources, ttf(cluster_space_available{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[1w]) > 0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Time Till Full by Volume",
     "type": "timeseries",
     "description": "Time till full of volume space. Only volumes that are online are analyzed.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "targets": [
      {
       "expr": "bottomk_last($TopResources, ttf(volume_size_available{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[1w]) > 0)",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Time Till Full by Volume",
     "type": "table",
     "description": "Time till full of volume space. Only volumes that are online are analyzed.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "targets": [
      {
       "expr": "bottomk_last($TopResources, ttf(volume_size_available{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[1w]) > 0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Aggregate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Time Till Full by Aggregate",
     "type": "timeseries",
     "description": "Time till full of aggregate space.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "targets": [
      {
       "expr": "bottomk_last($TopResources, ttf(aggr_space_available{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[1w]) > 0)",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Time Till Full by Aggregate",
     "type": "table",
     "description": "Time till full of aggregate space.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "targets": [
      {
       "expr": "bottomk_last($TopResources, ttf(aggr_space_available{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[1w]) > 0)"
      }
     ]
    }
   ]
  }
 ]
}