{{- $enabled := true -}}
{{- if hasKey .Values.monitoring.scrape.podMonitor "enabled" -}}
{{- $enabled = .Values.monitoring.scrape.podMonitor.enabled -}}
{{- end -}}
{{- if $enabled -}}
{{- range $name, $poller := .Values.harvestConfig.Pollers }}
{{- $ctx := dict "root" $ "pollerName" $name "poller" $poller -}}
{{ include "harvest.poller.podmonitor" $ctx }}
---
{{- end }}
{{- end }}
