{
 "title": "ONTAP: Aggregate",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, netapp_cluster)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(aggr_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\"}, node)"
    }
   },
   {
    "name": "Aggregate",
    "query": {
     "query": "label_values(aggr_new_status{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\",node=~\"$Node\"}, aggr)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n\nThe panels **\"Aggregates by Logical Space Usage in Object Store\"** and **\"Aggregates by Physical Space Usage in Object Store\"** are available only through the REST Collector.\n          "
   }
  },
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Aggregates",
   "type": "stat",
   "description": "Number of aggregates.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count by (aggr) (\n    aggr_labels{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "stat",
   "description": "Number of disks in the aggregate.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  aggr_raid_disk_count{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n)"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "stat",
   "description": "The aggregate's volume count, which includes both FlexVols and FlexGroup constituents.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  aggr_volume_count{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n)"
    }
   ]
  },
  {
   "title": "Total Space",
   "type": "stat",
   "description": "Total usable space in bytes, not including WAFL reserve and aggregate Snapshot copy reserve.",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  aggr_space_total{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n)"
    }
   ]
  },
  {
   "title": "Used and Reserved Space",
   "type": "stat",
   "description": "Space used or reserved in bytes. Includes volume guarantees and aggregate metadata..",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_space_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Available Space",
   "type": "stat",
   "description": "Space available in bytes.",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  aggr_space_available{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n)"
    }
   ]
  },
  {
   "title": "Space Used %",
   "type": "stat",
   "description": "Percent of space used.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n  *\n    sum(aggr_space_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})\n/\n  sum(\n    aggr_space_total{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )"
    }
   ]
  },
  {
   "title": "Aggregates",
   "type": "table",
   "description": "Aggregate details.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "aggr_new_status{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    },
    {
     "expr": "aggr_volume_count{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    },
    {
     "expr": "aggr_raid_disk_count{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    },
    {
     "expr": "aggr_space_total{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    },
    {
     "expr": "aggr_space_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    },
    {
     "expr": "aggr_space_used_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    },
    {
     "expr": "aggr_labels{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    },
    {
     "expr": "aggr_space_available{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Total Space",
   "type": "timeseries",
   "description": "Total aggregate size. If aggregate is restricted or offline, a value of 0 is returned.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_space_total{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_space_total{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Physical Space Used",
   "type": "timeseries",
   "description": "Total physical used size of an aggregate.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_space_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_space_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by  Physical Space Used %",
   "type": "timeseries",
   "description": "Total physical used size percentage of an aggregate.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aggr_space_physical_used_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_space_physical_used_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Space Available",
   "type": "timeseries",
   "description": "Space available.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_space_available{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_space_available{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Inactive Data",
   "type": "timeseries",
   "description": "The amount of inactive data in an aggregate.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_space_performance_tier_inactive_user_data{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_space_performance_tier_inactive_user_data{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by  Inactive Data %",
   "type": "timeseries",
   "description": "Inactive data percentage of an aggregate.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aggr_space_performance_tier_inactive_user_data_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_space_performance_tier_inactive_user_data_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by logical space usage in Object Store",
   "type": "timeseries",
   "description": "Displays the logical space usage of aggregates in the attached object store.\n\n*Note:* This field is only supported for Rest Collector.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_object_store_logical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_object_store_logical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}} - {{tier}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by physical space usage in Object Store",
   "type": "timeseries",
   "description": "Displays the physical space usage of aggregates in the attached object store.\n\n*Note:* This field is only supported for Rest Collector.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_object_store_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_object_store_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}} - {{tier}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by  Capacity Tier Used",
   "type": "timeseries",
   "description": "Used space in bytes in the cloud store. Only applicable for aggregates with a cloud store tier.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_space_capacity_tier_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_space_capacity_tier_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Space Used by Snapshots",
   "type": "timeseries",
   "description": "This panel displays detail of space used by snapshot copies and available space for Snapshot copies in bytes.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_snapshot_size_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_snapshot_size_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}} - USED"
    },
    {
     "expr": "aggr_snapshot_size_available{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_snapshot_size_available{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}} - AVAILABLE"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by  SIS space saved",
   "type": "timeseries",
   "description": "Amount of space saved by storage efficiency.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_space_sis_saved{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_space_sis_saved{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by  Data Compaction space saved",
   "type": "timeseries",
   "description": "Space saved in bytes by compacting the data.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_space_data_compaction_saved{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_space_data_compaction_saved{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by  Inodes Used %",
   "type": "timeseries",
   "description": "The percentage of disk space currently in use based on user-visible file count on the referenced file system.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aggr_inode_used_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_inode_used_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by  Inodes Files",
   "type": "timeseries",
   "description": "This panel displays detail of Number of user-visible files used in the referenced file system and Maximum number of user-visible files that this referenced file system can currently hold.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aggr_inode_files_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_inode_files_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}} - USED"
    },
    {
     "expr": "aggr_inode_files_total{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_inode_files_total{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}} - TOTAL"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by  Inode Capacity",
   "type": "timeseries",
   "description": "This panel displays detail of number of files that can currently be stored on disk for system metadata files and number of files that can currently be stored on disk for user-visible files.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aggr_inode_inodefile_private_capacity{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_inode_inodefile_private_capacity{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}} - PRIVATE"
    },
    {
     "expr": "aggr_inode_inodefile_public_capacity{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_inode_inodefile_public_capacity{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}} - PUBLIC"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Snapshot Inodes Used %",
   "type": "timeseries",
   "description": "The percentage of disk space currently in use based on user-visible file (inode) count on the referenced file system.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aggr_snapshot_inode_used_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_snapshot_inode_used_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by  Space Used by Snapshots %",
   "type": "timeseries",
   "description": "Percentage of disk space used by Snapshot copies.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aggr_snapshot_used_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_snapshot_used_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by  Space Used by Snapshots %",
   "type": "timeseries",
   "description": "Percentage of disk space used by Snapshot copies.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aggr_snapshot_used_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_snapshot_used_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Snapshot Files",
   "type": "timeseries",
   "description": "This panel displays detail of total files allowed in snapshot copies and total files created in snapshot copies.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aggr_snapshot_files_total{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_snapshot_files_total{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}} - TOTAL"
    },
    {
     "expr": "aggr_snapshot_files_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_snapshot_files_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}} - USED"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Snapshot MaxFiles",
   "type": "timeseries",
   "description": "This panel displays detail of files in use by snapshot copies, the largest value to which the maxfiles-available parameter can be increased by reconfiguration, on the referenced file system and maximum files available for snapshot copies.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aggr_snapshot_maxfiles_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_snapshot_maxfiles_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}} - USED"
    },
    {
     "expr": "aggr_snapshot_maxfiles_possible{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_snapshot_maxfiles_possible{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}} - POSSIBLE"
    },
    {
     "expr": "aggr_snapshot_maxfiles_available{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_snapshot_maxfiles_available{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}} - AVAILABLE"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Space Reserved for Snapshots %",
   "type": "timeseries",
   "description": "Percentage of space reserved for Snapshot copies.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aggr_snapshot_reserve_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_snapshot_reserve_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Storage Efficiency Ratios",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Reduction",
     "type": "stat",
     "description": "Storage efficiency ratio without snapshots and flexclones.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n    aggr_logical_used_wo_snapshots_flexclones{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n  )\n/\n  sum(\n    aggr_physical_used_wo_snapshots_flexclones{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n  )"
      }
     ]
    },
    {
     "title": "Data Reduction with FlexClones",
     "type": "stat",
     "description": "Storage efficiency ratio with flexclones.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n    aggr_logical_used_wo_snapshots{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n  )\n/\n  sum(\n    aggr_physical_used_wo_snapshots{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n  )"
      }
     ]
    },
    {
     "title": "Data Reduction with Snapshots & FlexClones",
     "type": "stat",
     "description": "Storage efficiency ratio of total space used.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aggr_total_logical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n/\n  sum(aggr_total_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
      }
     ]
    },
    {
     "title": "Top $TopResources Aggregates by Logical Used",
     "type": "timeseries",
     "description": "Logical used.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aggr_logical_used_wo_snapshots_flexclones{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_logical_used_wo_snapshots_flexclones{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Aggregates by Physical Used",
     "type": "timeseries",
     "description": "Total data deduction physical used without snapshots and Flexclones.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aggr_physical_used_wo_snapshots_flexclones{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_physical_used_wo_snapshots_flexclones{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Aggregates by Logical Used with FlexClones",
     "type": "timeseries",
     "description": "Logical used with flexclones.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aggr_logical_used_wo_snapshots{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_logical_used_wo_snapshots{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Aggregates by Physical Used with FlexClones",
     "type": "timeseries",
     "description": "Total Data Reduction Physical Used with FlexClones.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aggr_physical_used_wo_snapshots{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_physical_used_wo_snapshots{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Aggregates by Logical Used with Snapshots & FlexClones",
     "type": "timeseries",
     "description": "Logical Used with Snapshots & flexClones.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aggr_total_logical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_total_logical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Aggregates by Physical Used with Snapshots & FlexClones",
     "type": "timeseries",
     "description": "Physical Used with Snapshots & FlexClones.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aggr_space_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_space_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Average Disk Utilization Per Aggregate",
     "type": "table",
     "description": "Disk Utilization per Aggregate for latest record (independent of time range selected).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (node, aggr) (\n    aggr_disk_busy{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (node, aggr) (\n      avg_over_time(\n        aggr_disk_busy{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )"
      }
     ]
    },
    {
     "title": "Top $TopResources Average Disk Utilization Per Aggregate",
     "type": "timeseries",
     "description": "Disk Utilization per Aggregate in the selected time range.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (node, aggr) (\n    aggr_disk_busy{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (node, aggr) (\n      avg_over_time(\n        aggr_disk_busy{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flash Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Aggregates by Flash Pool Activity",
     "type": "timeseries",
     "description": "This panel displays detail of percentage of HDD read operations replace by SSD and number of HDD read operations replaced by SSD reads per second.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "flashpool_read_ops_replaced_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flashpool_read_ops_replaced_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "SSD Hit (%) - {{aggr}}"
      },
      {
       "expr": "flashpool_read_ops_replaced{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flashpool_read_ops_replaced{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "HDD Reads Replaced - {{aggr}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Aggregates by SSD and HDD Latency",
     "type": "timeseries",
     "description": "This panel displays detail of average of RAID I/O latency on read hit and average read miss latency.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "flashpool_hya_read_hit_latency_average{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flashpool_hya_read_hit_latency_average{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "Avg Hit Latency (SSD) - {{aggr}}"
      },
      {
       "expr": "flashpool_hya_read_miss_latency_average{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flashpool_hya_read_miss_latency_average{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "Avg Miss Latency (HDD) - {{aggr}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Aggregates by Flash Pool Capacity Used",
     "type": "timeseries",
     "description": "This panel displays detail of total read/write/total cached SSD blocks.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "4\n  *\n    flashpool_ssd_read_cached{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flashpool_ssd_read_cached{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "Read Cached (GB) - {{aggr}}"
      },
      {
       "expr": "4\n  *\n    flashpool_ssd_write_cached{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flashpool_ssd_write_cached{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "Write Cached (GB) - {{aggr}}"
      },
      {
       "expr": "4\n  *\n    flashpool_ssd_total{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flashpool_ssd_total{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "Total Capacity (GB) - {{aggr}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Aggregates by Cache Inserts",
     "type": "timeseries",
     "description": "Number of read-cache/write-cache blocks per second.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "flashpool_read_cache_ins_rate{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flashpool_read_cache_ins_rate{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "Read Cache Insert Rate - {{aggr}}"
      },
      {
       "expr": "flashpool_wc_write_blks_total{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flashpool_wc_write_blks_total{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "Write Cache Insert Rate - {{aggr}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Aggregates by Cache Removals",
     "type": "timeseries",
     "description": "Number of block destage/free per second.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "flashpool_evict_destage_rate{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flashpool_evict_destage_rate{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "Blocks Destaged - {{aggr}}"
      },
      {
       "expr": "flashpool_evict_remove_rate{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      flashpool_evict_remove_rate{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "Blocks Evicted - {{aggr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FabricPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Aggregates by Performance Tier Footprint",
     "type": "timeseries",
     "description": "A summation of volume footprints (including volume guarantees), in bytes. This includes all of the volume footprints in the block_storage tier and the cloud_storage tier.This is an advanced property; there is an added computational cost to retrieving its value. The field is not populated for either a collection GET or an instance GET unless it is explicitly requested using the <i>fields</i> query parameter containing either footprint or **.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aggr_space_performance_tier_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_space_performance_tier_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Aggregates by Performance Tier Footprint %",
     "type": "timeseries",
     "description": "Volume footprints percent.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aggr_space_performance_tier_used_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_space_performance_tier_used_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Aggregates by Capacity Tier Footprint",
     "type": "timeseries",
     "description": "Used space in bytes in the cloud store. Only applicable for aggregates with a cloud store tier.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aggr_space_capacity_tier_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      aggr_space_capacity_tier_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{aggr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Volumes by Space Used by Aggregate",
     "type": "timeseries",
     "description": "Flexgroup by-aggregate filtering does not display the per-aggregate breakdown, instead the sum of all flexgroup aggregates is displayed. This is how ONTAP reports the data, even when an aggregate is selected in the dropdown.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_size_used{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_size_used{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} - {{style}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Space Used %",
     "type": "timeseries",
     "description": "Flexgroup by-aggregate filtering does not display the per-aggregate breakdown, instead the sum of all flexgroup aggregates is displayed. This is how ONTAP reports the data, even when an aggregate is selected in the dropdown.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_size_used_percent{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_size_used_percent{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} - {{style}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Snapshot Space Used",
     "type": "timeseries",
     "description": "Flexgroup by-aggregate filtering does not display the per-aggregate breakdown, instead the sum of all flexgroup aggregates is displayed. This is how ONTAP reports the data, even when an aggregate is selected in the dropdown.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_snapshots_size_used{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_snapshots_size_used{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} - {{style}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Snapshot Space Used %",
     "type": "timeseries",
     "description": "Flexgroup by-aggregate filtering does not display the per-aggregate breakdown, instead the sum of all flexgroup aggregates is displayed. This is how ONTAP reports the data, even when an aggregate is selected in the dropdown.\n\nNote that in some scenarios, it is possible to exceed 100% of the space allocated.\n.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_snapshot_reserve_used_percent{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_snapshot_reserve_used_percent{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} - {{style}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Performance Tier Footprint",
     "type": "timeseries",
     "description": "Footprint of blocks written to the volume in bytes for the performance tier (bin 0).",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_performance_tier_footprint{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_performance_tier_footprint{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} - {{style}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Performance Tier Footprint %",
     "type": "timeseries",
     "description": "Footprint of blocks written to the volume in performance tier (bin 0) as a percentage of aggregate size.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_performance_tier_footprint_percent{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_performance_tier_footprint_percent{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} - {{style}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Capacity Tier Footprint",
     "type": "timeseries",
     "description": "Footprint of blocks written to the volume in bytes for capacity tier (bin 1).",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_capacity_tier_footprint{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_capacity_tier_footprint{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} - {{style}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Capacity Tier Footprint %",
     "type": "timeseries",
     "description": "Footprint of blocks written to the volume in capacity tier (bin 1) as a percentage of aggregate size.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_capacity_tier_footprint_percent{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_capacity_tier_footprint_percent{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} - {{style}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Volumes by Average Latency",
     "type": "timeseries",
     "description": "Average latency in microseconds for the WAFL filesystem to process all the operations on the volume; not including request processing or network communication time.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "volume_avg_latency{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_avg_latency{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} - {{style}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Average Throughput",
     "type": "timeseries",
     "description": "Volume total throughput.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(\n      volume_read_data{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n    +\n      volume_write_data{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_read_data{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n        )\n      +\n        avg_over_time(\n          volume_write_data{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n        )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by IOPs",
     "type": "timeseries",
     "description": "Number of operations per second serviced by the volume.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "volume_total_ops{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_total_ops{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Read Latency",
     "type": "timeseries",
     "description": "Average latency in microseconds for the WAFL filesystem to process read request to the volume; not including request processing or network communication time.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "volume_read_latency{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_read_latency{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} - {{style}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Read Throughput",
     "type": "timeseries",
     "description": "Bytes read per second.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "volume_read_data{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_read_data{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} - {{style}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Read IOPs",
     "type": "timeseries",
     "description": "Number of read operations per second from the volume.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "volume_read_ops{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_read_ops{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} - {{style}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write Latency",
     "type": "timeseries",
     "description": "Average latency in microseconds for the WAFL filesystem to process write request to the volume; not including request processing or network communication time.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "volume_write_latency{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_write_latency{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} - {{style}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write Throughput",
     "type": "timeseries",
     "description": "Bytes written per second.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "volume_write_data{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_write_data{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} - {{style}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write IOPs",
     "type": "timeseries",
     "description": "Number of write operations per second to the volume.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "volume_write_ops{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_write_ops{aggr=~\".*$Aggregate.*\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} - {{style}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Growth Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Aggregates Per Growth Rate of Physical Used",
     "type": "timeseries",
     "description": "Physical space used growth rate per second in the aggregate.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "deriv(\n    aggr_total_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[4m]\n  )\nand\n  topk(\n    $TopResources,\n    (\n      avg_over_time(\n        aggr_total_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Aggregates Per Growth Rate of Logical Used",
     "type": "timeseries",
     "description": "Logical space used growth rate per second in the aggregate.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "deriv(\n    aggr_total_logical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[4m]\n  )\nand\n  topk(\n    $TopResources,\n    (\n      avg_over_time(\n        aggr_total_logical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Aggregates by Physical Usage: Delta Report",
     "type": "table",
     "description": "This panel tracks changes in the physical usage space of the top $TopResources aggregates by physical space. It includes the following delta columns:\n\n- **1-Day Delta:** This column shows the change in physical usage space over the past 24 hours. \n  \n- **7-Day Delta:** This column displays the change in physical usage space over the past 7 days.\n  \n- **Time Range Delta:** This column reflects the change in physical usage space over the selected time range in the Grafana dashboard.\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "label_join(\n    delta(\n      aggr_total_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[1d]\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"netapp_cluster\",\n    \"aggr\"\n  )\nand on (datacenter, netapp_cluster, aggr)\n  topk(\n    $TopResources,\n    (\n      avg_over_time(\n        aggr_total_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )"
      },
      {
       "expr": "label_join(\n    delta(\n      aggr_total_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[1w]\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"netapp_cluster\",\n    \"aggr\"\n  )\nand on (datacenter, netapp_cluster, aggr)\n  topk(\n    $TopResources,\n    (\n      avg_over_time(\n        aggr_total_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )"
      },
      {
       "expr": "label_join(\n    delta(\n      aggr_total_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[$__range]\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"netapp_cluster\",\n    \"aggr\"\n  )\nand on (datacenter, netapp_cluster, aggr)\n  topk(\n    $TopResources,\n    (\n      avg_over_time(\n        aggr_total_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )"
      }
     ]
    },
    {
     "title": "Top $TopResources Aggregates by Logical Usage: Delta Report",
     "type": "table",
     "description": "This panel tracks changes in the logical usage space of the top $TopResources aggregates by physical space. It includes the following delta columns:\n\n- **1-Day Delta:** This column shows the change in logical usage space over the past 24 hours. \n  \n- **7-Day Delta:** This column displays the change in logical usage space over the past 7 days.\n  \n- **Time Range Delta:** This column reflects the change in logical usage space over the selected time range in the Grafana dashboard.\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "label_join(\n    delta(\n      aggr_total_logical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[1d]\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"netapp_cluster\",\n    \"aggr\"\n  )\nand on (datacenter, netapp_cluster, aggr)\n  topk(\n    $TopResources,\n    (\n      avg_over_time(\n        aggr_total_logical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )"
      },
      {
       "expr": "label_join(\n    delta(\n      aggr_total_logical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[1w]\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"netapp_cluster\",\n    \"aggr\"\n  )\nand on (datacenter, netapp_cluster, aggr)\n  topk(\n    $TopResources,\n    (\n      avg_over_time(\n        aggr_total_logical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )"
      },
      {
       "expr": "label_join(\n    delta(\n      aggr_total_logical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[$__range]\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"netapp_cluster\",\n    \"aggr\"\n  )\nand on (datacenter, netapp_cluster, aggr)\n  topk(\n    $TopResources,\n    (\n      avg_over_time(\n        aggr_total_logical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )"
      }
     ]
    }
   ]
  }
 ]
}