{
 "title": "ONTAP: AuditLog",
 "description": "The ONTAP Changelog Monitor, tracks configuration modifications in volumes, SVMs, and nodes, is deactivated by default. To leverage this feature, one must enable the ChangeLog plugin within the Volume, SVM, and Node Templates.",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"},netapp_cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Important Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<br>\n\nThis dashboard captures operations (create, update, delete) attempted on volumes via REST or ONTAP CLI commands. To use this dashboard, enable the AuditLog template. For more details, visit the [AuditLog documentation](https://github.com/NetApp/harvest/discussions/3478).\n"
   }
  },
  { "title": "Volume Audit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Create",
   "type": "stat",
   "description": "This change type indicates that Volume has been created.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (netapp_cluster, datacenter, object) (\n    changes(\n      audit_log{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"volume\",op=\"create\"}[$__range]\n    )\n  +\n    1\n)"
    }
   ]
  },
  {
   "title": "Update",
   "type": "stat",
   "description": "This change type indicates that Volume object has been updated.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (netapp_cluster, datacenter, object) (\n    changes(\n      audit_log{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"volume\",op=\"update\"}[$__range]\n    )\n  +\n    1\n)"
    }
   ]
  },
  {
   "title": "Delete",
   "type": "stat",
   "description": "This change type indicates that Volume has been deleted.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (netapp_cluster, datacenter, object) (\n    changes(\n      audit_log{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"volume\",op=\"delete\"}[$__range]\n    )\n  +\n    1\n)"
    }
   ]
  },
  {
   "title": "Volume Changes",
   "type": "table",
   "description": "`Cluster Time:` The time on the cluster.\n\n`Object:` The name of the ONTAP object that was changed.\n\n`OP:` The type of change that was made (e.g., create, update, delete).\n\n`User`: The user who performed this action.\n\n`Location`: The IP address of the user.\n\n `Application`: The application used to perform the action. Possible values are `http` and `ssh`.\n\n`Count`: Number of times operation is performed.\n\n**Note:** Only REST and ONTAP CLI commands are included in the audit. ZAPI commands are not supported.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "label_join(\n  last_over_time(\n    audit_log{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"volume\"}[$__range]\n  ),\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"netapp_cluster\",\n  \"object\",\n  \"volume\",\n  \"uuid\",\n  \"op\",\n  \"application\",\n  \"location\",\n  \"user\"\n)"
    },
    {
     "expr": "label_join(\n  sum by (netapp_cluster, datacenter, object, volume, uuid, op, application, location, user) (\n    changes(audit_log{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"volume\"}[$__range]) + 1\n  ),\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"netapp_cluster\",\n  \"object\",\n  \"volume\",\n  \"uuid\",\n  \"op\",\n  \"application\",\n  \"location\",\n  \"user\"\n)"
    }
   ]
  }
 ]
}