{
 "title": "ONTAP: Data Protection",
 "tags": [
  "harvest",
  "ontap",
  "cdot",
  "fsx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"},netapp_cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Snapshot copies (local)",
   "type": "piechart",
   "description": "This panel displays volume protection by Snapshot copies.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",state!=\"\",type=\"rw\"}) or vector(1)",
     "legendFormat": "Total"
    },
    {
     "expr": "count(\n    volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy=~\"none.*\",state!=\"\",type=\"rw\",volume!~\"MDV.*\"}\n  )\nor on ()\n  vector(0)",
     "legendFormat": "Not Protected"
    }
   ]
  },
  {
   "title": "SnapMirrors (local or remote)",
   "type": "piechart",
   "description": "This panel displays volume protection by SnapMirror relationship.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",state!=\"\",type=\"rw\"}) or vector(1)",
     "legendFormat": "Total"
    },
    {
     "expr": "count(\n    volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isDestinationOntap=\"true\",isProtected=\"true\",state!=\"\",svm_root=\"false\",type=\"rw\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Protected"
    }
   ]
  },
  {
   "title": "Back up to cloud",
   "type": "piechart",
   "description": "This panel displays volume protection by backed up to cloud bucket.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",state!=\"\"}) or vector(1)",
     "legendFormat": "Total"
    },
    {
     "expr": "count(\n    volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isDestinationCloud=\"true\",isProtected=\"true\",state!=\"\",svm_root=\"false\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Protected"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "table",
   "description": "This panel displays volume protection detail via Snapshot, SnapMirror or Bucket.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
    }
   ]
  },
  {
   "title": "Bucket protection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Buckets",
     "type": "stat",
     "description": "Number of total buckets.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ontaps3_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
      }
     ]
    },
    {
     "title": "Unprotected Buckets",
     "type": "stat",
     "description": "Number of buckets which are not protected.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ontaps3_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_protected=\"false\"})"
      }
     ]
    },
    {
     "title": "Not Backed up to Cloud",
     "type": "stat",
     "description": "Number of buckets which are not backed up to cloud.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ontaps3_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",protected_in_cloud=\"false\"})"
      }
     ]
    },
    {
     "title": "Buckets",
     "type": "table",
     "description": "This panel displays bucket detail.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ontaps3_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      },
      {
       "expr": "ontaps3_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      },
      {
       "expr": "ontaps3_logical_used_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Snapshot Copies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumes not protected",
     "type": "stat",
     "description": "Total number of volumes that are not protected.",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n    (\n        volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy=~\"none.*\",volume!~\"MDV.*\"}\n      * on (snapshot_policy) group_left ()\n        group by (snapshot_policy) (snapshot_policy_labels)\n    )\n  )\nor on ()\n  vector(0)"
      }
     ]
    },
    {
     "title": "Volumes protected",
     "type": "stat",
     "description": "Total number of volumes that are protected.",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n      volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\",volume!~\"MDV.*\"}\n    * on (snapshot_policy) group_left ()\n      group by (snapshot_policy) (snapshot_policy_labels)\n  )\nor on ()\n  vector(0)"
      }
     ]
    },
    {
     "title": "Volumes breached",
     "type": "stat",
     "description": "Total number of volumes whose snapshot size used is breached the snapshot reserve size.",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n        volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\"}\n      * on (snapshot_policy) group_left ()\n        group by (snapshot_policy) (snapshot_policy_labels)\n    * on (volume, svm, netapp_cluster) group_right ()\n      (\n            volume_snapshot_reserve_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} >= 0\n          and\n            volume_snapshots_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} >= 0\n        and\n            volume_snapshots_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n          >\n            volume_snapshot_reserve_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n      )\n  )\nor on ()\n  vector(0)"
      }
     ]
    },
    {
     "title": "Volumes not breached",
     "type": "stat",
     "description": "Total number of volumes whose snapshot size used is not breached the snapshot reserve size.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n      count(\n          (\n              volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\"}\n            * on (snapshot_policy) group_left ()\n              group by (snapshot_policy) (snapshot_policy_labels)\n          )\n        * on (volume, svm, netapp_cluster) group_right ()\n          (\n                volume_snapshot_reserve_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} > 0\n              and\n                volume_snapshots_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} > 0\n            and\n                volume_snapshots_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n              <=\n                volume_snapshot_reserve_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n          )\n      )\n    or on ()\n      vector(0)\n  )\n+\n  (\n      count(\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\"}\n          * on (snapshot_policy) group_left ()\n            group by (snapshot_policy) (snapshot_policy_labels)\n        * on (volume, svm, netapp_cluster) group_right ()\n          (\n              volume_snapshot_reserve_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} >= 0\n            and\n              volume_snapshots_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 0\n          )\n      )\n    or on ()\n      vector(0)\n  )"
      }
     ]
    },
    {
     "title": "Volumes Protected With Snapshot Copies (local)",
     "type": "table",
     "description": "This panel displays volumes detail with protected status and snapshot policy.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "label_replace(\n    label_replace(\n      volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",volume!~\"MDV.*\"},\n      \"Status\",\n      \"Protected\",\n      \"snapshot_policy\",\n      \"(.*)\"\n    ),\n    \"Status\",\n    \"Unprotected\",\n    \"snapshot_policy\",\n    \"(none.*)\"\n  )\n* on (snapshot_policy) group_left ()\n  group by (snapshot_policy) (snapshot_policy_labels)"
      }
     ]
    },
    {
     "title": "Volumes Breaching Snapshot Copy Reserve Space",
     "type": "table",
     "description": "Volumes details of snapshot copy reserve space.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\"}\n  * on (snapshot_policy) group_left ()\n    group by (snapshot_policy) (snapshot_policy_labels)\n* on (volume, svm, netapp_cluster) group_right ()\n  (\n      volume_snapshot_reserve_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} >= 0\n    and\n      volume_snapshots_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} >= 0\n  )"
      },
      {
       "expr": "volume_snapshots_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      }
     ]
    },
    {
     "title": " <10 Copies ",
     "type": "stat",
     "description": "Total number of volumes whose snapshot count is < 10.",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n      (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\",volume!~\"MDV.*\"}\n        * on (snapshot_policy) group_left ()\n          group by (snapshot_policy) (snapshot_policy_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n      )\n    * on (volume, svm, netapp_cluster)\n      (\n          volume_snapshot_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} > 0\n        and\n          volume_snapshot_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} < 10\n      )\n  )\nor on ()\n  vector(0)"
      }
     ]
    },
    {
     "title": "10-100 Copies",
     "type": "stat",
     "description": "Total number of volumes whose snapshot count is between 10 to 100.",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n      (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\",volume!~\"MDV.*\"}\n        * on (snapshot_policy) group_left ()\n          group by (snapshot_policy) (snapshot_policy_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n      )\n    * on (volume, svm, netapp_cluster)\n      (\n          volume_snapshot_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} >= 10\n        and\n          volume_snapshot_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} <= 100\n      )\n  )\nor on ()\n  vector(0)"
      }
     ]
    },
    {
     "title": "101-500 Copies",
     "type": "stat",
     "description": "Total number of volumes whose snapshot count is between 101 to 500.",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n      (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\",volume!~\"MDV.*\"}\n        * on (snapshot_policy) group_left ()\n          group by (snapshot_policy) (snapshot_policy_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n      )\n    * on (volume, svm, netapp_cluster)\n      (\n          volume_snapshot_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} > 100\n        and\n          volume_snapshot_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} <= 500\n      )\n  )\nor on ()\n  vector(0)"
      }
     ]
    },
    {
     "title": ">500 Copies",
     "type": "stat",
     "description": "Total number of volumes whose snapshot count is > 500.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n      (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\",volume!~\"MDV.*\"}\n        * on (snapshot_policy) group_left ()\n          group by (snapshot_policy) (snapshot_policy_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n      )\n    * on (volume, svm, netapp_cluster)\n      (volume_snapshot_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} > 500)\n  )\nor on ()\n  vector(0)"
      }
     ]
    },
    {
     "title": "Volume count by the number of Snapshot copies",
     "type": "table",
     "description": "This panel displays volumes detail with snapshot count.",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "(\n      volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\",volume!~\"MDV.*\"}\n    * on (snapshot_policy) group_left ()\n      group by (snapshot_policy) (snapshot_policy_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n  )\n* on (volume, svm, netapp_cluster)\n  (volume_snapshot_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} > 0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Local Policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Protection policies",
     "type": "table",
     "description": "This panel displays protection policy detail.",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "snapmirror_policy_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      }
     ]
    },
    {
     "title": "Snapshot policies",
     "type": "table",
     "description": "This panel displays Snapshot policy detail.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "snapshot_policy_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      }
     ]
    },
    {
     "title": "Schedules",
     "type": "table",
     "description": "This panel displays cluster schedules detail.",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "netapp_cluster_schedule_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  }
 ]
}