{
 "title": "ONTAP: Datacenter",
 "tags": [
  "harvest",
  "ontap",
  "cdot",
  "fsx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"},netapp_cluster)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   },
   {
    "name": "CPU_BUSY",
    "query": "System CPU resource utilization is a computed percentage that indicates how busy the system is based on a combination of the most heavily utilized domain and idle CPU cycles. This metric determines the amount of available CPU and will vary based on domains reaching their limits OR exhausting all idle CPU cycles, whichever comes first."
   }
  ]
 },
 "panels": [
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Space",
   "type": "stat",
   "description": "Total usable space in bytes, not including WAFL reserve and aggregate Snapshot copy reserve.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_space_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
    }
   ]
  },
  {
   "title": "Space Used %",
   "type": "stat",
   "description": "Percent of space used.",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(aggr_space_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n/\n  sum(aggr_space_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
    }
   ]
  },
  {
   "title": "Object Count",
   "type": "table",
   "description": "Object Count.\n\nNote: The REST and ZAPI collectors return a different number of volumes depending on whether you have set up object store servers on your cluster. \n\nFor more details, visit the [ZAPI and REST Gaps](https://netapp.github.io/harvest/latest/zapi-and-rest-gap.md).",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(count by (netapp_cluster) (node_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))",
     "legendFormat": "Nodes"
    },
    {
     "expr": "sum(count by (netapp_cluster) (svm_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))",
     "legendFormat": "SVMs"
    },
    {
     "expr": "sum(count by (netapp_cluster) (aggr_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))",
     "legendFormat": "Aggregates"
    },
    {
     "expr": "sum(count by (netapp_cluster) (lun_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))",
     "legendFormat": "Luns"
    },
    {
     "expr": "sum(count by (netapp_cluster) (volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))",
     "legendFormat": "Volumes"
    },
    {
     "expr": "sum(count by (netapp_cluster) (namespace_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "sum(count by (netapp_cluster) (ontaps3_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))",
     "legendFormat": "S3 Buckets"
    },
    {
     "expr": "sum(count by (netapp_cluster) (disk_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))",
     "legendFormat": "Disks"
    },
    {
     "expr": "sum(count by (netapp_cluster) (snapmirror_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))",
     "legendFormat": "Snapmirrrors"
    },
    {
     "expr": "sum(count by (netapp_cluster) (lif_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))",
     "legendFormat": "LIFs"
    },
    {
     "expr": "sum(count by (netapp_cluster) (fcp_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))",
     "legendFormat": "FC Ports"
    },
    {
     "expr": "sum(count by (netapp_cluster) (qtree_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))",
     "legendFormat": "Qtree"
    },
    {
     "expr": "sum(count by (netapp_cluster) (quota_disk_limit{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))",
     "legendFormat": "Quotas"
    },
    {
     "expr": "sum(count by (netapp_cluster) (qos_workload_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))",
     "legendFormat": "Workloads"
    },
    {
     "expr": "sum(count by (netapp_cluster) (shelf_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))",
     "legendFormat": "Shelves"
    }
   ]
  },
  {
   "title": "Available Space",
   "type": "stat",
   "description": "Available space.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_space_available{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
    }
   ]
  },
  {
   "title": "Used and Reserved Space",
   "type": "stat",
   "description": "Space used or reserved in bytes. Includes volume guarantees and aggregate metadata.",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_space_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
    }
   ]
  },
  {
   "title": "Top $TopResources Total Space by Cluster",
   "type": "timeseries",
   "description": "Total usable space in bytes, not including WAFL reserve and aggregate Snapshot copy reserve.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (netapp_cluster) (aggr_space_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\nand\n  topk(\n    $TopResources,\n    sum by (netapp_cluster) (\n      avg_over_time(aggr_space_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
     "legendFormat": "{{netapp_cluster}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Used and Reserved Space by Cluster",
   "type": "timeseries",
   "description": "Space used or reserved in bytes. Includes volume guarantees and aggregate metadata.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (netapp_cluster) (aggr_space_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\nand\n  topk(\n    $TopResources,\n    sum by (netapp_cluster) (\n      avg_over_time(aggr_space_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
     "legendFormat": "{{netapp_cluster}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Available Space by Cluster",
   "type": "timeseries",
   "description": "Available space.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (netapp_cluster) (aggr_space_available{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\nand\n  topk(\n    $TopResources,\n    sum by (netapp_cluster) (\n      avg_over_time(aggr_space_available{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
     "legendFormat": "{{netapp_cluster}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Space Used % by Cluster",
   "type": "timeseries",
   "description": "Percent of space used.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n      100 * sum by (datacenter, netapp_cluster) (aggr_space_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n    / on (datacenter, netapp_cluster)\n      sum by (datacenter, netapp_cluster) (aggr_space_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n  )\nand on (datacenter, netapp_cluster)\n  topk(\n    $TopResources,\n    (\n          100\n        *\n          sum by (datacenter, netapp_cluster) (\n            avg_over_time(aggr_space_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end())\n          )\n      / on (datacenter, netapp_cluster)\n        sum by (datacenter, netapp_cluster) (\n          avg_over_time(aggr_space_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end())\n        )\n    )\n  )",
     "legendFormat": "{{netapp_cluster}}"
    }
   ]
  },
  {
   "title": "Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Health",
     "type": "table",
     "description": "Cluster Health Details.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "cluster_new_status{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      }
     ]
    },
    {
     "title": "Node Health",
     "type": "table",
     "description": "Node details.",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      },
      {
       "expr": "node_new_status{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Issues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 39 },
     "options": {
      "content": "<br>These panels require ONTAP 9.6+ and the REST collector. Two actions are required to use this dashboard: <br>1. Enable the REST collector in your harvest.yml config<br>2. Enable the EMS collector in your harvest.yml config for EMS events<br>\nFor more information on the issues, please check the `ONTAP: Health` dashboard."
     }
    },
    {
     "title": "Errors",
     "type": "piechart",
     "description": "This panel displays error detail of disk, shelf, node, network port, license compliance, HA down and sensor failure alerts.",
     "gridPos": { "h": 16, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(health_disk_alerts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1)\nor\n  vector(0)",
       "legendFormat": "Broken Disk"
      },
      {
       "expr": "count(health_shelf_alerts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1)\nor\n  vector(0)",
       "legendFormat": "Shelf Error"
      },
      {
       "expr": "count(health_node_alerts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1)\nor\n  vector(0)",
       "legendFormat": "Node Down"
      },
      {
       "expr": "(\n      count(\n        health_network_fc_port_alerts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1\n      )\n    or\n      vector(0)\n  )\n+\n  (\n      count(\n          health_network_ethernet_port_alerts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"}\n        ==\n          1\n      )\n    or\n      vector(0)\n  )",
       "legendFormat": "Network Port Down"
      },
      {
       "expr": "count(health_license_alerts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1)\nor\n  vector(0)",
       "legendFormat": "License Non Compliant"
      },
      {
       "expr": "count(health_ha_alerts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1)\nor\n  vector(0)",
       "legendFormat": "HA Down"
      },
      {
       "expr": "count(\n      environment_sensor_threshold_value{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",threshold_state!=\"normal\"}\n    ==\n      1\n  )\nor\n  vector(0)",
       "legendFormat": "Sensor Failures"
      }
     ]
    },
    {
     "title": "Warnings",
     "type": "piechart",
     "description": "This panel displays warning detail of disk, shelf, health monitor, lif, volume move and volume anti-ransomware alerts.",
     "gridPos": { "h": 16, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(health_disk_alerts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"warning\"} == 1)\nor\n  vector(0)",
       "legendFormat": "Unassigned Disk"
      },
      {
       "expr": "count(health_shelf_alerts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"warning\"} == 1)\nor\n  vector(0)",
       "legendFormat": "Shelf Warning"
      },
      {
       "expr": "(\n    count(\n        last_over_time(\n          health_support_alerts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"warning\"}[1d]\n        )\n      ==\n        1\n    )\n  or\n    vector(0)\n)",
       "legendFormat": "Health Monitor Alerts (last 24h)"
      },
      {
       "expr": "count(health_lif_alerts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"warning\"} == 1)\nor\n  vector(0)",
       "legendFormat": "Lif are not at home port"
      },
      {
       "expr": "count(\n    health_volume_move_alerts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"warning\"} == 1\n  )\nor\n  vector(0)",
       "legendFormat": "Volume Move Alerts"
      },
      {
       "expr": "count(\n    health_volume_ransomware_alerts{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"error\"} == 1\n  )\nor\n  vector(0)",
       "legendFormat": "Volume Ransomware (9.10+)"
      }
     ]
    },
    {
     "title": "Active Emergency EMS",
     "type": "table",
     "description": "$EMSDescription",
     "gridPos": { "h": 16, "w": 8, "x": 16, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "count by (message) (\n    last_over_time(\n      ems_events{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",severity=\"emergency\"}[$__range]\n    )\n  ==\n    1\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Latency by Cluster",
     "type": "timeseries",
     "description": "Average latency in microseconds for the WAFL filesystem to process all the operations on the volume; not including request processing or network communication time.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "max by (netapp_cluster) (volume_avg_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\nand\n  topk(\n    $TopResources,\n    max by (netapp_cluster) (\n      avg_over_time(volume_avg_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
       "legendFormat": "{{netapp_cluster}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Throughput by Cluster",
     "type": "timeseries",
     "description": "Cluster throughput.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster) (volume_total_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\nand\n  topk(\n    $TopResources,\n    sum by (netapp_cluster) (\n      avg_over_time(volume_total_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
       "legendFormat": "{{netapp_cluster}}"
      }
     ]
    },
    {
     "title": "Top $TopResources  IOPs by Cluster",
     "type": "timeseries",
     "description": "Number of operations per second serviced by the cluster.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster) (volume_total_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\nand\n  topk(\n    $TopResources,\n    sum by (netapp_cluster) (\n      avg_over_time(volume_total_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
       "legendFormat": "{{netapp_cluster}}"
      }
     ]
    },
    {
     "title": "Top $TopResources CPU Busy by Cluster",
     "type": "timeseries",
     "description": "$CPU_BUSY",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (netapp_cluster) (node_cpu_busy{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\nand\n  topk(\n    $TopResources,\n    avg by (netapp_cluster) (\n      avg_over_time(node_cpu_busy{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} "
      }
     ]
    },
    {
     "title": "Top $TopResources Average CPU Utilization by Cluster",
     "type": "timeseries",
     "description": "Average processor utilization across all processors in the system.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (netapp_cluster) (node_avg_processor_busy{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\nand\n  topk(\n    $TopResources,\n    avg by (netapp_cluster) (\n      avg_over_time(node_avg_processor_busy{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
       "legendFormat": "{{netapp_cluster}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Power and Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
     "options": {
      "content": "<br>These panels require ONTAP 9.6+ and REST private CLI.\n\nSee <a target='blank' href='https://netapp.github.io/harvest/latest/power-algorithm'>power algorithm</a> for more details.<br>\nFor more information, please check the `ONTAP: Power` dashboard."
     }
    },
    {
     "title": "Total Power",
     "type": "stat",
     "description": "This panel displays total power of nodes and shelves.",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(environment_sensor_power{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}) or vector(0))\n+\n  (\n      sum(\n          shelf_power{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n        * on (datacenter, netapp_cluster, shelf)\n          shelf_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isEmbedded=\"No\"}\n      )\n    or\n      vector(0)\n  )"
      }
     ]
    },
    {
     "title": "Average Power/Used_TB",
     "type": "stat",
     "description": "Average Power per used TB.",
     "gridPos": { "h": 5, "w": 7, "x": 9, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "Watts/TB" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(avg(environment_sensor_power{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}) or vector(0))\n/\n  (\n          (sum(aggr_space_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}) / 1024 / 1024 / 1024 / 1024)\n        /\n          count(sum(node_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))\n      >\n        1\n    or\n      max(\n          aggr_space_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n        /\n          aggr_space_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n      )\n  )"
      }
     ]
    },
    {
     "title": "Max Node Temp",
     "type": "stat",
     "description": "Maximum temperature of all non-ambient sensors for node in Celsius.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(environment_sensor_max_temperature{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
      }
     ]
    },
    {
     "title": "Max Shelf Fan Speed",
     "type": "stat",
     "description": "Maximum fan speed for shelf in rpm.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(shelf_max_fan_speed{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
      }
     ]
    },
    {
     "title": "Average IOPs/Watt",
     "type": "stat",
     "description": "Average IOPs per Watt.",
     "gridPos": { "h": 5, "w": 7, "x": 9, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "IOPs/Watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_total_ops{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n/\n  (avg(environment_sensor_power{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}) or vector(1))"
      }
     ]
    },
    {
     "title": "Max Shelf Temp",
     "type": "stat",
     "description": "Maximum temperature of all non-ambient sensors for shelf in Celsius.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(shelf_max_temperature{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
      }
     ]
    },
    {
     "title": "Max Node Fan Speed",
     "type": "stat",
     "description": "Maximum fan speed for node in rpm.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(environment_sensor_max_fan_speed{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
      }
     ]
    },
    {
     "title": "Total Power Consumed",
     "type": "timeseries",
     "description": "This panel displays detail of power consumed by a node/shelf/total in Watts.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum(environment_sensor_power{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})",
       "legendFormat": "Node"
      },
      {
       "expr": "sum(shelf_power{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})",
       "legendFormat": "Shelf"
      },
      {
       "expr": "(sum(environment_sensor_power{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}) or vector(0))\n+\n  (sum(shelf_power{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}) or vector(0))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
     "options": {
      "content": "<br>For more information, please check the `ONTAP: Data Protection Snapshots` dashboard."
     }
    },
    {
     "title": "Protected Status",
     "type": "piechart",
     "description": "Volumes Protected With Snapshot Copies (local). For more information, please check the `ONTAP: Data Protection Snapshots` dashboard.",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(\n      volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\",volume!~\"MDV.*\"}\n    * on (snapshot_policy) group_left ()\n      group by (snapshot_policy) (snapshot_policy_labels)\n  )\nor on ()\n  vector(0)",
       "legendFormat": "Volumes protected"
      },
      {
       "expr": "count(\n    (\n        volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy=~\"none.*\",volume!~\"MDV.*\"}\n      * on (snapshot_policy) group_left ()\n        group by (snapshot_policy) (snapshot_policy_labels)\n    )\n  )\nor on ()\n  vector(0)",
       "legendFormat": "Volumes not protected"
      }
     ]
    },
    {
     "title": "Breached Status",
     "type": "piechart",
     "description": "Volumes Breaching Snapshot Copy Reserve Space.For more information, please check the `ONTAP: Data Protection Snapshots` dashboard.",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(\n        volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\"}\n      * on (snapshot_policy) group_left ()\n        group by (snapshot_policy) (snapshot_policy_labels)\n    * on (volume, svm, netapp_cluster) group_right ()\n      (\n            volume_snapshot_reserve_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} >= 0\n          and\n            volume_snapshots_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} >= 0\n        and\n            volume_snapshots_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n          >\n            volume_snapshot_reserve_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n      )\n  )\nor on ()\n  vector(0)",
       "legendFormat": "Volumes breached"
      },
      {
       "expr": "(\n      count(\n          (\n              volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\"}\n            * on (snapshot_policy) group_left ()\n              group by (snapshot_policy) (snapshot_policy_labels)\n          )\n        * on (volume, svm, netapp_cluster) group_right ()\n          (\n                volume_snapshot_reserve_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} >= 0\n              and\n                volume_snapshots_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} >= 0\n            and\n                volume_snapshots_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n              <=\n                volume_snapshot_reserve_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n          )\n      )\n    or on ()\n      vector(0)\n  )\n+\n  (\n      count(\n            volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\"}\n          * on (snapshot_policy) group_left ()\n            group by (snapshot_policy) (snapshot_policy_labels)\n        * on (volume, svm, netapp_cluster) group_right ()\n          (\n              volume_snapshot_reserve_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} >= 0\n            and\n              volume_snapshots_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} == 0\n          )\n      )\n    or on ()\n      vector(0)\n  )",
       "legendFormat": "Volumes not breached"
      }
     ]
    },
    {
     "title": "Snapshot Copies",
     "type": "piechart",
     "description": "For more information, please check the `ONTAP: Data Protection Snapshots` dashboard.",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(\n      (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\",volume!~\"MDV.*\"}\n        * on (snapshot_policy) group_left ()\n          group by (snapshot_policy) (snapshot_policy_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n      )\n    * on (volume, svm, netapp_cluster)\n      (\n          volume_snapshot_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} > 0\n        and\n          volume_snapshot_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} < 10\n      )\n  )\nor on ()\n  vector(0)",
       "legendFormat": " <10 Copies "
      },
      {
       "expr": "count(\n      (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\",volume!~\"MDV.*\"}\n        * on (snapshot_policy) group_left ()\n          group by (snapshot_policy) (snapshot_policy_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n      )\n    * on (volume, svm, netapp_cluster)\n      (\n          volume_snapshot_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} >= 10\n        and\n          volume_snapshot_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} <= 100\n      )\n  )\nor on ()\n  vector(0)",
       "legendFormat": "10-100 Copies"
      },
      {
       "expr": "count(\n      (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\",volume!~\"MDV.*\"}\n        * on (snapshot_policy) group_left ()\n          group by (snapshot_policy) (snapshot_policy_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n      )\n    * on (volume, svm, netapp_cluster)\n      (\n          volume_snapshot_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} > 100\n        and\n          volume_snapshot_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} <= 500\n      )\n  )\nor on ()\n  vector(0)",
       "legendFormat": "101-500 Copies"
      },
      {
       "expr": "count(\n      (\n          volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",snapshot_policy!=\"\",snapshot_policy!~\"none.*\",volume!~\"MDV.*\"}\n        * on (snapshot_policy) group_left ()\n          group by (snapshot_policy) (snapshot_policy_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n      )\n    * on (volume, svm, netapp_cluster)\n      (volume_snapshot_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"} > 500)\n  )\nor on ()\n  vector(0)",
       "legendFormat": ">500 Copies"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Efficiency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Reduction",
     "type": "stat",
     "description": "Storage efficiency ratio.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aggr_logical_used_wo_snapshots_flexclones{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n/\n  sum(aggr_physical_used_wo_snapshots_flexclones{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
      }
     ]
    },
    {
     "title": "Data Reduction with FlexClones",
     "type": "stat",
     "description": "Storage efficiency ratio with FlexClones.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aggr_logical_used_wo_snapshots{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n/\n  sum(aggr_physical_used_wo_snapshots{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
      }
     ]
    },
    {
     "title": "Data Reduction with Snapshots & FlexClones",
     "type": "stat",
     "description": "Storage efficiency ratio of total space used.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aggr_total_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\n/\n  sum(aggr_total_physical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
      }
     ]
    },
    {
     "title": "Top $TopResources Logical Used by Cluster",
     "type": "timeseries",
     "description": "Logical used.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster) (\n    aggr_logical_used_wo_snapshots_flexclones{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n  )\nand\n  topk(\n    $TopResources,\n    sum by (netapp_cluster) (\n      avg_over_time(\n        aggr_logical_used_wo_snapshots_flexclones{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Physical Used by Cluster",
     "type": "timeseries",
     "description": "Total data reduction physical used.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster) (\n    aggr_physical_used_wo_snapshots_flexclones{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n  )\nand\n  topk(\n    $TopResources,\n    sum by (netapp_cluster) (\n      avg_over_time(\n        aggr_physical_used_wo_snapshots_flexclones{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Logical Used with FlexClones by Cluster",
     "type": "timeseries",
     "description": "Logical used with flexclones.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster) (aggr_logical_used_wo_snapshots{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\nand\n  topk(\n    $TopResources,\n    sum by (netapp_cluster) (\n      avg_over_time(\n        aggr_logical_used_wo_snapshots{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Physical Used with FlexClones by Cluster",
     "type": "timeseries",
     "description": "Total Data Reduction Physical Used with FlexClones.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster) (aggr_physical_used_wo_snapshots{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\nand\n  topk(\n    $TopResources,\n    sum by (netapp_cluster) (\n      avg_over_time(\n        aggr_physical_used_wo_snapshots{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end()\n      )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Logical Used with Snapshots & FlexClones by Cluster",
     "type": "timeseries",
     "description": "Logical used with snapshots & flexclones.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster) (aggr_total_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\nand\n  topk(\n    $TopResources,\n    sum by (netapp_cluster) (\n      avg_over_time(aggr_total_logical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
       "legendFormat": "{{netapp_cluster}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Physical Used with Snapshots & FlexClones by Cluster",
     "type": "timeseries",
     "description": "Physical Used with snapshots & flexclones.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster) (aggr_space_physical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})\nand\n  topk(\n    $TopResources,\n    sum by (netapp_cluster) (\n      avg_over_time(aggr_space_physical_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h] @ end())\n    )\n  )",
       "legendFormat": "{{netapp_cluster}}"
      }
     ]
    }
   ]
  }
 ]
}