{
 "title": "ONTAP: Disk",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"},netapp_cluster)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(disk_labels{system_type!=\"7mode\",netapp_cluster=~\"$Cluster\"}, node)"
    }
   },
   {
    "name": "Aggregate",
    "query": {
     "query": "label_values(aggr_disk_busy{netapp_cluster=~\"$Cluster\",node=~\"$Node\"}, aggr)"
    }
   },
   {
    "name": "Plex",
    "query": {
     "query": "label_values(aggr_disk_busy{netapp_cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}, plex)"
    }
   },
   {
    "name": "Raid",
    "query": {
     "query": "label_values(aggr_disk_busy{netapp_cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\",plex=~\"$Plex\"}, raid)"
    }
   },
   {
    "name": "HostAdapter",
    "query": {
     "query": "label_values(hostadapter_bytes_read{system_type!=\"7mode\",netapp_cluster=~\"$Cluster\",node=~\"$Node\"}, hostadapter)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Disks",
   "type": "stat",
   "description": "Number of disks.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(disk_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Failed Disks",
   "type": "stat",
   "description": "Number of failed disks.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (serial_number) (\n    disk_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",failed=\"true\",node=~\"$Node\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "Raid Groups",
   "type": "stat",
   "description": "The utilization percent of the disk. aggr_disk_busy is [disk_busy](#disk_busy) aggregated by `aggr`.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (raid_group) (aggr_disk_busy{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})\n)"
    }
   ]
  },
  {
   "title": "Plexes",
   "type": "stat",
   "description": "The utilization percent of the disk. aggr_disk_busy is [disk_busy](#disk_busy) aggregated by `aggr`.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (plex, aggr) (aggr_disk_busy{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})\n)"
    }
   ]
  },
  {
   "title": "Total Disks by Aggregate(s)",
   "type": "stat",
   "description": "Number of disks in the aggregate.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  aggr_raid_disk_count{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n)"
    }
   ]
  },
  {
   "title": "Disk Capacity per Aggregate",
   "type": "table",
   "description": "Disk capacity per aggregate detail.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aggr_raid_disk_count{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    },
    {
     "expr": "aggr_space_total{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    },
    {
     "expr": "aggr_space_used_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Disk Utilization",
   "type": "table",
   "description": "Highest Disk Utilization per Aggregate for latest record (independent of time range selected).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (aggr, node) (\n    aggr_disk_max_total_transfers{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand\n  topk(\n    $TopResources,\n    max by (aggr, node) (\n      avg_over_time(\n        aggr_disk_max_total_transfers{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n      )\n    )\n  )"
    },
    {
     "expr": "max by (aggr, node) (\n    aggr_disk_max_busy{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand\n  topk(\n    $TopResources,\n    max by (aggr, node) (\n      avg_over_time(\n        aggr_disk_max_busy{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n      )\n    )\n  )"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Max Disk Utilization",
   "type": "timeseries",
   "description": "Highest Disk Utilization per Aggregate in the selected time range.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (node, aggr) (\n    aggr_disk_max_busy{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand\n  topk(\n    $TopResources,\n    max by (node, aggr) (\n      avg_over_time(\n        aggr_disk_max_busy{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Disk Transfers",
   "type": "timeseries",
   "description": "Total number of disk operations involving data transfer initiated per second\n.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (node, aggr) (\n    aggr_disk_max_total_transfers{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand\n  topk(\n    $TopResources,\n    max by (node, aggr) (\n      avg_over_time(\n        aggr_disk_max_total_transfers{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by User Read Chain Length",
   "type": "timeseries",
   "description": "Average number of blocks transferred in each user read operation. aggr_disk_max_user_read_chain is the maximum of [disk_user_read_chain](#disk_user_read_chain) for label `aggr`.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max by (node, aggr) (\n    aggr_disk_max_user_read_chain{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand\n  topk(\n    $TopResources,\n    max by (node, aggr) (\n      avg_over_time(\n        aggr_disk_max_user_read_chain{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by User Write Chain Length",
   "type": "timeseries",
   "description": "Average number of blocks transferred in each user write operation. aggr_disk_max_user_write_chain is the maximum of [disk_user_write_chain](#disk_user_write_chain) for label `aggr`.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max by (node, aggr) (\n    aggr_disk_max_user_write_chain{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n  )\nand\n  topk(\n    $TopResources,\n    max by (node, aggr) (\n      avg_over_time(\n        aggr_disk_max_user_write_chain{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n      )\n    )\n  )",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top Disks: Raid-level Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Disks by User Read Latency",
     "type": "timeseries",
     "description": "Average latency per block in microseconds for user read operations.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "raid_disk_user_read_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",plex=~\"$Plex\",raid=~\"$Raid\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      raid_disk_user_read_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",plex=~\"$Plex\",raid=~\"$Raid\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{disk}} - {{plex}} - {{raid}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Disks by User Write Latency",
     "type": "timeseries",
     "description": "Average latency per block in microseconds for user write operations.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "raid_disk_user_write_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",plex=~\"$Plex\",raid=~\"$Raid\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      raid_disk_user_write_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",plex=~\"$Plex\",raid=~\"$Raid\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{disk}} - {{plex}} - {{raid}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Disks by Total Transfers",
     "type": "timeseries",
     "description": "Total number of disk operations involving data transfer initiated per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "raid_disk_total_transfers{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",plex=~\"$Plex\",raid=~\"$Raid\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      raid_disk_total_transfers{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",plex=~\"$Plex\",raid=~\"$Raid\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{disk}} - {{plex}} - {{raid}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Disks by Disk Busy",
     "type": "timeseries",
     "description": "The utilization percent of the disk in the selected time range.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "raid_disk_busy{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",plex=~\"$Plex\",raid=~\"$Raid\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      raid_disk_busy{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",plex=~\"$Plex\",raid=~\"$Raid\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{disk}} - {{plex}} - {{raid}}"
      }
     ]
    }
   ]
  },
  {
   "title": "List of Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disks in Cluster",
     "type": "table",
     "description": "Some Clusters don't report average latency, so the values might be 0s.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "disk_bytes_per_sector * disk_sectors{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      },
      {
       "expr": "disk_stats_io_kbps{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      },
      {
       "expr": "disk_stats_average_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      },
      {
       "expr": "disk_uptime{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      },
      {
       "expr": "label_join(\n  disk_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"},\n  \"diskStatus\",\n  \" \",\n  \"NonSupportedField\",\n  \"outage\"\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Throughput by Node",
     "type": "timeseries",
     "description": "This panel displays detail of number of disk kilobytes (KB) read/written per second.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "KiBs" } },
     "targets": [
      {
       "expr": "sum by (node) (node_disk_data_read{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - READ"
      },
      {
       "expr": "sum by (node) (node_disk_data_written{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - WRITE"
      }
     ]
    },
    {
     "title": "Disk and Tape Drives Throughput by Node",
     "type": "timeseries",
     "description": "This panel displays detail of bytes written/read through a host adapter.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (node) (\n  hostadapter_bytes_written{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n)",
       "legendFormat": "{{node}} - WRITE"
      },
      {
       "expr": "sum by (node) (hostadapter_bytes_read{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - READ"
      }
     ]
    },
    {
     "title": "Top $TopResources Disk and Tape Drives Throughput by Host Adapter",
     "type": "timeseries",
     "description": "This panel displays detail of bytes written/read through a host adapter.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(\n    sum by (datacenter, netapp_cluster, node, hostadapter) (\n      hostadapter_bytes_written{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",hostadapter=~\"$HostAdapter\",node=~\"$Node\"}\n    )\n  )\nand on (datacenter, netapp_cluster, node, hostadapter)\n  topk(\n    $TopResources,\n    sum by (datacenter, netapp_cluster, node, hostadapter) (\n      avg_over_time(\n        hostadapter_bytes_written{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",hostadapter=~\"$HostAdapter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{node}} - {{hostadapter}} - WRITE"
      },
      {
       "expr": "(\n    sum by (datacenter, netapp_cluster, node, hostadapter) (\n      hostadapter_bytes_read{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",hostadapter=~\"$HostAdapter\",node=~\"$Node\"}\n    )\n  )\nand on (datacenter, netapp_cluster, node, hostadapter)\n  topk(\n    $TopResources,\n    sum by (datacenter, netapp_cluster, node, hostadapter) (\n      avg_over_time(\n        hostadapter_bytes_read{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",hostadapter=~\"$HostAdapter\",node=~\"$Node\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{node}} - {{hostadapter}} - READ"
      }
     ]
    },
    {
     "title": "Flash Cache",
     "type": "timeseries",
     "description": "This panel displays detail of external cache hit rate and estimated number of disk reads per second replaced by cache.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(flashcache_hit_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "Hit %"
      },
      {
       "expr": "sum(flashcache_disk_reads_replaced{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "HDD Reads Replaced"
      }
     ]
    },
    {
     "title": "Flash Pool",
     "type": "timeseries",
     "description": "This panel displays detail of percentage of HDD read operations replace by SSD and number of HDD read operations replaced by SSD reads per second.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(\n  flashpool_read_ops_replaced_percent{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n)",
       "legendFormat": "Hit %"
      },
      {
       "expr": "sum(flashpool_read_ops_replaced{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "HDD Reads Replaced"
      }
     ]
    },
    {
     "title": "CP (Consistency Points) Counts",
     "type": "timeseries",
     "description": "This panel displays details of the counts of two types of Consistency Points (CP).\n\n- **Back-to-Back CP (back_to_back_CP)**: For more information, see [Write Performance Impacted by Back to Back Consistency Points](https://kb.netapp.com/on-prem/ontap/Perf/Perf-KBs/Write_Performance_Impacted_by_Back_to_Back_Consistency_Points).\n- **Deferred Back-to-Back CP (deferred_back_to_back_CP)**: For more information, see [What are the different Consistency Point types and how are they measured](https://kb.netapp.com/on-prem/ontap/Perf/Perf-KBs/What_are_the_different_Consistency_Point_types_and_how_are_they_measured).",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (datacenter, netapp_cluster, node) (\n  wafl_cp_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=~\"back_to_back_CP|deferred_back_to_back_CP|back_to_back_cp|deferred_back_to_back_cp\",node=~\"$Node\"}\n)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write Latency by Node",
     "type": "timeseries",
     "description": "This panel displays details of the average latency in microseconds for the WAFL filesystem to process write requests to the volume.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "node_vol_write_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}