{
 "title": "ONTAP: File System Analytics (FSA)",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, netapp_cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(volume_analytics_dir_bytes_used{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\"}, svm)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(volume_analytics_dir_bytes_used{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\",svm=~\"$SVM\"}, volume)"
    }
   },
   {
    "name": "Activity",
    "query": "Weekly,Monthly,Quarterly,Yearly,Unknown"
   },
   { "name": "TopResources", "query": "1,2,3,4,5,6,8,10,15,20" }
  ]
 },
 "panels": [
  {
   "title": "Important Information about FSA dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard requires ONTAP 9.8+ and the APIs are only available via REST. Two actions are required to use this dashboard: <br>1. On Harvest, enable the REST collector in your `harvest.yml` config<br>2. On your ONTAP cluster, enable File System Analytics (FSA) for one or more volumes. See https://docs.netapp.com/us-en/ontap/task_nas_file_system_analytics_enable.html for more details. <br><br> Note: Prior to version 9.13.1, ONTAP requires you to enable FSA individually for each volume. Harvest only collects FSA metrics from FSA-enabled volumes on the cluster. By default, Harvest keeps track of the 20 largest volumes for FSA. If you wish to customize this, please see: https://github.com/NetApp/harvest/blob/main/conf/rest/9.12.0/volume_analytics.yaml."
   }
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Used",
   "type": "stat",
   "description": "The virtual space used (includes volume reserves) before storage efficiency, in bytes.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(volume_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "description": "The available space, in bytes.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  volume_size_available{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\n)"
    }
   ]
  },
  {
   "title": "Size",
   "type": "stat",
   "description": "Total size of AFS, excluding snap-reserve, in bytes.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(volume_size_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"})"
    }
   ]
  },
  {
   "title": "Used Percentage",
   "type": "bargauge",
   "description": "Volume space used percent.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n      sum(volume_size_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"})\n    *\n      100\n  )\n/\n  sum(volume_size_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"})"
    }
   ]
  },
  {
   "title": "Directories",
   "type": "stat",
   "description": "Total directory count including the root and children directories.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  volume_analytics_dir_subdir_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",dir_name=\".\",volume=~\"$Volume\"}\n)"
    }
   ]
  },
  {
   "title": "Top $TopResources Volumes by Directory Growth",
   "type": "timeseries",
   "description": "The actual number of bytes used on disk by this file. If byte_offset and length parameters are specified, this will return the bytes used by the file within the given range.",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "volume_analytics_dir_bytes_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_analytics_dir_bytes_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",dir_name!=\".\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{svm}}-{{volume}}-{{dir_name}}"
    }
   ]
  },
  {
   "title": "Files",
   "type": "stat",
   "description": "Total number of files in root and child directories.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  volume_analytics_dir_file_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",dir_name=\".\",volume=~\"$Volume\"}\n)"
    }
   ]
  },
  {
   "title": "Top $TopResources Volumes by Directory Growth",
   "type": "table",
   "description": "Shows Top 100 directories per volume.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "volume_analytics_dir_bytes_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_analytics_dir_bytes_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",dir_name!=\".\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n    )\n  )"
    },
    {
     "expr": "volume_analytics_dir_file_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_analytics_dir_bytes_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",dir_name!=\".\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n    )\n  )"
    },
    {
     "expr": "volume_analytics_dir_subdir_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_analytics_dir_bytes_used{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",dir_name!=\".\",svm=~\"$SVM\",volume=~\"$Volume\"}[3h] @ end()\n    )\n  )"
    }
   ]
  },
  {
   "title": "Volume Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Access ($Activity) History",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (time, order) (\n  volume_analytics_bytes_used_by_accessed_time{activity=~\"$Activity\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",dir_name=\".\",svm=~\"$SVM\",volume=~\"$Volume\"}\n)",
       "legendFormat": "{{ volume }}"
      }
     ]
    },
    {
     "title": "Volume Access ($Activity) History By Percent",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (time, order) (\n      volume_analytics_bytes_used_percent_by_accessed_time{activity=~\"$Activity\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",dir_name=\".\",svm=~\"$SVM\",volume=~\"$Volume\"}\n    * on (netapp_cluster, datacenter, svm, volume) group_left ()\n      volume_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\n  )\n/ on (netapp_cluster, datacenter, svm, volume) group_left ()\n  sum(volume_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{ volume }} - {{ time }}"
      }
     ]
    },
    {
     "title": "Volume Modify ($Activity) History",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (time, order) (\n  volume_analytics_bytes_used_by_modified_time{activity=~\"$Activity\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",dir_name=\".\",svm=~\"$SVM\",volume=~\"$Volume\"}\n)",
       "legendFormat": "{{ volume }}"
      }
     ]
    },
    {
     "title": "Volume Modify ($Activity) History By Percent",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (time, order) (\n      volume_analytics_bytes_used_percent_by_modified_time{activity=~\"$Activity\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",dir_name=\".\",svm=~\"$SVM\",volume=~\"$Volume\"}\n    * on (netapp_cluster, datacenter, svm, volume) group_left ()\n      volume_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\n  )\n/ on (netapp_cluster, datacenter, svm, volume) group_left ()\n  sum(volume_size{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{ volume }}"
      }
     ]
    }
   ]
  }
 ]
}