{
 "title": "ONTAP: NFS Clients",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, netapp_cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(volume_labels{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\"}, svm)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(volume_labels{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\",svm=~\"$SVM\"}, volume)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information about NFS Clients dashboard",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "You must enable the Rest collector in your `harvest.yml` config and uncomment the `nfs_clients.yaml` section in your `$HARVEST/conf/rest/default.yaml` file. Please see [nfs clients dashboard](https://github.com/NetApp/harvest/wiki/FAQ#nfs-clients-dashboard) for more details. Enabling `nfs_clients.yaml` may slow down data collection."
   }
  },
  {
   "title": "Total NFS Connections",
   "type": "stat",
   "description": "This panel requires a cluster with ONTAP 9.7+ and the Harvest REST collector.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  nfs_clients_idle_duration{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}\n)"
    }
   ]
  },
  {
   "title": "NFS Connections by Protocol",
   "type": "piechart",
   "description": "This panel requires a cluster with ONTAP 9.7+ and the Harvest REST collector.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  nfs_clients_idle_duration{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",protocol=\"nfs\",svm=~\"$SVM\",volume=~\"$Volume\"}\n)",
     "legendFormat": "nfs"
    },
    {
     "expr": "count(\n  nfs_clients_idle_duration{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",protocol=\"nfs3\",svm=~\"$SVM\",volume=~\"$Volume\"}\n)",
     "legendFormat": "nfs3"
    },
    {
     "expr": "count(\n  nfs_clients_idle_duration{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",protocol=\"nfs4\",svm=~\"$SVM\",volume=~\"$Volume\"}\n)",
     "legendFormat": "nfs4"
    },
    {
     "expr": "count(\n  nfs_clients_idle_duration{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",protocol=\"nfs4.1\",svm=~\"$SVM\",volume=~\"$Volume\"}\n)",
     "legendFormat": "nfs4.1"
    },
    {
     "expr": "count(\n  nfs_clients_idle_duration{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",protocol=\"nfs4.2\",svm=~\"$SVM\",volume=~\"$Volume\"}\n)",
     "legendFormat": "nfs4.2"
    }
   ]
  },
  {
   "title": "NFS Clients (active in the past 48 hours)",
   "type": "table",
   "description": "This panel requires a cluster with ONTAP 9.7+ and the Harvest REST collector.",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "nfs_clients_idle_duration{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume\"}"
    }
   ]
  }
 ]
}