{
 "title": "ONTAP: S3 Object Storage",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, netapp_cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(ontaps3_labels{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\"}, svm)"
    }
   },
   {
    "name": "Bucket",
    "query": {
     "query": "label_values(ontaps3_labels{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\", svm=~\"$SVM\"}, bucket)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Important Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard requires ONTAP 9.7+. Three actions are required to use this dashboard: <br>1. If you are using the Rest collector, then you must enable the OntapS3 counters in `$HARVEST/conf/rest/default.yaml`. <br>2. If you are using the ZapiPerf collector, then you must enable the OntapS3SVM counters in `$HARVEST/conf/zapiperf/default.yaml`. <br>3. If you are using the RestPerf collector, then you must enable the OntapS3SVM counters in `$HARVEST/conf/restperf/default.yaml`. <br>Please see https://github.com/NetApp/harvest/discussions/3137 for more details."
   }
  },
  { "title": "Bucket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Bucket Overview",
   "type": "table",
   "description": "You must enable the Rest collector in your harvest.yml config.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ontaps3_labels{bucket=~\"$Bucket\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n* on (volume, svm, netapp_cluster, datacenter) group_left (aggr)\n  volume_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}"
    },
    {
     "expr": "ontaps3_size{bucket=~\"$Bucket\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}"
    },
    {
     "expr": "ontaps3_size\n-\n  ontaps3_logical_used_size{bucket=~\"$Bucket\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}"
    },
    {
     "expr": "ontaps3_logical_used_size{bucket=~\"$Bucket\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}"
    },
    {
     "expr": "ontaps3_used_percent{bucket=~\"$Bucket\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}"
    },
    {
     "expr": "ontaps3_object_count{bucket=~\"$Bucket\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}"
    }
   ]
  },
  {
   "title": "Top $TopResources Buckets by Used Size",
   "type": "timeseries",
   "description": "Specifies the bucket logical used size up to this point.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ontaps3_logical_used_size{bucket=~\"$Bucket\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      ontaps3_logical_used_size{bucket=~\"$Bucket\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{svm}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Buckets by Used Size Percent",
   "type": "timeseries",
   "description": "Specifies the bucket logical used percent.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ontaps3_used_percent{bucket=~\"$Bucket\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      ontaps3_used_percent{bucket=~\"$Bucket\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{svm}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Bucket Permission",
   "type": "table",
   "description": "You must enable the Rest collector in your harvest.yml config.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "ontaps3_policy_labels{bucket=~\"$Bucket\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",permission_type!=\"\",svm=~\"$SVM\"}"
    }
   ]
  },
  {
   "title": "S3 Object Storage SVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests & Connections stats",
     "type": "table",
     "description": "This panel displays Requests and Connections counts at each SVM.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (datacenter, netapp_cluster, svm) (\n  ontaps3_svm_requests{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n)"
      },
      {
       "expr": "sum by (datacenter, netapp_cluster, svm) (\n  ontaps3_svm_connections{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n)"
      },
      {
       "expr": "sum by (datacenter, netapp_cluster, svm) (\n  ontaps3_svm_max_requests_outstanding{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n)"
      },
      {
       "expr": "sum by (datacenter, netapp_cluster, svm) (\n  ontaps3_svm_max_connected_connections{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n)"
      },
      {
       "expr": "sum by (datacenter, netapp_cluster, svm) (\n  ontaps3_svm_max_cmds_per_connection{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n)"
      }
     ]
    },
    {
     "title": "Top $TopResources SVMs by Operations",
     "type": "timeseries",
     "description": "Number of GET/PUT/HEAD/DELETE SVM operations.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (datacenter, netapp_cluster, svm) (\n    ontaps3_svm_get_object_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, netapp_cluster, svm) (\n      avg_over_time(\n        ontaps3_svm_get_object_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{svm}} - GET"
      },
      {
       "expr": "avg by (datacenter, netapp_cluster, svm) (\n    ontaps3_svm_put_object_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, netapp_cluster, svm) (\n      avg_over_time(\n        ontaps3_svm_put_object_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{svm}} - PUT"
      },
      {
       "expr": "avg by (datacenter, netapp_cluster, svm) (\n    ontaps3_svm_head_object_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, netapp_cluster, svm) (\n      avg_over_time(\n        ontaps3_svm_head_object_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{svm}} - HEAD"
      },
      {
       "expr": "avg by (datacenter, netapp_cluster, svm) (\n    ontaps3_svm_delete_object_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, netapp_cluster, svm) (\n      avg_over_time(\n        ontaps3_svm_delete_object_total{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{svm}} - DELETE"
      }
     ]
    },
    {
     "title": "Top $TopResources SVMs by Rate",
     "type": "timeseries",
     "description": "Number of GET/PUT/HEAD/DELETE SVM operations per second.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg by (datacenter, netapp_cluster, svm) (\n    ontaps3_svm_get_object_rate{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, netapp_cluster, svm) (\n      avg_over_time(\n        ontaps3_svm_get_object_rate{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{svm}} - GET"
      },
      {
       "expr": "avg by (datacenter, netapp_cluster, svm) (\n    ontaps3_svm_put_object_rate{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, netapp_cluster, svm) (\n      avg_over_time(\n        ontaps3_svm_put_object_rate{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{svm}} - PUT"
      },
      {
       "expr": "avg by (datacenter, netapp_cluster, svm) (\n    ontaps3_svm_head_object_rate{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, netapp_cluster, svm) (\n      avg_over_time(\n        ontaps3_svm_head_object_rate{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{svm}} - HEAD"
      },
      {
       "expr": "avg by (datacenter, netapp_cluster, svm) (\n    ontaps3_svm_delete_object_rate{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, netapp_cluster, svm) (\n      avg_over_time(\n        ontaps3_svm_delete_object_rate{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{svm}} - DELETE"
      }
     ]
    },
    {
     "title": "Top $TopResources SVMs by Latency",
     "type": "timeseries",
     "description": "Average latency for GET/PUT/HEAD/DELETE SVM operations.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (datacenter, netapp_cluster, svm) (\n    ontaps3_svm_get_object_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, netapp_cluster, svm) (\n      avg_over_time(\n        ontaps3_svm_get_object_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{svm}} - GET"
      },
      {
       "expr": "avg by (datacenter, netapp_cluster, svm) (\n    ontaps3_svm_put_object_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, netapp_cluster, svm) (\n      avg_over_time(\n        ontaps3_svm_put_object_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{svm}} - PUT"
      },
      {
       "expr": "avg by (datacenter, netapp_cluster, svm) (\n    ontaps3_svm_head_object_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, netapp_cluster, svm) (\n      avg_over_time(\n        ontaps3_svm_head_object_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{svm}} - HEAD"
      },
      {
       "expr": "avg by (datacenter, netapp_cluster, svm) (\n    ontaps3_svm_delete_object_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, netapp_cluster, svm) (\n      avg_over_time(\n        ontaps3_svm_delete_object_latency{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{svm}} - DELETE"
      }
     ]
    },
    {
     "title": "Top $TopResources SVMs by Data Transfer",
     "type": "timeseries",
     "description": "Rate of GET/PUT SVM data transfers per second.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg by (datacenter, netapp_cluster, svm) (\n    ontaps3_svm_get_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, netapp_cluster, svm) (\n      avg_over_time(ontaps3_svm_get_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h])\n    )\n  )",
       "legendFormat": "{{svm}} - GET"
      },
      {
       "expr": "avg by (datacenter, netapp_cluster, svm) (\n    ontaps3_svm_put_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (datacenter, netapp_cluster, svm) (\n      avg_over_time(ontaps3_svm_put_data{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\"}[3h])\n    )\n  )",
       "legendFormat": "{{svm}} - PUT"
      }
     ]
    }
   ]
  }
 ]
}