{
 "title": "ONTAP: Switch",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"},netapp_cluster)"
    }
   },
   {
    "name": "Switch",
    "query": {
     "query": "label_values(ethernet_switch_port_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\"},switch)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "label_values(ethernet_switch_port_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\",switch=~\"$Switch\"},interface)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information about the Switch Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard is compatible with ONTAP 9.8+ and requires the KeyPerf collector. To use this dashboard, please follow the step below:\n\n1. **Enable the KeyPerf Collector**: Update your `harvest.yml` configuration file to enable the [KeyPerf](https://netapp.github.io/harvest/latest/configure-keyperf/) collector."
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Switch Details",
   "type": "table",
   "description": "Displays detail of the Switches.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ethernet_switch_port_new_status{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",switch=~\"$Switch\"}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Interface Transmit Packets",
     "type": "timeseries",
     "description": "Displays total transmit packets per interface per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (switch, interface) (\n    rate(\n      ethernet_switch_port_transmit_packets{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[4m]\n    )\n  )\nand on (switch, interface)\n  topk(\n    $TopResources,\n    sum by (switch, interface) (\n      avg_over_time(\n        ethernet_switch_port_transmit_packets{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{switch}} - {{interface}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Interface Receive Packets",
     "type": "timeseries",
     "description": "Displays total receive packets per interface per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (switch, interface) (\n    rate(\n      ethernet_switch_port_receive_packets{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[4m]\n    )\n  )\nand on (switch, interface)\n  topk(\n    $TopResources,\n    sum by (switch, interface) (\n      avg_over_time(\n        ethernet_switch_port_receive_packets{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{switch}} - {{interface}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Interface Drops",
     "type": "timeseries",
     "description": "Displays drop packets per interface per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (switch, interface) (\n    rate(\n      ethernet_switch_port_receive_discards{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[4m]\n    )\n  )\nand on (switch, interface)\n  topk(\n    $TopResources,\n    sum by (switch, interface) (\n      avg_over_time(\n        ethernet_switch_port_receive_discards{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "Receive - {{switch}} - {{interface}}"
      },
      {
       "expr": "sum by (switch, interface) (\n    rate(\n      ethernet_switch_port_transmit_discards{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[4m]\n    )\n  )\nand on (switch, interface)\n  topk(\n    $TopResources,\n    sum by (switch, interface) (\n      avg_over_time(\n        ethernet_switch_port_transmit_discards{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "Transmit - {{switch}} - {{interface}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Interface Errors",
     "type": "timeseries",
     "description": "Displays errors per interface per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "errors/s" } },
     "targets": [
      {
       "expr": "sum by (switch, interface) (\n    rate(\n      ethernet_switch_port_transmit_errors{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[4m]\n    )\n  )\nand on (switch, interface)\n  topk(\n    $TopResources,\n    sum by (switch, interface) (\n      avg_over_time(\n        ethernet_switch_port_transmit_errors{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "Transmit - {{switch}} - {{interface}}"
      },
      {
       "expr": "sum by (switch, interface) (\n    rate(\n      ethernet_switch_port_receive_errors{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[4m]\n    )\n  )\nand on (switch, interface)\n  topk(\n    $TopResources,\n    sum by (switch, interface) (\n      avg_over_time(\n        ethernet_switch_port_receive_errors{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",interface=~\"$Interface\",switch=~\"$Switch\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "Receive - {{switch}} - {{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Down (Last 24h)",
     "type": "stat",
     "description": "Total interfaces count which are down once or more times in past 24 hours duration.",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n      min_over_time(\n        ethernet_switch_port_new_status{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",interface=~\"$Interface\",speed!=\"auto-speed\",switch=~\"$Switch\"}[1d]\n      )\n    ==\n      0\n  )\nor\n  vector(0)"
      }
     ]
    },
    {
     "title": "Down (Last 24h)",
     "type": "table",
     "description": "These interfaces are down once or more times in past 24 hours duration.",
     "gridPos": { "h": 9, "w": 20, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "min_over_time(\n    ethernet_switch_port_new_status{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",interface=~\"$Interface\",speed!=\"auto-speed\",switch=~\"$Switch\"}[1d]\n  )\n==\n  0"
      }
     ]
    },
    {
     "title": "Down (Last 24h)",
     "type": "timeseries",
     "description": "These interfaces are down once or more times in past 24 hours duration.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "min_over_time(\n    ethernet_switch_port_new_status{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",interface=~\"$Interface\",speed!=\"auto-speed\",switch=~\"$Switch\"}[1d]\n  )\n==\n  0",
       "legendFormat": "{{switch}} - {{interface}}"
      }
     ]
    }
   ]
  }
 ]
}