
collector:          Rest

schedule:
  - counter: 24h  # This handles cases such as cluster upgrades or collector cache updates.
  - data: 3m

objects:
  AvailabilityZone:               availability_zone.yaml
  StorageUnit:                    storage_unit.yaml