
collector:          Rest

schedule:
  - counter: 24h  # This handles cases such as cluster upgrades or collector cache updates.
  - data: 1m

objects:
  AvailabilityZone:               availability_zone.yaml
  Cluster:                        cluster.yaml
  Igroup:                         igroup.yaml
  StorageUnit:                    storage_unit.yaml