#!/bin/bash
# Used by pkg/auth/auth_test.go
# Single quotes are used to avoid escaping special characters
# Single quotes can not contain single quotes, so we use '\'' to close
# the single quote, add a single quote, and then open the single quote again
echo 'password: "password #\"`!@#$%^&*()-=[]|:'\''<>/ password"'