{
 "title": "ONTAP: Aggregate 7 mode",
 "tags": [
  "harvest",
  "ontap",
  "7mode"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(node_labels{system_type=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(aggr_new_status{system_type=\"7mode\",datacenter=~\"$Datacenter\"}, node)"
    }
   },
   {
    "name": "Aggregate",
    "query": {
     "query": "label_values(aggr_new_status{datacenter=~\"$Datacenter\",node=~\"$Node\"}, aggr)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Aggregates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(aggr_labels{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}) by (aggr))"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_raid_disk_count{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"})"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_volume_count_flexvol{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"})"
    }
   ]
  },
  {
   "title": "Total Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_space_total{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"})"
    }
   ]
  },
  {
   "title": "Available Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_space_available{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"})"
    }
   ]
  },
  {
   "title": "Space Used %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(aggr_space_used{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"})/sum(aggr_space_total{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"})"
    }
   ]
  },
  {
   "title": "Aggregates",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aggr_new_status{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
    },
    {
     "expr": "aggr_volume_count_flexvol{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
    },
    {
     "expr": "aggr_raid_disk_count{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
    },
    {
     "expr": "aggr_space_total{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
    },
    {
     "expr": "aggr_space_used{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
    },
    {
     "expr": "aggr_space_used_percent{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
    }
   ]
  },
  {
   "title": "Space Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_space_used{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Space Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_space_available{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "SIS space saved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_space_sis_saved{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Space Saved Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aggr_space_sis_saved_percent{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}} - SIS"
    }
   ]
  },
  {
   "title": "Inodes Used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aggr_inode_used_percent{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Inodes Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aggr_inode_files_used{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}} - USED"
    },
    {
     "expr": "aggr_inode_files_total{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}} - TOTAL"
    }
   ]
  },
  {
   "title": "Inode Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aggr_inode_inodefile_private_capacity{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}} - PRIVATE"
    },
    {
     "expr": "aggr_inode_inodefile_public_capacity{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}} - PUBLIC"
    }
   ]
  },
  {
   "title": "Space Used by Snapshots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_snapshot_size_used{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}} - USED"
    },
    {
     "expr": "aggr_snapshot_size_available{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}} - AVAILABLE"
    }
   ]
  },
  {
   "title": "Space Used by Snapshots %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aggr_snapshot_used_percent{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Snapshot Inodes Used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aggr_snapshot_inode_used_percent{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Snapshot Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aggr_snapshot_files_total{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}} - TOTAL"
    },
    {
     "expr": "aggr_snapshot_files_used{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}} - USED"
    }
   ]
  },
  {
   "title": "Snapshot MaxFiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aggr_snapshot_maxfiles_used{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}} - USED"
    },
    {
     "expr": "aggr_snapshot_maxfiles_possible{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}} - POSSIBLE"
    },
    {
     "expr": "aggr_snapshot_maxfiles_available{datacenter=~\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}",
     "legendFormat": "{{node}} - {{aggr}} - AVAILABLE"
    }
   ]
  }
 ]
}