{
 "title": "ONTAP: Cluster 7 mode",
 "tags": [
  "harvest",
  "ontap",
  "7mode"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(node_labels{system_type=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(node_labels{system_type=\"7mode\",datacenter=~\"$Datacenter\"},node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Nodes & Subsystems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$Node",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 1 },
   "repeat": "Cluster",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_labels{datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    },
    {
     "expr": "node_new_status{datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "cluster health status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_new_status{datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "CPU busy",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_cpu_busy{datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Max Disk Utilization by Cluster",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(disk_busy{datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "$Node - subsystems",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cluster_subsystem_suppressed_alerts{datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    },
    {
     "expr": "cluster_subsystem_outstanding_alerts{datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    },
    {
     "expr": "cluster_subsystem_new_status{datacenter=~\"$Datacenter\",node=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Avg Disk Utilization by Cluster",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(disk_busy{datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Capacity used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(aggr_space_used{datacenter=~\"$Datacenter\",node=~\"$Node\"})/sum(aggr_space_total{datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(volume_avg_latency{datacenter=~\"$Datacenter\",node=~\"$Node\"}) by(node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(volume_read_data{datacenter=~\"$Datacenter\",node=~\"$Node\"}) by (node) + sum(volume_write_data{datacenter=~\"$Datacenter\",node=~\"$Node\"}) by(node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "IOPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(volume_total_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Max Disk Utilization Per Aggregate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(aggr_disk_max_busy{datacenter=~\"$Datacenter\",node=~\"$Node\"}) by (node, aggr)",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Average Aggregate Space Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(aggr_space_used_percent{datacenter=~\"$Datacenter\",node=~\"$Node\"}) by (node, aggr)",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Max Node CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(node_cpu_busy{datacenter=~\"$Datacenter\",node=~\"$Node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}