{
 "title": "NetApp Detail: Disk 7 mode",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Datacenter",
    "query": "label_values(node_labels{system_type=\"7mode\"},datacenter)"
   },
   {
    "name": "Node",
    "query": "label_values(disk_labels{datacenter=\"$Datacenter\"},node)"
   },
   {
    "name": "Aggregate",
    "query": "label_values(aggr_disk_busy{node=\"$Node\"}, aggr)"
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   },
   {
    "name": "DiskType",
    "query": "label_values(disk_labels{node=\"$Node\"}, type)"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( count by(disk) (disk_labels{datacenter=\"$Datacenter\",node=~\"$Node\"}) )"
    }
   ]
  },
  {
   "title": "Failed Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( count by(serial_number) (disk_labels{datacenter=\"$Datacenter\",node=~\"$Node\",offline!=\"\"}) )"
    }
   ]
  },
  {
   "title": "Raid Groups",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( count by(raid) (aggr_disk_busy{datacenter=\"$Datacenter\",node=~\"$Node\"}) )"
    }
   ]
  },
  {
   "title": "Plexes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( count by(plex) (aggr_disk_busy{datacenter=\"$Datacenter\",node=~\"$Node\"}) )"
    }
   ]
  },
  {
   "title": "Disk Capacity per Aggregate",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aggr_raid_disk_count{datacenter=\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
    },
    {
     "expr": "aggr_space_total{datacenter=\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
    },
    {
     "expr": "aggr_space_used_percent{datacenter=\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
    }
   ]
  },
  {
   "title": "Disk Utilization per Aggregate",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (node, aggr) (aggr_disk_total_transfers{datacenter=\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"})"
    },
    {
     "expr": "max by (node, aggr) (aggr_disk_busy{datacenter=\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"})"
    }
   ]
  },
  {
   "title": "Disk Utiliziation",
   "type": "graph",
   "description": "Highest Disk Utilization per Aggregate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max by (node, aggr) (aggr_disk_busy{datacenter=\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"})",
     "legendFormat": "{{node}} - {{aggregate}}"
    }
   ]
  },
  {
   "title": "Disk Transfers",
   "type": "graph",
   "description": "Total number of disk operations involving data transfer initiated per second\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (node, aggr) (aggr_disk_total_transfers{datacenter=\"$Datacenter\",node=~\"$Node\",aggr=~\"$Aggregate\"})",
     "legendFormat": "{{node}} - {{aggregate}}"
    }
   ]
  },
  { "title": "List of Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Disks in Cluster",
   "type": "table",
   "description": "Some Clusters don't report average latency, so the values might be 0s.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "disk_bytes_per_sector * disk_sectors{datacenter=\"$Datacenter\",node=\"$Node\"}"
    },
    {
     "expr": "disk_uptime{datacenter=\"$Datacenter\",node=\"$Node\"}"
    },
    {
     "expr": "label_join(disk_labels{datacenter=\"$Datacenter\",node=\"$Node\"}, \"diskStatus\", \" \",\"NonSupportedField\", \"offline\")"
    }
   ]
  },
  {
   "title": "Disk Utilization: Node-level overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum (node_disk_data_read{datacenter=\"$Datacenter\",node=~\"$Node\"}) by (node)",
     "legendFormat": "{{node}} - READ"
    },
    {
     "expr": "sum (node_disk_data_written{datacenter=\"$Datacenter\",node=~\"$Node\"}) by (node)",
     "legendFormat": "{{node}} - WRITE"
    }
   ]
  },
  {
   "title": "Disk and Tape Drives Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum (hostadapter_bytes_written{datacenter=\"$Datacenter\",node=~\"$Node\"}) by (node)",
     "legendFormat": "{{node}} - WRITE"
    },
    {
     "expr": "sum (hostadapter_bytes_read{datacenter=\"$Datacenter\",node=~\"$Node\"}) by (node)",
     "legendFormat": "{{node}} - READ"
    }
   ]
  },
  {
   "title": "CP (Consistency Points) Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(wafl_cp_count{datacenter=\"$Datacenter\",node=~\"$Node\"}) by (subcounter)",
     "legendFormat": "{{subcounter}}"
    }
   ]
  },
  {
   "title": "Flash Cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "percent", "label": "Hit %" }
   ],
   "targets": [
    {
     "expr": "sum (flashcache_hit_percent{datacenter=\"$Datacenter\",node=~\"$Node\"})",
     "legendFormat": "Hit %"
    },
    {
     "expr": "sum (flashcache_disk_reads_replaced{datacenter=\"$Datacenter\",node=~\"$Node\"})",
     "legendFormat": "HDD Reads Replaced"
    }
   ]
  },
  {
   "title": "Flash Pool",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "percent", "label": "Hit %" }
   ],
   "targets": [
    {
     "expr": "sum (flashpool_read_ops_replaced_percent{datacenter=\"$Datacenter\",node=~\"$Node\"})",
     "legendFormat": "Hit %"
    },
    {
     "expr": "sum (flashpool_read_ops_replaced{datacenter=\"$Datacenter\",node=~\"$Node\"})",
     "legendFormat": "HDD Reads Replaced"
    }
   ]
  }
 ]
}