{
 "title": "NetApp Detail: Network 7 mode",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(node_labels{system_type=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(nic_labels{system_type=\"7mode\",datacenter=\"$Datacenter\"}, node)"
    }
   },
   {
    "name": "Eth",
    "query": {
     "query": "label_values(nic_labels{datacenter=\"$Datacenter\",node=~\"$Node\"}, nic)"
    }
   },
   {
    "name": "FCP",
    "query": {
     "query": "label_values(fcp_total_ops{datacenter=\"$Datacenter\",node=~\"$Node\"}, port)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,20,50,100,250,500,1000"
   }
  ]
 },
 "panels": [
  {
   "title": "Ethernet Throughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nic_tx_bytes+nic_rx_bytes{datacenter=\"$Datacenter\",node=~\"$Node\",nic=~\"$Eth\"})",
     "legendFormat": "Data"
    }
   ]
  },
  {
   "title": "FC Throughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fcp_total_data{datacenter=\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
     "legendFormat": "Data"
    },
    {
     "expr": "sum(fcp_total_ops{datacenter=\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
     "legendFormat": "Operations"
    }
   ]
  },
  {
   "title": "Ethernet Send",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nic_tx_bytes{datacenter=\"$Datacenter\",node=~\"$Node\",nic=~\"$Eth\"})"
    }
   ]
  },
  {
   "title": "Ethernet Receive",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nic_rx_bytes{datacenter=\"$Datacenter\",node=~\"$Node\",nic=~\"$Eth\"})"
    }
   ]
  },
  {
   "title": "FCP Send",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fcp_read_data{datacenter=\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
     "legendFormat": "Data"
    },
    {
     "expr": "sum(fcp_read_ops{datacenter=\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
     "legendFormat": "Operations"
    }
   ]
  },
  {
   "title": "FCP Receive",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fcp_write_data{datacenter=\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
     "legendFormat": "Data"
    },
    {
     "expr": "sum(fcp_write_ops{datacenter=\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
     "legendFormat": "Operations"
    }
   ]
  },
  { "title": "Ethernet Drilldown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Ethernet ports",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "nic_labels{datacenter=\"$Datacenter\",node=~\"$Node\",nic=~\"$Eth\"}"
    },
    {
     "expr": "nic_new_status{datacenter=\"$Datacenter\",node=~\"$Node\",nic=~\"$Eth\"}"
    },
    {
     "expr": "nic_util_percent{datacenter=\"$Datacenter\",node=~\"$Node\",nic=~\"$Eth\"}"
    },
    {
     "expr": "nic_tx_bytes{datacenter=\"$Datacenter\",node=~\"$Node\",nic=~\"$Eth\"}"
    },
    {
     "expr": "nic_rx_bytes{datacenter=\"$Datacenter\",node=~\"$Node\",nic=~\"$Eth\"}"
    }
   ]
  },
  {
   "title": "Send Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, nic_tx_bytes{datacenter=\"$Datacenter\",node=~\"$Node\",nic=~\"$Eth\"})",
     "legendFormat": "{{node}} - {{nic}}"
    }
   ]
  },
  {
   "title": "Receive Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, nic_rx_bytes{datacenter=\"$Datacenter\",node=~\"$Node\",nic=~\"$Eth\"})",
     "legendFormat": "{{node}} - {{nic}}"
    }
   ]
  },
  {
   "title": "Port Utilization %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nic_util_percent{datacenter=\"$Datacenter\",node=~\"$Node\",nic=~\"$Eth\"}",
     "legendFormat": "{{node}} {{nic}}"
    }
   ]
  },
  {
   "title": "Send Errors",
   "type": "graph",
   "description": "Summarized on Cluster or Node level. Select Eth to show for a specific Ethernet Port.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (nic_tx_total_errors{datacenter=\"$Datacenter\",node=~\"$Node\",nic=~\"$Eth\"})",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Receive Errors",
   "type": "graph",
   "description": "Summarized on Cluster or Node level. Select Eth to show for a specific Ethernet Port.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (nic_rx_total_errors{datacenter=\"$Datacenter\",node=~\"$Node\",nic=~\"$Eth\"})",
     "legendFormat": "TOTAL"
    }
   ]
  },
  { "title": "FibreChannel Drilldown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "FCP ports",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "fcp_util_percent{datacenter=\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}"
    },
    {
     "expr": "fcp_read_data{datacenter=\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}"
    },
    {
     "expr": "fcp_write_data{datacenter=\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"}"
    }
   ]
  },
  {
   "title": "Send Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, fcp_read_data{datacenter=\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
     "legendFormat": "{{node}} - {{port}}"
    }
   ]
  },
  {
   "title": "Receive Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, fcp_write_data{datacenter=\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
     "legendFormat": "{{node}} - {{port}}"
    }
   ]
  },
  {
   "title": "Send Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, fcp_avg_read_latency{datacenter=\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
     "legendFormat": "{{node}} - {{port}}"
    }
   ]
  },
  {
   "title": "Receive Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, fcp_avg_write_latency{datacenter=\"$Datacenter\",node=~\"$Node\",port=~\"$FCP\"})",
     "legendFormat": "{{node}} - {{port}}"
    }
   ]
  }
 ]
}