{
 "title": "ONTAP: Volume 7 mode",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(node_labels{system_type=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(volume_labels{system_type=\"7mode\",datacenter=\"$Datacenter\"}, node)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(volume_labels{datacenter=\"$Datacenter\",node=\"$Node\"}, svm)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\"}, volume)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Latency",
   "type": "stat",
   "description": "Average Latency of top $TopResources volumes",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(topk($TopResources, volume_avg_latency{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"}))"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "description": "Throughput of top $TopResources volumes",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(topk($TopResources, (volume_read_data+volume_write_data{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"}) * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"} ))"
    }
   ]
  },
  {
   "title": "Total IOPs",
   "type": "stat",
   "description": "IOPs of top $TopResources volumes",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(topk($TopResources, volume_total_ops{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"} ))"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk($TopResources, volume_avg_latency{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"})",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Top Average Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($TopResources,  (volume_read_data+volume_write_data{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"}) * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"} )",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Top IOPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk($TopResources, volume_total_ops{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"} )",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Volume Table Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumes in Node",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_new_status{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_size_total{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      },
      {
       "expr": "volume_size_used_percent{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"}"
      }
     ]
    },
    {
     "title": "Top Volume Read Latency",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "topk($TopResources, volume_read_latency{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top Volume Read Throughput",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "topk($TopResources, volume_read_data{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top Volume Read IOPS",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "topk($TopResources, volume_read_ops{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top Volume Write Latency",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "topk($TopResources, volume_write_latency{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top Volume Write Throughput",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "targets": [
      {
       "expr": "topk($TopResources, volume_write_data{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top Volume Write IOPS",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "targets": [
      {
       "expr": "topk($TopResources, volume_write_ops{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend WAFL Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk($TopResources, volume_read_latency{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Read Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk($TopResources, volume_read_data{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Read IOPs",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk($TopResources, volume_read_ops{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk($TopResources, volume_write_latency{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk($TopResources, volume_write_data{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Write IOPs",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk($TopResources, volume_write_ops{datacenter=\"$Datacenter\",node=\"$Node\",volume=~\"$Volume\"} * on  (volume, aggr) group_right() volume_labels{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per Volume Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per Volume Space Used",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_size_total{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Volume Total Size"
      },
      {
       "expr": "volume_size_used{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Volume Size Used"
      }
     ]
    },
    {
     "title": "Per Volume Space Used Percent",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_size_used_percent{datacenter=\"$Datacenter\",node=\"$Node\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Volume Size Used"
      }
     ]
    }
   ]
  }
 ]
}