{
 "title": "Harvest Metadata 7 mode",
 "tags": [
  "meta ",
  "harvest"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(poller_status, datacenter)"
    }
   },
   {
    "name": "Hostname",
    "query": {
     "query": "label_values(poller_status, hostname)"
    }
   },
   {
    "name": "Poller",
    "query": {
     "query": "label_values(poller_status, poller)"
    }
   },
   {
    "name": "Collector",
    "query": {
     "query": "label_values(metadata_component_status{type=\"collector\",poller=~\"$Poller\"}, name)"
    }
   },
   {
    "name": "Object",
    "query": {
     "query": "label_values(metadata_component_status{type=\"collector\",poller=~\"$Poller\",name=~\"$Collector\"}, target)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Datacenters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (datacenter) (poller_status{hostname=~\"$Hostname\"}))"
    }
   ]
  },
  {
   "title": "Pollers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (poller) (poller_status{hostname=~\"$Hostname\"}))"
    }
   ]
  },
  {
   "title": "Collectors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (poller, target) (metadata_component_status{hostname=~\"$Hostname\",poller=~\"$Poller\",type=\"collector\"}))"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (poller, target) (metadata_component_status{hostname=~\"$Hostname\",poller=~\"$Poller\",type=\"exporter\"}))"
    }
   ]
  },
  {
   "title": "Collected/24h",
   "type": "stat",
   "description": "Data points collected last 24h",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(metadata_component_count{hostname=~\"$Hostname\",poller=~\"$Poller\",type=\"collector\"}[1d:60s]))"
    }
   ]
  },
  {
   "title": "Collected/m",
   "type": "stat",
   "description": "Data points collected per minute",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(metadata_component_count{hostname=~\"$Hostname\",poller=~\"$Poller\",type=\"collector\"}[60s]))"
    }
   ]
  },
  {
   "title": "Exported/m",
   "type": "stat",
   "description": "Data points exported per minute",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(metadata_component_count{hostname=~\"$Hostname\",poller=~\"$Poller\",type=\"exporter\"}[1m]))"
    }
   ]
  },
  {
   "title": "Target Systems",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metadata_target_ping{hostname=~\"$Hostname\"}"
    },
    {
     "expr": "metadata_target_status{hostname=~\"$Hostname\"}"
    }
   ]
  },
  {
   "title": "% CPU Used",
   "type": "gauge",
   "description": "System CPU used by Harvest Pollers. Number can be higher than 100% on multi-core systems.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(poller_cpu_percent{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\"})"
    }
   ]
  },
  {
   "title": "% Memory Used",
   "type": "bargauge",
   "description": "System Memory used by Harvest Pollers",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(poller_memory_percent{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\"})"
    }
   ]
  },
  {
   "title": "Pollers",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "poller_status{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\"}"
    }
   ]
  },
  {
   "title": "Collectors",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metadata_component_status{poller=~\"$Poller\",type=\"collector\"}"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metadata_component_status{poller=~\"$Poller\",type=\"exporter\"}"
    }
   ]
  },
  {
   "title": "Average Poll time per Poller",
   "type": "graph",
   "description": "Average duration of data poll of all collectors",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (poller) (metadata_collector_poll_time{task=\"data\"})",
     "legendFormat": "{{poller}}"
    }
   ]
  },
  {
   "title": "Average  time per Collector",
   "type": "graph",
   "description": "Average duration of data poll (includes API time and plugins)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (collector) (metadata_collector_poll_time{task=\"data\"})",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Average  time per Exporter",
   "type": "graph",
   "description": "Average export time (includes render time)",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (exporter) (metadata_exporter_time{hostname=~\"$Hostname\",poller=~\"$Poller\"})",
     "legendFormat": "{{exporter}}"
    }
   ]
  },
  { "title": "System Resources Used", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "CPU Utilization %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (poller) (poller_cpu_percent{hostname=~\"$Hostname\",poller=~\"$Poller\"})",
     "legendFormat": "{{poller}}"
    }
   ]
  },
  {
   "title": "% System Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (poller) (poller_memory_percent{hostname=~\"$Hostname\",poller=~\"$Poller\"})",
     "legendFormat": "{{poller}}"
    }
   ]
  },
  {
   "title": "CPU times: breakdown",
   "type": "graph",
   "description": "CPU times per minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "expr": "sum by (poller, metric) (delta(poller_cpu{hostname=~\"$Hostname\",poller=~\"$Poller\"}[1m]))",
     "legendFormat": "{{poller}} - {{metric}}"
    }
   ]
  },
  {
   "title": "Memory: breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (poller, metric) (poller_memory{hostname=~\"$Hostname\",poller=~\"$Poller\",metric!=\"vms\"})",
     "legendFormat": "{{poller}} - {{metric}}"
    },
    {
     "expr": "sum by (poller) (poller_memory{hostname=~\"$Hostname\",poller=~\"$Poller\",metric=\"vms\"})",
     "legendFormat": "{{poller}} - vms"
    }
   ]
  },
  {
   "title": "IO Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(poller_io{hostname=~\"$Hostname\",poller=~\"$Poller\",metric=\"read_bytes\"}[1m])",
     "legendFormat": "{{poller}} - read_bytes"
    },
    {
     "expr": "rate(poller_io{hostname=~\"$Hostname\",poller=~\"$Poller\",metric=\"write_bytes\"}[1m])",
     "legendFormat": "{{poller}} - write_bytes"
    },
    {
     "expr": "rate(poller_io{hostname=~\"$Hostname\",poller=~\"$Poller\",metric=\"cancelled_write_bytes\"}[1m])",
     "legendFormat": "{{poller}} - cancelled_write_bytes"
    }
   ]
  },
  {
   "title": "IO Chars",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(poller_io{hostname=~\"$Hostname\",poller=~\"$Poller\",metric=\"rchar\"}[1m])",
     "legendFormat": "{{poller}} - rchar"
    },
    {
     "expr": "rate(poller_io{hostname=~\"$Hostname\",poller=~\"$Poller\",metric=\"wchar\"}[1m])",
     "legendFormat": "{{poller}} - wchar"
    }
   ]
  },
  {
   "title": "IO Syscalls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(poller_io{hostname=~\"$Hostname\",poller=~\"$Poller\",metric=\"syscr\"}[1m])",
     "legendFormat": "{{poller}} - syscr"
    },
    {
     "expr": "rate(poller_io{hostname=~\"$Hostname\",poller=~\"$Poller\",metric=\"wchar\"}[1m])",
     "legendFormat": "{{poller}} - syscw"
    }
   ]
  },
  {
   "title": "Net IO Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (poller,metric) (rate(poller_net{hostname=~\"$Hostname\",poller=~\"$Poller\",metric=~\".*_bytes\"}[1m]))",
     "legendFormat": "{{poller}} - {{metric}}"
    }
   ]
  },
  {
   "title": "Net IO Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (poller,metric) (rate(poller_net{hostname=~\"$Hostname\",poller=~\"$Poller\",metric=~\".*_packets\"}[1m]))",
     "legendFormat": "{{poller}} - {{metric}}"
    }
   ]
  },
  {
   "title": "Network IO Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (poller,metric) (rate(poller_net{hostname=~\"$Hostname\",poller=~\"$Poller\",metric=~\".*_errs\"}[1m]))",
     "legendFormat": "{{poller}} - {{metric}}"
    }
   ]
  },
  {
   "title": "FDs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (poller) (poller_fds{hostname=~\"$Hostname\",poller=~\"$Poller\"})",
     "legendFormat": "{{poller}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (poller) (poller_threads{hostname=~\"$Hostname\",poller=~\"$Poller\"})",
     "legendFormat": "{{poller}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (poller) (metadata_target_goroutines{hostname=~\"$Hostname\",poller=~\"$Poller\"})",
     "legendFormat": "{{poller}}"
    }
   ]
  },
  { "title": "Zapi Collectors Drilldown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Time per Data Poll",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (collector, object) (metadata_collector_poll_time{hostname=~\"$Hostname\",poller=~\"$Poller\",task=\"data\"})",
     "legendFormat": "{{collector}} - {{object}}"
    }
   ]
  },
  {
   "title": "Data Points per Poll",
   "type": "graph",
   "description": "API wait time of each data poll",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (collector, object) (metadata_collector_count{hostname=~\"$Hostname\",poller=~\"$Poller\",task=\"data\"})",
     "legendFormat": "{{collector}} - {{object}}"
    }
   ]
  },
  {
   "title": "API Time",
   "type": "graph",
   "description": "API wait time of each data poll",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (collector, object) (metadata_collector_api_time{hostname=~\"$Hostname\",poller=~\"$Poller\",task=\"data\"})",
     "legendFormat": "{{collector}} - {{object}}"
    }
   ]
  },
  {
   "title": "XML Parse Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 95 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (collector, object) (metadata_collector_parse_time{hostname=~\"$Hostname\",poller=~\"$Poller\",task=\"data\"})",
     "legendFormat": "{{collector}} - {{object}}"
    }
   ]
  },
  {
   "title": "Postprocessing Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 95 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (collector, object) (metadata_collector_calc_time{hostname=~\"$Hostname\",poller=~\"$Poller\",task=\"data\"})",
     "legendFormat": "{{collector}} - {{object}}"
    }
   ]
  },
  { "title": "Prometheus Drilldown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Average time per Export",
   "type": "graph",
   "description": "Note that the Prometheus exporter has two concurrent components, each performing different tasks. The main goroutine receives, renders data from collectors and stores in a cache (=\"export)\". The HTTP daemon will serve this data to the Prometheus database on demand (=\"http\"). It will also serve information about available metrics for humans (=\"info\").\n\nThe total time includes \"export\" and \"http\" time, but not \"info\" (which is not part of the export).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (target, task) (metadata_exporter_time{hostname=~\"$Hostname\",poller=~\"$Poller\"})",
     "legendFormat": "{{target}} - {{task}}"
    },
    {
     "expr": "sum by (target) (metadata_exporter_time{hostname=~\"$Hostname\",poller=~\"$Poller\",task!=\"info\",task!=\"render\"})",
     "legendFormat": "{{target}} - total"
    }
   ]
  },
  {
   "title": "Data Points per Export",
   "type": "graph",
   "description": "Two values:\n- IN: number of data points pushed from collectors to the exporter\n- OUT: number of data points delivered to the Prometheus database over HTTP (might be more than IN, if Prometheus scrapes Harvest with a higher interval)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (name, target) (metadata_component_count{hostname=~\"$Hostname\",poller=~\"$Poller\",type=\"exporter\"})",
     "legendFormat": "{{name}} - {{target}} - IN"
    },
    {
     "expr": "avg by (exporter, target) (metadata_exporter_count{hostname=~\"$Hostname\",poller=~\"$Poller\"})",
     "legendFormat": "{{exporter}} - {{target}} - OUT"
    }
   ]
  }
 ]
}