{
 "title": "ONTAP: Node 7 mode",
 "tags": [
  "harvest",
  "ontap",
  "7mode"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(node_labels{system_type=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(node_labels{system_type=\"7mode\",datacenter=~\"$Datacenter\"}, node)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( count by (node) (node_new_status{datacenter=~\"$Datacenter\",node=~\"$Node\"}) )"
    }
   ]
  },
  {
   "title": "Aggregates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (aggr) (aggr_new_status{datacenter=~\"$Datacenter\",node=~\"$Node\"}))"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(volume_avg_latency{datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(volume_write_data+volume_read_data{datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "IOPs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(volume_total_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_cpu_busy{datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by(node) (volume_avg_latency{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (node) (volume_write_data+volume_read_data{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Top Average IOPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(node) (volume_total_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Max Disk Utilization",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(disk_busy{datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uptime{datacenter=~\"$Datacenter\",node=~\"$Node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Backend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg(volume_read_latency{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(volume_write_latency{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "Write"
      },
      {
       "expr": "avg(volume_other_latency{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(volume_read_data{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(volume_write_data{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "IOPs",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(volume_read_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(volume_write_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(volume_other_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "System Utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(node_cpu_busy{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "CPU Busy"
      },
      {
       "expr": "max(disk_busy{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "Max Disk Utilization"
      }
     ]
    },
    {
     "title": "Reads From",
     "type": "timeseries",
     "description": "Percent of reads on node that are supplied from, and had to wait on, various media types",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(metric) (wafl_read_io_type{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "Protocol Backend IOPs",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(node_cifs_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "cifs"
      },
      {
       "expr": "sum(node_nfs_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "nfs"
      },
      {
       "expr": "sum(node_fcp_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "fcp"
      },
      {
       "expr": "sum(node_iscsi_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "iscsi"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "node_avg_processor_busy{datacenter=~\"$Datacenter\",node=~\"$Node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet Port Utilization Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk($TopResources, nic_util_percent{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{nic}}"
      }
     ]
    },
    {
     "title": "FC Port Utilization Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk($TopResources, fcp_util_percent{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}} -{{port}}"
      }
     ]
    },
    {
     "title": "Ethernet Port Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk($TopResources, nic_rx_bytes+nic_tx_bytes{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{nic}}"
      }
     ]
    },
    {
     "title": "FC Port Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk($TopResources, fcp_read_data+fcp_write_data{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CIFS Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CIFS Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_cifs_latency{datacenter=~\"$Datacenter\",node=~\"$Node\"})"
      }
     ]
    },
    {
     "title": "CIFS IOPs",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_cifs_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})"
      }
     ]
    },
    {
     "title": "CIFS IOPs by Type",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (metric) (node_cifs_op_count{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{metric}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NFSv3 Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFSv3 Avg Read Latency",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_nfs_read_avg_latency{datacenter=~\"$Datacenter\",node=~\"$Node\",nfsv=\"v3\"})"
      }
     ]
    },
    {
     "title": "NFSv3 Avg Latency",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_nfs_latency{datacenter=~\"$Datacenter\",node=~\"$Node\",nfsv=\"v3\"})"
      }
     ]
    },
    {
     "title": "NFSv3 Avg Write Latency",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_nfs_write_avg_latency{datacenter=~\"$Datacenter\",node=~\"$Node\",nfsv=\"v3\"})"
      }
     ]
    },
    {
     "title": "NFS Avg IOPS",
     "type": "table",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg(node_nfs_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "avg(node_nfs_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"}) - avg(node_nfs_read_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"}) - avg(node_nfs_write_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "Avg"
      },
      {
       "expr": "avg(node_nfs_write_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "Avg"
      },
      {
       "expr": "avg(node_nfs_read_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "NFSv3 Read and Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg(node_nfs_read_avg_latency{datacenter=~\"$Datacenter\",node=~\"$Node\",nfsv=\"v3\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(node_nfs_write_avg_latency{datacenter=~\"$Datacenter\",node=~\"$Node\",nfsv=\"v3\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "NFSv3 Read and Write IOPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg(node_nfs_read_ops{datacenter=~\"$Datacenter\",node=~\"$Node\",nfsv=\"v3\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(node_nfs_write_ops{datacenter=~\"$Datacenter\",node=~\"$Node\",nfsv=\"v3\"})",
       "legendFormat": "Write"
      },
      {
       "expr": "avg(node_nfs_total_ops{datacenter=~\"$Datacenter\",node=~\"$Node\",nfsv=\"v3\"})",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "iSCSI Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "iSCSI Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(iscsi_lif_avg_latency{datacenter=~\"$Datacenter\",node=~\"$Node\"})"
      }
     ]
    },
    {
     "title": "iSCSI IOPs",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(iscsi_lif_iscsi_read_ops+iscsi_lif_iscsi_write_ops+iscsi_lif_iscsi_other_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})"
      }
     ]
    },
    {
     "title": "Average Latency by LIF",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by(node, lif) (iscsi_lif_avg_latency{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{lif}}"
      }
     ]
    },
    {
     "title": "IOPs by LIF",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg by(node, lif) (iscsi_lif_iscsi_read_ops+iscsi_lif_iscsi_write_ops+iscsi_lif_iscsi_other_ops{datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{lif}}"
      }
     ]
    }
   ]
  }
 ]
}