{
 "title": "StorageGrid: Overview",
 "tags": [
  "harvest",
  "storagegrid"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(storagegrid_storage_utilization_data_bytes, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(storagegrid_storage_utilization_data_bytes{datacenter=~\"$Datacenter\"},netapp_cluster)"
    }
   },
   {
    "name": "Policy",
    "query": {
     "query": "label_values(storagegrid_private_load_balancer_storage_rx_bytes{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\"},policy)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data space usage breakdown",
   "type": "table",
   "description": "The percentage of the total usable space for object data that has been used for the site",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (site_name, netapp_cluster, datacenter) (\n  storagegrid_storage_utilization_data_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n)"
    },
    {
     "expr": "sum by (site_name, netapp_cluster, datacenter) (\n    storagegrid_storage_utilization_usable_space_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n  +\n    storagegrid_storage_utilization_data_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n)"
    },
    {
     "expr": "100\n  *\n    sum by (site_name, netapp_cluster, datacenter) (\n      storagegrid_storage_utilization_data_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n    )\n/\n  sum by (site_name, netapp_cluster, datacenter) (\n      storagegrid_storage_utilization_usable_space_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n    +\n      storagegrid_storage_utilization_data_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n  )"
    }
   ]
  },
  {
   "title": "Metadata allowed space usage breakdown",
   "type": "table",
   "description": "The percentage of the total allowed space for object metadata that has been used for the site",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (site_name, netapp_cluster, datacenter) (\n  storagegrid_storage_utilization_metadata_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n)"
    },
    {
     "expr": "sum by (site_name, netapp_cluster, datacenter) (\n  storagegrid_storage_utilization_metadata_allowed_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n)"
    },
    {
     "expr": "100\n  *\n    sum by (site_name, netapp_cluster, datacenter) (\n      storagegrid_storage_utilization_metadata_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n    )\n/\n  sum by (site_name, netapp_cluster, datacenter) (\n    storagegrid_storage_utilization_metadata_allowed_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n  )"
    }
   ]
  },
  {
   "title": "Data storage over time",
   "type": "timeseries",
   "description": "The amount of space used for user data during the selected time frame.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (netapp_cluster) (\n  storagegrid_storage_utilization_data_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n)",
     "legendFormat": "{{netapp_cluster}} - Space used"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 operations",
     "type": "timeseries",
     "description": "The number of S3-specific operations performed. You can use this information to monitor your system's workloads and efficiencies.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster) (\n  increase(\n    storagegrid_private_s3_total_requests{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",type=~\"put_.*\"}[2m]\n  )\n)",
       "legendFormat": "{{netapp_cluster}} - PUT"
      },
      {
       "expr": "sum by (netapp_cluster) (\n  increase(\n    storagegrid_private_s3_total_requests{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",type=~\"get_.*\"}[2m]\n  )\n)",
       "legendFormat": "{{netapp_cluster}} - GET"
      },
      {
       "expr": "sum by (netapp_cluster) (\n  increase(\n    storagegrid_private_s3_total_requests{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",type=~\"delete_.*\"}[2m]\n  )\n)",
       "legendFormat": "{{netapp_cluster}} - DELETE"
      },
      {
       "expr": "sum by (netapp_cluster) (\n  increase(\n    storagegrid_private_s3_total_requests{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",type=~\"head_.*\"}[2m]\n  )\n)",
       "legendFormat": "{{netapp_cluster}} - HEAD"
      },
      {
       "expr": "sum by (netapp_cluster) (\n  increase(\n    storagegrid_private_s3_total_requests{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",type=~\"post_.*\"}[2m]\n  )\n)",
       "legendFormat": "{{netapp_cluster}} - POST"
      }
     ]
    },
    {
     "title": "Network traffic",
     "type": "timeseries",
     "description": "**Received**: The rate at which data is being received.\n\n**Transmitted**: The rate at which data is being sent.\n\nFor troubleshooting, these values can help establish a general baseline for network performance.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster) (\n  rate(storagegrid_network_received_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[5m])\n)",
       "legendFormat": "{{netapp_cluster}} - Received"
      },
      {
       "expr": "sum by (netapp_cluster) (\n  rate(storagegrid_network_transmitted_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[5m])\n)",
       "legendFormat": "{{netapp_cluster}} - Transmitted"
      }
     ]
    },
    {
     "title": "S3 API requests",
     "type": "timeseries",
     "description": "The number of S3 API requests received during the selected time frame.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster) (\n  rate(storagegrid_s3_operations_successful{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[2m])\n)",
       "legendFormat": "{{netapp_cluster}} - Successful"
      },
      {
       "expr": "sum by (netapp_cluster) (\n  rate(storagegrid_s3_operations_failed{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[2m])\n)",
       "legendFormat": "{{netapp_cluster}} - Failed"
      },
      {
       "expr": "sum by (netapp_cluster) (\n  rate(storagegrid_s3_operations_unauthorized{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[2m])\n)",
       "legendFormat": "{{netapp_cluster}} - Unauthorized"
      }
     ]
    },
    {
     "title": "Error rate (requests/second)",
     "type": "timeseries",
     "description": "- Bad request: 400\n- Forbidden: 403\n- Not found: 404\n\nYou can use these metrics to ensure platform services are working. Unexpected values might mean a platform service is incorrectly configured, or they might indicate an external problem such as a network issue. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster) (\n  rate(\n    storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",code=\"400\",datacenter=~\"$Datacenter\"}[3m]\n  )\n)",
       "legendFormat": "{{netapp_cluster}} - Bad request (400)"
      },
      {
       "expr": "sum by (netapp_cluster) (\n  rate(\n    storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",code=\"403\",datacenter=~\"$Datacenter\"}[3m]\n  )\n)",
       "legendFormat": "{{netapp_cluster}} - Forbidden (403)"
      },
      {
       "expr": "sum by (netapp_cluster) (\n  rate(\n    storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",code=\"404\",datacenter=~\"$Datacenter\"}[3m]\n  )\n)",
       "legendFormat": "{{netapp_cluster}} - Not found (404)"
      }
     ]
    },
    {
     "title": "Average request duration (non-error)",
     "type": "timeseries",
     "description": "Provides a 3-minute moving average of request durations, broken down by request type (GET, PUT, and DELETE). Each request duration starts when a request header is parsed by the Load Balancer service and ends when the complete response body is returned to the client.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(\n    sum by (netapp_cluster) (\n      rate(\n        storagegrid_private_load_balancer_storage_request_time{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",method=\"DELETE\"}[3m]\n      )\n    )\n  )\n/\n  (\n    sum by (netapp_cluster) (\n      rate(\n        storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",method=\"DELETE\"}[3m]\n      )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - DELETE"
      },
      {
       "expr": "(\n    sum by (netapp_cluster) (\n      rate(\n        storagegrid_private_load_balancer_storage_request_time{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",method=\"GET\"}[3m]\n      )\n    )\n  )\n/\n  (\n    sum by (netapp_cluster) (\n      rate(\n        storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",method=\"GET\"}[3m]\n      )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - GET"
      },
      {
       "expr": "(\n    sum by (netapp_cluster) (\n      rate(\n        storagegrid_private_load_balancer_storage_request_time{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",method=\"PUT\"}[3m]\n      )\n    )\n  )\n/\n  (\n    sum by (netapp_cluster) (\n      rate(\n        storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",method=\"PUT\"}[3m]\n      )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - PUT"
      },
      {
       "expr": "(\n    sum by (netapp_cluster) (\n      rate(\n        storagegrid_private_load_balancer_storage_request_time{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",method=\"POST\"}[3m]\n      )\n    )\n  )\n/\n  (\n    sum by (netapp_cluster) (\n      rate(\n        storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",method=\"POST\"}[3m]\n      )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - POST"
      },
      {
       "expr": "(\n    sum by (netapp_cluster) (\n      rate(\n        storagegrid_private_load_balancer_storage_request_time{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",method=\"HEAD\"}[3m]\n      )\n    )\n  )\n/\n  (\n    sum by (netapp_cluster) (\n      rate(\n        storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",method=\"HEAD\"}[3m]\n      )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - HEAD"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources tenants by logical space used",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (netapp_cluster, tenant, datacenter) (\n    storagegrid_tenant_usage_data_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (netapp_cluster, tenant, datacenter) (\n      avg_over_time(\n        storagegrid_tenant_usage_data_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{tenant}}"
      }
     ]
    },
    {
     "title": "Top $TopResources tenants by quota usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (netapp_cluster, tenant, datacenter) (\n      storagegrid_tenant_usage_data_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n    /\n      storagegrid_tenant_usage_quota_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (netapp_cluster, tenant, datacenter) (\n        avg_over_time(\n          storagegrid_tenant_usage_data_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h]\n        )\n      /\n        avg_over_time(\n          storagegrid_tenant_usage_quota_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h]\n        )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{tenant}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Information Lifecycle Management (ILM)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "ILM queue (Objects)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster) (\n  storagegrid_ilm_awaiting_client_objects{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n)",
       "legendFormat": "{{netapp_cluster}} - To be scanned"
      },
      {
       "expr": "sum by (netapp_cluster) (\n  storagegrid_private_ilm_awaiting_delete_objects{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n)",
       "legendFormat": "{{netapp_cluster}} - To be deleted"
      }
     ]
    },
    {
     "title": "ILM evaluation rate (objects/second)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "objects/sec" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster) (\n  rate(storagegrid_ilm_objects_processed{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[1h])\n)",
       "legendFormat": "{{netapp_cluster}} - Scans"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources nodes by data usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(\n        storagegrid_storage_utilization_data_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n      /\n        (\n            storagegrid_storage_utilization_usable_space_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n          +\n            storagegrid_storage_utilization_data_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\n        )\n    *\n      100\n  )\nand\n  topk(\n    5,\n      (\n          avg_over_time(\n            storagegrid_storage_utilization_data_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h]\n          )\n        /\n          (\n              avg_over_time(\n                storagegrid_storage_utilization_usable_space_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h]\n              )\n            +\n              avg_over_time(\n                storagegrid_storage_utilization_data_bytes{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h]\n              )\n          )\n      )\n    *\n      100\n  )",
       "legendFormat": "{{netapp_cluster}} - {{node}}"
      }
     ]
    },
    {
     "title": "Top $TopResources nodes by CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "storagegrid_node_cpu_utilization_percentage{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      storagegrid_node_cpu_utilization_percentage{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}[3h]\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic Classification",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Load Balancer Request Traffic by Policy",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "8\n*\n  (\n      sum by (netapp_cluster, policy) (\n        rate(storagegrid_private_load_balancer_storage_rx_bytes{netapp_cluster=~\"$Cluster\",policy=~\"$Policy\"}[4m])\n      )\n    and on (netapp_cluster, policy)\n      topk(\n        $TopResources,\n        sum by (netapp_cluster, policy) (\n          avg_over_time(\n            storagegrid_private_load_balancer_storage_rx_bytes{netapp_cluster=~\"$Cluster\",policy=~\"$Policy\"}[3h]\n          )\n        )\n      )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{policy}} - Received"
      },
      {
       "expr": "8\n*\n  (\n      sum by (netapp_cluster, policy) (\n        rate(storagegrid_private_load_balancer_storage_tx_bytes{netapp_cluster=~\"$Cluster\",policy=~\"$Policy\"}[4m])\n      )\n    and on (netapp_cluster, policy)\n      topk(\n        $TopResources,\n        sum by (netapp_cluster, policy) (\n          avg_over_time(\n            storagegrid_private_load_balancer_storage_tx_bytes{netapp_cluster=~\"$Cluster\",policy=~\"$Policy\"}[3h]\n          )\n        )\n      )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{policy}} - Sent"
      }
     ]
    },
    {
     "title": "Top $TopResources Load Balancer Request Completion Rates by Policy",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster, policy) (\n      rate(\n        storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",policy=~\"$Policy\"}[4m]\n      )\n    )\n  >\n    0\nand on (netapp_cluster, policy)\n  topk(\n    $TopResources,\n    sum by (netapp_cluster, policy) (\n      avg_over_time(\n        storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",policy=~\"$Policy\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{policy}} - Total"
      },
      {
       "expr": "sum by (netapp_cluster, policy, method) (\n      rate(\n        storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",policy=~\"$Policy\"}[4m]\n      )\n    )\n  >\n    0\nand on (netapp_cluster, policy, method)\n  topk(\n    $TopResources,\n    sum by (netapp_cluster, policy, method) (\n      avg_over_time(\n        storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",policy=~\"$Policy\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{policy}} - {{method}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Error Response Rates by Policy",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster, policy, code) (\n      rate(\n        storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",code=~\"[45].*\",policy=~\"$Policy\"}[4m]\n      )\n    )\n  >\n    0\nand on (netapp_cluster, policy, code)\n  topk(\n    $TopResources,\n    sum by (netapp_cluster, policy, code) (\n      avg_over_time(\n        storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",code=~\"[45].*\",policy=~\"$Policy\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{policy}} - {{code}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Average Request Durations (Non-Error) By Policy",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (netapp_cluster, policy, method) (\n        rate(\n          storagegrid_private_load_balancer_storage_request_time{netapp_cluster=~\"$Cluster\",code=~\"2.+\",policy=~\"$Policy\"}[4m]\n        )\n      )\n    /\n      (\n        sum by (netapp_cluster, policy, method) (\n          rate(\n            storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",code=~\"2.+\",policy=~\"$Policy\"}[4m]\n          )\n        )\n      )\n  >\n    0\nand on (netapp_cluster, policy, method)\n  topk(\n    $TopResources,\n      sum by (netapp_cluster, policy, method) (\n        avg_over_time(\n          storagegrid_private_load_balancer_storage_request_time{netapp_cluster=~\"$Cluster\",code=~\"2.+\",policy=~\"$Policy\"}[3h]\n        )\n      )\n    /\n      (\n        sum by (netapp_cluster, policy, method) (\n          avg_over_time(\n            storagegrid_private_load_balancer_storage_request_count{netapp_cluster=~\"$Cluster\",code=~\"2.+\",policy=~\"$Policy\"}[3h]\n          )\n        )\n      )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{policy}} - {{method}}"
      }
     ]
    },
    {
     "title": "Write Request Rate by Object Size and Policy",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum by (netapp_cluster, policy, le) (\n  increase(\n    storagegrid_private_load_balancer_storage_request_body_bytes_bucket{method=~\"PUT|POST\",policy=~\"$Policy\"}[9d2m57s]\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Read Request Rate by Object Size and Policy",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "sum by (netapp_cluster, policy, le) (\n  increase(\n    storagegrid_private_load_balancer_storage_request_body_bytes_bucket{method=~\"GET\",policy=~\"$Policy\"}[9d2m57s]\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}