{
 "title": "ONTAP: FlexGroup",
 "tags": [
  "harvest",
  "ontap",
  "cdot",
  "fsx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, netapp_cluster)"
    }
   },
   {
    "name": "Aggregate",
    "query": {
     "query": "label_values(volume_labels{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\"}, aggr)"
    }
   },
   {
    "name": "FlexGroup",
    "query": {
     "query": "label_values(volume_labels{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\",aggr=~\"$Aggregate\",style=\"flexgroup\"}, volume)"
    }
   },
   {
    "name": "Constituent",
    "query": {
     "query": "label_values(volume_labels{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\",aggr=~\"$Aggregate\",style=\"flexgroup_constituent\",volume=~\"$FlexGroup.*\"}, volume)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information about FlexGroup dashboard",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "You must modify the `include_constituents` flag to `true` in all volume.yaml templates. Please see [FlexGroup dashboard](https://github.com/NetApp/harvest/wiki/FAQ#flexgroup-dashboard) for more details. Enabling FlexGroup constituents counters may slow down data collection due to a high number of constituents metrics."
   }
  },
  { "title": "Highlight", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Top $TopResources Constituents by Average Latency",
   "type": "timeseries",
   "description": "Average latency in microseconds for the WAFL filesystem to process all the operations on the volume; not including request processing or network communication time.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "volume_avg_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_avg_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{aggr}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Constituents by Average Throughput",
   "type": "timeseries",
   "description": "Volume total throughput.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(\n      volume_read_data{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\n    +\n      volume_write_data{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\n  )\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          volume_read_data{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n        )\n      +\n        avg_over_time(\n          volume_write_data{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n        )\n    )\n  )",
     "legendFormat": "{{aggr}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Constituents by Total IOPs",
   "type": "timeseries",
   "description": "Number of operations per second serviced by the volume.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "volume_total_ops{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_total_ops{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{aggr}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Volume Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "FlexGroup Constituents in Cluster",
     "type": "table",
     "description": "FlexGroup constituents details.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "volume_labels{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}"
      },
      {
       "expr": "volume_new_status{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}"
      },
      {
       "expr": "volume_size_total{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}"
      },
      {
       "expr": "volume_size_used_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}"
      },
      {
       "expr": "volume_sis_dedup_saved{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}"
      },
      {
       "expr": "volume_sis_compress_saved{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}"
      },
      {
       "expr": "volume_sis_dedup_saved\n+\n  volume_sis_compress_saved{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}"
      },
      {
       "expr": "volume_space_logical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}"
      },
      {
       "expr": "volume_space_physical_used{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Read Latency",
     "type": "table",
     "description": "Average latency in microseconds for the WAFL filesystem to process read request to the volume; not including request processing or network communication time.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "volume_read_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_read_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Read Throughput",
     "type": "table",
     "description": "Bytes read per second.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "volume_read_data{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_read_data{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Read IOPS",
     "type": "table",
     "description": "Number of read operations per second from the volume.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
     "targets": [
      {
       "expr": "volume_read_ops{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_read_ops{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write Latency",
     "type": "table",
     "description": "Average latency in microseconds for the WAFL filesystem to process write request to the volume; not including request processing or network communication time.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "volume_write_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_write_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write Throughput",
     "type": "table",
     "description": "Bytes written per second.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
     "targets": [
      {
       "expr": "volume_write_data{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_write_data{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write IOPS",
     "type": "table",
     "description": "Number of write operations per second to the volume.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
     "targets": [
      {
       "expr": "volume_write_ops{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_write_ops{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Volume FabricPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Volumes by Performance Tier Footprint",
     "type": "timeseries",
     "description": "Footprint of blocks written to the volume in bytes for the performance tier (bin 0).",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_performance_tier_footprint{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_performance_tier_footprint{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} "
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Performance Tier Footprint %",
     "type": "timeseries",
     "description": "Footprint of blocks written to the volume in performance tier (bin 0) as a percentage of aggregate size.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_performance_tier_footprint_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_performance_tier_footprint_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} "
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Capacity Tier Footprint",
     "type": "timeseries",
     "description": "Footprint of blocks written to the volume in bytes for capacity tier (bin 1).",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "volume_capacity_tier_footprint{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_capacity_tier_footprint{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} "
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Capacity Tier Footprint %",
     "type": "timeseries",
     "description": "Footprint of blocks written to the volume in capacity tier (bin 1) as a percentage of aggregate size.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_capacity_tier_footprint_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_capacity_tier_footprint_percent{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Volume WAFL Layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Volumes by Read Latency",
     "type": "timeseries",
     "description": "Average latency in microseconds for the WAFL filesystem to process read request to the volume; not including request processing or network communication time.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "volume_read_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_read_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write Latency",
     "type": "timeseries",
     "description": "Average latency in microseconds for the WAFL filesystem to process write request to the volume; not including request processing or network communication time.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "volume_write_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_write_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Other Latency",
     "type": "timeseries",
     "description": "Average latency in microseconds for the WAFL filesystem to process other operations to the volume; not including request processing or network communication time.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "volume_other_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_other_latency{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Read IOPs",
     "type": "timeseries",
     "description": "Number of read operations per second from the volume.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "volume_read_ops{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_read_ops{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write IOPs",
     "type": "timeseries",
     "description": "Number of write operations per second to the volume.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "volume_write_ops{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_write_ops{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Other IOPs",
     "type": "timeseries",
     "description": "Number of other operations per second to the volume.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "volume_other_ops{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_other_ops{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Read Throughput",
     "type": "timeseries",
     "description": "Bytes read per second.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "volume_read_data{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_read_data{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Write Throughput",
     "type": "timeseries",
     "description": "Bytes written per second.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "volume_write_data{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}\nand on (datacenter, netapp_cluster, svm, volume)\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_write_data{aggr=~\"$Aggregate\",netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",style=\"flexgroup_constituent\",volume=~\"$Constituent\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{aggr}} - {{volume}}"
      }
     ]
    }
   ]
  }
 ]
}