{
 "title": "Harvest Metadata",
 "tags": [ "harvest" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(metadata_target_status, datacenter)"
    }
   },
   {
    "name": "Hostname",
    "query": {
     "query": "label_values(metadata_target_status, hostname)"
    }
   },
   {
    "name": "Poller",
    "query": {
     "query": "label_values(metadata_target_status, poller)"
    }
   },
   {
    "name": "Collector",
    "query": {
     "query": "label_values(metadata_component_status{type=\"collector\",poller=~\"$Poller\"}, name)"
    }
   },
   {
    "name": "Object",
    "query": {
     "query": "label_values(metadata_component_status{type=\"collector\",poller=~\"$Poller\",name=~\"$Collector\"}, target)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Datacenters",
   "type": "stat",
   "description": "Number of datacenters.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (datacenter) (metadata_target_status{datacenter!=\"\",hostname=~\"$Hostname\"}))"
    }
   ]
  },
  {
   "title": "Pollers",
   "type": "stat",
   "description": "Number of pollers.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (poller) (poller_status{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\"})\n)"
    }
   ]
  },
  {
   "title": "Total Object Count Across Collectors",
   "type": "stat",
   "description": "This panel shows the total count of objects across all collectors.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (poller, target) (\n    metadata_component_status{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",name=~\"$Collector\",poller=~\"$Poller\",target=~\"$Object\",type=\"collector\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "Failed Object Count Across Collectors",
   "type": "stat",
   "description": "Failed Object Count Across Collectors.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (poller, name, target) (\n      metadata_component_status{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",name=~\"$Collector\",poller=~\"$Poller\",target=~\"$Object\",type=\"collector\"}\n    ==\n      2\n  )\n)"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "stat",
   "description": "Number of exporters.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (poller, target) (\n    metadata_component_status{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\",type=\"exporter\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "Collected/24h",
   "type": "stat",
   "description": "Data points collected last 24h.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum_over_time(\n    metadata_component_count{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",name=~\"$Collector\",poller=~\"$Poller\",target=~\"$Object\",type=\"collector\"}[1d:1m]\n  )\n)"
    }
   ]
  },
  {
   "title": "Collected/m",
   "type": "stat",
   "description": "Data points collected per minute.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum_over_time(\n    metadata_component_count{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",name=~\"$Collector\",poller=~\"$Poller\",target=~\"$Object\",type=\"collector\"}[2m]\n  )\n)"
    }
   ]
  },
  {
   "title": "Exported/m",
   "type": "stat",
   "description": "Data points exported per minute.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum_over_time(\n    metadata_component_count{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\",type=\"exporter\"}[2m]\n  )\n)"
    }
   ]
  },
  {
   "title": "% CPU Used",
   "type": "timeseries",
   "description": "System CPU used by Harvest Pollers. Number can be greater than 100% on multi-core systems.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(poller_cpu_percent{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\"})",
     "legendFormat": "% CPU used"
    }
   ]
  },
  {
   "title": "% Memory Used",
   "type": "timeseries",
   "description": "System Memory used by Harvest Pollers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(poller_memory_percent{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\"})",
     "legendFormat": "% Memory used"
    }
   ]
  },
  {
   "title": "Target Systems",
   "type": "table",
   "description": "Target system details.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metadata_target_ping{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\"}"
    },
    {
     "expr": "metadata_target_status{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\"}"
    }
   ]
  },
  {
   "title": "Pollers",
   "type": "table",
   "description": "Detail of pollers.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "poller_status{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\"}"
    },
    {
     "expr": "poller_memory{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",metric=\"rss\",poller=~\"$Poller\"}"
    }
   ]
  },
  {
   "title": "Collectors",
   "type": "table",
   "description": "Detail of collectors.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metadata_component_status{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",name=~\"$Collector\",poller=~\"$Poller\",type=\"collector\"}"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "table",
   "description": "Detail of exporters.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metadata_component_status{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\",type=\"exporter\"}"
    }
   ]
  },
  {
   "title": "Average Poll time per Poller",
   "type": "timeseries",
   "description": "Average duration of data poll of all collectors.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (poller) (\n  metadata_collector_poll_time{collector=~\"$Collector\",datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",object=~\"$Object\",poller=~\"$Poller\",task=\"data\"}\n)",
     "legendFormat": "{{poller}}"
    }
   ]
  },
  {
   "title": "Average  time per Collector",
   "type": "timeseries",
   "description": "Average duration of data poll (includes API time and plugins).",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (collector) (\n  metadata_collector_poll_time{collector=~\"$Collector\",datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",object=~\"$Object\",poller=~\"$Poller\",task=\"data\"}\n)",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Average  time per Exporter",
   "type": "timeseries",
   "description": "Average export time (includes render time).",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (exporter) (\n  metadata_exporter_time{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\"}\n)",
     "legendFormat": "{{exporter}}"
    }
   ]
  },
  {
   "title": "Poller RSS Memory",
   "type": "timeseries",
   "description": "Poller resident set memory.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "sum without (pid) (\n  poller_memory{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",metric=\"rss\",poller=~\"$Poller\"}\n)",
     "legendFormat": "{{poller}}"
    }
   ]
  },
  {
   "title": "Collectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time per Data Poll",
     "type": "timeseries",
     "description": "amount of time it took for the poll to finish.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (collector, object) (\n  metadata_collector_poll_time{collector=~\"$Collector\",datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",object=~\"$Object\",poller=~\"$Poller\",task=\"data\"}\n)",
       "legendFormat": "{{collector}} - {{object}}"
      }
     ]
    },
    {
     "title": "Instances per Poll",
     "type": "timeseries",
     "description": "Number of instances collected per Poll.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "ceil(\n  avg by (collector, object) (\n    metadata_collector_instances{collector=~\"$Collector\",datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",object=~\"$Object\",poller=~\"$Poller\",task=\"data\"}\n  )\n)",
       "legendFormat": "{{collector}} - {{object}}"
      }
     ]
    },
    {
     "title": "Data Points per Poll",
     "type": "timeseries",
     "description": "Number of metrics collected per Poll.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "avg by (collector, object) (\n  metadata_collector_metrics{collector=~\"$Collector\",datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",object=~\"$Object\",poller=~\"$Poller\",task=\"data\"}\n)",
       "legendFormat": "{{collector}} - {{object}}"
      }
     ]
    },
    {
     "title": "API Time",
     "type": "timeseries",
     "description": "API wait time of each data poll.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (collector, object) (\n  metadata_collector_api_time{collector=~\"$Collector\",datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",object=~\"$Object\",poller=~\"$Poller\",task=\"data\"}\n)",
       "legendFormat": "{{collector}} - {{object}}"
      }
     ]
    },
    {
     "title": "Parse Time",
     "type": "timeseries",
     "description": "amount of time to parse XML, JSON, etc. for cluster object.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (collector, object) (\n  metadata_collector_parse_time{collector=~\"$Collector\",datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",object=~\"$Object\",poller=~\"$Poller\",task=\"data\"}\n)",
       "legendFormat": "{{collector}} - {{object}}"
      }
     ]
    },
    {
     "title": "Postprocessing Time",
     "type": "timeseries",
     "description": "amount of time it took to compute metrics between two successive polls, specifically using properties like raw, delta, rate, average, and percent. This metric is available for ZapiPerf/RestPerf collectors.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (collector, object) (\n  metadata_collector_calc_time{collector=~\"$Collector\",datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",object=~\"$Object\",poller=~\"$Poller\",task=\"data\"}\n)",
       "legendFormat": "{{collector}} - {{object}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average time per Export",
     "type": "timeseries",
     "description": "Note that the Prometheus exporter has two concurrent components, each performing different tasks. The main goroutine receives, renders data from collectors and stores in a cache (=\"export)\". The HTTP daemon will serve this data to the Prometheus database on demand (=\"http\"). It will also serve information about available metrics for humans (=\"info\").\n\nThe total time includes \"export\" and \"http\" time, but not \"info\" (which is not part of the export).",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (target, task) (\n  metadata_exporter_time{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\"}\n)",
       "legendFormat": "{{target}} - {{task}}"
      },
      {
       "expr": "sum by (target) (\n  metadata_exporter_time{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\",task!=\"info\",task!=\"render\"}\n)",
       "legendFormat": "{{target}} - total"
      }
     ]
    },
    {
     "title": "Data Points per Export",
     "type": "timeseries",
     "description": "Two values:\n- IN: number of data points pushed from collectors to the exporter\n- OUT: number of data points delivered to the Prometheus database over HTTP (might be more than IN, if Prometheus scrapes Harvest with a higher interval).",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "avg by (name, target) (\n  metadata_component_count{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\",type=\"exporter\"}\n)",
       "legendFormat": "{{name}} - {{target}} - IN"
      },
      {
       "expr": "avg by (exporter, target) (\n  metadata_exporter_count{datacenter=~\"$Datacenter\",hostname=~\"$Hostname\",poller=~\"$Poller\"}\n)",
       "legendFormat": "{{exporter}} - {{target}} - OUT"
      }
     ]
    }
   ]
  }
 ]
}