{
 "title": "ONTAP: Shelf",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, netapp_cluster)"
    }
   },
   {
    "name": "Shelf",
    "query": {
     "query": "label_values(shelf_labels{datacenter=~\"$Datacenter\",netapp_cluster=~\"$Cluster\"}, shelf)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Shelves",
   "type": "stat",
   "description": "Number of shelves.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (shelf) (shelf_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}))"
    }
   ]
  },
  {
   "title": "Total Power (Shelf)",
   "type": "stat",
   "description": "Power consumed by shelf in Watts.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(shelf_power{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Max Shelf temp",
   "type": "stat",
   "description": "Maximum temperature of all non-ambient sensors for shelf in Celsius.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(shelf_max_temperature{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
    }
   ]
  },
  {
   "title": "Temperature Avg",
   "type": "stat",
   "description": "Temperature, in degrees celsius.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(shelf_temperature_reading{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"})"
    }
   ]
  },
  {
   "title": "Fan RPM Avg",
   "type": "stat",
   "description": "Fan speed, in rpm.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(shelf_fan_rpm{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
    }
   ]
  },
  {
   "title": "Max Shelf Fan Speed",
   "type": "stat",
   "description": "Maximum fan speed for shelf in rpm.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(shelf_max_fan_speed{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
    }
   ]
  },
  {
   "title": "Custom Sensor Avg",
   "type": "stat",
   "description": "Current, in milliamps.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(shelf_sensor_reading{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Top $TopResources Shelves by Power Consumed",
   "type": "timeseries",
   "description": "Power consumed by shelf in Watts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "shelf_power{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      shelf_power{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{shelf}} ({{netapp_cluster}})"
    }
   ]
  },
  {
   "title": "Top $TopResources Shelves by Average Temperature",
   "type": "timeseries",
   "description": "Average temperature of all non-ambient sensors for shelf in Celsius.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "shelf_average_temperature{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      shelf_average_temperature{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{shelf}} ({{netapp_cluster}})"
    }
   ]
  },
  {
   "title": "Storage Shelves",
   "type": "table",
   "description": "Storage shelf details.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "shelf_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
    },
    {
     "expr": "shelf_disk_count{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
    },
    {
     "expr": "shelf_new_status{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
    },
    {
     "expr": "shelf_power{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
    },
    {
     "expr": "shelf_average_ambient_temperature{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
    },
    {
     "expr": "shelf_min_ambient_temperature{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
    },
    {
     "expr": "shelf_max_temperature{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
    },
    {
     "expr": "shelf_average_temperature{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
    },
    {
     "expr": "shelf_min_temperature{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
    },
    {
     "expr": "shelf_max_fan_speed{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
    },
    {
     "expr": "shelf_average_fan_speed{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
    },
    {
     "expr": "shelf_min_fan_speed{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
    }
   ]
  },
  {
   "title": "PSU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Shelf PSUs",
     "type": "table",
     "description": "Storage shelf PSU details.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "shelf_psu_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
      },
      {
       "expr": "shelf_psu_power_drawn{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
      },
      {
       "expr": "shelf_psu_power_rating{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Module",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Shelf Modules",
     "type": "table",
     "description": "Storage shelf module details.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "shelf_module_labels{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature Sensors",
     "type": "bargauge",
     "description": "Temperature, in degrees celsius.",
     "gridPos": { "h": 11, "w": 13, "x": 0, "y": 23 },
     "repeat": "TempShelf",
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "shelf_temperature_reading{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}",
       "legendFormat": "{{shelf}} · {{sensor_id}}"
      }
     ]
    },
    {
     "title": "Cooling Sensors",
     "type": "bargauge",
     "description": "Fan speed, in rpm.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
     "repeat": "FanShelf",
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "shelf_fan_rpm{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}",
       "legendFormat": "{{shelf}} · {{fan_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Voltage & PSU Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltage Sensors",
     "type": "bargauge",
     "description": "Voltage, in volts.",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "shelf_voltage_reading{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}",
       "legendFormat": "{{shelf}} · {{sensor_id}}"
      }
     ]
    },
    {
     "title": "Energy Drawn from PSUs",
     "type": "bargauge",
     "description": "Power drawn, in watts.",
     "gridPos": { "h": 11, "w": 4, "x": 7, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by (shelf, psu_id) (shelf_psu_power_drawn{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})",
       "legendFormat": "{{shelf}} - PSU {{psu_id}}"
      }
     ]
    },
    {
     "title": "Power Rating from PSUs",
     "type": "bargauge",
     "description": "Power rating, in watts.",
     "gridPos": { "h": 11, "w": 4, "x": 11, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by (shelf, psu_id) (shelf_psu_power_rating{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"})",
       "legendFormat": "{{shelf}} - PSU {{psu_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Custom Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Custom Sensors - Shelf",
     "type": "bargauge",
     "description": "Current, in milliamps.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
     "repeat": "SensShelf",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "shelf_sensor_reading{netapp_cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",shelf=~\"$Shelf\"}",
       "legendFormat": "{{shelf}} · {{sensor_id}}"
      }
     ]
    }
   ]
  }
 ]
}