# Example Harvest alerts

groups:
- name: Harvest Rules
  rules:

  # Alert for any instance that is unreachable for >5 minutes.
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: "critical"
    annotations:
      summary: "Endpoint {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

  # Alert for any instance that has a volume used percentage > 90%
  - alert: Volume Used Percentage > 90%
    expr: volume_size_used_percent > 90
    for: 5m
    labels:
      severity: "critical"
    annotations:
      summary: "Volume {{ $labels.instance }} 90% used"
      description: "{{ $labels.instance }} of job {{ $labels.job }}'s volume is > 90 used"
