{
 "title": "NetApp Detail: SnapMirror",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datacenter", "query": { "query": "label_values(datacenter)" } },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(snapmirror_labels{datacenter=\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "DestinationNode",
    "query": {
     "query": "label_values(snapmirror_labels{datacenter=\"$Datacenter\", cluster=\"$Cluster\"}, destination_node)"
    }
   },
   {
    "name": "SourceNode",
    "query": {
     "query": "label_values(snapmirror_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}, source_node)"
    }
   },
   {
    "name": "DestinationSVM",
    "query": {
     "query": "label_values(snapmirror_labels{datacenter=\"$Datacenter\", cluster=\"$Cluster\"}, destination_vserver)"
    }
   },
   {
    "name": "SourceSVM",
    "query": {
     "query": "label_values(snapmirror_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}, source_vserver)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SnapMirrors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (relationship_id) (snapmirror_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Volume Protection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (relationship_id) (snapmirror_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",group_type=\"vol\"}))"
    }
   ]
  },
  {
   "title": "SVM Protection (DR)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (relationship_id) (snapmirror_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",group_type=\"svm\"}))"
    }
   ]
  },
  {
   "title": "Insync now",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (relationship_id) (snapmirror_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",relationship_status=\"insync\"}))"
    }
   ]
  },
  {
   "title": "Unhealthy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (relationship_id) (snapmirror_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",is_healthy=\"false\"}))"
    }
   ]
  },
  {
   "title": "Last Transfers",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg (snapmirror_last_transfer_duration{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}) by (relationship_id)"
    },
    {
     "expr": "snapmirror_last_transfer_size{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}"
    },
    {
     "expr": "snapmirror_lag_time{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}"
    }
   ]
  },
  { "title": "SnapMirrors per Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Destination Relationships per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "count by (destination_node, relationship_status) (snapmirror_total_transfer_bytes{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",destination_node=~\"$DestinationNode\",destination_node!=\"\"})",
     "legendFormat": "{{destination_node}} - {{relationship_status}}",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Destination - Break Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (destination_node) (snapmirror_break_failed_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",destination_node=~\"$DestinationNode\",destination_node!=\"\"})",
     "legendFormat": "{{destination_node}} - FAIL",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    },
    {
     "expr": "sum by (destination_node) (snapmirror_break_successful_count{datacenter=~\"$Datacenter\",cluster=~\"$System\",destination_node=~\"$DestinationNode\",destination_node!=\"\"})",
     "legendFormat": "{{destination_node}} - SUCCESS",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Destination - Resync Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (destination_node) (snapmirror_resync_failed_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",destination_node=~\"$DestinationNode\",destination_node!=\"\"})",
     "legendFormat": "{{destination_node}} - FAIL",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    },
    {
     "expr": "sum by (destination_node) (snapmirror_resync_successful_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",destination_node=~\"$DestinationNode\",destination_node!=\"\"})",
     "legendFormat": "{{destination_node}} - SUCCESS",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Destination - Update Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (destination_node) (snapmirror_update_failed_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",destination_node=~\"$DestinationNode\",destination_node!=\"\"})",
     "legendFormat": "{{destination_node}} - FAIL",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    },
    {
     "expr": "sum by (destination_node) (snapmirror_update_successful_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",destination_node=~\"$DestinationNode\",destination_node!=\"\"})",
     "legendFormat": "{{destination_node}} - SUCCESS",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Source Relationships per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "count by (source_node, relationship_status) (snapmirror_total_transfer_bytes{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_node=~\"$SourceNode\",source_node!=\"\"})",
     "legendFormat": "{{source_node}} - {{relationship_status}}",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Source - Break Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (source_node) (snapmirror_break_failed_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_node=~\"$SourceNode\",source_node!=\"\"})",
     "legendFormat": "{{source_node}} - FAIL",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    },
    {
     "expr": "sum by (source_node) (snapmirror_break_successful_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_node=~\"$SourceNode\",source_node!=\"\"})",
     "legendFormat": "{{source_node}} - SUCCESS",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Source - Resync Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (source_node) (snapmirror_resync_failed_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_node=~\"$SourceNode\",source_node!=\"\"})",
     "legendFormat": "{{source_node}} - FAIL",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    },
    {
     "expr": "sum by (source_node) (snapmirror_resync_successful_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_node=~\"$SourceNode\",source_node!=\"\"})",
     "legendFormat": "{{source_node}} - SUCCESS",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Source - Update Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (source_node) (snapmirror_update_failed_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_node=~\"$SourceNode\",source_node!=\"\"})",
     "legendFormat": "{{source_node}} - FAIL",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    },
    {
     "expr": "sum by (source_node) (snapmirror_update_successful_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_node=~\"$SourceNode\",source_node!=\"\"})",
     "legendFormat": "{{source_node}} - SUCCESS",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  { "title": "SnapMirrors per SVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Source Relationships per SVM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "count by (source_vserver, relationship_status) (snapmirror_total_transfer_bytes{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",source_vserver=~\"$SourceSVM\",source_vserver!=\"\"})",
     "legendFormat": "{{source_vserver}} - {{relationship_status}}",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  },
  {
   "title": "Destination Relationships per SVM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "count by (destination_vserver, relationship_status) (snapmirror_total_transfer_bytes{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",destination_vserver=~\"$DestinationSVM\",destination_vserver!=\"\"})",
     "legendFormat": "{{destination_vserver}} - {{relationship_status}}",
     "target": "aliasByNode(sumSeriesWithWildcards(netapp.perf.$Group.$Cluster.node.$Node.snapmirror.src.*, 5), 7)"
    }
   ]
  }
 ]
}