
name:             Security
query:            api/security
object:           security

counters:
  - ^management_protocols.telnet_enabled     => telnet_enabled
  - ^management_protocols.rsh_enabled        => rsh_enabled
  - ^fips.enabled                            => fips_enabled

export_options:
  instance_keys:
    - fips_enabled
  instance_labels:
    - telnet_enabled
    - rsh_enabled
