
collector:          Rest

schedule:
  - data: 3m

# See https://github.com/NetApp/harvest/blob/main/docs/architecture/rest-strategy.md
# for details on how Harvest handles the ONTAP transition from ZAPI to REST.

objects:
  Aggregate:                   aggr.yaml
  CloudTarget:                 cloud_target.yaml
  ClusterPeer:                 clusterpeer.yaml
  Disk:                        disk.yaml
#  ExportRule:                  exports.yaml
  Health:                      health.yaml
  Lun:                         lun.yaml
  Namespace:                   namespace.yaml
  NetConnections:              netconnections.yaml
#  NetPort:                     netport.yaml
  NetRoute:                    netroute.yaml
  NFSClients:                  nfs_clients.yaml
  Node:                        node.yaml
  NtpServer:                   ntpserver.yaml
  OntapS3:                     ontap_s3.yaml
  Port:                        port.yaml
  QosPolicyAdaptive:           qos_policy_adaptive.yaml
  QosPolicyFixed:              qos_policy_fixed.yaml
  Qtree:                       qtree.yaml
  Security:                    security.yaml
  SecurityAccount:             security_account.yaml
  SecurityAuditDestination:    security_audit_dest.yaml
  SecurityCert:                security_certificate.yaml
  SecurityLogin:               security_login.yaml
  SecuritySsh:                 security_ssh.yaml
  Sensor:                      sensor.yaml
  Shelf:                       shelf.yaml
  SnapMirror:                  snapmirror.yaml
  SnapshotPolicy:              snapshotpolicy.yaml
  Status:                      status.yaml
  Subsystem:                   subsystem.yaml
  Support:                     support.yaml
  SVM:                         svm.yaml
  Volume:                      volume.yaml
  VolumeAnalytics:             volume_analytics.yaml
