
collector:          Rest

schedule:
  - data: 180s

objects:
  Aggr:                        aggr.yaml
  ClusterPeer:                 clusterpeer.yaml
  Disk:                        disk.yaml
  Lun:                         lun.yaml
  Node:                        node.yaml
  NtpServer:                   ntpserver.yaml
  Port:                        port.yaml
  Qtree:                       qtree.yaml
  Security:                    security.yaml
  SecurityAccount:             security_account.yaml
  SecurityAuditDestination:    security_audit_dest.yaml
  SecurityCert:                security_certificate.yaml
  SecurityLogin:               security_login.yaml
  SecuritySsh:                 security_ssh.yaml
  Sensor:                      sensor.yaml
  Shelf:                       shelf.yaml
  SnapMirror:                  snapmirror.yaml
  SnapshotPolicy:              snapshotPolicy.yaml
  Status:                      status.yaml
  Subsystem:                   subsystem.yaml
  Support:                     support.yaml
  SVM:                         svm.yaml
  Volume:                      volume.yaml

