
collector:          Rest

schedule:
  - data: 60s

objects:
#  Disk:             disk.yaml
#  Lun:              lun.yaml
#  Status:           status.yaml
#  Node:             node.yaml
#  Aggr:             aggr.yaml
#  SnapMirror:       snapmirror.yaml
  Volume:           volume.yaml
#  Subsystem:        subsystem.yaml
#  Snapshot:         snapshot.yaml
#  Port:             port.yaml
#  Qtree:            qtree.yaml
#  Shelf:            shelf.yaml
#  Sensor:           sensor.yaml
  SVM:          svm.yaml



# for security dashboard at cluster
#  Support:         support.yaml
#  Security:        security.yaml
  SecurityAccount: security_account.yaml
#  ClusterPeer:     clusterpeer.yaml # test pending
#  SecurityCert:    security_certificate.yaml
#  SecurityLogin:    security_login.yaml
#  NtpServer:       ntpserver.yaml  # test pending
#  SecurityAuditDestination: security_audit_dest.yaml  # test pending



#  securitySsh:     security_ssh.yaml    ## to be removed, covered in svm
#  ProtocolCifs:     protocol_cifs.yaml  ## to be removed, covered in svm
#  ProtocolNfs:      protocol_nfs.yaml  ## to be removed, covered in svm
#  ProtocolAudit:    protocol_audit.yaml  ## to be removed, covered in svm
#  ProtocolFpolicy:    protocol_fpolicy.yaml  # test pending
#  NameservicesNis:    name_services_nis.yaml  ## to be removed, covered in svm
#  ProtocolNfsKerberos: protocols_nfs_kerberos_interfaces.yaml   ## to be removed, covered in svm
#  NameservicesLdap: name_services_ldap.yaml   ## to be removed, covered in svm
#  ProtocolSanIscsiService: protocol_san_iscsi_service.yaml  ## to be removed, covered in svm
#  ProtocolSanIscsiCredential: protocol_san_iscsi_credential.yaml   ## to be removed, covered in svm
