
collector:          Rest

schedule:
  - data: 180s

objects:
  Disk:             disk.yaml
  Lun:              lun.yaml
  Status:           status.yaml
  Node:             node.yaml
  Aggr:             aggr.yaml
  SnapMirror:       snapmirror.yaml
  Volume:           volume.yaml
  Subsystem:        subsystem.yaml
  Snapshot:         snapshot.yaml
  Port:             port.yaml
  Qtree:            qtree.yaml
  Shelf:            shelf.yaml
  Sensor:           sensor.yaml