pipeline {

    agent none

    options {
        buildDiscarder logRotator(
                    daysToKeepStr: '16',
                    numToKeepStr: '10'
            )
    }
    parameters {
        string(name: 'BRANCH', defaultValue: 'main', description: '[Optional] Branch name to clone. Default (main) ')
        string(name: 'DOCKER', defaultValue: '', description: 'http url of docker tar build or docker image')
        string(name: 'NATIVE', defaultValue: '', description: 'http url of native tar file')
    }

    stages {
        stage('Setup') {
            agent {
                label "master"
            }
            steps {
                sh '''
                echo "Setup"
                '''
            }
        }
        stage('Run Tests') {
            parallel {
                stage('NATIVE') {
                    agent {
                        label "rhel"
                    }
                    stages('Test on RPM Pkg') {
                        stage('Cleanup Workspace') {
                            steps {
                                cleanWs()
                                sh """
                                echo "Cleaned Up Workspace For Project"
                                """
                            }
                        }

                        stage('Setup GO') {
                            steps {
                                sh '''
                                wget --quiet -O go.tar.gz "https://dl.google.com/go/$(curl https://golang.org/VERSION?m=text).linux-amd64.tar.gz"
                                ls -ltrh
                                rm -rf /usr/local/go && tar -C /usr/local -xzf ./go.tar.gz
                                '''
                            }
                        }

                        stage('Code Checkout') {
                            steps {
                               sh '''
                               git clone --single-branch --branch $BRANCH https://github.com/NetApp/harvest.git
                                '''
                            }
                        }

                        stage('Install NATIVE pkg') {
                            steps {
                                sh """
                                echo "Installing"
                                export PATH=$PATH:/usr/local/go/bin
                                export BUILD_PATH=$NATIVE
                                cd $WORKSPACE/harvest/integration/test/
                                go mod vendor
                                go test -tags=install_native
                                """
                            }
                        }
                        stage('Running Test') {
                            steps {
                                sh """
                                echo "Running Unit Tests"
                                export PATH=$PATH:/usr/local/go/bin
                                cd $WORKSPACE/harvest/integration/test/
                                go test -tags=regression
                                """
                            }
                        }
                    }

                }
                stage('DOCKER') {
                    agent {
                        label "rhel"
                    }
                    stages('Test on docker Pkg') {
                        stage('Cleanup Workspace') {
                            steps {
                                cleanWs()
                                sh """
                                echo "Cleaned Up Workspace For Project"
                                """
                            }
                        }

                        stage('Setup GO') {
                            steps {
                                sh '''
                                wget --quiet -O go.tar.gz "https://dl.google.com/go/$(curl https://golang.org/VERSION?m=text).linux-amd64.tar.gz"
                                ls -ltrh
                                rm -rf /usr/local/go && tar -C /usr/local -xzf ./go.tar.gz
                                '''
                            }
                        }

                        stage('Code Checkout') {
                           steps {
                               sh '''
                               git clone --single-branch --branch $BRANCH https://github.com/NetApp/harvest.git
                                '''
                            }
                        }

                        stage('Install Docker') {
                            steps {
                                sh """
                                echo "Installing"
                                export PATH=$PATH:/usr/local/go/bin
                                #export BUILD_PATH=$DOCKER
                                cd $WORKSPACE/harvest
                                cp -rf $WORKSPACE/harvest/integration/test/harvest.yml .
                                make build
                                ./bin/harvest stop
                                ./bin/harvest generate docker full --port --output harvest-compose.yml
                                docker login -u harvesttest -p harvesttest
                                docker stop $(docker ps -a -q)
                                docker rm $(docker ps -a -q)
                                docker rmi $(docker images -q)
                                docker build -f docker/onePollerPerContainer/Dockerfile -t rahulguptajss/harvest:latest . --no-cache
                                docker-compose -f prom-stack.yml -f harvest-compose.yml up -d --remove-orphans
                                cd $WORKSPACE/harvest/integration/test/
                                go test -tags=install_docker
                                """
                            }
                        }
                        stage('Running Test') {
                            steps {
                                sh """
                                echo "Running Unit Tests"
                                export PATH=$PATH:/usr/local/go/bin
                                cd $WORKSPACE/harvest/integration/test/
                                go test -tags=regression
                                """
                            }
                        }
                    }

                }
            }
        }
    }
}