#!/bin/bash

#
# Copyright NetApp Inc, 2021 All rights reserved
#

# After installation/upgrade, copy latest harvest.yml as harvest.example.yml
if [ -e /opt/harvest/harvest.yml ]; then
    rm -rf /opt/harvest/harvest.example.yml
    cp /opt/harvest/harvest.yml /opt/harvest/harvest.example.yml
    echo "  --> copy new harvest.yml as [/opt/harvest/harvest.example.yml]"
fi
# restore old harvest.yml in case of upgrade
if [ -e /opt/harvest/backup_harvest.yml ]; then
    rm -rf /opt/harvest/harvest.yml
    cp /opt/harvest/backup_harvest.yml /opt/harvest/harvest.yml
    rm -rf /opt/harvest/backup_harvest.yml
    echo "  --> restoring backup_harvest.yml as [/opt/harvest/harvest.yml]"
fi

echo " --> set directory ownership"
chown -R harvest:harvest /opt/harvest
mkdir -p /var/log/harvest
chown -R harvest:harvest /var/log/harvest
chmod -R u+s /opt/harvest/bin
chmod -R g+s /opt/harvest/bin

echo "  --> copying service"
cp /opt/harvest/service/harvest.service /etc/systemd/system/
chmod 664 /etc/systemd/system/harvest.service

systemctl daemon-reload
systemctl start harvest.service
systemctl enable harvest.service
echo "  --> harvest service started through systemctl"
echo "  --> harvest installed location /opt/harvest"