#!/bin/bash

#
# Copyright NetApp Inc, 2021 All rights reserved
#

if [[ "$1" == "purge" || "$1" == "remove" ]]; then
    if [ "$1" == "purge" ]; then
        rm -r /var/log/harvest && echo " --> delete log directory"
    fi
    rm -r /var/run/harvest && echo " --> delete pid directory"
    unlink /usr/bin/harvest && echo " --> delete link"
    userdel harvest && echo " --> delete harvest user"
    groupdel harvest && echo " --> delete harvest group"
    echo " --> cleanup & uninstall complete"
fi
