#!/bin/bash

#
# Copyright NetApp Inc, 2021 All rights reserved
#

echo " --> set directory ownership"
chown -R harvest:harvest /opt/harvest
if [ -z "$2" ]; then
    mkdir -p /var/log/harvest
    mkdir -p /var/run/harvest
    chown -R harvest:harvest /var/log/harvest
    chown -R harvest:harvest /var/run/harvest
fi

if [ ! -e /usr/bin/harvest ]; then
    ln -s /opt/harvest/bin/harvest /usr/bin/harvest && echo " --> link created"
fi
