#!/bin/bash
#
# Copyright NetApp Inc, 2021 All rights reserved
#

echo " --> preparing $1"
if [[ "$1" == "install" || "$1" == "upgrade" ]]; then
    getent group harvest > /dev/null 2>&1 || addgroup -q --system harvest && echo " --> group created"
    getent passwd harvest > /dev/null 2>&1 || adduser -q --system --no-create-home \
        --ingroup harvest --disabled-password --shell /bin/false harvest && echo " --> user created"
fi
