#!/bin/bash

#
# Copyright NetApp Inc, 2021 All rights reserved
#

echo " --> stop harvest for $1"
systemctl stop harvest
# Stop any harvest process which are not under systemctl
ps -ef | grep -w -- --poller | grep -w bin/poller | awk '{print $2}' | xargs -r kill
if [ $? -ne 0 ]; then
  echo "  --> Error while stopping pollers"
fi
if [ -e /opt/harvest/harvest.yml ]; then
  echo " --> backing up harvest conf"
  cp /opt/harvest/harvest.yml /opt/harvest/backup_harvest.yml
  echo "  --> Backing up existing config file as [/opt/harvest/backup_harvest.yml]"
fi