{
 "title": "NetApp Harvest: Pollers",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Bucket", "query": "buckets()" },
   {
    "name": "Hostname",
    "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\")\r\n  |> keep(columns: [\"hostname\"])\r\n  |> group()\r\n  |> distinct(column: \"hostname\")"
   },
   {
    "name": "Poller",
    "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\")\r\n  |> filter(fn: (r) => contains(value: r[\"hostname\"], set: [${Hostname:json}]))\r\n  |> keep(columns: [\"poller\"])\r\n  |> group()\r\n  |> distinct(column: \"poller\")"
   },
   {
    "name": "Collector",
    "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\"and r[\"type\"] == \"collector\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> keep(columns: [\"name\"])\r\n  |> group()\r\n  |> distinct(column: \"name\")"
   },
   {
    "name": "Object",
    "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"type\"] == \"collector\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"name\"], set: ${Collector:json}))\r\n  |> keep(columns: [\"target\"])\r\n  |> group()\r\n  |> distinct(column: \"target\")"
   },
   {
    "name": "Exporter",
    "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"type\"] == \"exporter\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> keep(columns: [\"target\"])\r\n  |> group()\r\n  |> distinct(column: \"target\")"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Datacenters",
   "type": "stat",
   "description": "Number of Datacenters monitored by selected Harvest instances. (Controlled by the Hostname variable).",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> group()\r\n  |> unique(column: \"datacenter\")\r\n  |> count(column: \"datacenter\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pollers",
   "type": "stat",
   "description": "Number of Pollers in selected Harvest instances. (Usually one poller monitors one cluster).",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> group()\r\n  |> unique(column: \"poller\")\r\n  |> count(column: \"poller\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Collectors",
   "type": "stat",
   "description": "Number of Collectors in selected Pollers. (Each Collector-Object pair is treated as a collector).",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"type\"] == \"collector\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> map(fn: (r) => ({unique_name: r.name + \"_\" + r.target}) )\r\n  |> unique(column: \"unique_name\")\r\n  |> count(column: \"unique_name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "stat",
   "description": "Number of Exporters in selected Pollers.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"type\"] == \"exporter\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> map(fn: (r) => ({unique_name: r.name + \"_\" + r.target}) )\r\n  |> unique(column: \"unique_name\")\r\n  |> count(column: \"unique_name\")\r\n  |> yield(name: \"count\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Collected/1m",
   "type": "stat",
   "description": "Number of data points collected by Collectors each minute.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"_field\"] == \"count\" and r[\"type\"] == \"collector\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"name\"], set: ${Collector:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"target\"], set: ${Object:json}))\r\n  |> group()\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exported/1m",
   "type": "stat",
   "description": "Number of data points exported each minute.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"_field\"] == \"count\" and r[\"type\"] == \"exporter\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"target\"], set: ${Exporter:json}))  \r\n  |> group()\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "description": "System CPU used by selected Harvest instances and Pollers. Number can be higher than 100% on multi-core systems.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"cpu_percent\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group() // summarize data of all pollers\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false) // average over time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "description": "System Memory used by selected Harvest instances and Pollers.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"memory_percent\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group()\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pollers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"status_code\")\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\n  |> group(columns: [\"poller\", \"hostname\", \"datacenter\"], mode: \"by\")\n  |> last()\n  |> map(fn: (r) => ({r with status: int(v: r._value) }) )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Target Systems",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_target\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status_code\" or r[\"_field\"] == \"ping\")\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\n  |> group(columns: [\"poller\", \"hostname\", \"addr\"], mode: \"by\")\n  |> last()\n  |> map(fn: (r) => ({r with status_code: int(v: r._value) }) )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Collectors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"_field\"] == \"status_code\" and r[\"type\"] == \"collector\")\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\n  |> filter(fn: (r) => contains(value: r[\"name\"], set: ${Collector:json}))\n  |> filter(fn: (r) => contains(value: r[\"target\"], set: ${Object:json}))\n  |> group(columns: [\"poller\", \"name\", \"target\"], mode: \"by\")\n  |> last()\n  |> map(fn: (r) => ({r with status: int(v: r._value) }) )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_component\" and r[\"_field\"] == \"status_code\" and r[\"type\"] == \"exporter\")\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\n  |> filter(fn: (r) => contains(value: r[\"target\"], set: ${Exporter:json}))\n  |> group(columns: [\"poller\", \"name\", \"target\"], mode: \"by\")\n  |> last()\n  |> map(fn: (r) => ({r with status: int(v: r._value) }) )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Target System Latency (Ping)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_target\" and r[\"_field\"] == \"ping\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> map(fn: (r) => ({ r with unique_name: r.poller + \" - \" + r.addr}) )\r\n  |> group(columns: [\"unique_name\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Poll Time",
   "type": "graph",
   "description": "Average duration of data poll of all collectors",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"poll_time\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"poller\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Poll Time Per Collector",
   "type": "graph",
   "description": "Average duration of data poll (includes API time and plugins)",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"poll_time\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"collector\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Export Time",
   "type": "graph",
   "description": "Average duration of export",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_exporter\" and r[\"_field\"] == \"harvest_time\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"target\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU Utilization %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and  r[\"_field\"] == \"cpu_percent\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"poller\"], mode:\"by\")\r\n  |> keep(columns: [\"poller\", \"_value\", \"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "   from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"poller\" and r._field == \"memory_percent\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"poller\"], mode:\"by\")\r\n  |> keep(columns: [\"poller\", \"_value\", \"_time\"])\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU times: Breakdown",
   "type": "graph",
   "description": "CPU time per minute of each Poller",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental/aggregate\"\r\nfrom(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"_field\"], set: [\"cpu_iowait\", \"cpu_system\", \"cpu_user\"]))\r\n  |> map(fn: (r) => ({ r with display_name: r.poller + \"- \" + r._field}) )\r\n  |> aggregate.rate(every: 10s, groupColumns: [\"poller\", \"_field\"], unit: 10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory breakdown",
   "type": "graph",
   "description": "Graph is useful when a single Poller is selected",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /memory_\\w+/ and r[\"_field\"] != \"memory_percent\" and r[\"_field\"] != \"memory_vms\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> map(fn: (r) => ({ r with display_name: r.poller + \" - \" + r._field}) )\r\n  |> group(columns: [\"display_name\"], mode:\"by\")\r\n  |> keep(columns: [\"display_name\", \"_value\", \"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IO Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental/aggregate\"\r\nfrom(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and contains(value: r[\"_field\"], set: [\"io_write_bytes\", \"io_read_bytes\", \"io_cancelled_write_bytes\"]))\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> aggregate.rate(every: 10s, groupColumns: [\"poller\", \"_field\"], unit: 10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IO Chars",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental/aggregate\"\r\nfrom(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and contains(value: r[\"_field\"], set: [\"io_wchar\", \"io_rchar\"]))\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> aggregate.rate(every: 10s, groupColumns: [\"poller\", \"_field\"], unit: 10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IO Syscalls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental/aggregate\"\r\nfrom(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and contains(value: r[\"_field\"], set: [\"io_syscw\", \"io_syscr\"]))\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> aggregate.rate(every: 10s, groupColumns: [\"poller\", \"_field\"], unit: 10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net IO Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental/aggregate\"\r\nfrom(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and contains(value: r[\"_field\"], set: [\"net_sent_bytes\", \"net_rcv_bytes\"]))\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> aggregate.rate(every: 10s, groupColumns: [\"poller\", \"_field\"], unit: 10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net IO Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental/aggregate\"\r\nfrom(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and contains(value: r[\"_field\"], set: [\"net_sent_packets\", \"net_rcv_packets\"]))\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> aggregate.rate(every: 10s, groupColumns: [\"poller\", \"_field\"], unit: 10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network IO Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental/aggregate\"\r\nfrom(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and contains(value: r[\"_field\"], set: [\"net_sent_errs\", \"net_rcv_errs\"]))\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> aggregate.rate(every: 10s, groupColumns: [\"poller\", \"_field\"], unit: 10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FDs",
   "type": "graph",
   "description": "File descriptors opened by Pollers",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"fds\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"poller\"], mode:\"by\")\r\n  |> keep(columns: [\"poller\", \"_value\", \"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "description": "Unix Threads created by Pollers",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poller\" and r[\"_field\"] == \"threads\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"poller\"], mode:\"by\")\r\n  |> keep(columns: [\"poller\", \"_value\", \"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "description": "Goroutines created by Pollers",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_target\" and r[\"_field\"] == \"goroutines\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> group(columns: [\"poller\"], mode:\"by\")\r\n  |> keep(columns: [\"poller\", \"_value\", \"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Collectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Data Poll Time",
   "type": "graph",
   "description": "You can select here a Poller, Collector and Object, to narrow down the data.\n\nAverage duration of Data Poll. This includes API time (shown below).",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"poll_time\" and r[\"task\"] == \"data\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"collector\"], set: ${Collector:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"object\"], set: ${Object:json}))\r\n  |> map(fn: (r) => ({ r with display_name: r.collector + \" - \" + r.object}) )\r\n  |> group(columns: [\"display_name\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"display_name\", \"_value\", \"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": " Data Points",
   "type": "graph",
   "description": "Total number of data points collected",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"count\" and r[\"task\"] == \"data\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"collector\"], set: ${Collector:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"object\"], set: ${Object:json}))\r\n  |> map(fn: (r) => ({ r with display_name: r.collector + \" - \" + r.object}) )\r\n  |> group(columns: [\"display_name\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\r\n  |> keep(columns: [\"display_name\", \"_value\", \"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instances",
   "type": "graph",
   "description": "Total number of instances",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"count\" and r[\"task\"] == \"instance\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"collector\"], set: ${Collector:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"object\"], set: ${Object:json}))\r\n  |> map(fn: (r) => ({ r with display_name: r.collector + \" - \" + r.object}) )\r\n  |> group(columns: [\"display_name\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\r\n  |> keep(columns: [\"display_name\", \"_value\", \"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API Time",
   "type": "graph",
   "description": "Average API wait time of each data poll",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"api_time\" and r[\"task\"] == \"data\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"collector\"], set: ${Collector:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"object\"], set: ${Object:json}))\r\n  |> map(fn: (r) => ({ r with display_name: r.collector + \" - \" + r.object}) )\r\n  |> group(columns: [\"display_name\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"display_name\", \"_value\", \"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "XML Parse Time",
   "type": "graph",
   "description": "Average time it takes to Parse the XML load. Reported by Collectors that deal with XML data (Zapi and ZapiPerf).",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 86 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"parse_time\" and r[\"task\"] == \"data\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"collector\"], set: ${Collector:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"object\"], set: ${Object:json}))\r\n  |> group(columns: [\"collector\", \"object\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Postprocessing Time",
   "type": "graph",
   "description": "Average time to do delta-calculation on collected data points. This metric is reported by the ZapiPerf collector.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 86 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata_collector\" and r[\"_field\"] == \"calc_time\" and r[\"task\"] == \"data\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"poller\"], set: ${Poller:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"collector\"], set: ${Collector:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"object\"], set: ${Object:json}))\r\n  |> group(columns: [\"collector\", \"object\"], mode:\"by\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}