{
 "title": "ONTAP: SnapMirror",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Bucket", "query": "buckets()" },
   {
    "name": "Datacenter",
    "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\")\r\n  |> keep(columns: [\"datacenter\"])\r\n  |> group()\r\n  |> distinct(column: \"datacenter\")"
   },
   {
    "name": "Cluster",
    "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> keep(columns: [\"cluster\"])\r\n  |> group()\r\n  |> distinct(column: \"cluster\")"
   },
   {
    "name": "DestinationNode",
    "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> keep(columns: [\"destination_node\"])\r\n  |> group()\r\n  |> distinct(column: \"destination_node\")"
   },
   {
    "name": "SourceNode",
    "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> keep(columns: [\"source_node\"])\r\n  |> group()\r\n  |> distinct(column: \"source_node\")"
   },
   {
    "name": "DestinationSVM",
    "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> keep(columns: [\"destination_vserver\"])\r\n  |> group()\r\n  |> distinct(column: \"destination_vserver\")"
   },
   {
    "name": "SourceSVM",
    "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> keep(columns: [\"source_vserver\"])\r\n  |> group()\r\n  |> distinct(column: \"source_vserver\")"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SnapMirrors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> map(fn: (r) => ({unique_name: r.cluster + \"_\" + r.relationship_id}) )\r\n  |> unique(column: \"unique_name\")\r\n  |> count(column: \"unique_name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unhealthy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r._field == \"healthy\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => r._value == false)\r\n  |> map(fn: (r) => ({unique_name: r.cluster + \"_\" + r.relationship_id}) )\r\n  |> unique(column: \"unique_name\")\r\n  |> count(column: \"unique_name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SVM Protection (DR)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r._field == \"group_type\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => r._value == \"svm\")\r\n  |> map(fn: (r) => ({unique_name: r.cluster + \"_\" + r.relationship_id}) )\r\n  |> unique(column: \"unique_name\")\r\n  |> count(column: \"unique_name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FlexVol Protection",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r._field == \"group_type\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => r._value == \"none\")\r\n  |> map(fn: (r) => ({unique_name: r.cluster + \"_\" + r.relationship_id}) )\r\n  |> unique(column: \"unique_name\")\r\n  |> count(column: \"unique_name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FlexGroup Protection",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r._field == \"group_type\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => r._value == \"flexgroup\")\r\n  |> map(fn: (r) => ({unique_name: r.cluster + \"_\" + r.relationship_id}) )\r\n  |> unique(column: \"unique_name\")\r\n  |> count(column: \"unique_name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SnapMirrors",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"_field\"], set: [\"group_type\", \"relationship_status\", \"schedule\", \"unhealthy_reason\", \"healthy\"]))\r\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Destination Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Relationship State",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"relationship_status\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"destination_node\"], set: ${DestinationNode:json}))\r\n  |> map(fn: (r) => ({ r with display_name: r.destination_node + \" - \" + r._value}) )\r\n  |> group(columns: [\"display_name\"])\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Transfer Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"total_transfer_bytes\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"destination_node\"], set: ${DestinationNode:json}))\r\n  |> group(columns: [\"destination_node\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Transfer Lag Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"lag_time\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"destination_node\"], set: ${DestinationNode:json}))\r\n  |> group(columns: [\"destination_node\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Transfer Type",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"relationship_type\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"destination_node\"], set: ${DestinationNode:json}))\r\n  |> map(fn: (r) => ({ r with display_name: r.destination_node + \" - \" + r._value}) )\r\n  |> group(columns: [\"display_name\"])\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Transfer Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"last_transfer_size\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"destination_node\"], set: ${DestinationNode:json}))\r\n  |> group(columns: [\"destination_node\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Transfer Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"last_transfer_duration\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"destination_node\"], set: ${DestinationNode:json}))\r\n  |> group(columns: [\"destination_node\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Break Operations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"break_failed_count\" or r[\"_field\"] == \"break_successful_count\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"destination_node\"], set: ${DestinationNode:json}))\r\n  |> map(fn: (r) => ({ r with display_name: r.destination_node + \" - \" + r._field}) )\r\n  |> group(columns: [\"display_name\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Resync Operations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"resync_failed_count\" or r[\"_field\"] == \"resync_successful_count\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> map(fn: (r) => ({ r with display_name: r.destination_node + \" - \" + r._field}) )\r\n  |> group(columns: [\"display_name\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Update Operations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"update_failed_count\" or r[\"_field\"] == \"update_successful_count\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> map(fn: (r) => ({ r with display_name: r.destination_node + \" - \" + r._field}) )\r\n  |> group(columns: [\"display_name\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Destination SVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Relationship State",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"relationship_status\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"destination_node\"], set: ${DestinationNode:json}))\r\n  |> map(fn: (r) => ({ r with display_name: r.destination_vserver + \" - \" + r._value}) )\r\n  |> group(columns: [\"display_name\"])\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Transfer Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"total_transfer_bytes\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"destination_node\"], set: ${DestinationNode:json}))\r\n  |> group(columns: [\"destination_vserver\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Transfer Lag Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"lag_time\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"destination_node\"], set: ${DestinationNode:json}))\r\n  |> group(columns: [\"destination_vserver\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Transfer Type",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"relationship_type\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"destination_node\"], set: ${DestinationNode:json}))\r\n  |> map(fn: (r) => ({ r with display_name: r.destination_vserver + \" - \" + r._value}) )\r\n  |> group(columns: [\"display_name\"])\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Transfer Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"last_transfer_size\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"destination_node\"], set: ${DestinationNode:json}))\r\n  |> group(columns: [\"destination_vserver\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Transfer Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"last_transfer_duration\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"destination_node\"], set: ${DestinationNode:json}))\r\n  |> group(columns: [\"destination_vserver\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Break Operations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"break_failed_count\" or r[\"_field\"] == \"break_successful_count\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => contains(value: r[\"destination_node\"], set: ${DestinationNode:json}))\r\n  |> map(fn: (r) => ({ r with display_name: r.destination_vserver + \" - \" + r._field}) )\r\n  |> group(columns: [\"display_name\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Resync Operations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"resync_failed_count\" or r[\"_field\"] == \"resync_successful_count\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> map(fn: (r) => ({ r with display_name: r.destination_vserver + \" - \" + r._field}) )\r\n  |> group(columns: [\"display_name\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Update Operations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapmirror\" and r[\"_field\"] == \"update_failed_count\" or r[\"_field\"] == \"update_successful_count\")\r\n  |> filter(fn: (r) => r[\"datacenter\"] == \"${Datacenter}\")\r\n  |> filter(fn: (r) => r[\"cluster\"] == \"${Cluster}\")\r\n  |> map(fn: (r) => ({ r with display_name: r.destination_vserver + \" - \" + r._field}) )\r\n  |> group(columns: [\"display_name\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}