name: Write Secret to File

on: [push]

jobs:
  write_secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          MY_CLIENT_ID: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "MY_CLIENT_ID (base64) = $(echo ${MY_CLIENT_ID} | base64)"
          shell: bash
