name: Prune untagged images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6' # every Saturday at midnight

jobs:
  purge-image:
    permissions:
      contents: read
      pull-requests: write
    name: Prune untagged images
    runs-on: ubuntu-latest
    environment: scheduled
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Delete all containers from repository without tags
        uses: step-security/delete-untagged-ghcr-action@37825bcd9a94761395d78dd2e696baaa28288da3 # v6.1.0
        with:
          token: ${{ secrets.PAT_TOKEN }}
          package_name: 'harvest'
          untagged_only: true
          owner_type: user

      - name: Delete all containers from harvest-mcp repository without tags
        uses: step-security/delete-untagged-ghcr-action@37825bcd9a94761395d78dd2e696baaa28288da3 # v6.1.0
        with:
          token: ${{ secrets.PAT_TOKEN }}
          package_name: 'harvest-mcp'
          untagged_only: true
          owner_type: user
