name: Prune untagged images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6' # every Saturday at midnight

jobs:
  purge-image:
    permissions:
      contents: read
      pull-requests: write
    name: Prune untagged images
    runs-on: ubuntu-latest
    steps:
      - name: Delete all containers from repository without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@68758dd8caf1d9dbaed1fe9cc1a1f8fcea1c4cf0
        with:
          token: ${{ secrets.PAT_TOKEN }}
          package_name: 'harvest'
          untagged_only: true
          owner_type: user