name: Prune Untagged Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6' # every Saturday at midnight

jobs:
  purge-image:
    name: Prune untagged images
    runs-on: ubuntu-latest
    steps:
      - name: Prune all untagged images
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'harvest'
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'