name: Prune untagged images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6' # every Saturday at midnight

jobs:
  purge-image:
    permissions:
      contents: read
      pull-requests: write
    name: Prune untagged images
    runs-on: ubuntu-latest
    environment: scheduled
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Delete all containers from repository without tags
        uses: step-security/delete-untagged-ghcr-action@b25aaa1da23c7487da729ec8e0457db03fce561e # v6.1.1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          package_name: 'harvest'
          untagged_only: true
          owner_type: user

      - name: Delete all containers from harvest-mcp repository without tags
        uses: step-security/delete-untagged-ghcr-action@b25aaa1da23c7487da729ec8e0457db03fce561e # v6.1.1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          package_name: 'harvest-mcp'
          untagged_only: true
          owner_type: user
