# https://github.com/RebeccaStevens/issue-closed-labeler-action
name: Issue Closed Labeler

on:
  issues:
    types:
      - closed
  pull_request:
    types:
      - closed

jobs:
  run:
    name: "Label"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Update Labels
        uses: RebeccaStevens/issue-closed-labeler-action@latest
        with:
          rules: '[
            {
              "condition": "bug",
              "add": [
                "status/testme"
              ],
              "remove": "wip"
            }
          ]'