name: "Lint PR"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - uses: step-security/action-semantic-pull-request@75d2dd5deafa3e9fccc1626ecd58d076ed1d2c79 # v6.1.2
        with:
          types: |
            build
            chore
            ci
            doc
            feat
            fix
            perf
            refactor
            revert
            style
            test
          scopes: |
            collector
            config
            exporter
            grafana
            influxdb
            manager
            matrix
            poller
            prometheus
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}