name: "Lint PR"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - uses: step-security/action-semantic-pull-request@bc0cf74f5be4ce34accdec1ae908dff38dc5def1 # v6.1.1
        with:
          types: |
            build
            chore
            ci
            doc
            feat
            fix
            perf
            refactor
            revert
            style
            test
          scopes: |
            collector
            config
            exporter
            grafana
            influxdb
            manager
            matrix
            poller
            prometheus
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}